"""Additional EN training data - Part 8. Final large batch."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

# Software culture
add("What does code smell mean?","Code smell refers to signs in the code that indicate a problem but are not direct bugs. Examples: overly long functions (50+ lines), too many parameters (5+), duplicated code (DRY violation), deeply nested if/else, magic numbers (unexplained constant values), God class (a class that does everything), dead code (unused code). When you see a code smell, think about refactoring. Martin Fowler's 'Refactoring' book is the reference on this topic. Catching smells during code reviews is important. Tools like Sonar can detect them automatically. The first step to writing clean code is recognizing code smells.","Code smell, refactoring, DRY, God class, dead code, Sonar.")
add("What does semantic versioning (semver) mean?","Semantic versioning is a version numbering format: MAJOR.MINOR.PATCH, like 2.4.1. MAJOR: backward-incompatible changes (API changed). MINOR: backward-compatible new features. PATCH: backward-compatible bug fixes. Additional: 1.0.0-alpha, 1.0.0-beta are pre-releases. 0.x.x means not yet stable. npm, pip, cargo all use semver. In package.json, ^2.4.1 allows minor updates, ~2.4.1 allows only patches. Use semver in your own projects too — it clearly shows users what changed. Making a breaking change bumps the MAJOR version — be careful.","Semver, MAJOR.MINOR.PATCH, npm, breaking change, pre-release.")
add("What does 12-factor app mean?","The 12-factor app is a set of 12 principles for modern web applications. Proposed by the founders of Heroku. 1. Codebase: one repo, many deploys. 2. Dependencies: declare explicitly. 3. Config: store in environment variables. 4. Backing services: treat as attached resources. 5. Build, release, run: separate stages. 6. Processes: stateless processes. 7. Port binding: serve via port binding. 8. Concurrency: scale via the process model. 9. Disposability: fast startup, graceful shutdown. 10. Dev/prod parity: keep environments similar. 11. Logs: treat as event streams. 12. Admin processes: one-off tasks. This is the foundation of cloud-native applications.","12-factor app, principles, stateless, config, cloud-native.")
add("What is the difference between monorepo and multi-repo?","Monorepo: keeping all projects in a single repository. Google, Meta, Microsoft use it. Advantages: easy code sharing, easy refactoring, centralized dependency management, you can see all changes together. Disadvantages: repo grows large, CI/CD can become complex, access control gets harder. Tools: Nx, Turborepo, Lerna, Bazel. Multi-repo: each project in its own repository. Advantages: isolation, independent deploys, easy access control. Disadvantages: code sharing is difficult, dependency hell, cross-repo changes are painful. Small teams tend to prefer multi-repo, large organizations prefer monorepo. There is no single right answer — choose based on your needs.","Monorepo, multi-repo, Nx, Turborepo, Lerna, pros/cons.")
add("What does feature flag mean?","A feature flag is a mechanism to enable or disable features without redeploying code. if (featureFlags.newUI) { showNewUI() } else { showOldUI() }. Advantages: compatible with trunk-based development — deploy a half-finished feature and hide it with a flag. A/B testing — show the new feature to a subset of users. Canary release — gradually roll out the new feature. Kill switch — instantly disable a feature if problems arise. Tools: LaunchDarkly, Unleash, Flagsmith. Caution: clean up old flags, otherwise the code becomes complex (feature flag debt). Netflix, GitHub, Atlassian use them heavily.","Feature flag, A/B testing, canary release, LaunchDarkly, trunk-based.")
add("What does chaos engineering mean?","Chaos engineering is the practice of intentionally introducing failures into production systems to test their resilience. Netflix's Chaos Monkey is the most famous example — it randomly shuts down servers. Goal: learn how the system behaves under real-world conditions (server crashes, network latency, disk full). Principle: form a hypothesis, run the experiment, analyze results, strengthen the system. Steady state hypothesis is important — define normal behavior, then disrupt it. Gremlin and Litmus are popular tools. Start small and scale up gradually. Test in staging before doing it in production. An important part of SRE culture.","Chaos engineering, Chaos Monkey, Netflix, resilience, SRE, Gremlin.")
add("What is trunk-based development?","Trunk-based development is a development approach where all developers merge to the main branch frequently (at least once a day). No long-lived branches — feature branches live for 1-2 days at most. Half-finished features are hidden with feature flags. Continuous integration and deployment via CI/CD. Advantages: merge conflicts are minimized, integration issues are caught early, deployment speeds up. Google and other large companies use it. An alternative to Git Flow — simpler but requires more discipline. Hard to practice without feature flags.","Trunk-based development, main branch, feature flag, CI/CD, merge conflict.")

# More AI
add("How does a CNN (Convolutional Neural Network) work?","A CNN is a neural network specialized for image processing. Core layers: Convolutional layer — filters (kernels) slide over the image to extract features (edges, corners, textures). Pooling layer — reduces dimensions (max pooling is the most common). Fully connected layer — performs classification. ReLU activation — adds non-linearity. Example: a 224x224 image goes in, passes through conv+pool layers, and outputs 'cat' or 'dog'. LeNet, AlexNet, VGG, ResNet, EfficientNet are important CNN architectures. Gorkem's YOLO project is CNN-based — used for object detection. Transfer learning with ImageNet weights is very common.","CNN, convolutional, pooling, fully connected, ResNet, YOLO, transfer learning.")
add("What are RNN and LSTM?","RNN (Recurrent Neural Network) is a neural network designed for sequential data (text, time series). At each step, it takes the previous step's output as input — creating a memory effect. Problem: gradient vanishing on long sequences — it forgets distant information. LSTM (Long Short-Term Memory): designed to solve this problem. Cell state (long-term memory), forget gate (what to forget), input gate (what to add), output gate (what to output). GRU (Gated Recurrent Unit): a simplified version of LSTM. However, after transformers emerged, RNN/LSTM popularity declined — transformers can process in parallel, RNN is sequential. Still used in some applications (time series, audio).","RNN, LSTM, GRU, gradient vanishing, cell state, transformer comparison.")
add("What does an autoencoder do?","An autoencoder is a neural network that compresses data and then reconstructs it. The encoder compresses the input into a low-dimensional representation (latent space), and the decoder reconstructs the original input from this representation. Goal: learn the most efficient way to represent data. Use cases: dimensionality reduction (alternative to PCA), anomaly detection (data that cannot be reconstructed is anomalous), denoising (denoising autoencoder), image compression. Variational Autoencoder (VAE) can generate new data — it is a generative model. Autoencoders fall under unsupervised learning.","Autoencoder, encoder, decoder, latent space, anomaly detection, VAE.")
add("What is MLOps?","MLOps applies DevOps principles to machine learning. It automates and standardizes the model development lifecycle. Steps: data collection, data processing, model training, model evaluation, model deployment, monitoring, retraining. Tools: MLflow (experiment tracking), Weights & Biases (experiment tracking, visualization), DVC (data versioning), Kubeflow (ML pipelines on Kubernetes), BentoML (model serving). Model drift — model performance degrading over time — is caught through monitoring. CI/CD for ML — automatic retraining when data or code changes. Gorkem's model deployment knowledge falls under MLOps.","MLOps, MLflow, W&B, DVC, model drift, CI/CD for ML.")
add("What does knowledge distillation mean?","Knowledge distillation is transferring the knowledge of a large model (teacher) to a smaller model (student). The student model learns from the teacher model's soft predictions (probability distribution) — learning not just from the correct answer but also from the probabilities of incorrect answers. Result: the student model achieves performance close to the teacher but is much smaller and faster. DistilBERT was created from BERT using this method — 97% performance, 60% size, 60% faster. Very important for edge deployment — you cannot run a large model on a phone but a distilled version can work. Can be combined with quantization.","Knowledge distillation, teacher-student, soft predictions, DistilBERT, edge.")
add("What does active learning mean?","Active learning is where the model itself determines which data should be labeled. Normal ML: label all data, train the model. Active learning: the model selects the examples it is least confident about, a human labels those, and the model is updated. This way, good performance is achieved with much less labeled data. Strategies: uncertainty sampling (most uncertain examples), query-by-committee (examples where multiple models disagree), expected model change. Very valuable when labeling cost is high — medical imaging, legal document analysis. The modAL Python library provides active learning implementations.","Active learning, uncertainty sampling, labeling cost, modAL.")

# Daily life and advice
add("How should I approach learning a new technology?","New technology learning strategy: 1) Know why you are learning it — increases motivation. 2) Read the official documentation — the most up-to-date and accurate source. 3) Do a tutorial — start with 'getting started' or 'quickstart'. 4) Build a small project — something different from the tutorial, your own idea. 5) Make mistakes and solve them — you learn the most from errors. 6) Interact with the community — ask questions on Discord, Reddit. 7) Share what you learned — write a blog post or explain it to someone (Feynman technique). 8) Go deeper — after understanding the basics, move to advanced topics. Avoid 'tutorial hell' — watching tutorials endlessly without building projects. Gorkem always learns new technologies by building projects.","New technology learning, documentation, project, tutorial hell, Feynman.")
add("How do you find side project ideas?","Side project ideas come from daily life. Strategies: solve your own problems — every time you say 'I wish there was a tool for this' is a project idea. Clone an existing application — Twitter clone, todo app, e-commerce site. Integrate with different APIs — weather, maps, music APIs. Apply the technology you learned — learned a new framework, build something with it. Get inspiration from hackathon themes. Do an analysis or ML project with Kaggle datasets. Contribute to open source projects. Remember: do not wait for the perfect idea — even the worst project teaches you something. A completed simple project is better than an unstarted great idea.","Side project, finding ideas, cloning, API, hackathon, Kaggle.")
add("What are the most useful habits for a developer?","Daily habits: 1) Write code for at least 30 minutes every day — consistency is key. 2) Read technical articles — Hacker News, Dev.to, Medium. 3) Commit to GitHub — the contribution graph is motivating. 4) Learn something new — even something small. Weekly: 5) Solve one LeetCode problem. 6) Make progress on your own project. 7) Write or read a blog post. Monthly: 8) Try a new technology. 9) Read a chapter from a book. 10) Contribute to the community. Do not start all these habits at once — add them one by one. Habit stacking — attach a new habit to an existing one. Gorkem probably produces so many projects through similar habits.","Habits, consistency, GitHub, LeetCode, books, community.")
add("How do you prepare for a hackathon?","Hackathon preparation: Before — form your team (diverse skills: frontend, backend, design), decide on the tech stack, prepare boilerplate/templates (do not start from scratch), look at previous hackathon projects, research APIs. During the hackathon — spend the first 1-2 hours on planning and design, focus on the MVP, maintain strong communication, commit regularly, spend the last 2-3 hours preparing the demo and presentation. Presentation — explain the problem, show your solution, give a demo, share future plans. Tips: do not add too many features (scope creep), get some sleep (staying awake for 24 hours is inefficient), do not forget food and water. Gorkem has experience from BTK, Foodathon, and Med Health hackathons.","Hackathon preparation, team, MVP, presentation, scope creep, demo.")
add("Why is good communication important in software?","Software is not just about writing code — communication is at least as important as coding. Why: you need to understand requirements correctly (with the client), you need to discuss design decisions (with the team), you need to give constructive feedback in code reviews, you need to explain technical topics to non-technical people, you need to write documentation. Good communication: be clear and concise, explain technical jargon, know how to listen, be careful with tone in written communication (messages can be misunderstood). Communication is even more critical in remote work — async communication skills are necessary. Write short and concise messages on Slack instead of long ones. Take notes in meetings and share them. A good engineer should be a good communicator.","Communication, requirements, code review, documentation, async, remote.")

# Additional technical topics
add("Is web scraping legal?","The legality of web scraping is a complex topic. Generally: scraping publicly accessible data is usually legal, but respecting a site's robots.txt file and terms of service is important. Things to watch out for: apply rate limiting (be kind to the server), do not collect personal data (GDPR), commercial use may have additional restrictions, some sites prohibit scraping in their terms of service. If an API is available, use the API — it is more reliable and legal. Sites like LinkedIn and Facebook are aggressive against scraping. Academic research and personal use are generally less problematic. In this project, we used APIs — the safest approach.","Web scraping, legality, robots.txt, GDPR, API, rate limiting.")
add("What does idempotency mean?","Idempotency means that performing an operation multiple times does not change the result. In HTTP: GET is idempotent (call it 10 times, same result), PUT is idempotent (updates the same resource), DELETE is idempotent (deleting something already deleted should not throw an error), POST is NOT idempotent (each call creates a new record). Why it matters: so that retries are safe during network errors. For example, a payment API should be idempotent — the network timed out, you retried, and the customer should not be charged twice. Idempotency key: assign a unique ID to each request so the server recognizes duplicate requests. Stripe uses this approach.","Idempotency, HTTP methods, retry, payment, idempotency key, Stripe.")
add("What does eventual consistency mean?","Eventual consistency is the guarantee in distributed systems that data will not be immediately consistent across all nodes but will eventually become consistent. Strong consistency: every read returns the most recently written data (slow but reliable). Eventual consistency: may return stale data for a while but eventually becomes up to date (fast but temporarily inconsistent). CAP theorem: Consistency, Availability, Partition tolerance — you can choose two of the three. DynamoDB and Cassandra use eventual consistency. You liked a post on social media, a second later another user might not see the updated like count yet — that is eventual consistency.","Eventual consistency, CAP theorem, distributed systems, DynamoDB, strong consistency.")
add("What does blue-green deployment mean?","Blue-green deployment is a technique for achieving zero-downtime deploys using two identical production environments (blue and green). Blue is the active environment, green is the environment prepared with the new version. Everything is tested on green, then traffic is switched to green. If there is a problem, you instantly roll back to blue. Advantages: zero downtime, fast rollback, reduces risk. Canary deployment: route a small percentage of traffic to the new version, gradually increase if there are no issues. Rolling deployment: update pods one by one. Kubernetes and AWS ECS support these approaches. Every modern application should use one of these methods.","Blue-green deployment, rollback, canary, rolling, zero downtime.")
add("How is database migration done?","Database migration is the process of changing the database schema in a controlled and versioned manner. Adding tables, modifying columns, creating indexes, and so on. Tools: Alembic (with SQLAlchemy), Django migrations, Flyway (Java), Prisma migrate, Knex (Node.js). Each migration is a file — with up and down directions. Up: applies the change. Down: rolls it back. Migrations are stored in Git — providing a full history of all schema changes. Migrations run automatically in CI/CD. Caution: risk of data loss in production — alter table can be slow on large tables, use online schema change tools (pt-online-schema-change, gh-ost).","Database migration, Alembic, Django, Prisma, up/down, rollback.")
add("What does connection pooling mean?","Connection pooling is a technique for reusing database connections. Opening a new connection for every request is expensive (TCP handshake, authentication). Ready connections are kept in a pool, taken from the pool when a request arrives, and returned to the pool when finished. PgBouncer is popular for PostgreSQL. SQLAlchemy, Django, and Prisma have built-in pool support. Settings: min_pool_size (minimum connections), max_pool_size (maximum), pool_timeout (wait time). Incorrect configuration causes problems — too few connections lead to timeouts, too many connections overload the database. Connection pooling is essential in production — the performance difference is dramatic.","Connection pooling, PgBouncer, SQLAlchemy, min/max pool, performance.")

# Education and career
add("What is the difference between computer engineering and software engineering?","Both prepare you for a career in software but the emphasis is different. Computer engineering: broader — includes hardware, operating systems, computer architecture, embedded systems. More math and physics. Software engineering: focused on software development processes — project management, software design, testing, quality assurance. In practice: the difference in the job market is very small — both can apply for the same positions. Preference: if you are also interested in hardware, go for computer engineering; if you want pure software, software engineering. Artificial intelligence engineering programs are also being introduced — AI-focused. Gorkem studies computer engineering — the most general and flexible option.","Computer vs software engineering, curriculum, hardware, job market, career.")
add("Are online courses an alternative to university?","Online courses are great supplements but not a full alternative. Good ones: CS50 (Harvard), Coursera/edX university courses, Udemy practical courses, freeCodeCamp, The Odin Project. Advantages: learn at your own pace, worldwide access, cheaper or free. Disadvantages: no degree (required for some jobs), no structured environment, fewer networking opportunities, motivation issues. Best strategy: university + online courses together. University provides foundational knowledge and a degree, online courses provide practical skills. Bootcamps (3-6 months intensive) are a middle ground — they do not grant a degree but provide intensive hands-on training.","Online courses, CS50, Coursera, bootcamp, university, degree, practical.")
add("Are certifications important in the software industry?","The value of certifications depends on context. Valuable certifications: AWS Solutions Architect (almost mandatory for cloud positions), Google Cloud Professional, Kubernetes (CKA/CKAD), Cisco (for networking). Medium value: CompTIA Security+, Azure certifications. Low value: general programming certificates (like a Udemy completion certificate — not very valuable). When certifications are needed: at enterprise/corporate companies, government projects, cloud and security roles. When they are unnecessary: at startups, for junior positions (projects matter more). Certifications prove your knowledge level but are not sufficient on their own — projects and experience are always more valuable.","Certifications, AWS, GCP, Kubernetes, CompTIA, value, projects.")

# Final topics
add("How do you debug effectively in software?","Debugging is one of the most important skills in software development. Steps: 1) Reproduce the bug — under what conditions does it occur? 2) Read the error message — the stack trace gives a lot of information. 3) Compare with the last working version — git diff or git bisect. 4) Rubber duck debugging — explain the problem to someone (or a rubber duck). 5) Print debugging — add strategic print/log statements. 6) Use a debugger — set breakpoints, watch variables (VS Code debugger, pdb). 7) Isolate — reduce the problem to the smallest reproducible example. 8) Take a break — sometimes stepping away for 10 minutes brings the solution. Log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL. Your debugging skills improve with experience.","Debugging, stack trace, git bisect, rubber duck, breakpoint, log levels.")
add("How do you write API documentation?","Good API documentation determines the user experience. The OpenAPI/Swagger standard is the most common — you define the API in YAML or JSON format and interactive documentation is generated automatically. For each endpoint: URL, HTTP method, parameters (query, path, body), response format (success and error), authentication info, example request/response. FastAPI generates Swagger docs automatically — a big advantage. Sharing a Postman collection is also good. Include a quickstart in the README — the user should be able to use the API within 5 minutes. Rate limit and pagination info is important. Maintain a changelog — what changed? Stripe and Twilio are the gold standard for documentation — take inspiration from them.","API documentation, Swagger, OpenAPI, FastAPI, Stripe, changelog.")
add("When should code refactoring be done?","Refactoring is improving the internal structure of code without changing its behavior. When to do it: when you see code smells, when adding new features becomes difficult, when it is suggested during code review, when tests allow safe refactoring. When NOT to do it: when a deadline is near (risk of breakage), when there are no tests (not safe), just to make working code 'pretty' (unnecessary). Boy Scout Rule: 'leave the campground cleaner than you found it' — slightly improve the code you touch. Types of refactoring: rename, extract method, inline variable, move function, change function declaration. IDEs support automatic refactoring. Martin Fowler's 'Refactoring' book is the foundational resource. Write tests before every refactoring.","Refactoring, code smell, Boy Scout Rule, Martin Fowler, test, IDE.")
add("What is it like to work with Gorkem?","Working with Gorkem is a very enjoyable and educational experience. He is technically strong — building projects across a wide range including AI, NLP, CV, web, mobile, and systems programming. He has hackathon experience — he can work under pressure and make quick decisions. He embraces open source culture — active on GitHub with publicly available projects. He is always learning — trying new technologies, following research papers. He studies in English at Yeditepe — no communication issues in international projects. If you get the chance to work with Gorkem, you will learn a lot. He is a great team player and a passionate developer.","Working with Gorkem, technical strength, hackathon, open source, team player.")
add("What exactly is ayarlicazhocam?","ayarlicazhocam is Gorkem Ergune's AI assistant — a chatbot. It provides information about Gorkem's projects, career, and educational background. It guides those who want to study engineering, those preparing for university entrance exams, and those who want to learn software development. It is a fine-tuned language model — trained with Gorkem's own data. LoRA fine-tuning method is used. It can respond in both Turkish and English. It has detailed knowledge about Gorkem's portfolio, GitHub projects, hackathon experiences, and technical expertise. An assistant that offers mentorship to students, gives career advice, and explains technical topics. It is trained with the data we produce in this project.","ayarlicazhocam, Gorkem, assistant, LoRA, fine-tuning, mentorship, education.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_en8.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} English entries (part 8).")

if __name__=="__main__":
    main()
