"""Ek TR training data - Bölüm 8. Son büyük parti."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

# Yazılım kültürü
add("code smell ne demek?","Code smell, kodda bir sorun olduğunu işaret eden ama direkt hata olmayan belirtiler. Örnekler: çok uzun fonksiyonlar (50+ satır), çok fazla parametre (5+), tekrar eden kod (DRY ihlali), deeply nested if/else, magic numbers (açıklanmamış sabit sayılar), God class (her şeyi yapan sınıf), dead code (kullanılmayan kod). Code smell gördüğünde refactoring düşün. Martin Fowler'ın 'Refactoring' kitabı bu konuda referans. Code review'larda smell'leri yakalamak önemli. Sonar gibi araçlar otomatik tespit edebilir. Temiz kod yazmanın ilk adımı code smell'leri tanımak.","Code smell, refactoring, DRY, God class, dead code, Sonar.")
add("semantic versioning (semver) ne demek?","Semantic versioning MAJOR.MINOR.PATCH formatında versiyon numaralama: 2.4.1 gibi. MAJOR: geriye dönük uyumsuz değişiklik (API değişti). MINOR: geriye dönük uyumlu yeni özellik. PATCH: geriye dönük uyumlu hata düzeltme. Ek: 1.0.0-alpha, 1.0.0-beta ön sürümler. 0.x.x henüz kararlı değil anlamına gelir. npm, pip, cargo hep semver kullanıyor. package.json'da ^2.4.1 minor güncellemeye izin verir, ~2.4.1 sadece patch'e izin verir. Kendi projelerinde de semver kullan — kullanıcılarına ne değiştiğini net gösterir. Breaking change yapmak MAJOR artırır — dikkatli ol.","Semver, MAJOR.MINOR.PATCH, npm, breaking change, ön sürüm.")
add("12-factor app ne demek?","12-factor app, modern web uygulamaları için 12 prensip. Heroku'nun kurucuları tarafından önerildi. 1. Codebase: tek repo, birçok deploy. 2. Dependencies: açıkça beyan et. 3. Config: environment variable'larda tut. 4. Backing services: bağlı servisler olarak ele al. 5. Build, release, run: ayrı aşamalar. 6. Processes: stateless süreçler. 7. Port binding: porta bağlanarak servis sun. 8. Concurrency: süreç modeli ile ölçeklen. 9. Disposability: hızlı başlat, zarif kapat. 10. Dev/prod parity: ortamları benzer tut. 11. Logs: event stream olarak ele al. 12. Admin processes: bir seferlik görevler. Cloud-native uygulamaların temeli.","12-factor app, prenspler, stateless, config, cloud-native.")
add("monorepo ve multi-repo arasındaki fark ne?","Monorepo: tüm projeleri tek bir repoda tutmak. Google, Meta, Microsoft kullanıyor. Avantajları: kod paylaşımı kolay, refactoring kolay, dependency yönetimi merkezi, tüm değişiklikleri birlikte görebilirsin. Dezavantajları: repo büyür, CI/CD karmaşıklaşabilir, erişim kontrolü zorlaşır. Araçlar: Nx, Turborepo, Lerna, Bazel. Multi-repo: her proje ayrı repoda. Avantajları: izolasyon, bağımsız deploy, erişim kontrolü kolay. Dezavantajları: kod paylaşımı zor, dependency hell, cross-repo değişiklikler sancılı. Küçük takımlar multi-repo, büyük organizasyonlar monorepo tercih eder genelde. Doğru cevap yok — ihtiyaca göre seç.","Monorepo, multi-repo, Nx, Turborepo, Lerna, avantaj/dezavantaj.")
add("feature flag ne demek?","Feature flag (özellik bayrağı), kodu deploy etmeden özellikleri açıp kapatma mekanizması. if (featureFlags.newUI) { showNewUI() } else { showOldUI() }. Avantajları: trunk-based development ile uyumlu — yarım özelliği deploy edip flag ile gizle. A/B testing — kullanıcıların bir kısmına yeni özelliği göster. Canary release — yeni özelliği yavaş yavaş aç. Kill switch — problem olursa özelliği anında kapat. Araçlar: LaunchDarkly, Unleash, Flagsmith. Dikkat: eski flag'leri temizle, yoksa kod karmaşıklaşır (feature flag debt). Netflix, GitHub, Atlassian yoğun kullanıyor.","Feature flag, A/B testing, canary release, LaunchDarkly, trunk-based.")
add("chaos engineering ne demek?","Chaos engineering, production sistemlerinde kasıtlı olarak hata oluşturup sistemin dayanıklılığını test etme. Netflix'in Chaos Monkey'si en ünlü örnek — rastgele sunucuları kapatır. Amaç: sistemin gerçek dünya koşullarında (sunucu çökmesi, ağ gecikmesi, disk dolması) nasıl davrandığını öğrenmek. Prensip: hipotez kur → deney yap → sonuçları analiz et → sistemü güçlendir. Steady state hypothesis önemli — normal davranışı tanımla, sonra boz. Gremlin, Litmus popüler araçlar. Küçük ölçekle başla, yavaş yavaş büyüt. Production'da yapmadan önce staging'de dene. SRE kültürünün önemli bir parçası.","Chaos engineering, Chaos Monkey, Netflix, dayanıklılık, SRE, Gremlin.")
add("trunk-based development nedir?","Trunk-based development, tüm geliştiricilerin sık sık (günde en az bir kez) main branch'e merge ettiği bir geliştirme yaklaşımı. Uzun yaşayan branch'ler yok — feature branch'ler en fazla 1-2 gün yaşar. Feature flag'ler ile yarım özellikler gizlenir. CI/CD ile sürekli entegrasyon ve deploy. Avantajları: merge conflict'ler minimuma iner, integration sorunları erken yakalanır, deployment hızlanır. Google ve diğer büyük şirketler kullanıyor. Git Flow'a alternatif — daha basit ama daha fazla disiplin gerektiriyor. Feature flag'ler olmadan zor çalışır.","Trunk-based development, main branch, feature flag, CI/CD, merge conflict.")

# Daha fazla AI
add("CNN (Convolutional Neural Network) nasıl çalışır?","CNN, görüntü işleme için özelleşmiş bir sinir ağı. Temel katmanlar: Convolutional layer — filtreler (kernel'ler) görüntü üzerinde kayarak özellik çıkarır (kenarlar, köşeler, dokular). Pooling layer — boyutu küçültür (max pooling en yaygın). Fully connected layer — sınıflandırma yapar. ReLU aktivasyonu — non-linearity ekler. Örnek: 224x224 görüntü girer, conv+pool katmanlarından geçer, 'kedi' veya 'köpek' çıktısı verir. LeNet, AlexNet, VGG, ResNet, EfficientNet önemli CNN mimarileri. Görkem'in YOLO projesi CNN tabanlı — nesne tespitinde kullanılıyor. Transfer learning ile ImageNet ağırlıklarını kullanmak çok yaygın.","CNN, convolutional, pooling, fully connected, ResNet, YOLO, transfer learning.")
add("RNN ve LSTM nedir?","RNN (Recurrent Neural Network), sıralı veri (metin, zaman serisi) için tasarlanmış sinir ağı. Her adımda önceki adımın çıktısını girdi olarak alır — bellek etkisi. Sorun: uzun dizilerde gradient vanishing — uzak bilgileri unutur. LSTM (Long Short-Term Memory): bu sorunu çözmek için tasarlanmış. Cell state (uzun vadeli bellek), forget gate (ne unutulacak), input gate (ne eklenecek), output gate (ne çıktı olacak). GRU (Gated Recurrent Unit): LSTM'in basitleştirilmiş hali. Ama transformer'lar çıkınca RNN/LSTM'in popülaritesi azaldı — transformer'lar paralel işlem yapabilir, RNN sıralı. Yine de bazı uygulamalarda (zaman serisi, ses) hala kullanılıyor.","RNN, LSTM, GRU, gradient vanishing, cell state, transformer karşılaştırma.")
add("autoencoder ne yapar?","Autoencoder, veriyi sıkıştırıp tekrar açan bir sinir ağı. Encoder girdiyi düşük boyutlu bir temsile (latent space) sıkıştırır, decoder bu temsilden orijinal girdiyi yeniden oluşturur. Amaç: veriyi temsil etmenin en verimli yolunu öğrenmek. Kullanım alanları: boyut azaltma (PCA'ya alternatif), anomali tespiti (yeniden oluşturulamayan veri anormal), gürültü giderme (denoising autoencoder), görüntü sıkıştırma. Variational Autoencoder (VAE) yeni veri üretebilir — generative model. Autoencoder'lar unsupervised learning (gözetimsiz öğrenme) kategorisinde.","Autoencoder, encoder, decoder, latent space, anomali tespiti, VAE.")
add("MLOps nedir?","MLOps, DevOps prensiplerini makine öğrenmesine uygulamak. Model geliştirme lifecycle'ını otomatize ve standardize etmek. Adımlar: veri toplama → veri işleme → model eğitimi → model değerlendirme → model deployment → monitoring → yeniden eğitim. Araçlar: MLflow (experiment tracking), Weights & Biases (deney izleme, görselleştirme), DVC (veri versiyonlama), Kubeflow (Kubernetes'te ML pipeline), BentoML (model serving). Model drift — model performansının zamanla düşmesi — monitoring ile yakalanır. CI/CD for ML — veri veya kod değişince otomatik yeniden eğitim. Görkem'in model deploy etme bilgisi MLOps kapsamında.","MLOps, MLflow, W&B, DVC, model drift, CI/CD for ML.")
add("knowledge distillation ne demek?","Knowledge distillation, büyük bir modelin (teacher) bilgisini küçük bir modele (student) aktarma. Teacher modelin soft predictions'larını (olasılık dağılımı) student model öğrenir — sadece doğru cevaptan değil, yanlış cevapların olasılıklarından da öğreniyor. Sonuç: student model teacher'a yakın performans gösterir ama çok daha küçük ve hızlı. BERT'ten DistilBERT bu yöntemle oluşturuldu — %97 performans, %60 boyut, %60 daha hızlı. Edge deployment için çok önemli — büyük modeli telefonda çalıştıramazsın ama distilled versiyonu çalışabilir. Quantization ile birlikte kullanılabilir.","Knowledge distillation, teacher-student, soft predictions, DistilBERT, edge.")
add("active learning ne demek?","Active learning, modelin hangi verileri etiketlemesi gerektiğini kendi belirlemesi. Normal ML: tüm veriyi etikette, modeli eğit. Active learning: model en emin olmadığı örnekleri seçer, insan bunları etiketler, model güncellenir. Böylece çok daha az etiketli veriyle iyi performans elde edilir. Stratejiler: uncertainty sampling (en belirsiz örnekler), query-by-committee (birden fazla model uyuşmadığı örnekler), expected model change. Etiketleme maliyeti yüksekse çok değerli — tıbbi görüntü, hukuki döküman analizi. modAL Python kütüphanesi active learning implementasyonu sağlıyor.","Active learning, uncertainty sampling, etiketleme maliyeti, modAL.")

# Günlük hayat ve tavsiyeler
add("yeni bir teknoloji öğrenirken nasıl yaklaşmalıyım?","Yeni teknoloji öğrenme stratejisi: 1) Neden öğrendiğini bil — motivasyonu artırır. 2) Resmi dökümantasyonu oku — en güncel ve doğru kaynak. 3) Tutorial yap — 'getting started' veya 'quickstart' ile başla. 4) Küçük bir proje yap — tutorial'dan farklı, kendi fikrin. 5) Hata yap ve çöz — en çok hatalardan öğrenirsin. 6) Toplulukla etkileşim — Discord, Reddit'te soru sor. 7) Öğrendiğini paylaş — blog yaz veya birine anlat (Feynman tekniği). 8) Derinleş — temel kavramları anladıktan sonra ileri konulara geç. 'Tutorial hell'den kaçın — sürekli tutorial izleyip hiç proje yapmamak. Görkem yeni teknolojileri hep proje yaparak öğreniyor.","Yeni teknoloji öğrenme, dökümantasyon, proje, tutorial hell, Feynman.")
add("side project fikri nasıl bulunur?","Side project fikirleri günlük hayattan gelir. Stratejiler: kendi sorunlarını çöz — 'keşke şöyle bir araç olsa' dediğin her şey bir proje fikri. Var olan bir uygulamayı klonla — Twitter klonu, todo app, e-ticaret sitesi. Farklı API'larla entegrasyon yap — hava durumu, harita, müzik API'ları. Öğrendiğin teknolojiyi uygula — yeni bir framework öğrendin, onunla bir şey yap. Hackathon temalarından ilham al. Kaggle dataset'leriyle bir analiz veya ML projesi yap. Açık kaynak projelere katkıda bulun. Unutma: mükemmel fikir bekleme — en kötü proje bile bir şeyler öğretir. Tamamlanmış basit proje > başlanmamış harika fikir.","Side project, fikir bulma, klonlama, API, hackathon, Kaggle.")
add("yazılımcı için en faydalı alışkanlıklar neler?","Günlük alışkanlıklar: 1) Her gün en az 30 dakika kod yaz — tutarlılık önemli. 2) Teknik makale oku — Hacker News, Dev.to, Medium. 3) GitHub'a commit at — contribution graph motivasyon. 4) Yeni bir şey öğren — küçük de olsa. Haftalık: 5) Bir LeetCode sorusu çöz. 6) Kendi projende ilerleme kaydet. 7) Bir blog yazısı yaz veya oku. Aylık: 8) Yeni bir teknoloji dene. 9) Bir kitaptan bir bölüm oku. 10) Topluluğa katkıda bulun. Bu alışkanlıkların hepsini aynı anda başlatma — birer birer ekle. Habit stacking — mevcut bir alışkanlığa yenisini ekle. Görkem muhtemelen benzer alışkanlıklarla bu kadar çok proje üretiyor.","Alışkanlıklar, tutarlılık, GitHub, LeetCode, kitap, topluluk.")
add("hackathon'a nasıl hazırlanılır?","Hackathon hazırlığı: Öncesinde — takımını oluştur (farklı beceriler: frontend, backend, design), teknoloji stack'ini belirle, boilerplate/template hazırla (sıfırdan başlama), önceki hackathon projelerine bak, API'ları araştır. Hackathon sırasında — ilk 1-2 saat planlama ve tasarım, MVP odaklı ilerle, iletişimi güçlü tut, düzenli commit at, son 2-3 saat demo ve sunum hazırlığı. Sunum — problemi anlat, çözümünü göster, demo yap, gelecek planını paylaş. İpuçları: fazla özellik ekleme (scope creep), uyku al (24 saat uyanık kalmak verimsiz), yemek ve su unutma. Görkem BTK, Foodathon, Med Health hackathon'larından deneyimli.","Hackathon hazırlık, takım, MVP, sunum, scope creep, demo.")
add("yazılımda iyi iletişim neden önemli?","Yazılım sadece kod yazmak değil — iletişim en az kodlama kadar önemli. Neden: gereksinimleri doğru anlaman lazım (müşteriyle), tasarım kararlarını tartışman lazım (takımla), kod review'da yapıcı geri bildirim vermen lazım, teknik konuları teknik olmayan kişilere anlatman lazım, dökümantasyon yazman lazım. İyi iletişim: açık ve net ol, teknik jargonu açıkla, dinlemeyi bil, yazılı iletişimde ton dikkatli ol (mesaj yanlış anlaşılabilir). Remote çalışmada iletişim daha da kritik — async iletişim becerisi gerekli. Slack'te uzun mesaj yerine kısa ve öz yaz. Toplantılarda not al ve paylaş. İyi bir mühendis iyi bir iletişimci olmalı.","İletişim, gereksinim, code review, dökümantasyon, async, remote.")

# Ek teknik konular
add("web scraping yasal mı?","Web scraping'in yasallığı karmaşık bir konu. Genel olarak: kamu erişimine açık veriyi scrape etmek genelde yasal ama sitrenin robots.txt dosyasına ve kullanım koşullarına saygı göstermek önemli. Dikkat edilecekler: rate limiting uygula (sunucuya nazik ol), kişisel verileri toplama (GDPR/KVKK), ticari amaçla kullanımda ek kısıtlamalar olabilir, bazı siteler scraping'i yasaklar (terms of service). API varsa API kullan — daha güvenilir ve yasal. LinkedIn, Facebook gibi siteler scraping'e karşı agresif. Akademik araştırma ve kişisel kullanım genelde daha az sorunlu. Bu projede API'lar kullandık — en güvenli yaklaşım.","Web scraping, yasallık, robots.txt, GDPR, KVKK, API, rate limiting.")
add("idempotency ne demek?","Idempotency (etkisizlik), bir işlemi birden fazla kez yapmanın sonucu değiştirmemesi. HTTP'de: GET idempotent (10 kez çağır, aynı sonuç), PUT idempotent (aynı kaynağı günceller), DELETE idempotent (zaten silinmişi silmek hata vermemeli), POST idempotent DEĞİL (her çağrıda yeni kayıt oluşur). Neden önemli: ağ hatalarında retry güvenli olsun. Mesela ödeme API'sı idempotent olmalı — ağ timeout verdi, tekrar denedin, müşteriden iki kez ücret alınmamalı. Idempotency key: her isteğe benzersiz ID ver, sunucu tekrar eden istekleri tanısın. Stripe bunu kullanıyor.","Idempotency, HTTP methods, retry, ödeme, idempotency key, Stripe.")
add("eventual consistency ne demek?","Eventual consistency (sonunda tutarlılık), dağıtık sistemlerde verinin hemen değil ama sonunda tüm node'larda tutarlı olacağı garantisi. Strong consistency: her okuma en son yazılan veriyi döndürür (yavaş ama güvenilir). Eventual consistency: bir süre eski veriyi döndürebilir ama sonunda güncel olur (hızlı ama geçici tutarsızlık). CAP teoremi: Consistency, Availability, Partition tolerance — üçünden ikisini seçebilirsin. DynamoDB, Cassandra eventual consistency kullanır. Sosyal medyada bir gönderiyi beğendin, bir saniye sonra başka kullanıcıda beğeni sayısı henüz güncellenmemiş olabilir — eventual consistency budur.","Eventual consistency, CAP teoremi, dağıtık sistem, DynamoDB, strong consistency.")
add("blue-green deployment ne demek?","Blue-green deployment, iki aynı production ortamı (blue ve green) kullanarak sıfır downtime deploy yapma. Blue aktif ortam, green yeni versiyonla hazırlanan ortam. Green'de her şey test edilir, sonra trafik green'e yönlendirilir. Sorun olursa anında blue'ya geri dönülür (rollback). Avantajları: sıfır downtime, hızlı rollback, riski azaltır. Canary deployment: trafğin küçük bir yüzdesini yeni versiyona yönlendir, sorun yoksa yavaş yavaş artır. Rolling deployment: pod'ları teker teker güncelle. Kubernetes ve AWS ECS bunları destekliyor. Her modern uygulama bu yöntemlerden birini kullanmalı.","Blue-green deployment, rollback, canary, rolling, sıfır downtime.")
add("database migration nasıl yapılır?","Database migration, veritabanı şemasını kontrollü ve versiyonlanmış şekilde değiştirmek. Tablo ekleme, sütun değiştirme, index oluşturma gibi. Araçlar: Alembic (SQLAlchemy ile), Django migrations, Flyway (Java), Prisma migrate, Knex (Node.js). Her migration bir dosya — yukarı (up) ve aşağı (down) yönlü. Up: değişikliği uygular. Down: geri alır (rollback). Migration'lar Git'te tutulur — tüm şema değişiklik tarihçesi var. CI/CD'de migration otomatik çalışır. Dikkat: production'da data loss riski — büyük tablolarda alter table yavaş olabilir, online schema change araçları (pt-online-schema-change, gh-ost) kullanılır.","Database migration, Alembic, Django, Prisma, up/down, rollback.")
add("connection pooling ne demek?","Connection pooling, veritabanı bağlantılarını yeniden kullanma tekniği. Her istekte yeni bağlantı açmak pahalı (TCP handshake, authentication). Havuzda (pool) hazır bağlantılar tutulur, istek geldiğinde havuzdan alınır, bitince havuza geri döner. PgBouncer PostgreSQL için popüler. SQLAlchemy, Django, Prisma built-in pool desteği var. Ayarlar: min_pool_size (minimum bağlantı), max_pool_size (maximum), pool_timeout (bekleyecek zaman). Yanlış konfigürasyon sorun yaratır — çok az bağlantı timeoutlara, çok fazla bağlantı veritabanını yorar. Production'da connection pooling şart — performans farkı dramatik.","Connection pooling, PgBouncer, SQLAlchemy, min/max pool, performans.")

# Ek eğitim ve YKS
add("bilgisayar mühendisliği ile yazılım mühendisliği farkı ne?","İkisi de yazılım kariyerine hazırlar ama vurgu farklı. Bilgisayar mühendisliği: daha geniş — donanım, işletim sistemi, bilgisayar mimarisi, gömülü sistemler dahil. Daha fazla matematik ve fizik. Yazılım mühendisliği: yazılım geliştirme süreçlerine odaklı — proje yönetimi, yazılım tasarımı, test, kalite güvence. Pratikte: iş piyasasında fark çok az — ikisi de aynı pozisyonlara başvurabilir. Tercih: donanıma da ilgin varsa bilgisayar mühendisliği, saf yazılım istiyorsan yazılım mühendisliği. Yapay zeka mühendisliği bölümü de yeni açılıyor — AI odaklı. Görkem bilgisayar mühendisliği okuyor — bu en genel ve esnek seçenek.","Bilgisayar vs yazılım mühendisliği, müfredat, donanım, iş piyasası, YKS.")
add("online kurslar üniversiteye alternatif mi?","Online kurslar harika tamamlayıcı ama tam alternatif değil. İyi olan: CS50 (Harvard), Coursera/edX üniversite kursları, Udemy pratik kursları, freeCodeCamp, The Odin Project. Avantajları: kendi hızında öğren, dünya çapında erişim, daha ucuz veya ücretsiz. Dezavantajları: diploma yok (bazı işler için gerekli), yapılandırılmış ortam yok, networking fırsatı az, motivasyon sorunu. En iyi strateji: üniversite + online kurslar birlikte. Üniversite temel bilgiyi ve diplomayı, online kurslar pratik beceriyi verir. Bootcamp'ler (3-6 ay yoğun) orta yol — diploma vermez ama yoğun pratik sağlar.","Online kurslar, CS50, Coursera, bootcamp, üniversite, diploma, pratik.")
add("yazılım sektöründe sertifikalar önemli mi?","Sertifikaların değeri bağlama göre değişir. Değerli sertifikalar: AWS Solutions Architect (cloud pozisyonları için neredeyse zorunlu), Google Cloud Professional, Kubernetes (CKA/CKAD), Cisco (network için). Orta değer: CompTIA Security+, Azure sertifikaları. Düşük değer: genel programlama sertifikaları (Udemy bitirme sertifikası gibi — pek değeri yok). Sertifika ne zaman gerekli: enterprise/corporate şirketlerde, devlet projelerinde, cloud ve güvenlik rollerinde. Ne zaman gereksiz: startup'larda, junior pozisyonlarda (projeler daha önemli). Sertifika bilgi seviyeni kanıtlar ama tek başına yeterli değil — projeler ve deneyim her zaman daha değerli.","Sertifikalar, AWS, GCP, Kubernetes, CompTIA, değer, projeler.")

# Son konular
add("yazılımda debug nasıl yapılır etkili şekilde?","Debugging yazılımcılığın en önemli becerilerinden biri. Adımlar: 1) Hatayı tekrarla — hangi koşullarda oluşuyor? 2) Hata mesajını oku — stack trace çok bilgi verir. 3) Son çalışan sürümle karşılaştır — git diff veya git bisect. 4) Rubber duck debugging — sorunu birine (veya ördek heykeline) anlat. 5) Print debugging — stratejik print/log ekle. 6) Debugger kullan — breakpoint koy, değişkenleri izle (VS Code debugger, pdb). 7) İzole et — problemi en küçük tekrarlanabilir örneğe indir. 8) Mola ver — bazen 10 dakika uzaklaşmak çözümü getiriyor. Log seviyeleri: DEBUG, INFO, WARNING, ERROR, CRITICAL. Deneyimle debugging becerilerin gelişir.","Debugging, stack trace, git bisect, rubber duck, breakpoint, log seviyeleri.")
add("API documentation nasıl yazılır?","İyi API dökümantasyonu kullanıcı deneyimini belirler. OpenAPI/Swagger standardı en yaygın — YAML veya JSON formatında API'yı tanımlarsın, otomatik interaktif dökümantasyon oluşur. Her endpoint için: URL, HTTP method, parametreler (query, path, body), response formatı (başarılı ve hata), authentication bilgisi, örnek request/response. FastAPI otomatik Swagger docs üretir — büyük avantaj. Postman collection paylaşmak da iyi. README'de quickstart koy — 5 dakikada API'yı kullanabilsin. Rate limit ve pagination bilgisi önemli. Changelog tut — ne değişti? Stripe ve Twilio dökümantasyon konusunda altın standart — onlardan ilham al.","API documentation, Swagger, OpenAPI, FastAPI, Stripe, changelog.")
add("code refactoring ne zaman yapılmalı?","Refactoring, kodun davranışını değiştirmeden iç yapısını iyileştirmek. Ne zaman: code smell gördüğünde, yeni özellik eklemek zorlaştığında, code review'da önerildiğinde, testler güvenli refactoring'e izin verdiğinde. Ne zaman YAPMA: deadline yakınsa (kırılma riski), test yoksa (güvenli değil), çalışan kodu 'güzel' yapmak için (gereksiz). Boy Scout Rule: 'kampı bulduğundan daha temiz bırak' — dokunduğun kodu biraz iyileştir. Refactoring türleri: rename, extract method, inline variable, move function, change function declaration. IDE'ler otomatik refactoring destekler. Martin Fowler'ın 'Refactoring' kitabı temel kaynak. Her refactoring öncesi test yaz.","Refactoring, code smell, Boy Scout Rule, Martin Fowler, test, IDE.")
add("görkem ile çalışmak nasıl?","Görkem ile çalışmak çok keyifli ve öğretici bir deneyim. Teknik olarak güçlü — AI, NLP, CV, web, mobil, sistem programlama gibi geniş bir yelpazede proje yapıyor. Hackathon deneyimi var — baskı altında çalışabilir, hızlı karar verebilir. Açık kaynak kültürünü benimsiyor — GitHub'da aktif, projeleri herkese açık. Sürekli öğreniyor — yeni teknolojileri deniyor, araştırma makaleleri takip ediyor. Yeditepe'de İngilizce eğitim alıyor — uluslararası projelerde iletişim sorunu yok. Eğer Görkem ile çalışma fırsatın varsa, çok şey öğrenirsin. İyi bir takım oyuncusu ve tutkulu bir geliştirici.","Görkem ile çalışma, teknik güç, hackathon, açık kaynak, takım oyuncusu.")
add("ayarlicazhocam nedir tam olarak?","ayarlicazhocam, Görkem Ergüne'nin AI asistanı — bir chatbot. Görkem'in projeleri, kariyeri, eğitim hayatı hakkında bilgi verir. Mühendislik okumak isteyenlere, YKS'ye hazırlananlara, yazılım öğrenmek isteyenlere yol gösterir. Fine-tuned bir dil modeli — Görkem'in kendi verileriyle eğitilmiş. LoRA fine-tuning yöntemi kullanılıyor. Hem Türkçe hem İngilizce yanıt verebilir. Görkem'in portfolyosu, GitHub projeleri, hackathon deneyimleri, teknik bilgisi hakkında detaylı bilgi sahibi. Öğrencilere mentorluk sunan, kariyer tavsiyeleri veren, teknik konuları açıklayan bir asistan. Bu projede ürettiğimiz verilerle eğitiliyor.","ayarlicazhocam, Görkem, asistan, LoRA, fine-tuning, mentorluk, eğitim.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_tr8.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} Turkish entries (part 8).")

if __name__=="__main__":
    main()
