"""Extra EN training data - Part 21. Networking Deep, Linux, Git Advanced, Algorithms, Data Structures."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

add("what are the most important Linux commands for developers?","Essential Linux commands every developer should know. File operations: ls -la (list with details), cp, mv, rm, mkdir -p, find . -name '*.py', chmod/chown (permissions). Text processing: grep -rn 'pattern' (recursive search), sed 's/old/new/g' (stream edit), awk '{print $1}' (column processing), cat/head/tail/less (view files), wc -l (line count), sort | uniq (unique values). Process management: ps aux (list processes), top/htop (resource usage), kill -9 PID, lsof -i :8080 (what's using port 8080), nohup command & (run in background). Networking: curl (HTTP requests), wget (download), netstat/ss (network connections), ping, traceroute, dig (DNS lookup). System: df -h (disk space), du -sh * (directory sizes), free -h (memory), uname -a (system info). Package management: apt (Debian/Ubuntu), yum/dnf (RHEL/Fedora), brew (macOS). Shell: pipe | (chain commands), > (redirect output), >> (append), 2>&1 (redirect stderr), && (run if previous succeeds), || (run if previous fails). Learn these and you can navigate any server confidently.","Linux commands, grep, sed, awk, process management, networking, shell, pipe.")

add("what is SSH and how to use it securely?","SSH (Secure Shell) provides encrypted remote access to servers. Basic: ssh user@hostname. Key-based authentication (recommended over passwords): ssh-keygen -t ed25519 generates key pair. Copy public key to server: ssh-copy-id user@hostname. Now login without password. SSH config file (~/.ssh/config): Host myserver, HostName 192.168.1.100, User admin, IdentityFile ~/.ssh/id_ed25519 — then just ssh myserver. Security best practices: 1) Disable password authentication (PasswordAuthentication no in sshd_config). 2) Disable root login (PermitRootLogin no). 3) Use non-standard port (Port 2222). 4) Use fail2ban to block brute force attempts. 5) Use SSH keys with passphrase. 6) Keep OpenSSH updated. Advanced: SSH tunneling (ssh -L 8080:localhost:5432 server — access remote PostgreSQL locally), SSH agent forwarding (ssh -A — use local keys on remote server), jump hosts (ProxyJump in config), scp/rsync for file transfer. SSH is the foundation of server management — every developer must be comfortable with it.","SSH, key-based auth, ed25519, SSH config, tunneling, security, fail2ban, scp.")

add("what is Git rebase vs merge?","Both integrate changes from one branch to another but work differently. Merge: creates a merge commit that combines two branch histories. Non-destructive — preserves complete history. Results in a merge commit with two parents. Good for: shared branches, preserving full history. Rebase: replays your commits on top of the target branch — creates new commits with different hashes. Results in a linear history. git rebase main on your feature branch moves your commits after main's latest. Good for: clean commit history, feature branches before merging. Interactive rebase (git rebase -i HEAD~5): reorder commits, squash multiple commits into one, edit commit messages, drop commits. Powerful for cleaning up before PR. Golden rule: NEVER rebase commits that have been pushed to a shared branch — it rewrites history and causes conflicts for others. Safe workflow: rebase your local feature branch onto main, then merge (or squash merge) into main. Squash merge: all feature branch commits become one commit on main — cleanest history but loses individual commit granularity. Choose based on team convention — consistency matters more than the specific choice.","Git rebase, merge, interactive rebase, squash, linear history, golden rule, workflow.")

add("what is Git bisect and how to use it?","Git bisect uses binary search to find the commit that introduced a bug. Process: 1) git bisect start. 2) git bisect bad (current commit has the bug). 3) git bisect good v1.0 (this commit was working). 4) Git checks out a middle commit — you test it. 5) git bisect good or git bisect bad based on your test. 6) Repeat until Git identifies the exact commit. 7) git bisect reset when done. With N commits, it finds the bug in log2(N) steps — 1000 commits needs only ~10 tests. Automated bisect: git bisect run ./test.sh — provide a script that exits 0 for good, non-zero for bad. Git runs it automatically. Example: git bisect run pytest tests/test_login.py — automatically finds which commit broke login tests. Tips: write regression tests for bugs — then bisect can be fully automated. Works best with small, atomic commits (another reason for clean commit history). This is one of Git's most underused but powerful features. Every developer should know about it.","Git bisect, binary search, bug finding, automated bisect, regression test, debugging.")

add("what are the essential data structures?","Core data structures every developer should understand. Array/List: contiguous memory, O(1) access by index, O(n) insert/delete. Best for: ordered collections, random access. Linked List: nodes with pointers, O(1) insert/delete at known position, O(n) access. Best for: frequent insertions, implementing stacks/queues. Stack: LIFO (Last In First Out). Push/pop O(1). Use cases: function call stack, undo/redo, expression evaluation, DFS. Queue: FIFO (First In First Out). Enqueue/dequeue O(1). Use cases: BFS, task scheduling, message queues. Hash Table/Map: key-value pairs, O(1) average lookup/insert. Use cases: caching, counting, deduplication. Collision handling: chaining, open addressing. Tree: hierarchical structure. Binary Search Tree: O(log n) operations (if balanced). Self-balancing: AVL, Red-Black Tree. B-Tree: used in databases for indexing. Heap: priority queue, O(log n) insert, O(1) find-min/max. Graph: nodes and edges. Adjacency list vs matrix. BFS, DFS, Dijkstra, topological sort. Trie: prefix tree for string operations — autocomplete, spell check. Choose the right data structure for your access pattern — it matters more than algorithm optimization.","Data structures, array, linked list, stack, queue, hash table, tree, graph, heap, trie.")

add("what are important sorting algorithms?","Sorting algorithms every developer should understand. Bubble Sort: repeatedly swap adjacent elements. O(n²). Educational only — never use in practice. Selection Sort: find minimum, place at start, repeat. O(n²). Simple but slow. Insertion Sort: insert each element into its correct position. O(n²) worst case but O(n) for nearly sorted data. Good for small arrays. Merge Sort: divide array in half, sort each half, merge. O(n log n) always. Stable. O(n) extra space. Good for linked lists and external sorting. Quick Sort: pick pivot, partition around it, recurse. O(n log n) average, O(n²) worst case. In-place (O(log n) stack space). Fastest in practice for most cases. Used by most standard libraries. Heap Sort: build max-heap, extract max repeatedly. O(n log n) always. In-place. Not stable. Counting Sort: count occurrences, O(n+k) where k is range. Non-comparison based. Good for integers in known range. Radix Sort: sort by each digit. O(d*(n+k)). Good for fixed-length strings, integers. Tim Sort: hybrid merge+insertion sort. Used by Python and Java. O(n log n). Stable. Optimized for real-world data patterns. In practice: use your language's built-in sort (Tim Sort or Introsort) — they're highly optimized.","Sorting, Quick Sort, Merge Sort, Heap Sort, Tim Sort, O(n log n), comparison, stable.")

add("what are graph algorithms every developer should know?","Graph algorithms solve problems involving networks and relationships. BFS (Breadth-First Search): explore level by level using queue. O(V+E). Use cases: shortest path in unweighted graph, finding connected components, web crawling. DFS (Depth-First Search): explore as deep as possible using stack/recursion. O(V+E). Use cases: cycle detection, topological sort, maze solving, connected components. Dijkstra's Algorithm: shortest path from source to all vertices in weighted graph (non-negative weights). O((V+E) log V) with min-heap. Use case: GPS navigation, network routing. Bellman-Ford: shortest path with negative weights. O(VE). Detects negative cycles. A* Search: Dijkstra + heuristic. Faster pathfinding when you have domain knowledge (straight-line distance). Used in games and robotics. Topological Sort: linear ordering of vertices in DAG. Use cases: task scheduling, build dependencies, course prerequisites. Kruskal's/Prim's: minimum spanning tree. Connect all vertices with minimum total edge weight. Union-Find: efficient connected component tracking. Used in Kruskal's and social network analysis. In practice: most developers use graph databases (Neo4j) or libraries (NetworkX) rather than implementing from scratch — but understanding the algorithms helps you choose the right approach.","Graph algorithms, BFS, DFS, Dijkstra, A*, topological sort, MST, Union-Find.")

add("what is dynamic programming?","Dynamic programming (DP) solves complex problems by breaking them into overlapping subproblems. Key insight: if the same subproblem is solved multiple times, store the result and reuse it. Two approaches: 1) Top-down (memoization): solve recursively, cache results. Natural extension of recursive thinking. Example: fibonacci(n) — store fib(k) once computed. 2) Bottom-up (tabulation): solve smallest subproblems first, build up. Usually more efficient (no recursion overhead). Example: fill array from fib[0] to fib[n]. Classic DP problems: Fibonacci (intro), coin change (minimum coins for amount), longest common subsequence, knapsack problem, edit distance (Levenshtein), longest increasing subsequence, matrix chain multiplication. How to identify DP problems: optimal substructure (optimal solution contains optimal solutions to subproblems) + overlapping subproblems (same subproblem solved multiple times). DP is one of the hardest interview topics — practice is key. Start with 1D DP, then 2D, then more complex. LeetCode has excellent DP problem sets organized by difficulty.","Dynamic programming, memoization, tabulation, subproblems, knapsack, LCS, coin change.")

add("what is the difference between REST API authentication methods?","Multiple ways to authenticate API requests. API Key: simple string passed in header (X-API-Key: abc123) or query parameter. Easy to implement but no user context, hard to rotate, leaked keys are dangerous. Good for: server-to-server, public APIs with rate limiting. Basic Auth: username:password base64 encoded in Authorization header. Simple but credentials sent with every request (always use HTTPS). Good for: internal tools, simple integrations. Bearer Token (JWT): Authorization: Bearer <token>. Stateless, contains user info (claims), signed, expires. Most common for modern APIs. Good for: web/mobile apps, microservices. OAuth 2.0: authorization framework for third-party access. Access tokens + refresh tokens. Good for: 'Sign in with Google/GitHub', third-party API access. API keys for identification + OAuth for authorization is a common pattern. Session-based: cookie with session ID, server stores session data. Good for: traditional web apps. mTLS (mutual TLS): both client and server present certificates. Good for: service-to-service in zero-trust networks. Choose based on: who's the consumer (user vs service), security requirements, complexity tolerance.","API authentication, API key, JWT, Bearer token, OAuth, Basic Auth, mTLS, session.")

add("what is container orchestration beyond Kubernetes?","While Kubernetes dominates container orchestration, alternatives exist. Docker Swarm: built into Docker, simple setup, good for smaller deployments. Less feature-rich than K8s but much simpler. Docker Compose for development, Swarm for production — natural progression. Nomad (HashiCorp): not just containers — orchestrates containers, VMs, and standalone applications. Simpler than K8s, integrates with Vault and Consul. Good for: mixed workloads, teams already using HashiCorp stack. Amazon ECS: AWS-native container orchestration. Simpler than K8s, deep AWS integration (IAM, CloudWatch, ALB). Two launch types: EC2 (manage your instances) and Fargate (serverless containers — no instances to manage). Google Cloud Run: serverless containers — deploy a container, get a URL. Scales to zero. Pay per request. Perfect for APIs and microservices. Azure Container Apps: similar to Cloud Run, built on Kubernetes but abstracts it away. When to use K8s: large scale, multi-cloud, need full control, complex networking/scheduling requirements. When not to: small team, few services, don't want operational overhead — use managed services (ECS, Cloud Run) instead.","Container orchestration, Docker Swarm, Nomad, ECS, Fargate, Cloud Run, Kubernetes alternatives.")

add("what is the difference between monorepo tools?","Monorepo tools manage multiple packages/projects in a single repository. Turborepo: fast builds with intelligent caching (local + remote). Understands task dependencies. Minimal config. Best for: TypeScript/JavaScript projects, teams wanting simplicity. Nx: full-featured monorepo toolkit. Computation caching, affected detection (only test what changed), dependency graph visualization, code generators, plugins for React, Angular, Node. Best for: large teams, enterprise. Lerna: original JS monorepo tool. Manages versioning and publishing of npm packages. Now maintained by Nx team. Best for: npm package publishing. Bazel: Google's build system. Supports any language. Hermetic builds (reproducible), distributed caching, remote execution. Steep learning curve. Best for: large polyglot monorepos (Google has everything in one repo). Rush: Microsoft's monorepo tool. Phantom dependency detection, incremental builds. Best for: large npm monorepos. pnpm workspaces: simple monorepo support with pnpm's efficient node_modules structure (symlinks, not copies). Best for: lightweight monorepo without extra tools. Start with Turborepo (simplest) or Nx (most features) for JavaScript projects.","Monorepo, Turborepo, Nx, Lerna, Bazel, Rush, pnpm, workspaces, caching.")

add("what is caching strategies for web applications?","Caching stores computed results to serve future requests faster. Layers: 1) Browser cache — Cache-Control headers (max-age, no-cache, no-store, immutable). Versioned assets (style.abc123.css) with long max-age. 2) CDN cache — edge servers cache static and dynamic content. Vary header for content negotiation. 3) Application cache — Redis/Memcached for computed data (API responses, session data, user profiles). 4) Database cache — query result cache, materialized views. Patterns: Cache-aside (lazy loading): check cache → miss → query DB → store in cache → return. Most common. Write-through: write to cache and DB simultaneously. Consistent but slower writes. Write-behind: write to cache, asynchronously write to DB. Fast writes but risk of data loss. Invalidation strategies: TTL (time-based expiry), event-based (invalidate on update), versioning. Cache invalidation is famously one of the two hard problems in CS (along with naming things and off-by-one errors). Common issues: thundering herd (many requests hit DB when cache expires — use mutex/lock), cache stampede, stale data. Redis features for caching: TTL, LRU eviction, pub/sub for invalidation.","Caching, Redis, Cache-aside, write-through, TTL, CDN, Cache-Control, invalidation.")

add("what is the event loop in JavaScript?","JavaScript is single-threaded — the event loop handles concurrency. Call Stack: executes code synchronously, one function at a time. When you call a function, it's pushed onto the stack; when it returns, it's popped. Web APIs / Node APIs: handle async operations (setTimeout, fetch, DOM events, file I/O). These run in separate threads provided by the runtime. Callback Queue (Task Queue): callbacks from completed async operations wait here. Microtask Queue: Promises (.then), MutationObserver, queueMicrotask. Higher priority than callback queue. Event Loop: continuously checks if call stack is empty → drains microtask queue first → then takes one task from callback queue → pushes to call stack. This is why setTimeout(fn, 0) doesn't execute immediately — it goes to the callback queue and waits for the stack and microtask queue to empty. Promise resolution order: console.log('1'), setTimeout(() => console.log('2'), 0), Promise.resolve().then(() => console.log('3')). Output: 1, 3, 2 — microtasks (promises) before macrotasks (setTimeout). Understanding the event loop is essential for debugging async JavaScript behavior and avoiding blocking the main thread.","Event loop, call stack, microtask, macrotask, callback queue, Promise, setTimeout, async.")

add("what is WebAssembly System Interface WASI?","WASI extends WebAssembly beyond the browser — providing a standardized interface for system resources. WebAssembly in the browser: sandboxed, accesses only browser APIs. WASI: standardized API for file system, networking, clocks, random numbers — making Wasm a universal runtime. Benefits: 1) Portable — Wasm + WASI binary runs anywhere (Linux, macOS, Windows, embedded). 2) Sandboxed — capability-based security, programs only access resources explicitly granted. 3) Fast — near-native performance. 4) Language-agnostic — compile C, Rust, Go, Python to Wasm. Use cases: serverless functions (Cloudflare Workers, Fermyon), plugin systems (Envoy, Zellij terminal), portable CLI tools, edge computing, embedded systems. Docker integration: docker run with Wasm runtime (WasmEdge, Wasmtime). Runtimes: Wasmtime (reference implementation, Bytecode Alliance), Wasmer, WasmEdge (optimized for cloud-native), wazero (Go, zero dependencies). Component Model: composable Wasm modules with defined interfaces — the future of Wasm ecosystem. Solomon Hykes: 'If WASM+WASI existed in 2008, we wouldn't have needed Docker.'","WASI, WebAssembly, portable, sandboxed, Wasmtime, Wasmer, edge computing, Docker, serverless.")

add("what is zero-trust security?","Zero-trust is a security model where nothing is trusted by default — every request must be verified, regardless of location. Traditional security: castle-and-moat — trusted inside the network, untrusted outside. Problem: once an attacker gets inside, they have full access. Zero-trust principles: 1) Never trust, always verify — authenticate and authorize every request. 2) Least privilege — grant minimum necessary access. 3) Assume breach — design systems assuming attackers are already inside. Implementation: 1) Identity verification — strong authentication (MFA), SSO, identity provider (Okta, Auth0). 2) Device verification — is the device managed, patched, compliant? 3) Network microsegmentation — isolate services, no flat network. 4) Encryption everywhere — mTLS between services, encrypt data at rest. 5) Continuous monitoring — log everything, detect anomalies. Technologies: mTLS (mutual TLS between services), service mesh (Istio), BeyondCorp (Google's zero-trust implementation), ZTNA (Zero Trust Network Access — replaces VPN). Zero-trust is not a product you buy — it's an architecture approach. Relevant for any developer building secure systems.","Zero-trust, never trust always verify, least privilege, mTLS, microsegmentation, BeyondCorp.")

add("what is trunk-based development in detail?","Trunk-based development (TBD) is a branching strategy where all developers commit to a single branch (main/trunk). Rules: 1) Commit to main at least daily. 2) Feature branches live at most 1-2 days. 3) Keep main always deployable. 4) Use feature flags to hide incomplete features. Why: short-lived branches reduce merge conflicts, enable continuous integration, faster feedback loops, simpler mental model. Feature flags: code is deployed but features are toggled off until ready. Tools: LaunchDarkly, Unleash, Flagsmith, or simple config. Techniques for large features: branch by abstraction (introduce abstraction layer, implement new behind it, switch, remove old), feature flags (toggle visibility), dark launching (deploy but don't expose to users, test with synthetic traffic). Pair with: CI/CD (automated tests gate commits), code review (pair programming or quick async reviews), comprehensive test suite (confidence that main is always deployable), monitoring (detect issues quickly after deploy). Google, Facebook, Netflix, LinkedIn use trunk-based development. It requires discipline and strong CI/CD but results in faster delivery and fewer integration problems.","Trunk-based development, feature flags, branch by abstraction, CI/CD, continuous integration.")

add("what is the difference between stateful and stateless applications?","Stateful: application maintains state between requests — remembers previous interactions. Examples: database connections, WebSocket connections, shopping cart in server memory. If the server crashes, state is lost. Scaling is harder — requests from the same user must go to the same server (sticky sessions). Stateless: each request contains all information needed to process it — server doesn't remember previous requests. Examples: REST APIs (each request includes auth token and all data), serverless functions. Benefits: easy horizontal scaling (any server can handle any request), simpler recovery (just restart), no session synchronization needed. Making applications stateless: 1) Store session data in external store (Redis, database). 2) Use JWTs for authentication (token contains user info). 3) Store files in object storage (S3), not local filesystem. 4) Use external caches (Redis) instead of in-memory caches. 5) Store job state in a queue (Kafka, SQS), not process memory. The 12-Factor App principle: processes should be stateless and share-nothing. In practice, most modern web applications are stateless by design — state lives in databases, caches, and object stores, not in application processes.","Stateful, stateless, session, horizontal scaling, Redis, JWT, 12-Factor, share-nothing.")

add("how do you handle secrets in applications?","Secrets management is critical — leaked credentials cause data breaches. Never do: hardcode secrets in code, commit to git, store in plaintext config files, log secrets, share via chat/email. Environment variables: basic approach — store in .env (never committed), inject at deployment. Better than hardcoding but still plaintext on disk. Secret managers: AWS Secrets Manager, Google Secret Manager, Azure Key Vault, HashiCorp Vault — encrypted storage, access control, rotation, audit logs. Best approach. Kubernetes: Secrets resource (base64 encoded, not encrypted by default — use Sealed Secrets, external-secrets-operator, or SOPS for encryption). CI/CD: GitHub Actions Secrets, GitLab CI Variables — encrypted, injected at runtime. Rotation: regularly rotate secrets, automate with secret manager. If compromised: revoke immediately, rotate, audit access logs. Git history: if secret was ever committed, it's in history forever. Use git-secrets (pre-commit hook to prevent), BFG Repo-Cleaner or git filter-branch to remove from history. .env.example: commit a template with dummy values for documentation. Gorkem's projects should always use environment variables at minimum, secret managers for production.","Secrets management, Vault, AWS Secrets Manager, environment variables, rotation, git-secrets.")

add("what is the difference between SQL transactions isolation levels?","Transaction isolation levels control how concurrent transactions interact. Read Uncommitted: can read uncommitted changes from other transactions (dirty reads). Fastest but least safe. Almost never used. Read Committed: only see committed data. But same query in same transaction can return different results if another transaction commits between reads (non-repeatable reads). PostgreSQL default. Repeatable Read: consistent snapshot at start of transaction. Same query returns same results throughout transaction. But phantom reads possible (new rows matching query added by other transaction). MySQL InnoDB default. Serializable: transactions execute as if serial (one after another). Prevents all anomalies but slowest — locks extensively or uses MVCC. Anomalies: dirty read (reading uncommitted data), non-repeatable read (row changes between reads), phantom read (new rows appear between reads). PostgreSQL uses MVCC (Multi-Version Concurrency Control) — snapshots instead of locks. Each transaction sees a consistent snapshot. Practical advice: Read Committed works for most applications. Use Serializable for financial transactions where absolute consistency is required. Always handle serialization errors with retry logic.","Transaction isolation, Read Committed, Repeatable Read, Serializable, MVCC, dirty read, phantom.")

add("what is content negotiation in HTTP?","Content negotiation allows clients and servers to agree on the format of data exchanged. Server-driven: client sends Accept header, server responds with the best match. Accept: application/json (prefer JSON), Accept: text/html (prefer HTML), Accept: application/xml (prefer XML). Accept-Language: en-US,en;q=0.9,tr;q=0.8 (prefer English, then Turkish). Accept-Encoding: gzip, br (compression). The server responds with Content-Type header indicating the chosen format. Quality factor (q=0.9): preference weight from 0 to 1. If server can't satisfy any preference, return 406 Not Acceptable. In REST APIs: typically support JSON (default) and optionally XML. Use Content-Type for request body format (what the client sends), Accept for response format (what the client wants). Vary header: tells caches that response varies by certain request headers — Vary: Accept, Accept-Encoding. Important for CDN caching with different content types. Agent-driven: server sends 300 Multiple Choices with available options, client picks one. Rarely used in practice.","Content negotiation, Accept header, Content-Type, quality factor, Vary, 406, HTTP.")

add("what is the importance of documentation in software?","Documentation is the difference between a usable project and an abandoned one. Types: 1) README — first thing people see. Project purpose, installation, quick start, usage examples. 2) API documentation — endpoints, parameters, responses, error codes. Tools: Swagger/OpenAPI, Redoc, Postman. 3) Architecture documentation — system overview, component interactions, data flow. C4 model (context, container, component, code). 4) ADRs (Architecture Decision Records) — why we chose X over Y. Invaluable for future developers. 5) Runbooks — step-by-step guides for common operations (deployment, incident response). 6) Code comments — explain WHY, not WHAT. The code tells what, comments tell why. 7) Onboarding docs — getting a new developer productive quickly. Writing tips: write for your audience (developers vs users vs stakeholders), keep it updated (outdated docs are worse than no docs), use examples liberally, structure with headers and lists, include diagrams (Mermaid, draw.io). Docs as code: store documentation in git alongside code, review in PRs, generate sites (Docusaurus, MkDocs, GitBook). The best documentation is the documentation that exists and is maintained.","Documentation, README, API docs, ADR, runbook, Docusaurus, code comments, onboarding.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_en21.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} English entries (part 21).")
if __name__=="__main__":
    main()
