"""Extra TR training data - Part 25. Microservices, Event-Driven, GraphQL, WebSockets, Testing, API Design."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

add("microservices mimarisi nedir ne zaman kullanılmalı?","Microservices, uygulamayı küçük bağımsız servislere ayıran bir mimari. Her servis kendi veritabanına sahip, bağımsız deploy edilebilir, farklı teknoloji kullanabilir. Monolith ile karşılaştırma: tek deployable birim, paylaşılan veritabanı, tek codebase. Microservices avantajları: bağımsız deployment (auth servisini payments'a dokunmadan deploy et), teknoloji esnekliği (ML servisi Python, API gateway Go), bağımsız ölçeklendirme (search servisini ayrı scale et), hata izolasyonu (bir servis çökünce diğerleri çalışmaya devam eder), ekip otonomisi (küçük ekipler servislere end-to-end sahip olur). Zorluklar: dağıtık sistem karmaşıklığı (ağ hataları, gecikme), servisler arası veri tutarlılığı (eventual consistency, saga pattern), operasyonel yük (container orchestration, service discovery, monitoring gerekir), servisler arası hata ayıklama (Jaeger/Zipkin ile distributed tracing). Ne zaman kullanmalı: büyük ekipler (Conway Yasası), farklı ölçeklendirme ihtiyaçları, polyglot gereksinimler. Ne zaman KULLANMAMALI: küçük ekipler, yeni projeler (monolith'le başla, sonra servisleri ayır), belirsiz domain sınırları. İyi yapılandırılmış monolith ile başla, sınırlar netleşince servislere ayır.","Microservices, monolith, bağımsız deployment, ölçeklendirme, dağıtık sistem, Conway.")

add("event-driven mimari nedir?","Event-driven architecture (EDA) servisler arası iletişim için olayları (events) kullanır. Doğrudan API çağrıları yerine (senkron), servisler olay yayınlar, diğer servisler tepki verir (asenkron). Bileşenler: Event Producers (olayları yayınlar — kullanıcı kaydoldu, sipariş verildi), Event Broker (mesaj kuyruğu — Kafka, RabbitMQ, AWS SNS/SQS), Event Consumers (olaylara tepki verir — hoşgeldin e-postası gönder, analitiği güncelle). Desenler: Event Notification (minimal veri, tüketici detayları çeker), Event-Carried State Transfer (olayda tam veri, geri çağrıya gerek yok), Event Sourcing (olayları gerçek kaynak olarak sakla, olayları tekrarlayarak durumu yeniden oluştur), CQRS (okuma ve yazma modellerini ayır). Avantajlar: gevşek bağlantı, ölçeklenebilirlik, dayanıklılık (e-posta servisi çöktüyse olaylar kuyrukta bekler). Zorluklar: eventual consistency, hata ayıklama karmaşıklığı, olay sıralaması (Kafka partition'ları yardımcı olur), idempotency (tekrarlanan olayları yönet). Araçlar: Apache Kafka (dağıtık log, yüksek verim), RabbitMQ (geleneksel mesaj broker), AWS EventBridge (serverless event bus).","Event-driven, Kafka, RabbitMQ, event sourcing, CQRS, pub/sub, asenkron, gevşek bağlantı.")

add("GraphQL nedir REST ile karşılaştırması?","GraphQL, API'ler için bir sorgu dili. İstemci tam olarak hangi veriyi istediğini belirtir, sunucu sadece onu döner. Facebook tarafından geliştirildi (2015). REST: sabit endpoint'ler sabit veri yapıları döner. /users/1 tüm kullanıcı alanlarını döner. Kullanıcının adı ve postları mı lazım? İki istek: GET /users/1 ve GET /users/1/posts. Over-fetching (ihtiyaç olmayan alanları almak) ve under-fetching (birden fazla istek gereksinimi). GraphQL: tek endpoint, istemci istenen şekli tanımlayan sorgu gönderir. Tek istek tam olarak gerekeni döner. Schema tipleri ve ilişkileri tanımlar. Resolver'lar veriyi çeker. Avantajlar: over/under-fetching yok, güçlü tipleme, introspection (kendi kendini belgeleyen), mobil için harika (veri transferini minimize et). Zorluklar: önbellekleme zorlaşır (POST istekleri), N+1 sorgu problemi (DataLoader ile batching), basit API'ler için gereksiz karmaşıklık. Araçlar: Apollo Client/Server, Relay, graphql-yoga, Hasura (Postgres'ten otomatik oluştur). Ne zaman kullanmalı: karmaşık UI'lar, mobil uygulamalar, farklı veri ihtiyaçları olan birden fazla istemci.","GraphQL, REST, over-fetching, schema, resolver, Apollo, sorgu dili, API tasarımı.")

add("WebSocket nedir gerçek zamanlı iletişim nasıl yapılır?","WebSocket istemci ve sunucu arasında tam çift yönlü, kalıcı bağlantı sağlar. HTTP'nin aksine (istek-yanıt, bağlantı kapanır), WebSocket bağlantıyı açık tutar — her iki taraf istediği zaman veri gönderebilir. Handshake: HTTP isteği olarak başlar (Upgrade header), sunucu kabul eder, bağlantı WebSocket protokolüne geçer (ws:// veya wss://). Kullanım alanları: sohbet uygulamaları, canlı bildirimler, gerçek zamanlı dashboard'lar, işbirlikçi düzenleme, çok oyunculu oyunlar, canlı spor skorları. Alternatifler: Server-Sent Events (SSE) — sadece sunucudan istemciye, daha basit, HTTP kullanır, otomatik yeniden bağlantı. Bildirimler ve canlı akışlar için iyi. Long Polling — istemci istek yapar, sunucu veri olana kadar bekletir. Daha basit ama daha fazla overhead. Kütüphaneler: Socket.IO (WebSocket + fallback'ler, odalar, namespace'ler), ws (Node.js native), Pusher, Ably. WebSocket ölçeklendirme: sticky sessions, Redis pub/sub (sunucular arası iletişim). Çoğu gerçek zamanlı ihtiyaç için SSE daha basit ve yeterli. Çift yönlü iletişim gerektiğinde WebSocket kullan.","WebSocket, gerçek zamanlı, SSE, Socket.IO, tam çift yönlü, long polling, kalıcı bağlantı.")

add("test stratejileri nelerdir ne zaman hangisi kullanılır?","Test piramidi (alttan üste): Unit testler — bireysel fonksiyonları izole olarak test eder. Hızlı, çok sayıda. Bağımlılıkları mock'la. Araçlar: Jest, pytest, JUnit. Integration testler — bileşenlerin birlikte nasıl çalıştığını test eder. Veritabanı sorguları, API endpoint'leri. Daha yavaş, daha az sayıda. E2E (End-to-End) testler — kullanıcı akışlarını tüm sistem üzerinden test eder. En yavaş, en az sayıda. Araçlar: Cypress, Playwright, Selenium. TDD (Test-Driven Development): önce test yaz → başarısız olduğunu gör → geçmesi için minimum kod yaz → refactor et. Tasarımı düşünmeye zorlar. BDD (Behavior-Driven Development): davranışı doğal dilde tanımla (Given-When-Then). Diğer test türleri: performans testi (k6, Locust ile yük testi), güvenlik testi (OWASP ZAP), erişilebilirlik testi (axe, Lighthouse), görsel regresyon testi (Percy), contract testi (Pact — servis arayüzlerini doğrula). İyi uygulamalar: davranışı test et implementasyonu değil, testleri bağımsız tut, test verisi için factory/fixture kullan, CI her PR'da tüm testleri çalıştırsın. %100 line coverage değil anlamlı coverage hedefle.","Test piramidi, unit test, integration, E2E, TDD, BDD, Cypress, Playwright, coverage.")

add("API versiyonlama ve geriye uyumluluk nedir?","API versiyonlama, mevcut istemcileri bozmadan değişiklikleri yönetir. Stratejiler: URL versiyonlama (/api/v1/users, /api/v2/users) — en yaygın, açık, anlaşılması kolay. Header versiyonlama (Accept: application/vnd.api.v2+json) — daha temiz URL'ler ama daha az keşfedilebilir. Query parametresi (?version=2) — kolay ama daha az RESTful. Geriye uyumluluk kuralları: alan eklemek güvenlidir (istemciler bilinmeyen alanları yok sayar), alan kaldırmak istemcileri bozar, alan tipini değiştirmek bozar. Deprecation stratejisi: zaman çizelgesiyle kullanımdan kaldırma duyurusu yap, Deprecation/Sunset header'ları ekle, deprecated endpoint kullanımını izle, migrasyon kılavuzları sağla. Breaking change'ler yeni versiyon gerektirir: alan kaldırma, tip değişiklikleri, davranış değişiklikleri. Non-breaking: opsiyonel alan ekleme, yeni endpoint ekleme. Semantic versiyonlama: MAJOR (kırıcı), MINOR (yeni özellikler, geriye uyumlu), PATCH (hata düzeltmeleri). Araçlar: API gateway'ler (Kong, AWS API Gateway) versiyonları yönlendirebilir. OpenAPI/Swagger ile belgele.","API versiyonlama, geriye uyumluluk, deprecation, semantic versioning, kırıcı değişiklik.")

add("CAP teoremi ve dağıtık veritabanı ödünleşimleri nedir?","CAP teoremi: dağıtık sistemler üç özellikten en fazla ikisini garanti edebilir. Consistency (Tutarlılık) — her okuma en son yazmayı döner. Tüm düğümler aynı anda aynı veriyi görür. Availability (Kullanılabilirlik) — her istek bir yanıt alır. Hiçbir istek reddedilmez. Partition Tolerance (Bölünme Toleransı) — ağ bölünmeleri olmasına rağmen sistem çalışmaya devam eder. Dağıtık sistemlerde ağ bölünmeleri OLACAKTIR. Gerçek seçim: CP (Tutarlılık + Bölünme Toleransı) — bölünme sırasında tutarlılığı korumak için istekleri reddeder. Örnekler: HBase, MongoDB. AP (Kullanılabilirlik + Bölünme Toleransı) — bölünme sırasında istekleri kabul eder ama eski veri döndürebilir. Örnekler: Cassandra, DynamoDB. PACELC uzantısı: Partition varsa → A veya C seç, yoksa → Latency veya Consistency seç. Tutarlılık modelleri: Strong consistency (en pahalı), Eventual consistency (en ucuz — tüm replikalar sonunda yakınsar). Gerçek dünya: çoğu uygulama eventual consistency kullanır. Bankacılık transferleri strong consistency gerektirir. Sosyal medya akışları eventual consistency tolere eder. İş gereksinimlerine göre seç.","CAP teoremi, tutarlılık, kullanılabilirlik, bölünme toleransı, PACELC, eventual consistency.")

add("altyapı kodu olarak IaC ve Terraform nedir?","Infrastructure as Code (IaC), altyapıyı manuel yapılandırma yerine kod aracılığıyla yönetir. Avantajlar: versiyon kontrolü (altyapı değişikliklerinin git geçmişi), tekrar üretilebilirlik (aynı kod = aynı altyapı), otomasyon (altyapı için CI/CD), dokümantasyon (kod ZATEN dokümantasyondur). Terraform (HashiCorp): bildirimsel IaC aracı. İstenen durumu HCL'de yaz, Terraform oraya nasıl ulaşılacağını belirler. İş akışı: terraform init (sağlayıcıları indir) → terraform plan (değişiklikleri önizle) → terraform apply (değişiklikleri uygula) → terraform destroy (yık). State: Terraform altyapı durumunu terraform.tfstate'te takip eder. Üretimde uzakta sakla (S3 + DynamoDB kilitleme ile). Modüller: yeniden kullanılabilir bileşenler. VPC, ECS servisi, RDS için modüller oluştur. Alternatifler: Pulumi (gerçek programlama dilleri — Python, TypeScript), AWS CloudFormation (sadece AWS, YAML/JSON), CDK (AWS, TypeScript/Python). İyi uygulamalar: modül kullan, kilitleme ile uzak state, ortamları ayır (dev/staging/prod), plan'dan önce apply, değişkenler ve çıktılar kullan. Terraform en popüler çoklu bulut IaC aracıdır.","Terraform, IaC, HCL, state yönetimi, modüller, Pulumi, CloudFormation, altyapı.")

add("gözlemlenebilirlik ve izleme nedir?","Observability, bir sistemin iç durumunu dış çıktılarından anlama yeteneğidir. Üç sütun: Metrikler — zaman içindeki sayısal ölçümler. CPU kullanımı, istek gecikmesi, hata oranı. Araçlar: Prometheus (pull-tabanlı, PromQL), Grafana (görselleştirme), Datadog. Loglar — olayların zaman damgalı kayıtları. Uygulama logları, erişim logları. Araçlar: ELK Stack (Elasticsearch + Logstash + Kibana), Loki. Trace'ler — bir isteği servisler boyunca takip et. Her servis bir span ekler, span'lar trace oluşturur. Araçlar: Jaeger, Zipkin, OpenTelemetry (vendor-neutral standart). Önemli metrikler: RED metodu (servisler için — Rate, Errors, Duration), USE metodu (kaynaklar için — Utilization, Saturation, Errors). SLI/SLO/SLA: SLI (gerçek ölçüm, ör: %99.5 istek 200ms altında), SLO (hedef, ör: %99.9 kullanılabilirlik), SLA (cezalarla sözleşme). Uyarılar: nedenlere değil belirtilere göre uyar. SLO ihlallerinde sayfa. Uyarı yorgunluğundan kaçın — daha az ama anlamlı uyarılar. OpenTelemetry uygulamaları enstrümante etmek için standart haline geliyor.","Gözlemlenebilirlik, metrikler, loglar, trace, Prometheus, Grafana, OpenTelemetry, SLO.")

add("containerization ileri konuları nelerdir?","docker run'ın ötesinde — üretim container uygulamaları. Multi-stage build'ler: derleme ve çalışma zamanı aşamalarını ayır. Build aşaması kodu derler (build araçlarıyla büyük image), runtime aşaması sadece artifact'leri kopyalar (küçük, güvenli image). Image optimizasyonu: alpine/slim temel image kullan, katmanları minimize et, build cache'i kullan (nadiren değişen katmanları önce koy), .dockerignore kullan, root olarak çalıştırma (USER node), güvenlik açıkları için tara (Trivy, Snyk). Docker Compose: çoklu container uygulamalarını tanımla. Services, networks, volumes. Container orkestrasyonu: Kubernetes (karmaşık ama güçlü), Docker Swarm (daha basit), AWS ECS/Fargate (yönetilen). Kubernetes kavramları: Pod (en küçük birim), Deployment (pod replikalarını yönet, rolling update), Service (pod'lar için kararlı ağ), Ingress (HTTP yönlendirme), ConfigMap/Secret (yapılandırma), PersistentVolume (depolama). Container ağı: bridge (varsayılan), overlay (çapraz host), host. Güvenlik: root olmayan kullanıcı, salt okunur dosya sistemi, image'leri düzenli tara, üretim için distroless image kullan.","Container, multi-stage build, Docker Compose, Kubernetes, pod, image optimizasyonu.")

add("CI/CD pipeline tasarımı nasıl yapılır?","CI/CD kod oluşturma, test ve dağıtımı otomatikleştirir. CI (Sürekli Entegrasyon): kodu sık birleştir, her push'ta otomatik build ve test. Entegrasyon sorunlarını erken yakala. CD (Sürekli Teslimat): staging'e otomatik pipeline, production'a manuel onay. CD (Sürekli Dağıtım): production'a tamamen otomatik pipeline. Pipeline aşamaları: 1) Kaynak — git push/PR'da tetikle. 2) Build — derle, paketle, artifact oluştur. 3) Test — unit, integration, E2E testler. 4) Güvenlik — SAST, bağımlılık tarama, container tarama. 5) Staging'e deploy — otomatik. 6) Production'a deploy — manuel onay veya otomatik. Araçlar: GitHub Actions (GitHub'a entegre, YAML workflow'ları), GitLab CI, Jenkins (self-hosted), CircleCI, ArgoCD (Kubernetes için GitOps). GitHub Actions temelleri: .github/workflows/ içinde workflow'lar, olaylarla tetiklenir (push, PR, schedule), job'lar runner'larda çalışır. İyi uygulamalar: hızlı pipeline'lar (testleri paralelleştir, bağımlılıkları önbelleğe al), fail fast (linting ve unit testleri önce çalıştır), immutable artifact'ler (bir kez build et, tüm ortamlara aynı artifact'i deploy et), feature flag'ler, rollback stratejisi (blue-green, canary deployment). Görkem'in projeleri GitHub kullanır — GitHub Actions doğal CI/CD seçimidir.","CI/CD, GitHub Actions, pipeline, sürekli dağıtım, GitOps, ArgoCD, blue-green.")

add("veritabanı migration ve şema yönetimi nasıl yapılır?","Veritabanı migration'ları şema değişikliklerini zaman içinde yönetir. Manuel ALTER TABLE çalıştırmak yerine, veritabanı şemanızı versiyonlayan migration script'leri yazarsınız. Nasıl çalışır: her migration'ın up (uygula) ve down (geri al) fonksiyonu vardır. Migration'lar sırayla çalışır, hangilerinin uygulandığını takip eder. Araçlar: Flyway (Java), Alembic (Python/SQLAlchemy), Knex.js (Node.js), Rails migration, golang-migrate, Prisma Migrate. İyi uygulamalar: production'a uygulandıktan sonra migration'ı asla düzenleme, migration'lar mümkünse idempotent olsun, migration'ları production verisi kopyası üzerinde test et, rollback planın olsun, production'da tablo kilitlemeyi önle. Yaygın migration'lar: sütun ekleme (nullable veya default ile güvenli), sütun kaldırma (önce sütunu kullanmayan kodu deploy et, sonra kaldır), sütun yeniden adlandırma (yeni ekle → veriyi kopyala → kodu güncelle → eskiyi kaldır). Sıfır kesintili migration'lar: expand-and-contract deseni. 1) Expand: eski yanına yeni sütun ekle. 2) Migrate: veriyi kopyala, kodu her ikisine de yazmaya güncelle. 3) Contract: tüm kod yeniyi kullandıktan sonra eskiyi kaldır.","Veritabanı migration, şema yönetimi, Alembic, Prisma, sıfır kesinti, expand-contract.")

add("API rate limiting ve throttling nedir?","Rate limiting bir istemcinin zaman penceresi içinde kaç istek yapabileceğini kontrol eder. Kötüye kullanımı önler, adil kullanımı sağlar, backend kaynaklarını korur. Algoritmalar: Token Bucket — kova N token tutar, sabit hızda yenilenir. Her istek bir token tüketir. Kova boyutuna kadar ani artışlara izin verir. En yaygın. Leaky Bucket — istekler kuyruğa girer, sabit hızda işlenir. Ani artışları düzleştirir. Fixed Window — sabit zaman penceresi başına istekleri say (ör: dakikada 100 istek). Basit ama pencere sınırında ani artışa izin verir. Sliding Window — sabit pencere ve kayan log'un hibriti. Doğruluk ve verimlilik arasında iyi denge. Uygulama: uygulama seviyesi (middleware), API Gateway (Kong, AWS API Gateway), reverse proxy (Nginx limit_req), dağıtık (Redis tabanlı). Yanıt header'ları: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, Retry-After. Limit aşıldığında HTTP 429. Stratejiler: kullanıcı başına, IP başına, API-key başına, endpoint başına. Farklı kullanıcılar için farklı katmanlar. İstemci tarafında exponential backoff. Rate limiting herhangi bir public API için gereklidir.","Rate limiting, token bucket, sliding window, throttling, 429, Redis, API gateway.")

add("web performans optimizasyonu nasıl yapılır?","Web performansı kullanıcı deneyimini ve iş metriklerini doğrudan etkiler. Core Web Vitals (Google sıralama faktörleri): LCP (Largest Contentful Paint < 2.5s) — ana içeriğin ne kadar hızlı yüklendiği. Optimize: kritik kaynakları preload et, görselleri optimize et, CDN kullan, SSR. INP (Interaction to Next Paint < 200ms) — sayfa etkileşime ne kadar hızlı yanıt veriyor. Optimize: uzun görevleri böl, web worker kullan, debounce/throttle handler'ları. CLS (Cumulative Layout Shift < 0.1) — görsel kararlılık. Optimize: görsellere/videolara açık boyutlar belirle, mevcut içerik üzerinde içerik eklemeyi önle. Optimizasyon teknikleri: Code splitting — sadece geçerli sayfa için gereken kodu yükle. Image optimization — WebP/AVIF formatları, responsive images, lazy loading. Caching — Cache-Control header'ları, ETag'ler, service worker'lar. CDN — statik varlıkları kullanıcılara yakın kenar konumlardan sun. Sıkıştırma — Brotli. Font yükleme — font-display: swap, kritik fontları preload et. Bundling — tree shaking, minification, bundle analizi. Ölçüm: Chrome DevTools Performance tab, Lighthouse, WebPageTest.","Web performansı, Core Web Vitals, LCP, INP, CLS, code splitting, lazy loading, CDN.")

add("OAuth 2.0 ve OpenID Connect nedir?","OAuth 2.0 bir yetkilendirme framework'üdür — üçüncü taraf uygulamaların şifre paylaşmadan kullanıcı adına kaynaklara erişmesini sağlar. OpenID Connect (OIDC) OAuth 2.0 üzerine kimlik doğrulama ekler — kullanıcının kim olduğunu kanıtlar. OAuth 2.0 akışları: Authorization Code (web uygulamaları için en yaygın) — auth sunucusuna yönlendir, kullanıcı giriş yapar, authorization code al, token'larla değiştir. Authorization Code + PKCE (SPA ve mobil için) — kod müdahalesini önlemek için proof key ekler. Client Credentials (makineden makineye) — kullanıcı yok, servis client_id ve secret ile kimlik doğrular. Token'lar: Access Token — kısa ömürlü, API istekleriyle gönderilir (Authorization: Bearer ...). Refresh Token — uzun ömürlü, yeniden giriş yapmadan yeni access token almak için. ID Token (OIDC) — kullanıcı bilgisi içeren JWT. Token saklama: HttpOnly cookie'ler (web için en güvenli). ASLA localStorage'da saklama (XSS'e açık). Sağlayıcılar: Auth0, Okta, Firebase Auth, Keycloak (self-hosted), AWS Cognito. JWT: header.payload.signature. Base64 kodlanmış, şifreli DEĞİL — içine gizli bilgi koyma. İmzayı sunucu tarafında doğrula.","OAuth 2.0, OIDC, authorization code, PKCE, JWT, access token, refresh token, Auth0.")

add("fonksiyonel programlama kavramları nelerdir?","Fonksiyonel programlama (FP) hesaplamayı matematiksel fonksiyonların değerlendirilmesi olarak ele alır. Temel kavramlar: Pure (saf) fonksiyonlar — aynı girdi her zaman aynı çıktıyı verir, yan etkisi yoktur. Test etmesi, anlaması, paralelleştirmesi kolay. Immutability (değişmezlik) — veri asla değişmez. Değişikliklerle yeni kopyalar oluşturulur. Paylaşılan değiştirilebilir durumdan kaynaklanan hataları önler. First-class fonksiyonlar — fonksiyonlar değerdir. Argüman olarak geçir, fonksiyonlardan döndür, değişkenlere ata. Higher-order fonksiyonlar — fonksiyon alan veya döndüren fonksiyonlar. map, filter, reduce büyük üçlü. Composition — basit fonksiyonları birleştirerek karmaşık olanları oluştur: compose(f, g)(x) = f(g(x)). Currying — çok argümanlı fonksiyonu tek argümanlı fonksiyonlar dizisine dönüştür: add(a, b) → add(a)(b). Partial application için yararlı. Closure'lar — fonksiyon oluşturulduğu scope'taki değişkenleri hatırlar. Pattern matching — değerleri kalıplara göre eşleştir (Rust match, Haskell case). Diller: Haskell (saf FP), Scala, Elixir, F#, Clojure. Çok paradigmalı: JavaScript, Python, Rust, Kotlin. FP diline ihtiyacın yok — FP prensiplerini her yerde kullan. Saf fonksiyonları tercih et, mutasyonu minimize et.","Fonksiyonel programlama, saf fonksiyonlar, immutability, higher-order, composition, currying.")

add("tasarım desenleri nelerdir yazılım mühendisliğinde?","Tasarım desenleri yaygın yazılım tasarım problemlerine yeniden kullanılabilir çözümlerdir. Yaratıcı (Creational) desenler: Singleton (tek örnek, global erişim — dikkatli kullan, test etmesi zor), Factory Method (tam sınıf belirtmeden nesne oluştur — plugin'ler için yararlı), Builder (karmaşık nesneleri adım adım oluştur — çok opsiyonel parametreli nesneler için), Dependency Injection (bağımlılıkları oluşturmak yerine geçir — test edilebilirlik, gevşek bağlantı). Yapısal (Structural) desenler: Adapter (arayüzü istemcinin beklediğine dönüştür — eski API'yi sarmala), Decorator (sınıfı değiştirmeden davranış ekle — Express'te middleware), Proxy (nesneye erişimi kontrol et — caching proxy, auth proxy), Facade (karmaşık alt sistemi basitleştir). Davranışsal (Behavioral) desenler: Observer (pub/sub — event emitter'lar, React state güncellemeleri), Strategy (çalışma zamanında algoritma değiştir — farklı sıralama veya ödeme yöntemleri), Command (eylemi nesne olarak kapsülle — undo/redo), Iterator (yapıyı açığa çıkarmadan koleksiyonu gez). En önemlileri: Dependency Injection, Observer, Strategy, Factory, Decorator. Anti-desen: desenleri aşırı kullanma. Basit kodun işe yaradığı yerde desen zorlamayın.","Tasarım desenleri, yaratıcı, yapısal, davranışsal, singleton, factory, observer, strategy.")

add("mesaj kuyrukları ve asenkron işleme nedir?","Mesaj kuyrukları üreticiler ve tüketicileri ayırarak asenkron işlemeyi mümkün kılar. Üretici mesajı kuyruğa gönderir, tüketici daha sonra işler. Sistemleri zaman ve mekanda ayırır. Kullanım alanları: e-posta gönderme (API yanıtını bloklamadan), görüntü işleme (arka planda boyutlandır/sıkıştır), sipariş işleme (doğrula, ücretlendir, yerine getir — asenkron), veri pipeline alımı. Teknolojiler: RabbitMQ — geleneksel mesaj broker. Exchange'ler mesajları kuyruklara yönlendirir. Birden fazla desen destekler: direct, topic, fanout. Görev kuyrukları ve RPC için iyi. Apache Kafka — dağıtık olay akış platformu. Yüksek verim, kalıcı depolama, tekrar oynatma yeteneği. Partition'lı topic'ler. Paralel işleme için consumer group'lar. Event sourcing, log toplama, akış işleme için harika. AWS SQS — yönetilen kuyruk servisi. Standard (en az bir kez, en iyi çaba sıralaması) ve FIFO (tam olarak bir kez, garantili sıralama). Dead letter queue'lar başarısız mesajlar için. Redis — pub/sub veya stream'ler ile basit mesaj broker olarak kullanılabilir. Dikkat edilecekler: mesaj sıralaması, en az bir kez vs tam olarak bir kez teslim, idempotency, dead letter queue'lar, backpressure.","Mesaj kuyrukları, RabbitMQ, Kafka, SQS, asenkron işleme, pub/sub, dead letter queue.")

add("edge computing ve serverless nedir?","Edge computing veriyi üretildiği yere yakın işler — gecikmeyi ve bant genişliğini azaltır. CDN edge (Cloudflare Workers, Vercel Edge Functions, AWS Lambda@Edge): dünya çapındaki CDN konumlarında kod çalıştır. Kullanım: A/B testi, coğrafi konum tabanlı yönlendirme, edge'de kimlik doğrulama, kişiselleştirme. IoT edge: sensör verilerini buluta göndermeden önce yerel olarak işle. Serverless: sunucu yönetmeden kod çalıştır. Bulut sağlayıcı ölçeklendirme, kullanılabilirlik, bakımı yönetir. AWS Lambda, Google Cloud Functions, Azure Functions, Cloudflare Workers. Avantajlar: yürütme başına ödeme (boşta maliyet yok), otomatik ölçeklendirme (sıfırdan binlere anında), sunucu yönetimi yok. Zorluklar: cold start (ilk çağrı yavaş), vendor lock-in, yürütme süresi limitleri (Lambda: 15 dk), hata ayıklama zorlaşır, durum yönetimi (fonksiyonlar stateless — harici depolama kullan). Serverless kalıpları: API backend (Lambda + API Gateway), olay işleme (S3, SQS, DynamoDB stream'leri tarafından tetiklenen Lambda), zamanlanmış işler, gerçek zamanlı dosya işleme. Ne zaman kullanmalı: değişken trafik, olay tabanlı iş yükleri. Ne zaman KULLANMAMALI: sürekli yüksek trafik (EC2 daha ucuz), uzun süren işlemler.","Edge computing, serverless, Lambda, Cloudflare Workers, cold start, CDN, IoT edge.")

add("kod review en iyi uygulamaları nelerdir?","Kod review kaliteyi artırır, bilgiyi paylaşır, production'dan önce hataları yakalar. Reviewer olarak: 24 saat içinde review yap (takım arkadaşlarını bloklamadan), önce bağlamı anla (PR açıklamasını oku), önce doğruluk, sonra stil için review et, spesifik ol ve alternatifler öner ('bu yanlış' deme, 'X olursa ne olur?' gibi sorular sor), küçük yorumlarla onay ver. Yazar olarak: PR'ları küçük tut (ideal olarak 400 satırın altında), açıklayıcı PR başlığı ve açıklaması yaz, review istemeden önce self-review yap, commit mesajlarında ve PR açıklamalarında NEDEN'i açıkla, tüm yorumları yanıtla. Nelere bakılmalı: doğruluk (problemi çözüyor mu?), edge case'ler (null, boş, eşzamanlı erişim), güvenlik (injection, kimlik doğrulama, yetkilendirme), performans (N+1 sorguları, gereksiz döngüler), okunabilirlik, testler (anlamlı mı, edge case'leri kapsıyor mu?), geriye uyumluluk. Nelere ODAKLANMAMALI: stil sorunları (formatlamayı linter'lara bırak — Prettier, ESLint, Black), doğruluğu etkilemeyen kişisel tercihler. Araçlar: GitHub PR'ları, GitLab MR'ları, code owners dosyaları, merge'den önce zorunlu review'lar.","Kod review, pull request, reviewer, yazar, geri bildirim, en iyi uygulamalar, PR boyutu.")

add("temiz kod prensipleri nelerdir?","Temiz kod okunabilir, bakımı kolay ve basittir. Robert C. Martin'in temel prensipleri: Anlamlı isimler — değişkenler, fonksiyonlar, sınıflar amacı ortaya koymalı. Aranabilir, telaffuz edilebilir isimler kullan. Kısaltmalardan kaçın. userAge ua değil, calculateTotalPrice calcTP değil. Küçük fonksiyonlar — her fonksiyon TEK bir şey yapar. Bir bölümün ne yaptığını açıklamak için yorum gerekiyorsa, onu adlandırılmış fonksiyona çıkar. DRY (Don't Repeat Yourself) — ama aşırı soyutlama yapma. Yanlış soyutlamadan tekrarlama daha ucuzdur. Üç kuralı: üçüncü tekrardan sonra soyutla. KISS (Keep It Simple) — işe yarayan en basit çözüm genellikle en iyisidir. YAGNI (İhtiyacın Olmayacak) — ihtiyaç olmadan özellik oluşturma. Gelecek gereksinimleri tahmin etmek genellikle yanlıştır. Tek Sorumluluk İlkesi — her modül, sınıf veya fonksiyonun değişmek için tek bir nedeni olmalı. Boy Scout Kuralı — kodu bulduğundan daha temiz bırak. Hata yönetimi — istisnaları akış kontrolü için kullanma, uygun seviyede hataları yönet, istisnaları sessizce yutma. Yorumlar — kod kendi kendini belgelemeli. Yorumlar NEDEN'i açıklar, NE'yi değil. Formatlama — tutarlı girintileme, mantıksal gruplama. Formatter'lar kullan (Prettier, Black).","Temiz kod, isimlendirme, küçük fonksiyonlar, DRY, KISS, YAGNI, SRP, okunabilirlik.")

add("teknik borç nedir nasıl yönetilir?","Teknik borç, hızlı çözümleri daha iyi yaklaşımlar yerine seçmenin gelecekteki yeniden çalışma maliyetidir. Türleri: Kasıtlı (bilinçli kısayollar — 'şimdi gönder, sonra refactor yap') vs Kasıtsız (bilgi eksikliğinden kötü tasarım). Yaygın formları: test yok (refactor yapmaya korkmak), copy-paste kod, eski bağımlılıklar, karmaşık sistemler için dokümantasyon yok, sıkı bağlı bileşenler, codebase genelinde tutarsız desenler. Yönetim stratejileri: görünür kıl — issue tracker'da takip et, tech-debt olarak etiketle. Etkiyi ölçüle — 'bu her özelliği 2 gün yavaşlatıyor' 'refactor yapmamız lazım'dan daha ikna edici. Zaman ayır — sprint'in %20'si teknik borç için (Google yaklaşımı). Boy Scout Kuralı — dokunduğun kodu iyileştir. Refactoring sprint'leri — periyodik adanmış temizlik. Birikmeyi önle — code review, linting, CI/CD kalite kapıları. Ne zaman ödenmeli: etkilenen alana özellik eklemeden önce, geliştirmeyi ölçülebilir şekilde yavaşlattığında, düzenli olarak hatalara neden olduğunda, yeni geliştiricilerin alışmasını zorlaştırdığında. Ne zaman kabul edilmeli: prototip/MVP, kısa ömürlü kod, değişmesi muhtemel olmayan izole bileşenler. Teknik borç doğası gereği kötü değildir — bir araçtır.","Teknik borç, refactoring, kod kalitesi, yönetim, kasıtlı, Boy Scout Kuralı, sprint.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_tr25.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} Turkish entries (part 25).")
if __name__=="__main__":
    main()
