"""Ek TR training data - Bölüm 5. Çeşitli konular, günlük hayat, teknik detaylar."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

# Hackathon deneyimleri
add("BTK Hackathon deneyiminden bahseder misin?","BTK Hackathon, Görkem'in katıldığı e-ticaret odaklı bir hackathon. Bu tür etkinliklerde genelde 24-48 saat içinde bir ürün veya prototip geliştiriyorsun. Takım çalışması, hızlı karar verme, baskı altında kodlama deneyimi kazanıyorsun. E-ticaret teması altında AI destekli öneri sistemi, chatbot, otomasyon gibi çözümler üretilmiş olabilir. Hackathon'lar CV'de çok değerli çünkü gerçek dünya problemi çözdüğünü, takım çalışması yapabildiğini ve hızlı prototip oluşturabildiğini gösteriyor. Jüri önünde sunum yapma deneyimi de bonus.","BTK Hackathon, e-ticaret, takım çalışması, prototip, sunum.")
add("Tıkla Gelsin Foodathon'da ne yaptınız?","Tıkla Gelsin Foodathon, yemek sipariş sektörüne yönelik bir hackathon. Görkem burada katılarak yemek teknolojisi (food-tech) alanında bir çözüm geliştirmiş. Sipariş optimizasyonu, teslimat rotası planlaması, müşteri deneyimi iyileştirme, AI tabanlı menü önerisi gibi konularda çalışılmış olabilir. Food-tech büyüyen bir sektör ve teknoloji burada büyük fark yaratıyor. Hackathon'da sektör profesyonelleriyle tanışma ve mentorluk alma fırsatı da oluyor. Bu tür etkinlikler girişimcilik ruhunu da besliyor.","Foodathon, yemek teknolojisi, sipariş, AI öneri, girişimcilik.")
add("Med Health hackathon'unda ne yaptınız?","Med Health (Mediterranean Health), sağlık teknolojisi odaklı bir hackathon. Görkem burada sağlık alanında bir teknoloji çözümü geliştirmiş. Erken uyarı sistemi, hasta takip uygulaması, sağlık verisi analizi gibi projeler yapılmış olabilir. Görkem'in depression-phq9-analysis projesiyle de uyumlu — sağlık teknolojisine ilgisi var. Health-tech startup'ları yatırımcıların en çok ilgilendiği alanlardan biri. Hackathon deneyimi iş görüşmelerinde anlatacak çok güzel hikayeler sağlıyor.","Med Health hackathon, sağlık teknolojisi, erken uyarı, health-tech.")

# Web geliştirme detayları
add("React ile Vue arasındaki fark ne?","React ve Vue ikisi de frontend framework/library. React, Facebook tarafından geliştirildi, JSX kullanır (JavaScript içinde HTML yazarsın), çok geniş ekosistem, iş ilanlarında en çok aranan. Vue, daha kolay öğrenme eğrisi, template-based (HTML benzeri), küçük-orta projelerde çok verimli, Evan You tarafından geliştirildi. React'te state yönetimi için Redux/Zustand, Vue'da Vuex/Pinia. React daha esnek ama daha fazla karar vermen gerekiyor, Vue daha opinionated ama hızlı başlarsın. Angular da var — Google'ın, TypeScript zorunlu, enterprise projelerde yaygın. Hangisini seçersen seç, mantığı aynı — component-based UI.","React vs Vue, JSX, template, ekosistem, Angular, component-based.")
add("Next.js nedir?","Next.js, React üzerine kurulmuş bir full-stack framework. React tek başına sadece client-side rendering yapar, Next.js ise server-side rendering (SSR), static site generation (SSG), ve API routes ekliyor. SEO için çok önemli — arama motorları SSR sayfaları daha iyi indeksler. File-based routing — pages klasörüne dosya ekleyince otomatik route olur. Image optimization, code splitting, middleware gibi performans özellikleri var. Vercel (Next.js'in arkasındaki şirket) ile kolay deployment. Modern web geliştirmenin standardı haline geldi. Görkem'in portfolyo sitesi de benzer bir framework kullanıyor olabilir.","Next.js, SSR, SSG, SEO, file-based routing, Vercel.")
add("TypeScript neden kullanmalıyım?","TypeScript, JavaScript'e tip güvenliği ekleyen bir dil. JavaScript'te runtime'da 'undefined is not a function' hatası alırsın, TypeScript'te daha kodu yazarken editör seni uyarır. Avantajları: daha az bug, daha iyi IDE desteği (auto-complete, refactoring), kodun dökümantasyon gibi okunur, büyük projelerde bakım kolaylaşır. Dezavantajları: öğrenme eğrisi, derleme adımı, küçük projelerde gereksiz olabilir. Büyük şirketler (Google, Microsoft, Airbnb) TypeScript kullanıyor. React, Vue, Node.js projeleri TypeScript ile yazılabiliyor. Yeni projeye başlıyorsan TypeScript ile başla.","TypeScript, tip güvenliği, JavaScript farkı, avantaj/dezavantaj.")
add("REST API tasarlarken nelere dikkat etmeliyim?","REST API tasarımında bazı kurallar var. URL'ler isim olmalı (verb değil): /users, /products (GET /users iyi, GET /getUsers kötü). HTTP methodlarını doğru kullan: GET (oku), POST (oluştur), PUT (güncelle), DELETE (sil), PATCH (kısmen güncelle). Status kodları doğru döndür: 200 başarı, 201 oluşturuldu, 400 hatalı istek, 401 yetkisiz, 404 bulunamadı, 500 sunucu hatası. Versiyonlama yap: /api/v1/users. Pagination kullan: büyük listelerde sayfalama. Filtreleme ve sıralama query parametreleri ile. HATEOAS ile ilişkili kaynakları linkle. Güvenlik: authentication, rate limiting, input validation. İyi dökümentasyon: Swagger/OpenAPI.","REST API, URL tasarımı, HTTP methods, status kodları, pagination, Swagger.")
add("WebAssembly (WASM) ne işe yarar?","WebAssembly, tarayıcıda native hıza yakın performansla kod çalıştırmayı sağlayan bir binary format. C, C++, Rust gibi dillerde yazılmış kodu tarayıcıda çalıştırabilirsin. Neden önemli: JavaScript performansının yetmediği yerlerde — 3D oyunlar, video düzenleme, bilimsel hesaplama, CAD uygulamaları. Figma WASM kullanıyor, Google Earth da. JavaScript'in yerini almıyor — beraber çalışıyorlar. WASI (WebAssembly System Interface) ile tarayıcı dışında da çalışabilir — serverless, edge computing. Performans kritik uygulamalar için önemli bir teknoloji.","WebAssembly, WASM, native performans, Rust, Figma, WASI.")
add("Tailwind CSS nedir?","Tailwind CSS, utility-first CSS framework'ü. Geleneksel CSS'te sınıf isimleri verip ayrı dosyada stil yazarsın. Tailwind'de HTML'e doğrudan küçük utility sınıfları yazarsın: class='bg-blue-500 text-white p-4 rounded-lg'. Avantajları: hızlı geliştirme, tutarlı tasarım, responsive kolay, custom CSS dosyası minimuma iner. Dezavantajları: HTML kalabalıklaşır, başta alışmak gerekir. JIT (Just-in-Time) modu ile sadece kullandığın sınıflar üretilir — dosya boyutu küçük kalır. Headless UI ve DaisyUI gibi component kütüphaneleri ile beraber kullanılabiliyor. Çok popüler — birçok modern proje Tailwind kullanıyor.","Tailwind CSS, utility-first, avantaj/dezavantaj, JIT, DaisyUI.")
add("GraphQL ne zaman kullanılmalı?","GraphQL, Facebook'un geliştirdiği bir sorgu dili. REST'ten farkı: istemci tam olarak ihtiyacı olan veriyi ister — ne fazla ne eksik (over-fetching ve under-fetching problemi yok). Tek endpoint: /graphql, tüm sorgular buraya gider. Ne zaman kullanılmalı: birden fazla istemci (web, mobile) farklı veri ihtiyaçları olduğunda, ilişkili verileri tek sorguda çekmek istediğinde, frontend'in hızlı iterasyon yapması gerektiğinde. Ne zaman kullanılmamalı: basit CRUD API, dosya upload, gerçek zamanlı yoğun uygulamalar (burada REST+WebSocket daha basit olabilir). Apollo ve Relay popüler istemci kütüphaneleri.","GraphQL, REST farkı, over-fetching, tek endpoint, Apollo, ne zaman kullanılmalı.")

# Veri bilimi ve analitik
add("veri bilimi ile makine öğrenmesi arasındaki fark ne?","Veri bilimi (Data Science) daha geniş bir alan — veri toplama, temizleme, analiz, görselleştirme ve iç görü çıkarma. İstatistik, domain bilgisi ve programlama kesişimi. Makine öğrenmesi ise veri biliminin bir alt dalı — veriden otomatik öğrenen algoritmalar. Veri bilimci SQL, pandas, matplotlib ile veri analizi yapar, dashboard oluşturur, iş kararlarına yönelik raporlar sunar. ML mühendisi model eğitir, pipeline kurar, deploy eder. İkisi de Python kullanır ama odak noktaları farklı. Kaggle hem veri bilimi hem ML için harika bir platform.","Data Science vs ML, fark, veri bilimci, ML mühendisi, Kaggle.")
add("pandas kütüphanesi ne işe yarar?","pandas, Python'da veri analizi ve manipülasyonu için temel kütüphane. DataFrame yapısı — tablo gibi satır ve sütunlardan oluşur. CSV, Excel, JSON, SQL'den veri okuma. Filtreleme, gruplama, birleştirme, pivot tablo. Eksik veri yönetimi (NaN handling). Zaman serisi analizi. Büyük veriyi hızlıca analiz etmeni sağlar. df.head(), df.describe(), df.groupby() en çok kullanılan fonksiyonlar. Matplotlib ve seaborn ile görselleştirme yapılır. Veri bilimi ve ML pipeline'larının ilk adımı genelde pandas ile veri yükleme ve keşif. Her veri çalışanının bilmesi gereken kütüphane.","pandas, DataFrame, veri analizi, CSV, filtreleme, gruplama.")
add("matplotlib ve seaborn ile görselleştirme nasıl yapılır?","matplotlib Python'un temel görselleştirme kütüphanesi — çizgi grafik, bar grafik, scatter plot, histogram, pie chart yapabilirsin. plt.plot(), plt.bar(), plt.scatter() temel fonksiyonlar. seaborn ise matplotlib üzerine kurulu, daha güzel ve istatistiksel grafikler sunar — heatmap, violin plot, box plot, pair plot. sns.heatmap() korelasyon matrisi görselleştirmede çok kullanılır. Her iki kütüphane de pandas DataFrame'leriyle mükemmel çalışır. Veri analizi ve sunum için görselleştirme çok önemli — bir grafik bin kelimeye bedeldir.","matplotlib, seaborn, grafik türleri, heatmap, veri görselleştirme.")
add("ETL süreci ne demek?","ETL: Extract (Çıkar), Transform (Dönüştür), Load (Yükle). Veri mühendisliğinin temel süreci. Extract: farklı kaynaklardan veri çekmek — veritabanları, API'lar, dosyalar, web scraping. Transform: veriyi temizlemek, dönüştürmek, birleştirmek — eksik verileri doldurmak, formatlama, hesaplama. Load: işlenmiş veriyi hedef veritabanına veya veri ambarına yüklemek. Apache Airflow ETL süreçlerini otomatize etmek için popüler. dbt (data build tool) transform adımı için kullanılıyor. Büyük şirketlerde veri mühendisleri ETL pipeline'ları kurar ve yönetir. Bizim scraping projemiz de aslında bir ETL süreci.","ETL, extract, transform, load, Airflow, dbt, veri mühendisliği.")

# Mobil geliştirme
add("mobil uygulama geliştirmek istiyorum nereden başlamalıyım?","Mobil geliştirme için birkaç yol var. Native: iOS için Swift (Xcode), Android için Kotlin (Android Studio) — en iyi performans ama iki ayrı kod tabanı. Cross-platform: React Native (JavaScript), Flutter (Dart) — tek kod tabanıyla her iki platformda çalışır. Flutter son yıllarda çok popülerleşti, güzel UI yapımı kolay. Başlangıç için Flutter önerilir — Dart öğrenmesi kolay, hot reload ile hızlı geliştirme, zengin widget kütüphanesi. İlk proje olarak basit bir todo uygulaması veya hava durumu uygulaması yap. Google Codelabs ve Flutter.dev ücretsiz kaynaklar. App Store ve Google Play'e yayınlama sürecini de öğren.","Mobil geliştirme, Swift, Kotlin, Flutter, React Native, başlangıç.")
add("Flutter mı React Native mi?","İkisi de cross-platform mobil geliştirme framework'ü. Flutter: Google tarafından, Dart dili, kendi rendering engine'i (Skia), çok güzel UI, sıcak yenileme, Material Design ve Cupertino widget'ları. React Native: Meta tarafından, JavaScript/TypeScript, native component'ları kullanır, büyük ekosistem, web developer'lar için geçiş kolay. Performans: Flutter biraz daha iyi (kendi engine'i). Topluluk: React Native daha büyük ama Flutter hızla büyüyor. İş ilanları: her ikisi de yaygın. Benim önerim: JavaScript biliyorsan React Native, sıfırdan başlıyorsan Flutter. Her ikisi de iyi tercih.","Flutter vs React Native, performans, topluluk, iş ilanları.")

# Oyun geliştirme
add("oyun geliştirmeye nasıl başlanır?","Oyun geliştirme heyecan verici bir alan. Engine seçimi: Unity (C#, en yaygın, 2D ve 3D), Unreal Engine (C++/Blueprint, AAA kalitesi, ücretsiz), Godot (GDScript, açık kaynak, hafif). Başlangıç için Unity veya Godot önerilir. İlk proje: basit bir platformer, pong veya flappy bird klonu yap. Temel kavramlar: game loop, sprite, collision detection, physics, input handling. Görkem'in raylib-space-shooter projesi C ile oyun geliştirme — raylib hafif ve öğrenme için harika. Oyun geliştirme hem eğlenceli hem de grafik, fizik, AI, networking gibi birçok CS konusunu bir arada öğretir.","Oyun geliştirme, Unity, Unreal, Godot, raylib, başlangıç projeleri.")

# Siber güvenlik
add("siber güvenlik alanına nasıl girilir?","Siber güvenlik çok geniş bir alan. Alt dallar: penetration testing (sızma testi), incident response (olay müdahale), security operations (SOC), application security, network security, forensics. Başlangıç: networking temelleri (TCP/IP, DNS, HTTP), Linux komut satırı, Python scripting. Pratik platformlar: TryHackMe, HackTheBox, OverTheWire. Sertifikalar: CompTIA Security+, CEH, OSCP. CTF (Capture The Flag) yarışmalarına katıl — eğlenceli ve öğretici. Görkem'in email-phishing-detection projesi güvenlik ve AI'ın birleşimi. Bug bounty programlarıyla para da kazanabilirsin — HackerOne, Bugcrowd.","Siber güvenlik, penetration testing, TryHackMe, sertifikalar, CTF, bug bounty.")

# Kişisel gelişim
add("yazılımcı olarak İngilizce ne kadar önemli?","İngilizce yazılımda olmazsa olmaz. Neden: dökümantasyonların çoğu İngilizce, Stack Overflow İngilizce, en iyi kaynaklar İngilizce, global şirketlerde çalışmak için İngilizce şart, açık kaynak projelerde iletişim İngilizce. Teknik İngilizce ile günlük İngilizce farklı — teknik terimleri öğrenmek daha kolay çünkü zaten kullanıyorsun (variable, function, database). Geliştirmek için: İngilizce dökümantasyon oku, İngilizce YouTube kanalları izle (Fireship, Traversy Media, 3Blue1Brown), İngilizce blog oku, kod yorumlarını İngilizce yaz. Görkem İngilizce eğitim alıyor — bu büyük avantaj.","İngilizce önemi, dökümantasyon, global kariyer, teknik İngilizce, YouTube.")
add("kitap okumak yazılımcıya ne katar?","Kitap okumak düşünme becerisini geliştirir ve perspektif kazandırır. Yazılım kitapları: Clean Code (Robert Martin), The Pragmatic Programmer, Design Patterns (GoF), Cracking the Coding Interview, System Design Interview. Genel: Atomic Habits (alışkanlık), Deep Work (odaklanma), The Lean Startup (girişimcilik). Teknik kitaplar blog ve video ile öğrenilemeyen derinlik sağlar. Haftada 30 dakika bile olsa düzenli oku. E-kitap veya Audible da seçenek. Okuduğunu uygulamak önemli — sadece okumak yetmez. Bir kitaptan bir tane bile uygulayacağın şey çıksa yeterli.","Kitap okuma, Clean Code, Pragmatic Programmer, Atomic Habits, düzenli okuma.")
add("açık kaynak projelere nasıl katkıda bulunurum?","Açık kaynak katkısı kariyerin için çok değerli. Başlangıç: GitHub'da 'good first issue' veya 'help wanted' etiketli issue'ları ara. İlgi alanına uygun projeler bul. İlk katkılar küçük olabilir — typo düzeltme, dökümantasyon iyileştirme, basit bug fix. Adımlar: projeyi fork et, branch oluştur, değişikliği yap, PR gönder. CONTRIBUTING.md dosyasını oku — her projenin kuralları farklı. Büyük projeler: first-contributions reposu, freeCodeCamp, VS Code, Python. Katkıda bulunmak: gerçek dünya kodu görürsün, code review alırsın, networking yaparsın, CV'de çok iyi durur. Görkem'in GitHub'da aktif olması bu kültürü yaşadığını gösteriyor.","Açık kaynak, good first issue, fork, PR, CONTRIBUTING.md, CV.")
add("yazılımcı burnout'u nasıl önlenir?","Burnout yazılım sektöründe çok yaygın. Belirtiler: motivasyon kaybı, yorgunluk, sinirlilik, verimsizlik, koddan nefret etme. Önlemek için: iş-yaşam dengesi kur — mesai bitince bilgisayarı kapat. Hobby edin — yazılım dışı bir şey yap (spor, müzik, yemek). Düzenli tatil yap. Hayır demeyi öğren — her projeyi kabul etme. Mükemmeliyetçiliği bırak. Fiziksel sağlığına dikkat et — egzersiz, uyku, beslenme. Sosyal ilişkilerini ihmal etme. Eğer burnout yaşıyorsan profesyonel destek almaktan çekinme. Yazılım hayatının tamamı değil, hayatının bir parçası olmalı.","Burnout, iş-yaşam dengesi, hobby, mükemmeliyetçilik, fiziksel sağlık.")

# Matematik ve bilim
add("lineer cebir yapay zeka için neden önemli?","Lineer cebir AI'ın matematik dili. Nöral ağlar temelinde matris çarpımı — girdi verisi matris, ağırlıklar matris, çıktı matris çarpımı. Vektörler ve matrisler: embedding'ler vektör, ağırlıklar matris, attention mekanizması matris çarpımı. Eigenvalue ve eigenvector: PCA (boyut azaltma) bunlara dayanır. SVD (Singular Value Decomposition): recommendation sistemleri, veri sıkıştırma. Determinant ve ters matris: regresyon çözümlerinde kullanılır. 3Blue1Brown'un 'Essence of Linear Algebra' serisi en iyi kaynak — görsel ve sezgisel anlatıyor. Lineer cebir öğren, AI'ı derinlemesine anlarsın.","Lineer cebir, matris çarpımı, embedding, PCA, SVD, 3Blue1Brown.")
add("olasılık ve istatistik yapay zeka için neden önemli?","Olasılık ve istatistik makine öğrenmesinin temelinde var. Bayes teoremi: sınıflandırma, spam filtresi, naive Bayes. Olasılık dağılımları: Gaussian (normal dağılım), Bernoulli, Poisson — model varsayımlarını anlamak için. Hipotez testi: A/B testing, model performansı karşılaştırma. Maximum likelihood estimation: model parametrelerini optimize etmek. Korelasyon ve regresyon: değişkenler arası ilişki. Confidence interval ve p-value: sonuçların istatistiksel anlamlılığı. Overfitting bile istatistiksel bir kavram — bias-variance tradeoff. Khan Academy ve StatQuest YouTube kanalı iyi kaynaklar.","Olasılık, istatistik, Bayes, dağılımlar, hipotez testi, MLE.")

# Daha fazla teknik konu
add("message queue ne işe yarar?","Message queue (mesaj kuyruğu), servislerin birbirleriyle asenkron iletişim kurmasını sağlayan bir araç. Producer mesajı kuyruğa koyar, consumer hazır olunca alır. Neden kullanılır: servisleri birbirinden ayırma (decoupling), yük dengeleme, güvenilirlik (mesaj kaybolmaz), ölçeklenebilirlik. Popüler çözümler: RabbitMQ (genel amaçlı, kolay), Apache Kafka (yüksek hacim, streaming), AWS SQS (managed), Redis (basit kuyruklar). Örnek: e-ticaret sitesinde sipariş verildiğinde stok güncelleme, e-posta gönderme, fatura oluşturma — hepsi kuyruğa mesaj olarak bırakılır ve ilgili servisler işler. Microservice mimarilerinde standart.","Message queue, RabbitMQ, Kafka, asenkron iletişim, decoupling.")
add("monitoring ve observability ne demek?","Monitoring sistemlerin çalışıp çalışmadığını izlemek. Observability ise sistemin iç durumunu anlayabilmek. Üç temel sütun: Metrics (sayısal ölçümler — CPU, bellek, istek sayısı), Logs (olayların kaydı), Traces (bir isteğin sistemdeki yolculuğu). Prometheus + Grafana metriklerde standart. ELK Stack (Elasticsearch, Logstash, Kibana) log yönetiminde. Jaeger veya Zipkin dağıtık trace'lerde. Alert sistemi: bir metrik eşik aşınca bildirim — PagerDuty, Opsgenie. 'Ölçemediğin şeyi yönetemezsin' — production'da monitoring olmazsa olmaz. SRE (Site Reliability Engineering) kültürünün temel taşı.","Monitoring, observability, Prometheus, Grafana, ELK, traces, SRE.")
add("infrastructure as code ne demek?","Infrastructure as Code (IaC), altyapıyı kod olarak tanımlamak ve yönetmek. Manuel olarak sunucu kurmak yerine Terraform, Pulumi veya CloudFormation ile YAML/HCL dosyasında tanımlarsın. terraform apply deyince altyapı otomatik kurulur. Avantajları: tekrarlanabilirlik (aynı altyapıyı istediğin kadar kur), versiyon kontrolü (altyapı değişikliklerini Git'te izle), otomasyon (CI/CD ile altyapı deploy), dökümantasyon (kod altyapıyı anlatıyor). Ansible konfigürasyon yönetimi için, Terraform altyapı provisioning için. DevOps mühendislerinin temel becerisi.","IaC, Terraform, Ansible, CloudFormation, DevOps, versiyon kontrolü.")
add("service mesh ne demek?","Service mesh, microservice'ler arası iletişimi yöneten bir altyapı katmanı. Sidecar proxy'ler (her servisin yanında çalışan küçük proxy'ler) ile trafik yönetimi yapılır. Ne sağlar: servisler arası şifreleme (mTLS), trafik yönetimi (canary deployment, A/B testing), retry ve circuit breaker, observability (her istek izlenebilir). Istio en popüler service mesh. Linkerd daha hafif bir alternatif. Consul Connect HashiCorp'un çözümü. Ne zaman gerekir: çok sayıda microservice varsa (50+). Küçük sistemlerde gereksiz karmaşıklık ekler. Kubernetes ile beraber kullanılır genelde.","Service mesh, Istio, sidecar proxy, mTLS, canary deployment.")
add("git branching stratejileri neler?","Git'te birçok branching stratejisi var. Git Flow: main, develop, feature, release, hotfix branch'leri — büyük ekipler için yapılandırılmış. GitHub Flow: main + feature branch'ler, PR ile merge — basit ve etkili. Trunk-based development: herkes main branch'e kısa yaşayan branch'lerle sık sık merge eder — CI/CD ile uyumlu. GitLab Flow: GitHub Flow + environment branch'ler (staging, production). Başlangıçta GitHub Flow önerilir — basit ama etkili. Feature branch oluştur, PR aç, code review al, merge et. Commit mesajları anlamlı olsun. Branch isimlerinde convention kullan: feature/login, bugfix/auth-error.","Git branching, Git Flow, GitHub Flow, trunk-based, PR, code review.")

# Yapay zeka etiği
add("yapay zeka etiği neden önemli?","AI etiği, yapay zekanın toplum üzerindeki etkisini düşünmek demek. Önyargı (bias): eğitim verisi önyargılıysa model de önyargılı olur — işe alımda, kredi değerlendirmede ayrımcılık. Gizlilik: yüz tanıma ile gözetleme, kişisel veri kullanımı. Şeffaflık: black-box modeller kararlarını açıklayamıyor (explainable AI önemli). Deepfake: sahte içerik üretimi. İş kaybı: otomasyon ile işsizlik riski. Silah kullanımı: otonom silahlar. AI geliştiricileri olarak bu konuları düşünmemiz lazım. EU AI Act gibi düzenlemeler geliyor. Sorumlu AI (Responsible AI) prensipleri: adalet, şeffaflık, gizlilik, güvenlik. Teknoloji nötr değil — nasıl kullanıldığı önemli.","AI etiği, bias, gizlilik, şeffaflık, deepfake, sorumlu AI, EU AI Act.")
add("explainable AI (XAI) ne demek?","Explainable AI, yapay zeka modellerinin kararlarını açıklayabilir hale getirmek. Derin öğrenme modelleri genelde black-box — doğru tahmin yapar ama neden o tahmin diye açıklayamaz. Bu sağlık, hukuk, finans gibi kritik alanlarda problem. Yöntemler: LIME (Local Interpretable Model-agnostic Explanations), SHAP (SHapley Additive exPlanations), attention visualization, feature importance. Mesela bir kredi red kararında 'gelir düşük olduğu için reddedildi' gibi bir açıklama sunabilirsin. EU AI Act yüksek riskli AI sistemlerinde açıklanabilirlik gerektiriyor. Güvenilir AI için şeffaflık şart.","XAI, LIME, SHAP, black-box, şeffaflık, EU AI Act.")

# Proje yönetimi
add("agile ve scrum ne demek?","Agile, yazılım geliştirmede esnek ve iteratif bir yaklaşım — uzun planlama yerine kısa döngülerle (sprint) ilerlersin. Scrum, Agile'ın en popüler framework'ü. Sprint (2-4 hafta), daily standup (günlük 15 dk toplantı), sprint review, sprint retrospective temel ritüeller. Roller: Product Owner (ne yapılacağını belirler), Scrum Master (süreci yönetir), Development Team (geliştirme yapar). Backlog: yapılacak işlerin listesi. User story: 'Kullanıcı olarak X istiyorum ki Y olsun' formatında. Jira, Trello, Linear gibi araçlarla takip edilir. Çoğu yazılım şirketi Scrum veya Kanban kullanıyor.","Agile, Scrum, sprint, daily standup, Product Owner, Jira.")
add("yazılım projesini nasıl planlamalıyım?","Proje planlaması başarının anahtarı. İlk adım: gereksinimleri net belirle — ne yapılacak, ne yapılmayacak (scope). Wireframe veya mockup oluştur — Figma ile. Teknik mimariyi belirle — frontend, backend, veritabanı, API tasarımı. İşleri küçük parçalara böl — her parça 1-2 günde tamamlanabilir olsun. Önceliklendirme yap — MVP (Minimum Viable Product) ile başla, en önemli özellikleri önce geliştir. Git branching stratejisi belirle. CI/CD kur. Zaman çizelgesi oluştur ama esnek ol. Düzenli ilerleme kontrolü yap. Görkem hackathon'larda hızlı planlama yapmayı öğrenmiştir — 48 saatte ürün çıkarmak iyi planlama gerektirir.","Proje planlama, gereksinim, wireframe, MVP, önceliklendirme, CI/CD.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_tr5.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} Turkish entries (part 5).")

if __name__=="__main__":
    main()
