"""Ek TR training data - Bolum 19. Web Guvenligi, API Tasarimi, Veritabani Ileri, Algoritmalar, Kariyer."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

add("SQL injection nasil onlenir?","SQL injection en tehlikeli ve yaygin guvenlik aciklarindan biri. Saldirgan girdiye SQL kodu enjekte eder: ' OR 1=1 -- gibi. Sonuc: tum veritabani okunabilir, silinebilir veya degistirilebilir. Onleme: 1) Parametreli sorgular / Prepared statements — ASLA string birlestirme ile SQL olusturma. Python: cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,)). 2) ORM kullan (Django ORM, SQLAlchemy) — otomatik olarak parametreli sorgular yapar. 3) Girdi dogrulama — beklenen formatlara uymayan girdileri reddet. 4) En az ayricalik — veritabani kullanicilarina minimum yetkiler ver, DROP TABLE yetkisi yok. 5) WAF (Web Application Firewall) ek koruma icin. 6) Duzenli guvenlik taramasi (OWASP ZAP, SQLMap). Gorkem'in projelerinde parametreli sorgular kullanmak temel bir guvenlik uygulama.","SQL injection, parametreli sorgular, ORM, girdi dogrulama, WAF, guvenlik.")

add("OWASP Top 10 nedir?","OWASP Top 10, en kritik web guvenlik aciklarini listeler. 1) Bozuk Erisim Kontrolu: yetkisiz erisim — normal kullanicilarin admin sayfalarina ulasmasI. 2) Kriptografik Basarisizliklar: hassas veri sifrelenmemis, sifreler HTTP uzerinden gonderilmis. 3) Enjeksiyon: SQL, NoSQL, OS komut enjeksiyonu. 4) Guvenli Olmayan Tasarim: tasarim asamasinda guvenlik dusunulmemis. 5) Guvenlik Yapilandirma Hatalari: varsayilan sifreler, gereksiz servislerin acik olmasi. 6) Savunmasiz Bilesenler: bilinen guvenlik aciklarina sahip eski kutuphaneler. 7) Kimlik Dogrulama Basarisizliklari: zayif kimlik dogrulama. 8) Yazilim/Veri Butunlugu Basarisizliklari: guvenilmeyen kaynaklardan guncellemeler. 9) Gunlukleme ve Izleme Basarisizliklari: saldirilar fark edilmiyor. 10) SSRF: Sunucu Tarafi Istek Sahteciligi. Her web gelistiricisi bu listeyi bilmeli ve projelerini buna karsi dogrulamali.","OWASP Top 10, web guvenligi, enjeksiyon, kimlik dogrulama, erisim kontrolu.")

add("REST API tasarim prensipleri nelerdir?","Iyi bir REST API tasarimi icin prensipler: 1) Kaynak odakli URL'ler — /users, /users/123, /users/123/orders. Fiil degil isim kullan. 2) HTTP metodlari dogru kullan — GET (oku), POST (olustur), PUT (tamamen guncelle), PATCH (kismi guncelle), DELETE (sil). 3) Dogru HTTP durum kodlari — 200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 422 Unprocessable Entity, 500 Internal Server Error. 4) Surumleme — URL'de (/api/v1/) veya baslikta (Accept: application/vnd.api.v1+json). 5) Sayfalama — buyuk koleksiyonlar icin limit/offset veya cursor tabanli. 6) Filtreleme ve siralama — ?status=active&sort=-created_at. 7) HATEOAS — yanitlarda ilgili kaynak linklerini dahil et. 8) Tutarli hata formati — {error: {code, message, details}}. 9) Rate limiting — istismari onle. 10) Belgelendirme — OpenAPI/Swagger ile otomatik dokumantasyon.","REST API, HTTP metodlari, durum kodlari, surumleme, sayfalama, HATEOAS, OpenAPI.")

add("veritabani indeksleme stratejileri nelerdir?","Indeksler veritabani sorgularini onemli olcude hizlandirir — bir kitabin dizini gibi dusun. B-Tree indeks en yaygindir: esitlik ve aralik sorgulari icin ideal. Hash indeks: sadece esitlik sorgulari icin, cok hizli. Bilesik indeks: birden fazla sutun uzerinde tek indeks — WHERE a=1 AND b=2 sorgulari icin mukemmel. Kismi indeks: bir kosulu karsilayan satirlari indeksler — WHERE status='active' gibi. Kapsayan indeks: sorgunun ihtiyac duydugu tum sutunlari icerir, tabloya dokunmadan yanit verir. Uyari: her indeks yazmalari yavaslatir ve disk alani kullanir. EXPLAIN ANALYZE ile sorgu planlarini incele ve gereksiz indeksleri kaldir. Iyi kural: WHERE, JOIN ve ORDER BY'da kullanilan sutunlara indeks ekle ama asiri yapma. PostgreSQL'de kIsmi indeksler ve ifade indeksleri (orn. LOWER(email)) cok guclu ozelliklerdir.","Veritabani indeksleme, B-Tree, Hash, Bilesik, Kismi, Kapsayan indeks, EXPLAIN.")

add("veritabani normalizasyonu nedir?","Normalizasyon, veritabani tasariminda veri tekrarini azaltma ve tutarliligi artirma surecidir. 1NF: hucre basina tek deger, tekrarlanan gruplar yok. 2NF: 1NF artI kismi bagimliliklar yok — tum anahtar olmayan sutunlar birincil anahtara tam bagli. 3NF: 2NF arti gecisli bagimliliklar yok — A, B'yi B de C'yi belirliyorsa, C'yi ayri tabloya tasi. BCNF: 3NF'nin daha siki versiyonu. 4NF ve 5NF cok degerli ve birlestirme bagimliliklarini ele alir, pratikte nadiren gerekli. Cogu uygulama 3NF ile iyi calisir. Dikkat: asiri normalizasyon performansi dusurur — ozellikle okuma agirlikli sistemlerde bazen kasitli denormalizasyon gereklidir. Veri ambarlari yildiz semasi gibi denormalize yapilari tercih eder. Denormalizasyon bilinçli bir karar olmali — performans ihtiyaci nedeniyle, tembellik nedeniyle degil.","Normalizasyon, 1NF, 2NF, 3NF, BCNF, denormalizasyon, veri ambari.")

add("ACID ozellikleri nedir veritabaninda?","ACID, veritabani islem guvenirligini 4 ozellik ile saglar. Atomicity (Butunluk): bir islem ya tamamen tamamlanir ya da hic tamamlanmaz — para transferinde borclandirma alacaklandirma olmadan asla gerceklesmez. Consistency (Tutarlilik): bir islem veritabanini bir gecerli durumdan digerine tasir — kisitlamalar asla ihlal edilmez. Isolation (Izolasyon): eszamanli islemler birbirini etkilemez — izolasyon seviyeleri mevcuttur (Read Uncommitted, Read Committed, Repeatable Read, Serializable). Durability (Dayaniklilik): onaylanmis islemler sistem cokse bile kalicidir — WAL (Write-Ahead Logging) ile saglanir. PostgreSQL tamamen ACID uyumludur. MongoDB 4.0'dan beri cok belgeli ACID islem destegi ekledi. ACID finansal uygulamalar icin esastir — bu yuzden Gorkem'in bankacilik projesi SQL kullaniyor.","ACID, Atomicity, Consistency, Isolation, Durability, islem, WAL.")

add("Big O notasyonu nedir ve neden onemli?","Big O, algoritma performansinin girdi boyutuyla nasil olceklendigini tanimlar. O(1) sabit: hash tablosu arama — boyut ne olursa olsun ayni hiz. O(log n) logaritmik: ikili arama — girdiyi iki katina cikarmak bir adim ekler. O(n) lineer: lineer arama — her elemani kontrol et. O(n log n) lineeritmik: merge sort, quicksort ortalama — karsilastirma tabanli en iyi siralama. O(n^2) karesel: bubble sort, ic ice donguler — 10x girdi = 100x sure. O(2^n) ustel: rekürsif fibonacci — buyuk n icin pratik olarak kullanisiz. Kurallar: sabitleri dusur (O(2n) = O(n)), dusuk terimleri dusur (O(n^2 + n) = O(n^2)), aksi belirtilmedikce en kotu durum. Alan karmasikligi da onemli: merge sort O(n) alan, quicksort O(log n). Mulakatlarda: cozumunuzun zaman VE alan karmasikligini her zaman analiz edin.","Big O, zaman karmasikligi, alan karmasikligi, O(n), O(log n), algoritma analizi.")

add("SQL JOIN turleri nelerdir?","JOIN'ler birden fazla tablodan satirlari bir kosula gore birlestirir. INNER JOIN: her iki tablodan sadece eslesen satirlari dondurur. Kullanicinin siparisi yoksa gorunmez. LEFT JOIN: sol tablodan tum satirlar + sagdan eslesen satirlar. Eslemeyen sag taraf NULL olur. Kullanim: tum kullanicilari siparisleriyle listele (siparissiz kullanicilar dahil). RIGHT JOIN: sag tablodan tum satirlar + soldan eslesen. Daha az yaygin — tablolari degistirip LEFT JOIN kullanabilirsiniz. FULL OUTER JOIN: her iki tablodan tum satirlar. Eslesme olmayan yerlerde NULL. CROSS JOIN: A tablosundaki her satir B'deki her satirla birlestirilir (Kartezyen carpim). N * M satir. Nadiren gerekli. SELF JOIN: tablo kendisiyle birlestirilir. Kullanim: calisan-yonetici iliskileri. Performans: indeksli sutunlarda JOIN'ler hizlidir. N+1 sorgu problemi: ORM tembel yukleme — tek JOIN yerine N+1 sorgu ile N ilgili nesneyi alma.","SQL JOIN, INNER JOIN, LEFT JOIN, FULL OUTER JOIN, CROSS JOIN, N+1 sorunu, indeks.")

add("clean architecture nedir?","Clean Architecture Robert C. Martin'in (Uncle Bob) mimari yaklasimdir. Temel fikir: is mantigi dis dunyadan bagimsiz olmali — framework, veritabani veya UI degisirse, temel alan degismemeli. Katmanlar (icten disa): Entities (is kurallari), Use Cases (uygulama mantigi), Interface Adapters (controller'lar, presenter'lar, gateway'ler), Frameworks & Drivers (web framework, DB, UI). Bagimlilik Kurali: bagimliliklar her zaman iceride gosterir — ic katmanlar dis katmanlari bilmez. Faydalar: test edilebilirlik (veritabani olmadan is mantigini test et), esneklik (temel degistirmeden PostgreSQL'den MongoDB'ye gec), anlasilabilirlik. Dezavantajlar: kucuk projeler icin asiri karmasik, cok fazla sablonlu kod. Buyuk, uzun omurlu projeler icin degerli — ama bir startup MVP icin asiri muhendislik olabilir.","Clean Architecture, Uncle Bob, bagimlilik kurali, entities, use cases, katmanlar.")

add("domain-driven design DDD nedir?","DDD, Eric Evans'in karmasik is mantigini modelleme yaklasimidir. Temel fikir: yazilim yapisi isin alan yapisini yansitmali. Ortak Dil (Ubiquitous Language): gelisitirciler ve alan uzmanlari ayni dili konusur — kodda da kullan. Sinirli Baglam (Bounded Context): buyuk sistemi bagimsiz bolgelere bol — ayni terim farkli baglamlarda farkli anlamlara gelebilir (Musteri siparis vs CRM'de). Entity: kimligè sahip nesneler (Kullanici, Siparis). Value Object: kimliksiz, degeri ile tanimlanan (Adres, Para). Aggregate: tutarlilik siniri — birlikte degismesi gereken varliklar grubu. Repository: aggregate'lere erisim saglar. Domain Event: 'siparis olusturuldu' gibi olaylar. DDD karmasik is mantigina sahip projeler icin cok degerli ama basit CRUD uygulamalari icin gereksiz.","DDD, Bounded Context, Entity, Value Object, Aggregate, Ubiquitous Language.")

add("containerization vs virtualization farki nedir?","Sanal Makineler (VM): hypervisor uzerinde tam bir isletim sistemi calistirir — Tip 1 (bare metal — VMware ESXi, KVM) veya Tip 2 (host OS uzerinde — VirtualBox). Her VM'in kendi cekirdegi, suruculeri, kutuphaneleri var. Agir (gigabyte'lar), baslamasi yavas (dakikalar), ama guclu izolasyon. Konteynerler: host isletim sistemi cekirdegini payrasir, Linux namespace'leri (PID, ag, mount, kullanici) ve cgroup'lar (kaynak sinirlamalari) kullanarak islem duzeyinde izole eder. Hafif (megabyte'lar), aninda baslar (milisaniyeler), VM'lerden daha az izolasyon. Docker konteynerleri populer hale getirdi. Ne zaman VM: farkli OS gerekli, guclu guvenlik izolasyonu, eski uygulamalar. Ne zaman konteyner: mikroservisler, CI/CD, tutarli gelistirme/uretim ortamlari, hizli olcekleme. Modern yaklasim: VM'lerin icinde calisanlar konteynerler — Kubernetes dugumleri VM'lerdir, her biri bircok konteyner calistirir.","Konteynerlestime, sanallastirma, VM, Docker, namespace'ler, cgroup'lar, hypervisor.")

add("fonksiyonel programlama nedir ve ne zaman kullanilir?","Fonksiyonel programlama (FP) hesaplamayi matematiksel fonksiyonlarin degerlendirilmesi olarak ele alir. Temel ilkeler: 1) Saf fonksiyonlar — ayni girdi her zaman ayni ciktiyi verir, yan etkisi yok. Test etmesi, anlamasi ve paralellestirmesi kolay. 2) Degismezlik — veriler degismez. Degistirmek yerine yeni veri olustur. Hatalarin butun bir sinifini ortadan kaldirir (paylasilan degisken durum). 3) Birinci sinif fonksiyonlar — fonksiyonlar degerdir, arguman olarak gecilebilir. 4) Yuksek dereceli fonksiyonlar — map, filter, reduce. 5) Kompozisyon — basit fonksiyonlardan karmasik fonksiyonlar olustur. FP dilleri: Haskell (saf), Erlang/Elixir (eszamanli), Clojure, Scala. Mainstream dillerde FP: Python (map, filter, lambda, liste kavramalar), JavaScript (dizi metodlari, React hook'lari), Java (stream'ler, lambda'lar). Ne zaman kullanilir: veri donusumleri, eszamanli/paralel kod, karmasik durum yonetimi. En iyi yaklasim: OOP kodunuz icinde FP ilkelerini kullanin.","Fonksiyonel programlama, saf fonksiyonlar, degismezlik, yuksek dereceli fonksiyonlar, Haskell.")

add("concurrency modelleri arasindaki farklar nelerdir?","Farkli diller eszamanliligi farkli sekilde ele alir. 1) Kilitlerle is parcaciklari (Java, C++, Python): isletim sistemi duzeyinde is parcaciklari, paylasilan bellek, mutex/semafor ile senkronizasyon. Artilari: basit zihinsel model. Eksileri: kilitlenme, yaris kosullari, hata ayiklamasi zor. 2) Aktor modeli (Erlang, Akka): aktorler kendi durumlariyla bagimsiz birimler, mesajlarla iletisim kurar. Paylasilan durum yok = kilit yok. Artilari: hata toleransli, olceklenebilir. 3) CSP — Communicating Sequential Processes (Go): goroutine'ler kanallar araciligiyla iletisim kurar. 'Bellegi paylasarak iletisim kurma; iletisim kurarak bellegi paylasin.' 4) Async/await (JavaScript, Python, Rust): isbirlikci coklu gorev ile tek is parcacikli olay dongusu. Artilari: is parcacigi sorunlari yok, I/O icin harika. 5) Yesil is parcaciklari (Java Loom, Go goroutine): hafif kullanici alani is parcaciklari. Secim: I/O agirlikli → async/await, CPU agirlikli → is parcaciklari veya islemler, dagitik → aktorler.","Eszamanlilik, is parcaciklari, aktor modeli, CSP, async/await, goroutine, olay dongusu.")

add("process ve thread arasindaki fark nedir?","Process kendi bellek alanina sahip bagimsiz program yurutmesidir. Thread bir process icindeki yurutme birimidir, process'in bellegini payrasir. Process: ayri bellek, IPC ile iletisim (pipe, soket, paylasilan bellek), cokmesi diger process'leri etkilemez, olusturmasi daha agir. Thread: paylasilan bellek (heap), paylasilan degiskenlerle iletisim (senkronizasyon gerekir), cokmesi tum process'i dusuurebilir, olusturmasi daha hafif. Eszamanlilik vs Paralellik: eszamanlilik birden fazla gorevi yonetmektir (tek CPU'da serpistirilebilir), paralellik gercekten birden fazla CPU'da ayni anda calismaktir. Is parcacigi guvenligi: is parcaciklari paylasilan verilere ayni anda eristiginde yaris kosullari olusur. Cozumler: mutex/kilit, semafor, okuma-yazma kilidi, atomik islemler. Python'da: GIL gercek is parcacigi paralelligini engeller — CPU bagli gorevler icin multiprocessing, I/O bagli icin threading kullan.","Process, thread, eszamanlilik, paralellik, mutex, yaris kosulu, GIL, goroutine.")

add("environment variable'lar nasil yonetilir?","Ortam degiskenleri yapilandirmayi kodunuzun disinda saklar — veritabani URL'leri, API anahtarlari, ozellik bayraklari. Neden: gelistirme/hazirlik/uretim icin farkli degerler, sirlar kodda olmamali, yeniden dagitim olmadan degistirmesi kolay. .env dosyalari: yerel olarak sakla, ASLA git'e commit etme (.gitignore'a ekle). Kutuphaneler: python-dotenv (Python), dotenv (Node.js). Docker'da: Dockerfile'da ENV, --env-file bayragi, docker-compose'da environment. CI/CD'de: GitHub Actions secrets, GitLab CI degiskenleri. Ureitmde: AWS Parameter Store, AWS Secrets Manager, HashiCorp Vault, Doppler. 12-Factor App metodolojisi: yapilandirmayi ortam degiskenlerinde sakla. En iyi uygulamalar: aciklayici isimler kullan (DB degil DATABASE_URL), .env.example dosyasi sagla (commit edilmis, sahte degerlerle), baslatmada ortam degiskenlerini dogrula (hizli basa). Ortam degiskenlerini asla loglama — sir icerebilirler.","Ortam degiskenleri, .env, sir yonetimi, Vault, 12-Factor App, yapilandirma.")

add("Agile ve Scrum pratikte nasil calisir?","Agile, surekli geri bildirimle yazilimi yinelemeli olarak teslim eden bir yazilim gelistirme felsefesidir. Agile Manifesto degerleri: sureclerden cok bireyler, belgelerden cok calisan yazilim, sozlesmelerden cok musteri isbirligi, plana uymaktan cok degisime yanit verme. Scrum en populer Agile cercevesidir. Roller: Product Owner (ne insaa edilecegini tanimlar, backlog'u onceliklendirir), Scrum Master (sureci kolaylastirir, engelleyicileri kaldirir), Gelistirme Takimi (urunu insa eder). Etkinlikler: Sprint (1-4 haftalik iterasyon), Sprint Planlama (ne insaa edilecegine karar ver), Gunluk Toplanti (15 dk), Sprint Incelemesi (paydaşlara demo), Sprint Retrospektifi (nasil iyilestiririz). Hikaye puanlari: zamani degil karmasikligi tahmin et. Hiz: sprint basina tamamlanan ortalama puan. Kanban bir alternatif: sprintler yerine surekli akis, devam eden is sinirlari. Pratikte: cogu takim 'Scrumban' yapar — bir karisim.","Agile, Scrum, Sprint, Product Owner, Scrum Master, Kanban, hiz, retrospektif.")

add("gelisitirciler icin yumusak becerilerin onemi nedir?","Teknik beceriler mulakati getirir, yumusak beceriler terfi ettirir. Temel yumusak beceriler: 1) Iletisim — teknik kavramlari teknik olmayan kisilere acikla, net belgelendirme yaz, tasarim kararlarindaki trade-off'lari ifade et. 2) Isbirligi — kod incelemesi (yapici geri bildirim ver), esli programlama, bilgi paylasimi. 3) Problem cozme — karmasik problemleri daha kucuk parcalara bol, dogru soruları sor. 4) Zaman yonetimi — dogru tahmin yap (tampon ekle), acımasızca onceliklendirmek, hayir demeyi ogren. 5) Empati — kullanici ihtiyaclarini anla, kod incelemelerinde takim arkadaslarinin bakis acisini dikkate al. 6) Uyarlanabilirlik — teknoloji hizla degisir, ogrenme istekliligi mevcut bilgiden daha degerli. 7) Mentorluk — baskalarina ogretmek kendi anlamanizi pekistirir. 8) Geri bildirim alma — kod incelemesi yorumlarini kisisel alma. Iyi iletisim kuran iyi bir gelistirici, iletisim kuramayan harika bir gelistiriciden daha degerlidir.","Yumusak beceriler, iletisim, isbirligi, empati, mentorluk, geri bildirim, liderlik.")

add("acik kaynak katkilarinin onemi nedir?","Acik kaynaga katkida bulunmak hem kariyerinize hem topluluğa fayda saglar. Faydalar: uretim kalitesinde kod tabanlarindan ogrenin, deneyimli gelistiricilerle calisin, becerilerinizin kamusal kaniti olusturun, ag kurun (OSS bakim sorumluları genellikle ust sirketlerde calisir), günluk kullandiginiz araclara geri verin. Baslarken: 1) Gercekten kullandiginiz bir proje secin — kod tabanini anlarsiniz ve motive olursunuz. 2) Kucuk baslayin — belgelerdeki yazim hatalarini duzelt, hata mesajlarini iyilestir, testler ekle. 3) 'Good first issue' veya 'help wanted' etiketlerini arayin. 4) CONTRIBUTING.md'yi okuyun ve projenin kurallarini takip edin. 5) Net aciklamalarla temiz PR'lar gonderin. Yaygin yanilgilar: uzman olmaniz gerekmiyor (bircok katki belgelerdir), bir projeyi surdurmek zorunda degilsiniz, kucuk katkilar bile onemli. Programlar: Hacktoberfest, Google Summer of Code. GitHub katki grafiginiz ve birlestirilen PR'lariniz herhangi bir ozgecmis maddesinden daha yuksek sesle konusur.","Acik kaynak, katkilar, GitHub, good first issue, Hacktoberfest, topluluk, kariyer.")

add("yazilim gelistirmenin AI ile gelecegi nasil?","AI, yazilimin nasil insa edildigini donusturuyor. Mevcut durum: AI kodlama asistanlari (GitHub Copilot, Cursor, Claude Code) sablonlu kodu ele alir, uygulamalar onerir, kodu aciklar, testler yazar. Ne degisiyor: 1) Kod uretimi — AI ilk taslaklari yazar, insanlar inceler ve iyilestirir. 2) Hata ayiklama — AI hata izlerini analiz eder ve duzeltmeler onerir. 3) Test — AI koddan test durumları uretir. 4) Belgelendirme — AI belgeleri yazar ve gunceller. 5) Kod inceleme — AI hatalari, guvenlik sorunlarini yakalar. Ne degismiyor: gereksinimleri anlama, sistem tasarimi, mimari kararlar, karmasik dagitik sistemlerde hata ayiklama, kullanici ihtiyaclarini anlama. AI gelistiricilerin yerini alacak mi? Hayir — ama AI kullanan gelistiriciler kullanmayanlarin yerini alacak. Gelisen gelisitirciler derin teknik anlamayi etkili AI arac kullanimiyla birlestirenler olacak — tam olarak Gorkem'in insaa ettigi kombinasyon.","AI gelecegi, kodlama asistanlari, Copilot, Cursor, gelistirici becerileri, otomasyon.")

add("rubber duck debugging nedir?","Rubber duck debugging, kodunuzu satir satir cansiz bir nesneye (geleneksel olarak lastik ordek) acikladiginiz bir yontemdir. Problemi ifade etme eylemi sistematik dusunmeye zorlar. Genellikle aciklanirken hatayi bulursunuz cunku sozlu ifade farkli bilissel surecleri devreye sokar. Neden ise yarar: kod okurken beklediginizi gorursunuz. Yuksek sesle acikladiginizda, kodun gercekte ne yaptigini tanimlamaniz gerekir. 'Kodun ne yaptigini dusundugunuz' ile 'kodun gercekte ne yaptigi' arasindaki fark, hatalarin yasadigi yerdir. Lastik ordek alternatifleri: bir meslektasiniza aciklama (esli programlama), her adimi aciklayan yorumlar yazin, ChatGPT/Claude'u lastik ordeginiz olarak kullanin. Feynman Teknigi benzerdir — basitce aciklayamiyorsaniz, anlamamissinizdir. Bu teknik deneyimli gelistiriciler icin bile sasirtici derecede etkilidir.","Rubber duck debugging, Feynman Teknigi, problem cozme, sozel ifade, hata ayiklama yontemi.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_tr19.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} Turkish entries (part 19).")
if __name__=="__main__":
    main()
