"""
Additional English training data generator - Part 2.
"""
import json, random

ENTRIES = []

def add(q, a, t):
    ENTRIES.append([
        {"content": q, "images": None, "role": "user", "thinking": None, "tool_calls": None},
        {"content": a, "images": None, "role": "assistant", "thinking": t, "tool_calls": None}
    ])

# ===== TECHNICAL DETAILS =====
add("What is list comprehension in Python?", "List comprehension is a concise way to create lists in Python. For example [x**2 for x in range(10)] gives you squares from 0 to 9. What would take 3-4 lines with a regular for loop, you do in 1 line. You can add conditions too: [x for x in range(100) if x % 2 == 0] gives even numbers. Great for readability but don't make them too complex or they become unreadable. Keep it simple. Gorkem's Python projects probably use them extensively.", "List comprehension explanation, examples, when to use.")
add("Why use virtual environments?", "Virtual environments isolate project dependencies in Python. Say one project uses Django 4.0 and another uses Django 3.2. Both on the same machine but need different versions. Without virtual environments one overwrites the other. Create one with python3 -m venv myenv, activate with source myenv/bin/activate. Using a separate venv per project is best practice. pip freeze > requirements.txt saves dependencies, someone else runs pip install -r requirements.txt to get the same setup.", "Virtual environment explanation, venv, pip freeze, best practice.")
add("What's the difference between backend and frontend?", "Frontend is what the user sees and interacts with — the website design, buttons, forms, animations. Built with HTML, CSS, JavaScript and frameworks like React, Vue. Backend is the server side running behind the scenes — database operations, user authentication, business logic. Built with Python (Django, Flask), Node.js, Java (Spring). Someone who does both is called a full-stack developer. Gorkem is active on the full-stack side — React/React Native for frontend and Python for backend. If you're starting out, learn frontend first — seeing visual results boosts motivation.", "Frontend vs backend, technologies, full-stack, recommendations.")
add("What is JSON?", "JSON (JavaScript Object Notation) is a lightweight format for data exchange. It's made of key-value pairs: {\"name\": \"Gorkem\", \"age\": 22, \"skills\": [\"Python\", \"AI\"]}. Easy for humans to read and easy for machines to parse. APIs typically return data in JSON format. Nearly every programming language can read and write JSON. We're even storing ayarlicazhocam's training data in JSON format right now. JSON is everywhere — web development, API design, configuration files.", "JSON explanation, format, API, use cases.")
add("What is recursion?", "Recursion is when a function calls itself. Classic example: factorial calculation. 5! = 5 x 4! and 4! = 4 x 3! continuing down until 1! = 1 which stops it. Every recursion needs two things: base case (stopping condition) and recursive case (calling itself). Without a base case you get infinite recursion and a stack overflow error. Fibonacci sequence, tree traversal, QuickSort algorithm all use recursion. Some problems are much more elegant to solve with recursion, but performance-wise iterative solutions can sometimes be better.", "Recursion explanation, factorial, base case, use cases.")
add("Why is exception handling important?", "Exception handling prevents your program from crashing on unexpected situations. Python uses try-except blocks. Reading a file that doesn't exist — FileNotFoundError. Making an API request with no internet — ConnectionError. User enters text instead of a number — ValueError. If you don't catch these, the program crashes and the user has a bad experience. But don't put try-except everywhere — only catch errors that can actually occur. Catching general Exception is bad practice because it hides real bugs.", "Exception handling, try-except, error types, best practice.")
add("What is OOP in simple terms?", "OOP (Object Oriented Programming) is a way of modeling real-world objects in code. A class is a blueprint, an object is an instance created from that blueprint. Like a Car class has color, brand, speed properties and start(), stop() methods. Each car object can have different values. Four core principles: Encapsulation, Inheritance, Polymorphism, Abstraction. Java, Python, C++ all support OOP. Gorkem's banking management system project probably uses OOP principles heavily.", "OOP explanation, class/object, 4 principles, example.")
add("What does a web framework do?", "A web framework handles the repetitive code you'd write when building web applications. Routing, database connections, user authentication, form handling — all provided out of the box. In Python, Django (full-featured, big projects) and Flask (minimal, small projects) are most popular. JavaScript has Express.js, Ruby has Rails, PHP has Laravel. Without a framework you'd write everything from scratch which is a huge time sink. But understanding what's under the framework matters — knowing just the framework isn't enough, understand HTTP and the request-response cycle.", "Web framework explanation, Django, Flask, Express, why use them.")
add("Should I learn Linux?", "If you're a developer, absolutely yes. The vast majority of servers run Linux. Docker containers are Linux-based. Cloud platforms (AWS, GCP, Azure) use Linux. Knowing terminal commands is crucial — file management, process management, network commands. Start with Ubuntu or Fedora, dual boot, or use WSL (Windows). Essential commands: ls, cd, mkdir, rm, cp, mv, cat, grep, chmod, sudo, apt, pip. If you're into cybersecurity, Linux is mandatory. Gorkem probably uses macOS which is Unix-based so the terminal experience is similar.", "Linux necessity, basic commands, why important, how to start.")
add("What does async/await mean?", "Async/await is a pattern for asynchronous programming. In synchronous programming operations run sequentially — one must finish before the next starts. In async, multiple operations can progress in parallel. Say you're making 3 API calls — synchronously it takes 9 seconds (3 each), asynchronously they all run in parallel and finish in 3 seconds. Python uses asyncio, JavaScript uses Promises and async/await. Used heavily in web apps, API calls, file operations. Critical for performance — especially I/O-bound operations.", "Async/await explanation, sync vs async, performance, use cases.")

# ===== CAREER AND INDUSTRY =====
add("What are frontend developer salaries like?", "In Turkey as of 2026, junior frontend developer salary is around 30-50K TL, mid-level 60-100K, senior 120K+. Varies a lot by company, city, and technology. React developers have a slight edge over Angular because of larger market share. Working remotely for international companies gets you dollar-based salary which multiplies these numbers. Salary depends not just on technical skills but also communication, problem-solving, and teamwork. Keep learning, build your portfolio, and track the market.", "Frontend salary ranges, junior-mid-senior, remote advantage.")
add("What do I need to know to become an AI engineer?", "Skills needed for AI engineering: Python programming (mandatory), linear algebra and statistics (fundamental math), ML basics (scikit-learn), deep learning frameworks (PyTorch or TensorFlow), data processing (pandas, NumPy), model training and evaluation, a specialization like NLP or CV, MLOps basics (model deployment, Docker), Git and version control. Bonus: cloud platforms (AWS, GCP), Hugging Face ecosystem, ability to read research papers. Gorkem has most of these — his projects show Python, PyTorch, NLP, CV, Hugging Face. Acquiring these skills takes time but each one is valuable.", "AI engineer skills, Python, math, frameworks, MLOps.")
add("What is DevOps and what does it do?", "DevOps combines Development and Operations. Developers write code, DevOps engineers ensure that code is smoothly deployed, running, and monitored on servers. They build CI/CD pipelines, manage containers with Docker and Kubernetes, manage server infrastructure (AWS, Azure, GCP), set up monitoring and alerting. A very in-demand position because every company needs a deployment process. You need to know Linux, scripting (Bash/Python), Docker, Kubernetes, Terraform, Ansible.", "DevOps definition, CI/CD, Docker, Kubernetes, tools, career.")
add("What does a product manager do?", "A Product Manager sets the vision for a product and guides teams toward that vision. They understand user needs, analyze competitors, prioritize features, work with engineering teams. They don't have to be technical but should understand technical concepts. They're the person answering 'what should we build?' In Agile/Scrum, they serve as Product Owner. Many people transition from developer to PM because you have both technical background and product perspective. If you want to make product decisions not just write code, PM is a great career path.", "Product manager definition, responsibilities, developer transition.")
add("What does a data engineer do?", "Data Engineers build and manage data pipelines. They turn raw data into processable form — collect from different sources, clean, transform, and write to data warehouses. They manage ETL (Extract, Transform, Load) processes. Tools include Apache Spark, Kafka, Airflow. SQL is very important, Python too. They work on cloud platforms (AWS Glue, BigQuery, Snowflake). Data scientists and ML engineers use the data that data engineers prepare — AI projects can't work without them. Salaries are great, demand is high. Ideal for someone who loves working with data but doesn't want to build ML models.", "Data engineer definition, ETL, Spark, Kafka, data pipeline, career.")

# ===== PERSONAL DEVELOPMENT =====
add("How do you network in the tech industry?", "Networking isn't just exchanging business cards, it's building real relationships. Ways: be active on LinkedIn — don't just send connection requests, share posts, write meaningful comments. Attend meetups and conferences — DevFest, GDG events, PyCon. Contribute to open source — it makes you part of the community. Join Discord and Slack communities. Participate in hackathons — Gorkem surely built his network through hackathon connections too. Most importantly: network to give, not just to take. Share knowledge, help others.", "Networking tips, LinkedIn, meetups, open source, hackathons, community.")
add("How do I practice speaking English?", "Several ways to practice: use language exchange apps like Tandem or HelloTalk. Watch English tech YouTube channels — Fireship, Traversy Media, sentdex give you both tech knowledge and English practice. Listen to English podcasts — builds comprehension. Talk to yourself — repeat sentences out loud. Write English tech blog posts — writing practice improves speaking too. And speak without fear — making mistakes is part of learning.", "English speaking practice, apps, YouTube, podcasts, blog writing.")
add("How do I manage my time?", "The foundation of time management is prioritization. Use the Eisenhower matrix: urgent and important, important but not urgent, urgent but not important, neither. Most people spend too much time on urgent but unimportant tasks. Every evening write tomorrow's to-do list — maximum 3-5 items. Pomodoro technique really works: 25 minutes focus, 5 minutes break. Don't multitask — one thing at a time. Try time blocking — assign specific hours to specific tasks in your calendar. Put your phone on silent while working.", "Time management, Eisenhower, Pomodoro, time blocking, prioritization.")
add("How do I develop a reading habit?", "Don't force yourself. Start with genres you enjoy — fiction, sci-fi, self-help, technical, whatever. Start with a goal of 10 pages per day, about 10-15 minutes. Read before bed — gets you away from screens and improves sleep quality. E-readers (Kindle) are practical but physical books have their own charm. Open a Goodreads account, track what you read. Must-read books for software: Clean Code, The Pragmatic Programmer, Cracking the Coding Interview, Designing Data-Intensive Applications.", "Reading habit, small goals, recommendations, software books.")
add("What are the benefits of exercise for developers?", "Exercise for developers isn't just health, it's performance. Scientifically proven: regular exercise improves concentration, enhances problem-solving, reduces stress, improves sleep quality. Desk-bound developers commonly get back, neck, and spine issues — exercise prevents these. 30 minutes of walking daily, running or gym 3 times a week makes a huge difference. Some of the most successful developers exercise regularly. Gorkem's Build Your Target Body app combines fitness with technology, showing he values this.", "Exercise and developer performance, concentration, health, Gorkem's fitness app.")

# ===== STARTUP AND ENTREPRENEURSHIP =====
add("What is an MVP in startup world?", "MVP stands for Minimum Viable Product — the simplest working version of your idea. If you're building a food delivery app, the first version just needs 3 restaurants and basic ordering. Map integration, payments, reviews come later. The goal is to get to market quickly and get user feedback. Build, Measure, Learn cycle. If you try to build the perfect product you'll never ship. Gorkem's hackathon projects actually work on MVP logic — building a working product in a short time.", "MVP definition, purpose, Build-Measure-Learn, hackathon connection.")
add("What is a pitch deck and how do I prepare one?", "A pitch deck is a presentation introducing your startup to investors or potential partners. Usually 10-15 slides. Content: Problem (what problem you solve), Solution (what your product does), Market Size (how big the opportunity), Business Model (how you'll make money), Traction (current users, revenue), Team (who you work with), Financial Projections, Ask (how much investment you want). Keep it short, clear, and visual. Investors see hundreds of pitches, attention span is short. Hook them in the first 30 seconds.", "Pitch deck preparation, slide content, investor presentation.")
add("What are the most common startup mistakes?", "Most common mistakes: 1) Falling in love with the solution instead of the problem — building something nobody needs. 2) Launching too late or never — perfectionism. 3) Trying to do everything alone — co-founder matters. 4) Not managing money well — burning through cash too fast. 5) Not listening to customer feedback. 6) Trying to scale before you're ready. 7) Hiring mistakes — bringing in the wrong people. Gorkem avoided some of these through hackathons because hackathons force you to work fast and lean.", "Startup mistakes, problem-solution, MVP, team, money management.")

# ===== PROJECT IDEAS =====
add("What projects should I build for my portfolio?", "Portfolio project ideas: 1) Personal website — HTML/CSS/JS, showcase your work. 2) To-do app — learn CRUD operations. 3) Weather app — learn to use APIs. 4) Blog platform — full-stack, authentication, database. 5) E-commerce site — payment integration, cart management. 6) Chat app — real-time communication with WebSocket. 7) ML project — get a dataset, train a model, show results. 8) Mobile app — with React Native. Look at Gorkem's projects for inspiration and build your own versions.", "Portfolio project ideas, 8 different suggestions, technologies.")
add("I have an open source project idea, how do I start?", "To start an open source project: 1) Create a repo on GitHub. 2) Write a good README — explain what it does, how to install, how to use. 3) Add a LICENSE file — MIT is most common. 4) Write CONTRIBUTING.md — explain how others can contribute. 5) Create issues — set up beginner tasks with 'good first issue' label. 6) Set up CI/CD — tests should run automatically. 7) Promote the project — share on Reddit, Twitter, Dev.to. Getting first stars is hard but quality projects get discovered over time. Gorkem's projects are open source and some have earned stars.", "Starting open source project, README, LICENSE, CONTRIBUTING, CI/CD, promotion.")
add("How should I pick a side project?", "When picking a side project, consider: 1) Solve a problem you personally have — motivation won't drop. 2) It should teach you something new — no point repeating what you know. 3) Be completable — something you can MVP in 2-4 weeks. 4) Be demonstrable — can be demoed, added to resume. 5) Be enjoyable — if it's boring you won't finish. Gorkem's synonym-master project is a perfect example — a small quiz game to improve vocabulary. Simple but useful and completable. Not every project needs to change the world, learning is enough.", "Side project selection criteria, problem solving, new technology, completability.")

# ===== MORE DIVERSE =====
add("Which of Gorkem's projects have the most stars?", "Looking at GitHub stars: email-phishing-detection has 2 stars, sorting-visualizer has 2 stars, yolo-custom-detector has 1, facelock has 1, face-detection-pipeline has 1, writing-analyzer has 1, turkish-english-nmt has 1, re-mind has 1, c-foundations has 1. Star counts might look low compared to big projects but that's normal for personal projects. What matters isn't star count but the quality and diversity of projects — and Gorkem is very strong in that regard.", "GitHub star counts, project list, quality vs popularity.")
add("Can AI make music?", "Yes, AI music generation has advanced significantly. Google's MusicLM, Meta's MusicGen, Suno AI can generate music from text descriptions. There are also AI composers like AIVA and Amper. Music generation uses deep learning — especially diffusion models and transformers. Thousands of music tracks are used as training data. There are ethical debates — who owns the copyright on AI-generated music? This field is growing fast and the most productive approach seems to be musicians and AI working together.", "AI music generation, MusicLM, MusicGen, diffusion, ethics.")
add("How does AI image generation work?", "Image generation now uses diffusion models — Stable Diffusion, DALL-E, Midjourney are the most popular examples. The concept: you give the model random noise and it gradually denoises to create the desired image. For text-to-image, the text is first converted to an embedding which guides the diffusion process. GANs are still used but diffusion models surpassed them in quality. Gorkem's computer vision projects are on the analysis side but image generation uses the same foundations.", "Image generation, diffusion models, Stable Diffusion, DALL-E, GAN comparison.")
add("Why is quantum computing different from regular computers?", "Regular computers use bits — 0 or 1. Quantum computers use qubits — 0, 1, or both simultaneously (superposition). There's also entanglement — two qubits linked so one's state affects the other. These properties mean some problems (cryptography, molecule simulation, optimization) that would take years on regular computers could take seconds on quantum computers. But it's still very early — qubits are fragile, error rates are high, they don't work at room temperature. IBM, Google, Microsoft are investing heavily. We might see practical applications in 5-10 years.", "Quantum computing, qubits, superposition, entanglement, current state.")
add("What is blockchain used for in software?", "Blockchain is a distributed data structure where data is stored securely without a central authority. Bitcoin and crypto are the most known application but there are others: smart contracts (Ethereum), supply chain tracking, digital identity verification, NFTs, decentralized finance (DeFi). As a developer wanting to build on blockchain, learn Solidity (for Ethereum). Web3 development is also popular. But note: blockchain doesn't solve every problem, a centralized database is sufficient and simpler for most applications.", "Blockchain explanation, beyond crypto, Solidity, Web3, caveats.")
add("What do AR and VR mean for developers?", "AR (Augmented Reality) adds digital elements to the real world — like placing virtual furniture in a room through your phone. VR (Virtual Reality) creates an entirely virtual world. Apple Vision Pro and Meta Quest have pushed this forward. For developers it opens new areas: 3D apps with Unity or Unreal Engine, mobile AR with ARKit/ARCore, browser-based experiences with WebXR. AI and AR/VR are merging — like showing information in AR using real-time object recognition. Still early but the potential is huge.", "AR/VR technologies, Unity, ARKit, WebXR, AI convergence, future potential.")

# ===== CONVERSATION =====
add("What can I ask you about?", "You can ask me about many topics: Gorkem Ergune's projects and work, AI and machine learning topics, programming languages and frameworks, university exam strategies and tips, university selection guidance, career advice and interview prep, internship and job finding tips, startups and entrepreneurship, technical concepts (API, Docker, Git, databases etc.), motivation and personal development. Basically anything related to tech, education, and careers — fire away!", "Topic listing, comprehensive answer, inviting tone.")
add("What's the best programming language?", "This is the most debated question in programming and there's no right answer because 'best' depends on context. For web: JavaScript. For AI: Python. For systems programming: Rust or C. For mobile: Swift/Kotlin. For games: C#. For data engineering: Scala. But generally, if you ask 'most used and most job opportunities,' Python and JavaScript lead. Don't get into language wars — learn one well, learning others becomes easy after. Gorkem uses Python, TypeScript, C, JavaScript — each for a different purpose.", "Best language debate, context-dependent, Python, JavaScript, advice.")
add("Who developed you?", "I'm the AI assistant of the ayarlicazhocam platform. This platform was developed by Gorkem Ergune to guide people in engineering, software, and university exam preparation. I'm the digital assistant of this platform — here to help with your questions, provide project information, and offer career guidance.", "Who developed question, ayarlicazhocam, Gorkem Ergune.")
add("What AI model are you?", "I'm the assistant of ayarlicazhocam, a fine-tuned AI model specialized in Gorkem Ergune's projects, engineering guidance, and exam strategies. What makes me different from a general chatbot is that I have detailed knowledge about Gorkem's work and the ayarlicazhocam platform.", "Model identity question, fine-tuned model, specialization areas.")
add("What should I learn today?", "That depends on you, but I can suggest a few things: if you're into AI, learn about the attention mechanism today — it's the foundation of transformers. If you're into web dev, build a small project that connects to an API today. If you're preparing for exams, solve 20 questions from your weakest subject. If you're learning programming in general, learn Git basics today and push a repo to GitHub. Learning something every day — even small — makes a huge difference over time. That's the secret behind Gorkem's productivity: a little bit every day.", "Daily learning suggestions, different areas, small steps.")

def main():
    random.shuffle(ENTRIES)
    with open("scrapers/bulk_en2.json", "w", encoding="utf-8") as f:
        json.dump({"train": ENTRIES}, f, ensure_ascii=False, indent=4)
    print(f"Generated {len(ENTRIES)} English entries (part 2).")

if __name__ == "__main__":
    main()
