"""Ek TR training data - Bölüm 9. Büyük parti - çeşitli konular."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

# --- Derin teknik konular ---
add("hash table nasıl çalışır?","Hash table (hash map), key-value çiftlerini O(1) ortalama sürede saklamak ve erişmek için kullanılan veri yapısı. Hash fonksiyonu key'i bir index'e dönüştürür. Collision (çarpışma) olduğunda chaining (linked list) veya open addressing kullanılır. Python dict, JavaScript Object/Map, Java HashMap hash table implementasyonları. Load factor doluluk oranını gösterir — genelde %75'te resize yapılır. İyi bir hash fonksiyonu uniform dağılım sağlamalı. Mülakatların en çok sorulan veri yapısı — anagram, two sum, frequency count soruları hep hash table kullanır.","Hash table, hash fonksiyonu, collision, O(1), mülakat.")
add("binary search tree nedir?","BST (Binary Search Tree), her düğümün sol alt ağacındaki değerlerin düğümden küçük, sağ alt ağacındaki değerlerin büyük olduğu ağaç yapısı. Arama, ekleme, silme ortalama O(log n). Ama dengesiz olursa (tek kollu ağaç) O(n)'e düşer. Self-balancing BST'ler: AVL tree (kesin dengeli), Red-Black tree (yaklaşık dengeli — Java TreeMap bunu kullanır). İn-order traversal sıralı sonuç verir. BST mülakatların klasik konusu — LCA (Lowest Common Ancestor), validate BST, invert binary tree popüler sorular.","BST, binary search tree, AVL, Red-Black, traversal, mülakat.")
add("heap veri yapısı ne işe yarar?","Heap, en büyük veya en küçük elemanı O(1)'de bulmayı sağlayan ağaç tabanlı veri yapısı. Min-heap: kök en küçük. Max-heap: kök en büyük. Ekleme ve silme O(log n). Python'da heapq modülü min-heap sağlar. Kullanım alanları: priority queue (öncelik kuyruğu), Dijkstra'nın en kısa yol algoritması, heap sort, medyan bulma (iki heap kullanarak), top-K elemanları bulma. Mülakatlarda sıkça çıkar — 'en büyük K elemanı bul' heap kullanır. Array ile implement edilebilir — parent: (i-1)/2, left child: 2i+1, right child: 2i+2.","Heap, priority queue, min-heap, max-heap, heapq, Dijkstra.")
add("dynamic programming nedir?","Dynamic programming (DP), büyük problemi küçük alt problemlere ayırıp, her alt problemi bir kez çözerek sonuçları saklama (memoization) tekniği. İki yaklaşım: top-down (recursive + memoization) ve bottom-up (iterative + tablo). Klasik DP problemleri: Fibonacci, knapsack (sırt çantası), longest common subsequence (LCS), coin change, edit distance, longest increasing subsequence. Mülakatların en zorlu ama en çok sorulan konusu. İpucu: 'en uzun', 'en kısa', 'kaç yol var', 'minimum maliyet' gibi sorular genelde DP. Pratik çok önemli — en az 30-40 DP sorusu çöz.","Dynamic programming, memoization, top-down, bottom-up, mülakat, Fibonacci.")
add("graph algoritmaları neler?","Graph (çizge) problemleri CS'de çok önemli. BFS (Breadth-First Search): seviye seviye gezer, en kısa yol (ağırlıksız). DFS (Depth-First Search): derinliğe dalıp geri gelir, döngü tespiti, topological sort. Dijkstra: ağırlıklı en kısa yol (pozitif ağırlıklar). Bellman-Ford: negatif ağırlıklı en kısa yol. Floyd-Warshall: tüm çiftler arası en kısa yol. Kruskal/Prim: minimum spanning tree. Topological Sort: DAG'da bağımlılık sırası. Graph representation: adjacency list (seyrek), adjacency matrix (yoğun). NetworkX Python'da graph analizi için harika kütüphane.","Graph, BFS, DFS, Dijkstra, topological sort, adjacency list.")
add("big O notasyonu ne demek?","Big O, bir algoritmanın girdi büyüklüğüne göre ne kadar zaman veya alan kullandığını ifade eder. En yaygınlar: O(1) sabit — hash table erişimi. O(log n) logaritmik — binary search. O(n) doğrusal — dizi tarama. O(n log n) — merge sort, quick sort ortalama. O(n²) karesel — bubble sort, nested loop. O(2^n) üstel — brute force kombinasyonlar. O(n!) faktöriyel — permütasyonlar. Mülakatların ilk sorusu genelde 'bu kodun time complexity'si ne?' Space complexity de önemli — ne kadar bellek kullanılıyor. Best case, average case, worst case ayrımını bil.","Big O, time complexity, space complexity, O(1), O(n), O(n log n), mülakat.")
add("linked list ve array arasındaki fark?","Array: bellekte ardışık, random access O(1), başa/ortaya ekleme O(n), sabit boyut (dynamic array resize yapar). Linked list: bellekte dağınık, erişim O(n), başa ekleme O(1), dinamik boyut. Singly linked list: tek yönlü. Doubly linked list: çift yönlü. Circular linked list: son eleman başa bağlı. Pratikte array çok daha sık kullanılır — cache locality avantajı. Linked list ne zaman: sık başa/ortaya ekleme/silme, boyut bilinmiyor. LRU Cache implementasyonu doubly linked list + hash map kullanır. Mülakatların klasiği: linked list reverse, döngü tespiti (Floyd's algorithm), merge sorted lists.","Linked list, array, random access, cache locality, LRU Cache, mülakat.")
add("stack ve queue ne işe yarar?","Stack (yığın): LIFO (Last In First Out) — son giren ilk çıkar. push (ekle), pop (çıkar), peek (bak). Kullanım: fonksiyon çağrı yığını, undo mekanizması, parantez eşleştirme, DFS. Queue (kuyruk): FIFO (First In First Out) — ilk giren ilk çıkar. enqueue (ekle), dequeue (çıkar). Kullanım: BFS, görev kuyruğu, yazıcı kuyruğu. Deque (double-ended queue): iki uçtan da ekleme/çıkarma. Priority queue: önceliğe göre çıkarma (heap ile). Python: list (stack), collections.deque (queue), queue.PriorityQueue. Monotonic stack/queue mülakat sorularında çok çıkar.","Stack, queue, LIFO, FIFO, deque, priority queue, BFS, DFS.")
add("trie veri yapısı ne?","Trie (prefix tree), string araması ve autocomplete için optimize edilmiş ağaç yapısı. Her düğüm bir harf, kökten yaprağa bir kelime oluşur. Kelime araması O(m) — m kelimenin uzunluğu (veri miktarından bağımsız). Kullanımlar: autocomplete (arama motoru önerileri), spell checker, IP routing (longest prefix match), T9 klavye, kelime oyunları. Hash table'dan avantajı: prefix araması çok hızlı, sıralı traversal mümkün. Dezavantajı: bellek kullanımı yüksek. Compact trie (radix tree) bellek tasarrufu sağlar. Mülakatılarda 'implement autocomplete' veya 'word search' soruları trie kullanır.","Trie, prefix tree, autocomplete, spell checker, O(m), radix tree.")

# --- Yazılım pratikleri ---
add("dependency injection ne demek?","Dependency Injection (DI), bir sınıfın bağımlılıklarını kendisi oluşturmak yerine dışarıdan alması. Mesela UserService doğrudan Database() oluşturmak yerine constructor'da alır: UserService(db: Database). Avantajları: test edilebilirlik (mock database verebilirsin), gevşek bağlantı (loose coupling), değiştirilebilirlik. SOLID'in D'si (Dependency Inversion) bununla ilgili. Spring (Java), NestJS (TypeScript), FastAPI (Python) DI container'lar sunuyor. Factory pattern ile beraber kullanılır. Over-engineering riski var — basit projelerde gereksiz olabilir ama büyük projelerde bakımı çok kolaylaştırır.","Dependency injection, loose coupling, test edilebilirlik, SOLID, Spring, NestJS.")
add("microservice vs monolith ne zaman hangisi?","Monolith: tek büyük uygulama. Avantajları: geliştirmesi basit, deploy basit, debugging basit, başlangıç için ideal. Dezavantajları: büyüdükçe karmaşıklaşır, tek bir hata her şeyi çökertebilir, ölçekleme zor. Microservice: küçük bağımsız servisler. Avantajları: bağımsız deploy, teknoloji çeşitliliği, ölçeklenebilirlik, hata izolasyonu. Dezavantajları: dağıtık sistem karmaşıklığı, network latency, data consistency zorluğu, operasyonel yük (Kubernetes, monitoring gerekir). Kural: monolith ile başla, ihtiyaç oldukça microservice'e geç. 'Premature microservices' en yaygın mimari hatalardan biri. Netflix, Amazon micro'ya geçti ama küçük başladılar.","Microservice, monolith, ne zaman, avantaj/dezavantaj, Netflix.")
add("CQRS pattern ne demek?","CQRS (Command Query Responsibility Segregation), okuma ve yazma işlemlerini ayırma kalıbı. Command: veriyi değiştirir (create, update, delete). Query: veriyi okur. Neden ayrılır: okuma ve yazma farklı optimizasyon gerektirir. Okuma için denormalize edilmiş hızlı read model, yazma için normalize edilmiş write model. Event sourcing ile beraber sık kullanılır. Avantajları: performans (okuma/yazma bağımsız ölçeklenir), karmaşık domain'lerde netlik. Dezavantajları: karmaşıklık ekler, eventual consistency yönetimi. Her projede gerekmez — basit CRUD'da overkill. E-ticaret, bankacılık gibi domain'lerde güçlü.","CQRS, Command, Query, read model, write model, event sourcing.")
add("circuit breaker pattern ne?","Circuit breaker, bir servisin çöktüğünde diğer servisleri de çökertmesini engelleyen kalıp. Elektrik sigortası gibi çalışır. Üç durum: Closed (normal — istekler geçer), Open (servis çöktü — istekler direkt hata döner, sunucuyu yormaz), Half-Open (periyodik olarak kontrol — düzeldi mi?). Neden: bir microservice timeout veriyorsa, binlerce istek birikir, thread'ler tükenir, cascade failure olur. Netflix'in Hystrix kütüphanesi popülerleştirdi. Resilience4j (Java), Polly (.NET), pybreaker (Python) implementasyonlar. Retry, timeout, fallback stratejileriyle beraber kullanılır.","Circuit breaker, Closed/Open/Half-Open, cascade failure, Hystrix, retry.")
add("saga pattern ne?","Saga pattern, microservice'lerde dağıtık transaction yönetimi. Monolith'te tek veritabanı transaction'ı var ama microservice'lerde her servisin kendi DB'si var — tek transaction olmaz. Saga: her servis kendi transaction'ını yapar ve başarısızlıkta compensating transaction (geri alma) çalıştırır. İki tür: Choreography (her servis event yayınlar, diğerleri dinler — basit ama takibi zor) ve Orchestration (merkezi bir orkestratör koordine eder — daha kontrollü). Örnek: sipariş → stok azalt → ödeme al. Ödeme başarısız → stok geri artır → sipariş iptal. Temporal, Camunda orkestrasyon araçları.","Saga, dağıtık transaction, choreography, orchestration, compensating, Temporal.")

# --- Kariyer detayları ---
add("yazılım mülakatında sistem tasarımı soruları nasıl çözülür?","Sistem tasarımı mülakatı genelde senior pozisyonlar için ama temeli erken öğrenmek iyi. Yaklaşım: 1) Gereksinimler — fonksiyonel ve non-fonksiyonel (ölçeklenebilirlik, kullanıcı sayısı). 2) High-level tasarım — ana bileşenler (frontend, backend, DB, cache). 3) Detaylar — API tasarımı, veri modeli, ölçekleme stratejisi. 4) Trade-off'lar — neden bu teknolojiyi seçtin? Popüler sorular: URL shortener, Twitter timeline, chat sistemi, video streaming, search engine. Kaynaklar: 'System Design Interview' kitabı (Alex Xu), Grokking the System Design Interview, ByteByteGo YouTube kanalı. Gerçek dünya sistemlerini analiz et — Netflix, Uber, WhatsApp nasıl çalışıyor?","Sistem tasarımı, mülakat, gereksinim, trade-off, Alex Xu, ByteByteGo.")
add("yazılımda soft skills ne kadar önemli?","Soft skills teknik beceriler kadar önemli — belki daha fazla. İletişim: fikrlerini net ifade etmek, dinlemek, yazılı iletişim. Takım çalışması: farklı görüşlere saygı, çatışma çözme, paylaşım. Problem çözme: teknik değil genel — problemi tanımla, analiz et, çöz. Zaman yönetimi: önceliklendirme, deadline yönetimi. Empati: kullanıcı deneyimi, takım arkadaşları. Liderlik: mentorluk, inisiyatif alma. Adaptasyon: yeni teknolojilere, değişen gereksinimlere uyum. Mülakatların davranışsal kısmı tamamen soft skills. Amazon'un Leadership Principles'ları soft skills odaklı. Görkem'in hackathon'ları takım çalışması ve iletişim becerilerini geliştirmiştir.","Soft skills, iletişim, takım çalışması, empati, liderlik, mülakat.")
add("yazılım mühendisliğinde kariyer yolları neler?","Yazılım kariyerinde birçok yol var. IC (Individual Contributor): Junior → Mid → Senior → Staff → Principal Engineer. Management: Tech Lead → Engineering Manager → VP of Engineering → CTO. Specialist: ML Engineer, Security Engineer, Site Reliability Engineer, DevOps Engineer, Data Engineer, Mobile Developer, Frontend/Backend Specialist. Yan yollar: Developer Advocate, Technical Writer, Solutions Architect, Consultant. Freelance/Indie: kendi ürününü yap, SaaS kur. Akademi: araştırmacı, profesör. Herkesin IC veya management yapması gerekmiyor — specialist olarak da çok başarılı ve mutlu olabilirsin. Kariyer doğrusal olmak zorunda değil.","Kariyer yolları, IC, management, specialist, freelance, CTO.")
add("teknik blog yazarak nasıl para kazanılır?","Teknik blog ile para kazanma yolları: 1) Reklam — Google AdSense, Carbon Ads (developer odaklı). 2) Sponsorluk — bir şirket yazı sponsor eder. 3) Affiliate marketing — ürün linklerinden komisyon. 4) Premium içerik — ücretli kurslar, e-kitaplar, newsletter (Substack, Gumroad). 5) Freelance fırsatları — blog senin portfolyön, müşteri çeker. 6) İş teklifi — blog yazmak görünürlük sağlar. Başarılı teknik bloglar: Tania Rascia, Josh Comeau, Kent C. Dodds. İlk para gelene kadar uzun sürebilir — tutarlılık önemli. SEO öğren, niş bul, değer üret. Medium Partner Program da gelir sağlayabilir. Blog yazmak doğrudan zenginleştirmez ama kariyerini dolaylı yoldan çok besler.","Teknik blog, para kazanma, AdSense, sponsorluk, affiliate, Substack.")

# --- Günlük hayat / motivasyon ---
add("yazılımda plateau (durgunluk) nasıl aşılır?","Plateau, bir süre ilerleme hissetmemek — herkes yaşar. Aşma stratejileri: farklı bir alan dene — frontend yapıyorsan backend dene, web yapıyorsan mobile. Zor bir proje al — comfort zone'un dışına çık. Birinden öğren — pair programming, mentorluk, konferans. Bir kitap oku — temel bilgi eksiklerini tamamla. Öğret — blog yaz, video çek, birine anlat. Open-source katkısı yap — farklı kod tabanları görmek perspektif kazandırır. Mülakat soruları çöz — eksik algoritmik bilgiyi ortaya çıkarır. Ara ver — bazen dinlenmek gerekiyor. Plateau geçici — devam edersen kırılır.","Plateau, durgunluk, farklı alan, comfort zone, öğretme, dinlenme.")
add("yazılımcı olarak kişisel marka nasıl oluşturulur?","Kişisel marka kariyer için çok güçlü bir araç. Adımlar: 1) Uzmanlık alanı belirle — 'AI ile çalışan Python geliştiricisi' gibi. 2) İçerik üret — blog, Twitter thread, YouTube video, LinkedIn post. 3) Tutarlı ol — haftada en az 1 paylaşım. 4) Toplulukta aktif ol — konferanslarda konuşma, meetup organize et. 5) Portföy oluştur — GitHub, kişisel site. 6) Networking — insanlarla gerçek ilişkiler kur. Görkem'in marka ögeleri: AI Product Developer, Yeditepe CS, 30+ GitHub projesi, hackathon deneyimi, ayarlicazhocam. Kişisel marka bir gecede oluşmaz — aylar/yıllar gerektiriyor ama compound effect çok güçlü.","Kişisel marka, uzmanlık, içerik, tutarlılık, topluluk, networking.")
add("yazılımcı olarak sağlıklı yaşam nasıl sürdürülür?","Masabaşı iş olduğu için sağlık çok önemli. Fiziksel: günde 30 dk egzersiz (yürüyüş bile yeter), standing desk kullan, her saat 5 dk kalk, göz egzersizi (20-20-20 kuralı), bilek ve sırt esnemeleri. Beslenme: bol su iç, abur cubur yerine meyve ve kuruyemiş, kahve limitini aşma (2-3 fincan). Uyku: 7-8 saat, mavi ışık filtresi kullan, yatmadan 1 saat önce ekran bırak. Mental: hobi edin (yazılım dışı), sosyal ilişkiler, doğada vakit geçir, meditasyon veya mindfulness dene. Burnout'u erken fark et. Ergonomik setup'a yatırım yap. Sağlık en büyük sermaye — onsuz hiçbir başarı anlamlı değil.","Sağlık, egzersiz, beslenme, uyku, mental sağlık, ergonomi, burnout.")
add("Görkem'in kariyer hedefleri neler olabilir?","Görkem'in profilinden çıkarılan hedefler: AI alanında lider olmak — miniature-transformers, wiki2bpe, yolo-custom-detector gibi projeler bu yönü gösteriyor. Kendi AI startup'ını kurmak — ayarlicazhocam bu yolda bir adım. Uluslararası kariyere açılmak — İngilizce eğitim, GitHub'da İngilizce projeler. Açık kaynak topluluğuna katkı — 30+ public repo. Sağlık teknolojisinde etki yaratmak — depression-phq9-analysis, med-health projeleri. Sürekli öğrenme — her alanda proje yapması bunu gösteriyor. Eğitim sektörüne katkı — study-tracker, sorting-visualizer eğitim araçları. Her hedef birbiriyle bağlantılı — güçlü bir portföy oluşturuyor.","Kariyer hedefleri, AI liderlik, startup, uluslararası, açık kaynak, sağlık teknolojisi.")

# --- Daha fazla teknik ---
add("continuous delivery vs continuous deployment farkı ne?","Ikisi de CI/CD'nin parçası ama farklı. Continuous Delivery: her commit production'a deploy edilebilir durumda — ama deploy kararı insan verir (düğmeye basılır). Continuous Deployment: her commit otomatik olarak production'a deploy olur — insan müdahalesi yok. CD tüm testlerin güvenilir olmasını gerektirir. Delivery daha güvenli — son kontrol insanda. Deployment daha hızlı — feature dakikalar içinde kullanıcıya ulaşır. Amazon günde binlerce kez deploy yapıyor (continuous deployment). Çoğu şirket continuous delivery ile başlayıp güven arttıkça deployment'a geçiyor. Feature flag'ler continuous deployment'ı güvenli kılar.","Continuous delivery vs deployment, fark, Amazon, feature flag, güven.")
add("database sharding ne demek?","Sharding, büyük bir veritabanını küçük parçalara (shard) bölme. Her shard bir sunucuda — yük dağılır. Horizontal sharding: satırlar farklı shard'lara dağıtılır (user_id % shard_count). Vertical sharding: farklı tablolar farklı sunuculara. Shard key seçimi kritik — hot spot oluşturmamak lazım. Avantajları: ölçeklenebilirlik, performans. Dezavantajları: cross-shard query zorlaşır, JOIN çok sınırlı, rebalancing karmaşık. Vitess (YouTube'un kullandığı MySQL sharding), CockroachDB (otomatik sharding). Genelde milyonlarca kayıt olduğunda gerekir — erken sharding yapma. Partition ile fark: partition tek sunucuda, sharding birden fazla.","Sharding, horizontal, vertical, shard key, Vitess, CockroachDB.")
add("data lake ve data warehouse farkı ne?","Data warehouse: yapılandırılmış veri, şema tanımlı (schema-on-write), SQL ile sorgulama, iş zekası ve raporlama için. Snowflake, Redshift, BigQuery. Data lake: her türlü veri (yapılandırılmış, yarı yapılandırılmış, yapılandırılmamış), şemasız (schema-on-read), ham veri depolar, ML ve ileri analitik için. AWS S3, Azure Data Lake, Google Cloud Storage. Lakehouse: ikisinin birleşimi — Delta Lake (Databricks), Apache Iceberg. Hangisini seç: raporlama → warehouse, ML/advanced analytics → lake, ikisi de → lakehouse. ETL warehouse'a yüklerken, ELT lake'e yüklerken kullanılır. Modern veri mimarisinde ikisi de yer alıyor.","Data lake, data warehouse, lakehouse, Snowflake, Delta Lake, schema.")
add("API gateway pattern detaylı anlat","API gateway, tüm istemci isteklerinin tek noktadan geçtiği aracı katman. Sorumlulukları: authentication/authorization (JWT doğrulama), rate limiting, request routing (isteği doğru servise yönlendirme), response aggregation (birden fazla servisten veri birleştirme), protocol translation (gRPC → REST), caching, logging, monitoring, SSL termination, request/response transformation, versiyonlama. Popüler: Kong (açık kaynak, Lua tabanlı), AWS API Gateway, Traefik, NGINX, Apigee (Google). BFF (Backend for Frontend): web ve mobile için ayrı gateway'ler. Bottleneck riski var — gateway çökerse her şey çöker. Genelde birden fazla instance çalıştırılır.","API gateway, routing, aggregation, Kong, BFF, bottleneck.")
add("race condition ne demek?","Race condition, birden fazla thread'in aynı kaynağa eşzamanlı erişip beklenmedik sonuç üretmesi. Örnek: iki thread aynı banka hesabından para çekiyor — bakiyeyi okur (1000), çeker (500), yazar (500) ama ikisi de 1000 okudu, ikisi de 500 yazdı, toplam 1000 çekilmesi gereken 500 çekildi. Çözümler: mutex/lock (karşılıklı dışlama), semaphore, atomic operations, database transaction isolation. Python'da GIL (Global Interpreter Lock) thread safety sağlar ama multi-processing'de dikkat. Go'da goroutine ve channel. Java'da synchronized keyword. Dağıtık sistemlerde distributed lock (Redis ile). Debugging çok zor — intermittent bug'lar genelde race condition.","Race condition, mutex, lock, semaphore, atomic, GIL, distributed lock.")
add("deadlock ne demek?","Deadlock, iki veya daha fazla thread'in birbirinin tuttuğu kaynağı beklediği çıkmaz durum. Thread A lock 1'i tutar lock 2'yi bekler, Thread B lock 2'yi tutar lock 1'i bekler — ikisi de sonsuza kadar bekler. Deadlock koşulları (hepsi olmalı): mutual exclusion, hold and wait, no preemption, circular wait. Önleme: lock sırası belirle, timeout koy, try-lock kullan. Veritabanlarında da olur — DB genelde bir transaction'ı rollback eder. Go'da goroutine leak, Java'da thread dump analizi ile tespit edilir. Concurrent programlamanın en zorlu konularından biri. Görkem'in gorkem-os projesi muhtemelen lock mekanizmaları içeriyor.","Deadlock, çıkmaz, mutex, koşullar, lock sırası, timeout, gorkem-os.")

# --- Eğitim ve öğrenme ---
add("yazılım öğrenirken en sık yapılan hatalar neler?","Yaygın hatalar: 1) Tutorial hell — sürekli izle ama proje yapma. 2) Her dili öğrenmeye çalışmak — bir dilde derinleş önce. 3) Temelleri atlmak — framework öğrenip algoritma bilmemek. 4) Mükemmeliyetçilik — 'mükemmel olmadan yayınlayamam'. 5) Karşılaştırma — 'herkes benden iyi'. 6) Dökümantasyon okumamak — video izleyip resmi dökümantasyonu ihmal etmek. 7) Versiyon kontrolü kullanmamak — Git'i erken öğren. 8) Test yazmamak — 'çalışıyor ya'. 9) Yardım istememek — saatlerce takılmak. 10) Plansız kodlamak — düşünmeden yazmaya başlamak. Herkes bunları yapar — önemli olan fark edip düzeltmek.","Hatalar, tutorial hell, mükemmeliyetçilik, temeller, Git, test.")
add("CS50 kursu neden bu kadar popüler?","CS50, Harvard'ın açık kaynak bilgisayar bilimleri giriş kursu. David Malan'ın enerjik anlatımı, production kalitesinde videolar, pratik problem set'leri ile ünlü. İçerik: C (düşük seviye), Python, SQL, HTML/CSS/JS, Flask. Bilgisayar biliminin temellerini öğretir — algoritma, veri yapıları, bellek, abstraction. Ücretsiz — edX'te auditable. Sertifika ücretli. Her yıl güncelleniyor. CS50W (web), CS50AI (AI), CS50G (game) uzantıları var. Kendi hızında ilerle. Final proje gerekli — kendi fikrinle bir şey yap. Görkem gibi CS öğrencileri için bile faydalı — farklı perspektif kazandırır.","CS50, Harvard, David Malan, C, Python, ücretsiz, edX.")
add("kaggle yarışmaları nasıl çalışır?","Kaggle, veri bilimi ve ML yarışma platformu. Şirketler problem ve veri seti yayınlar, katılımcılar en iyi modeli geliştirmeye çalışır. Ödüller: para (bazen $100K+), iş fırsatı, prestij. Başlangıç: 'Getting Started' yarışmalarıyla — Titanic, House Prices, Digit Recognizer. Notebook'lar (kernel): diğerlerinin çözümlerini oku ve öğren. Discussion forumları çok değerli. Kaggle rank: Novice → Contributor → Expert → Master → Grandmaster. Dataset'ler: binlerce açık veri seti. Kaggle Learn: ücretsiz mini kurslar. CV'de Kaggle profili değerli — özellikle ML pozisyonları için. Rekabet motivasyon sağlıyor.","Kaggle, yarışma, Titanic, rank, notebook, dataset, CV.")
add("online bootcamp mı yoksa kendi kendine mi öğrenmeliyim?","Her ikisinin de avantajları var. Kendi kendine: ücretsiz veya ucuz, kendi hızında, istediğin konuyu seç, ama disiplin gerekir, yapılandırılmış yol yok, geri bildirim az. Bootcamp: yapılandırılmış müfredat, mentör desteği, proje tabanlı, iş bulma desteği, ama pahalı ($5K-$20K), yoğun tempo (12-16 hafta tam zamanlı), kalite değişken. Tavsiye: ücretsiz kaynakları dene (freeCodeCamp, The Odin Project, CS50). Kendi kendine ilerleyemiyorsan bootcamp düşün. Bootcamp seçerken: mezun sonuçlarını araştır, müfredatı kontrol et, ücretsiz deneme var mı bak. Türkiye'de: Patika.dev, Kodluyoruz ücretsiz alternatifler.","Bootcamp, kendi kendine öğrenme, freeCodeCamp, Odin Project, Patika.dev.")

# --- Görkem ve ayarlicazhocam ek ---
add("ayarlicazhocam'ın vizyonu ne?","ayarlicazhocam'ın vizyonu, yapay zeka teknolojisini kişisel asistanlık alanında kullanarak insanlara erişilebilir mentorluk sunmak. Herkesin bir mentöre erişimi yok — ayarlicazhocam bu boşluğu doldurmayı hedefliyor. Mühendislik öğrencilerine kariyer rehberliği, YKS öğrencilerine strateji, yazılım öğrenmek isteyenlere teknik destek. Görkem'in bilgi ve deneyimlerini ölçeklenebilir hale getirmek. Fine-tuned bir LLM olarak kişiselleştirilmiş yanıtlar veriyor. Gelecekte daha fazla konu ve daha derinlemesine rehberlik sunması planlanıyor. AI for good konseptinin güzel bir örneği.","ayarlicazhocam vizyonu, mentorluk, erişilebilirlik, ölçeklenebilirlik, AI for good.")
add("bu eğitim verisi nasıl hazırlandı?","Bu eğitim verisi (training data) birden fazla yöntemle hazırlandı. 1) İnsan tarafından yazılan veri: ilk 45-50 entry Görkem'in hayatı, projeleri, kariyer, YKS hakkında doğal dilde yazıldı. 2) Web scraping: Stack Overflow, GitHub Trending, Wikipedia, Dev.to, Hugging Face API'larından otomatik veri çekildi. 3) Sentetik veri üretimi: çeşitli konularda programatik olarak entry'ler oluşturuldu — teknik konular, kariyer, eğitim, motivasyon. Her entry user-assistant çifti formatında, thinking alanı ile. Hem Türkçe hem İngilizce versiyonlar var. LoRA fine-tuning için optimize edildi. Çeşitlilik ve kalite dengesine dikkat edildi.","Eğitim verisi, hazırlık süreci, scraping, sentetik, LoRA, çeşitlilik.")
add("LoRA fine-tuning nasıl yapılır adım adım?","LoRA fine-tuning adımları: 1) Veri hazırla — user/assistant çiftleri, JSON formatında (biz bunu yaptık). 2) Base model seç — Llama, Mistral, Phi gibi. 3) PEFT/LoRA konfigürasyonu — rank (r), alpha, target modules belirle. 4) Training ayarları — learning rate, epochs, batch size. 5) Eğitimi başlat — Hugging Face transformers + PEFT kütüphanesi ile. 6) Model değerlendir — test verisiyle performans ölç. 7) Model deploy et — Hugging Face Hub'a yükle, API olarak sun. Araçlar: unsloth (hızlı), axolotl (kolay config), Hugging Face TRL. QLoRA ile 4-bit quantize model üzerinde LoRA yapılır — daha az GPU. Google Colab T4 ile yapılabilir.","LoRA fine-tuning, adımlar, PEFT, base model, QLoRA, unsloth, Colab.")

# --- Ek çeşitli konular ---
add("açık kaynak nasıl para kazanır?","Açık kaynak projelerin para kazanma modelleri: 1) Open core — temel ücretsiz, enterprise özellikler ücretli (GitLab, Elastic). 2) SaaS — yazılımı hosted olarak sun (WordPress.com, MongoDB Atlas). 3) Destek ve danışmanlık — Red Hat modeli. 4) Sponsorluk — GitHub Sponsors, Open Collective. 5) Dual licensing — açık kaynak + ticari lisans (MySQL). 6) Donations — Wikipedia modeli. 7) Bounties — feature geliştirme için ödeme. Başarılı örnekler: Red Hat (IBM $34B'a aldı), Elastic, HashiCorp, Databricks. Tüm büyük AI kütüphaneleri açık kaynak — PyTorch, TensorFlow, Hugging Face. Açık kaynak ile iş modeli oluşturmak mümkün ama kolay değil.","Açık kaynak para kazanma, open core, SaaS, sponsorluk, Red Hat, dual licensing.")
add("SaaS (Software as a Service) nedir?","SaaS, yazılımı internet üzerinden hizmet olarak sunmak. Kullanıcı yüklemez, tarayıcıdan erişir. Örnekler: Gmail, Slack, Notion, Salesforce, GitHub, Figma. İş modeli: aylık/yıllık abonelik (subscription). Avantajları: kurulum yok, otomatik güncelleme, her yerden erişim, ölçeklenebilir. Dezavantajları: internet gerekli, veri kontrolü sınırlı, vendor lock-in. SaaS geliştirmek: multi-tenant mimari (tek sunucu birden fazla müşteri), billing sistemi (Stripe), kullanıcı yönetimi, analytics. Micro-SaaS: küçük niş SaaS ürünleri — tek kişi geliştirilip pasif gelir sağlayabilir. Indie hacker hareketi SaaS tabanlı.","SaaS, abonelik, multi-tenant, Stripe, micro-SaaS, indie hacker.")
add("MVP (Minimum Viable Product) nasıl yapılır?","MVP, bir ürünün en temel haliyle pazara sunulması. Amaç: minimum çabayla maksimum öğrenme. Adımlar: 1) Problem tanımla — gerçek bir sorunu mu çözüyorsun? 2) Core feature belirle — olmazsa olmaz özellikler neler? 3) Hızlı geliştir — mükemmellik değil çalışan ürün. 4) Kullanıcıya sun — gerçek geri bildirim al. 5) Öğren ve iterate et — veriyle karar ver. Lean Startup metodolojisi: Build → Measure → Learn döngüsü. MVP araçları: Bubble/Webflow (no-code), Firebase (backend), Vercel (deploy). Dropbox'un MVP'si bir videoydu. Airbnb'nin MVP'si kendi dairelerinin fotoğraflarıydı. Mükemmellik düşmanı iyidir — ship it, sonra geliştir.","MVP, Lean Startup, core feature, iterate, no-code, Build-Measure-Learn.")
add("startup'ta teknik kurucu olmak nasıl bir deneyim?","Teknik kurucu (technical co-founder) startup'ın teknoloji tarafından sorumlu kişi. Sorumluluklar: mimari kararlar, teknoloji seçimi, ekip kurma, kodlama (başta çoğu şeyi kendin yazarsın), teknik yol haritası. Zorluklar: her şeyi kendin yapmak (full-stack + DevOps + güvenlik), belirsizlik, hız baskısı, teknik borç yönetimi, iş tarafını da anlamak. İpuçları: MVP ile başla, premature optimization yapma, kullanıcı geri bildirimini dinle, co-founder ilişkisi evliliğe benzer — uyum çok önemli. Görkem ayarlicazhocam ile teknik kurucu deneyimi yaşıyor. YC, Techstars gibi akseleratörler startup'ları destekliyor.","Teknik kurucu, startup, sorumluluklar, zorluklar, MVP, akseleratör.")
add("startup için yatırım nasıl alınır?","Yatırım aşamaları: Pre-seed (fikir aşaması, $50K-$500K — melek yatırımcılar, F&F), Seed ($500K-$2M — seed fonlar, angel), Series A ($2M-$15M — VC'ler), Series B+ (büyüme). Türkiye'de: BIC Angels, Galata Business Angels, 500 Istanbul, Startups.watch ekosistemi. Global: Y Combinator, Techstars, Sequoia, a16z. Yatırımcı ne arar: takım (en önemli), pazar büyüklüğü (TAM, SAM, SOM), traction (kullanıcı sayısı, gelir), ürün-pazar uyumu. Pitch deck: problem, çözüm, pazar, iş modeli, traction, takım, finansal projeksiyonlar. Bootstrapping de bir seçenek — kendi kendini finanse et, daha yavaş ama daha bağımsız.","Yatırım, pre-seed, seed, Series A, VC, Y Combinator, pitch deck, bootstrap.")

# --- Son teknik konular ---
add("event loop ne demek JavaScript'te?","JavaScript single-threaded — tek thread'de çalışır ama asenkron işlem yapabilir. Event loop bu sihrin arkasındaki mekanizma. Call stack: fonksiyon çağrılarının sırası. Web APIs: setTimeout, fetch gibi asenkron API'lar. Callback queue: tamamlanan async işlemlerin callback'leri buraya gelir. Microtask queue: Promise'lar buraya gelir (priority daha yüksek). Event loop: call stack boşalınca queue'dan task alır. Bu yüzden setTimeout(fn, 0) bile hemen çalışmaz — stack boşalmasını bekler. Node.js de aynı event loop'u kullanır. Philip Roberts'ın 'What the heck is the event loop' konuşması en iyi kaynak. async/await event loop üzerinde çalışır.","Event loop, call stack, callback queue, microtask, Promise, Node.js.")
add("closure ne demek?","Closure, bir fonksiyonun dış kapsamdaki değişkenlere erişimini koruması. İç fonksiyon dış fonksiyonun değişkenlerini 'hatırlar', dış fonksiyon return ettikten sonra bile. JavaScript'te çok yaygın: function counter() { let count = 0; return function() { count++; return count; } }. Python'da da var — nonlocal keyword ile. Kullanımlar: data privacy (değişkeni dışarıdan gizleme), factory functions, partial application, callback'ler. React'te useState aslında closure kullanır. Mülakatların klasik sorusu: 'for loop'ta closure davranışı'. Functional programming'in temel kavramlarından biri.","Closure, dış kapsam, JavaScript, data privacy, useState, functional.")
add("garbage collection nasıl çalışır?","Garbage collection (GC), kullanılmayan bellek alanlarını otomatik temizleme. Manuel bellek yönetimi yerine (C'deki malloc/free) GC bunu otomatik yapar. Yöntemler: reference counting (referans sayısı sıfır olunca temizle — circular reference sorunu), mark-and-sweep (erişilebilir nesneleri işaretle, gerisini temizle), generational GC (yeni nesneler daha sık temizlenir — çoğu nesne kısa ömürlü). Python: reference counting + cycle detector. Java/Go: mark-and-sweep tabanlı. JavaScript V8: generational GC. GC pause (stop-the-world) performans etkisi — Go bunu minimize etti. GC'yi anlamak memory leak'leri önlemeye yardımcı olur.","Garbage collection, reference counting, mark-and-sweep, generational, GC pause.")
add("compile vs interpret farkı ne?","Compiled diller: kaynak kodu makine koduna derlenir, sonra çalıştırılır. Hızlı çalışır ama platform bağımlı. C, C++, Rust, Go. Interpreted diller: kaynak kodu satır satır yorumlanarak çalıştırılır. Yavaş ama taşınabilir ve esnek. Python, JavaScript, Ruby. JIT (Just-In-Time) compilation: çalışma zamanında derleme — her ikisinin avantajını birleştirir. Java (JVM), JavaScript (V8), Python (PyPy). Bytecode: ara format — kaynak kod → bytecode → VM'de çalıştır. Python .pyc dosyaları bytecode. Pratikte: hız kritikse compiled (C, Rust), hızlı geliştirme istiyorsan interpreted (Python, JS). Modern trend: JIT ile aradaki fark kapanıyor.","Compiled, interpreted, JIT, bytecode, hız, C, Python, V8.")
add("functional programming ne demek?","Functional programming (FP), fonksiyonları birinci sınıf vatandaş olarak kullanan paradigma. Temel prensipler: pure functions (aynı girdi → aynı çıktı, side effect yok), immutability (veri değişmez, yeni kopyası oluşur), first-class functions (fonksiyon değişkene atanır, parametre olarak geçirilir), higher-order functions (map, filter, reduce). Avantajları: daha az bug (side effect yok), paralel programlama kolay, test edilebilirlik. Saf FP dilleri: Haskell, Clojure, Erlang/Elixir. Multi-paradigm: Python, JavaScript, Scala, Kotlin. Python'da: lambda, map(), filter(), reduce(), list comprehension. FP öğrenmek düşünme biçimini değiştirir — imperative'den declarative'e geçiş.","Functional programming, pure function, immutability, map/filter/reduce, Haskell.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_tr9.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} Turkish entries (part 9).")

if __name__=="__main__":
    main()
