"""Ek TR training data - Bölüm 3. Çeşitli konular."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

add("BERT ne işe yarar?","BERT (Bidirectional Encoder Representations from Transformers) Google'ın 2018'de çıkardığı bir NLP modeli. İsim üstünde çift yönlü — bir kelimeyi anlamak için hem solundaki hem sağındaki kelimelere bakıyor. GPT tek yönlü çalışırken BERT iki yönlü çalışır. Metin sınıflandırma, soru cevaplama, duygu analizi, isimlendirilmiş varlık tanıma gibi görevlerde çok başarılı. Fine-tuning yaparak kendi görevine uyarlayabilirsin. Görkem'in writing-analyzer projesi de benzer NLP tekniklerini kullanıyor.","BERT açıklaması, çift yönlü, kullanım alanları.")
add("loss function ne demek?","Loss function (kayıp fonksiyonu), modelin tahminlerinin gerçek değerlerden ne kadar uzak olduğunu ölçen matematik fonksiyonu. Model eğitimi sırasında bu değeri minimize etmeye çalışırsın. Sınıflandırma için cross-entropy loss, regresyon için MSE (Mean Squared Error) kullanılır. Loss düşüyorsa model öğreniyor demektir, artıyorsa bir sorun var. Overfitting'de training loss düşer ama validation loss artar. Deep learning'in temeli optimizasyon — ve optimizasyon loss function'a dayanır.","Loss function, cross-entropy, MSE, overfitting tespiti.")
add("overfitting ve underfitting ne demek?","Overfitting modelin eğitim verisini ezberlemesi — eğitim verisinde çok iyi ama yeni veride kötü performans gösterir. Underfitting ise modelin yeterince öğrenmemesi — hem eğitim hem test verisinde kötü. Overfitting çözümleri: daha fazla veri, dropout, regularization, data augmentation, erken durdurma. Underfitting çözümleri: daha karmaşık model, daha fazla epoch, daha iyi feature engineering. İkisinin arasındaki denge iyi bir model demek. Görkem model eğitirken bu dengeyi muhtemelen çok iyi biliyor.","Overfitting vs underfitting, çözümler, denge.")
add("batch size ve learning rate ne demek?","Batch size bir seferde modele verilen örnek sayısı. Küçük batch size daha gürültülü gradient ama daha iyi genelleme, büyük batch size daha kararlı ama daha fazla bellek kullanır. Yaygın değerler: 16, 32, 64, 128. Learning rate modelin her adımda ne kadar güncelleneceğini belirler. Çok büyükse model optimal noktayı atlar, çok küçükse çok yavaş öğrenir. Genelde 0.001 ile başlanır. Learning rate scheduling (zamanla azaltma) ve warmup gibi teknikler de var. Hyperparameter tuning bu ikisini doğru ayarlamakla başlar.","Batch size ve learning rate açıklaması, değerler, hyperparameter tuning.")
add("epoch ne demek?","Epoch, tüm eğitim verisinin modelden bir kez geçmesi demek. 10 epoch dersen veri 10 kez modelden geçiyor. Çok az epoch underfitting'e, çok fazla epoch overfitting'e yol açar. Doğru sayıyı bulmak için early stopping kullanılır — validation loss artmaya başladığında eğitimi durdurur. Genelde 10-100 epoch arası kullanılır, projeye göre değişir. Her epoch sonunda modelin performansını izlemen lazım.","Epoch açıklaması, underfitting-overfitting dengesi, early stopping.")
add("data augmentation ne demek?","Data augmentation, mevcut veriyi çeşitli dönüşümlerle çoğaltma tekniği. Görüntü için: döndürme, ölçekleme, kırpma, renk değiştirme, yansıtma, gürültü ekleme. Metin için: eş anlamlı kelime değiştirme, cümle sırası değiştirme, rastgele silme. Amaç modelin daha fazla varyasyon görmesini sağlayarak overfitting'i azaltmak. Özellikle az verin varsa çok etkili. Görkem'in YOLO projesi muhtemelen data augmentation kullanıyor çünkü custom object detection az veriyle yapıldığında augmentation şart.","Data augmentation, görüntü ve metin teknikleri, overfitting azaltma.")
add("GPU neden AI için önemli?","GPU (Graphics Processing Unit) aslında grafik işlemci ama yapısı gereği paralel hesaplama yapıyor. AI modelleri matris çarpımı ağırlıklı — ve GPU binlerce küçük çekirdekle bu çarpımları paralel yapıyor. CPU'da saatler süren eğitim GPU'da dakikalara iner. NVIDIA'nın CUDA platformu GPU programlamayı kolaylaştırdı. Google'ın TPU'su da var. Cloud'da GPU kiralayabilirsin — Google Colab ücretsiz GPU sunuyor, Kaggle da. Eğitim için GPU şart ama inference (tahmin) için CPU yeterli olabilir bazı durumlarda.","GPU önemi, paralel hesaplama, CUDA, cloud GPU, Colab.")
add("model deployment nasıl yapılır?","Model eğittikten sonra onu kullanıcılara sunman lazım, buna deployment denir. Birkaç yol: REST API olarak sunmak — Flask veya FastAPI ile modeli bir endpoint'e koy. Docker container ile paketlemek — taşınabilir ve tekrarlanabilir. Cloud platformlarına deploy etmek — AWS SageMaker, Google Vertex AI, Azure ML. Hugging Face Spaces ile demo yapmak — Gradio veya Streamlit ile arayüz ekle. Edge deployment — TFLite veya ONNX ile mobil cihazlarda. MLOps araçları — MLflow, Weights & Biases ile model versiyonlama ve izleme. Görkem'in wiki2bpe projesi Hugging Face Hub'a publish ediyor.","Model deployment yöntemleri, API, Docker, cloud, Hugging Face, MLOps.")
add("feature engineering ne demek?","Feature engineering, ham veriden modelin daha iyi öğrenebileceği özellikler (feature) çıkartma süreci. Mesela bir tarih sütunundan yıl, ay, gün, haftanın günü, tatil mi değil mi gibi özellikler çıkarırsın. Metin verisinden kelime sayısı, cümle uzunluğu, büyük harf oranı gibi özellikler. Sayısal veride normalizasyon, standardizasyon, logaritmik dönüşüm. İyi feature engineering bazen model seçiminden bile önemli — basit bir model iyi özelliklerle karmaşık modelden daha iyi sonuç verebilir. Kaggle yarışmalarında kazananları ayıran şey genelde feature engineering.","Feature engineering, tarih/metin/sayısal özellikler, Kaggle önemi.")
add("cross-validation ne demek?","Cross-validation, modelin performansını daha güvenilir şekilde değerlendirme yöntemi. En yaygını k-fold: veriyi k parçaya bölersin, her seferinde bir parçayı test diğerlerini eğitim için kullanırsın, k kez tekrarlarsın. Sonuçların ortalamasını alırsın. Tek bir train-test split'ten çok daha güvenilir çünkü tüm veriyi hem eğitim hem test için kullanmış olursun. Özellikle az veride çok önemli. 5-fold ve 10-fold en yaygın. Stratified k-fold ise sınıf dengesini korur — dengesiz veri setlerinde kullanılır.","Cross-validation, k-fold, neden güvenilir, stratified.")
add("web socket nedir?","WebSocket, istemci ve sunucu arasında sürekli açık bağlantı sağlayan bir protokol. Normal HTTP'de her istek için bağlantı açılır-kapanır. WebSocket'te bağlantı bir kez açılır ve iki yönlü iletişim olur — sunucu da istemciye mesaj gönderebilir. Chat uygulamaları, canlı bildirimler, gerçek zamanlı oyunlar, borsa uygulamaları için ideal. Socket.io en popüler JavaScript kütüphanesi. Python'da websockets veya FastAPI'nin WebSocket desteği var. Görkem'in chat veya gerçek zamanlı proje yapması durumunda WebSocket kullanması gerekir.","WebSocket açıklaması, HTTP farkı, chat, gerçek zamanlı uygulamalar.")
add("regex nedir?","Regex (Regular Expression — Düzenli İfade) metin içinde kalıp eşleştirme yapan bir araç. E-posta doğrulama, telefon numarası çıkartma, URL bulma, log dosyası analizi gibi işlerde kullanılır. Mesela [a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,} bir e-posta kalıbı. Python'da re modülü, JavaScript'te RegExp ile kullanılır. Başlangıçta karmaşık görünür ama öğrenince çok güçlü bir araç. regex101.com sitesinde online pratik yapabilirsin. Her yazılımcının temel regex bilmesi lazım.","Regex açıklaması, kullanım alanları, e-posta örneği, pratik kaynağı.")
add("design patterns nedir?","Design patterns (tasarım kalıpları) yazılım geliştirmede tekrar eden problemlere kanıtlanmış çözümler. Gang of Four kitabı 23 temel kalıp tanımlar. En bilinenleri: Singleton (tek örnek), Factory (nesne üretimi), Observer (olay dinleme), Strategy (algoritma değiştirme), MVC (Model-View-Controller). Her kalıp belirli bir problemi çözer. Ezberlemeye gerek yok ama konseptleri bilmek kod kaliteni artırır. Mülakatlarla da sorulabiliyor. Python ve Java'da en çok kullanılıyor. Clean code yazmanın bir parçası.","Design patterns, GoF, Singleton, Factory, Observer, MVC, mülakat.")
add("SSH nedir?","SSH (Secure Shell) uzak bir sunucuya güvenli bağlantı kurmanı sağlayan bir protokol. Terminal üzerinden ssh user@server komutuyla bağlanırsın. Veriler şifrelenir yani güvenli. Sunucu yönetimi, dosya transferi (SCP/SFTP), port yönlendirme için kullanılır. SSH key pair (public/private key) ile şifresiz giriş yapabilirsin — GitHub'a SSH key eklemek de bu mantıkla çalışır. Cloud sunucularına bağlanmak için SSH zorunlu. Her yazılımcının SSH kullanmayı bilmesi gerekir.","SSH açıklaması, güvenli bağlantı, key pair, GitHub, cloud.")
add("load balancer ne yapar?","Load balancer gelen istekleri birden fazla sunucuya dağıtarak yükü dengeler. Bir sunucu 1000 istek kaldırıyorsa, 3 sunucu load balancer arkasında 3000 istek kaldırır. Avantajları: yüksek erişilebilirlik (bir sunucu çökse diğerleri devam eder), performans (yük dağılır), ölçeklenebilirlik (sunucu ekle). Nginx, HAProxy, AWS ELB popüler load balancer'lar. Round-robin, least-connections, IP hash gibi dağıtım algoritmaları var. Büyük ölçekli uygulamalar için şart.","Load balancer, yük dengeleme, HA, Nginx, algoritmalar.")
add("CDN nedir?","CDN (Content Delivery Network) statik içerikleri (görüntüler, CSS, JS dosyaları) dünyanın farklı noktalarındaki sunucularda önbelleğe alır. Bir kullanıcı Türkiye'den siteye girdiğinde İstanbul'daki CDN sunucusundan yüklenir, ABD'deki ana sunucuya gitmesi gerekmez. Sonuç: daha hızlı sayfa yükleme, daha az sunucu yükü, daha iyi kullanıcı deneyimi. Cloudflare, AWS CloudFront, Akamai popüler CDN'ler. Bir web sitesi yayınlıyorsan CDN kullanmak performance optimization'ın ilk adımı.","CDN açıklaması, önbellek, hız, Cloudflare, CloudFront.")
add("OAuth nedir?","OAuth bir yetkilendirme protokolü — 'Google ile giriş yap', 'GitHub ile giriş yap' butonları OAuth kullanıyor. Kullanıcı şifresini senin uygulamanla paylaşmak zorunda kalmadan, Google veya GitHub üzerinden kimliğini doğrular. OAuth 2.0 şu anki standart. Access token ve refresh token kavramları var. Uygulama geliştirirken OAuth entegrasyonu çok yaygın — sosyal medya login, API erişimi, üçüncü taraf entegrasyonlar. Firebase Authentication, Auth0, Passport.js OAuth implementasyonu kolaylaştırıyor.","OAuth açıklaması, sosyal giriş, token, Firebase, Auth0.")
add("GraphQL subscription ne demek?","GraphQL subscription, gerçek zamanlı veri akışı sağlayan bir GraphQL özelliği. Normal query ve mutation'dan farklı olarak subscription WebSocket üzerinden çalışır ve sunucudan istemciye anlık veri gönderir. Mesela bir chat uygulamasında yeni mesaj geldiğinde otomatik güncelleme. Bir dashboard'da canlı veri akışı. Borsa uygulamasında fiyat değişimleri. Apollo Client ve Server bu özelliği destekliyor. REST API ile aynı şeyi yapmak için polling veya WebSocket kendi başına kurman gerekir.","GraphQL subscription, gerçek zamanlı, WebSocket, Apollo, kullanım alanları.")
add("microservice'ler arası iletişim nasıl yapılır?","Microservice'ler arası iletişim iki şekilde olur: senkron ve asenkron. Senkron: REST API veya gRPC ile doğrudan çağrı — basit ama servisleri birbirine bağlıyor. Asenkron: mesaj kuyruğu (RabbitMQ, Apache Kafka) ile — servisler birbirini beklemez, mesaj kuyruğa bırakılır ve diğer servis hazır olunca alır. Event-driven architecture bu mantıkla çalışır. gRPC REST'ten daha hızlı çünkü Protocol Buffers kullanır. Büyük sistemlerde asenkron tercih edilir çünkü bir servisin çökmesi diğerlerini etkilemez.","Microservice iletişimi, senkron/asenkron, Kafka, gRPC, event-driven.")
add("yazılımda SOLID prensipleri ne?","SOLID, Robert C. Martin'in önerdiği 5 nesne yönelimli tasarım prensibi. S — Single Responsibility: her sınıf tek bir iş yapsın. O — Open/Closed: genişlemeye açık, değişime kapalı. L — Liskov Substitution: alt sınıf üst sınıfın yerine geçebilmeli. I — Interface Segregation: büyük arayüzler yerine küçük, spesifik arayüzler. D — Dependency Inversion: somut sınıflara değil soyutlamalara bağımlı ol. Bu prensiplere uygun kod yazmak bakımı kolay, test edilebilir ve ölçeklenebilir kod demek. Mülakatlarda da sıkça soruluyor.","SOLID prensipleri, S-O-L-I-D açıklaması, neden önemli, mülakat.")
add("A/B testing ne demek?","A/B testing, bir ürünün iki farklı versiyonunu kullanıcılara gösterip hangisinin daha iyi performans gösterdiğini ölçmek. Mesela bir butonun rengini değiştirdin — mavi mi kırmızı mı daha çok tıklanıyor? Kullanıcıların yarısına A, yarısına B gösterilir ve sonuçlar istatistiksel olarak karşılaştırılır. Google, Netflix, Amazon sürekli A/B test yapıyor. Optimizely, Google Optimize gibi araçlar var. Veri odaklı karar vermenin temeli. Ürün yönetimi ve UI/UX'te çok kullanılıyor.","A/B testing açıklaması, buton örneği, araçlar, veri odaklı karar.")
add("technical debt ne demek?","Technical debt (teknik borç) hızlı çözüm için alınan kısayolların zamanla biriken maliyeti. 'Şimdilik çalışsın, sonra düzeltiriz' dediğin her kod biraz teknik borçtur. Başta hızlı ilerlersin ama zamanla kod bakımsız hale gelir, yeni özellik eklemek zorlaşır, buglar artar. Teknik borcu yönetmek önemli: düzenli refactoring yap, code review yap, test yaz. Tamamen sıfır teknik borç mümkün değil ama kontrol altında tutmak lazım. Startup'larda özellikle yaygın çünkü hız öncelikli.","Technical debt, kısayollar, refactoring, code review, startup.")
add("serverless nedir?","Serverless, sunucu yönetimi yapmadan kod çalıştırmak demek. Sunucu var tabii ama sen yönetmiyorsun, bulut sağlayıcı yönetiyor. AWS Lambda, Google Cloud Functions, Azure Functions örnekleri. Bir fonksiyon yazarsın, bir olay tetiklendiğinde (HTTP isteği, dosya yükleme, zamanlayıcı) çalışır. Avantajları: ölçekleme otomatik, sadece kullandığın kadar öde, altyapı yönetimi yok. Dezavantajları: cold start gecikmeleri, uzun işlemler için uygun değil, vendor lock-in. Event-driven ve API backend'ler için harika.","Serverless açıklaması, Lambda, Cloud Functions, avantaj/dezavantaj.")
add("caching neden önemli?","Caching (önbellek) sık erişilen verileri hızlı erişilebilir bir yerde tutmak. Veritabanı sorgusu 100ms sürüyorsa, cache'ten okumak 1ms sürer. Kullanıcı deneyimini dramatik şekilde iyileştirir. Redis en popüler in-memory cache. CDN statik dosyalar için cache. Browser cache CSS/JS dosyalarını lokal tutar. Application-level cache API yanıtlarını tutar. Cache invalidation (ne zaman güncelleneceği) en zor kısmı — 'bilgisayar biliminde iki zor şey var: cache invalidation ve isimlendirme' diye meşhur bir söz var.","Caching önemi, Redis, CDN, browser cache, invalidation.")
add("API rate limiting ne demek?","Rate limiting, bir API'ye belirli sürede yapılabilecek istek sayısını sınırlamak. Mesela dakikada 100 istek. Neden? Sunucuyu aşırı yükten korumak, DDoS saldırılarını engellemek, adil kullanım sağlamak. 429 Too Many Requests HTTP status kodu döner. Bizim scraping scriptlerimizde de rate limiting'e dikkat etmemiz gerekiyor — sunuculara nazik davranmak önemli. Token bucket ve sliding window algoritmaları rate limiting implementasyonu için kullanılır.","Rate limiting açıklaması, 429 status, DDoS koruma, algoritmalar.")
add("gRPC nedir?","gRPC, Google'ın geliştirdiği yüksek performanslı RPC (Remote Procedure Call) framework'ü. REST'e göre avantajları: Protocol Buffers ile binary serialization (JSON'dan küçük ve hızlı), HTTP/2 üzerinde çalışır (multiplexing, streaming), güçlü tip kontrolü, otomatik kod üretimi. Microservice'ler arası iletişimde REST'ten çok daha verimli. Python, Go, Java, C++ dahil birçok dilde destekleniyor. Dezavantajı: browser'dan doğrudan çağrılamaz (gRPC-Web gerekir), debugging REST'e göre daha zor. Büyük sistemlerde microservice iletişimi için standart haline geliyor.","gRPC açıklaması, Protocol Buffers, HTTP/2, REST karşılaştırması.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_tr3.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} Turkish entries (part 3).")

if __name__=="__main__":
    main()
