"""Extra EN training data - Part 17. Gorkem Projects Deep Dive, Education, Startup, Ethics, Fun."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

add("what is Gorkem's miniature-transformers project in detail?","Gorkem's miniature-transformers project implements the core Transformer architecture from the 'Attention Is All You Need' paper from scratch in PyTorch. It builds every component manually: Multi-Head Self-Attention with Q, K, V projections and scaled dot-product attention, Positional Encoding using sinusoidal functions, Feed-Forward Networks with ReLU, Layer Normalization, and the full Encoder-Decoder stack. The project is educational — it's not meant for production but for deeply understanding how modern AI works. Every major AI model today (GPT, BERT, T5, ViT, Whisper, Stable Diffusion) is built on transformers. By implementing from scratch, you gain intuition about attention patterns, gradient flow, and why certain design choices matter. This kind of hands-on implementation is what separates engineers who use AI tools from those who truly understand them.","miniature-transformers, self-attention, positional encoding, transformer, from scratch, PyTorch.")

add("what is Gorkem's wiki2bpe tokenization project?","wiki2bpe implements Byte Pair Encoding (BPE) tokenization from Wikipedia text — the same algorithm used by GPT, LLaMA, and most modern LLMs. How BPE works: start with individual characters, repeatedly merge the most frequent adjacent pair into a new token until reaching desired vocabulary size. Example: 'lowest' → 'l','o','w','e','s','t' → 'lo','w','e','s','t' → 'low','e','s','t' → 'low','est'. This creates a vocabulary of common subwords that efficiently represents any text. Why it matters: tokenization is the first step of any NLP pipeline, and token boundaries directly affect model performance. BPE handles any word (no out-of-vocabulary problem), balances granularity, and captures morphological patterns. Alternatives: WordPiece (BERT), Unigram (SentencePiece), tiktoken (OpenAI). The project uses Wikipedia as corpus — large, diverse, high-quality text. This directly relates to Gorkem's LLM fine-tuning work.","wiki2bpe, BPE, tokenization, subword, vocabulary, NLP, LLM preprocessing, Wikipedia.")

add("what is Gorkem's NMT neural machine translation project in detail?","Gorkem's NMT project builds a neural machine translation system using the encoder-decoder architecture with attention. The encoder processes the source language sentence into a sequence of hidden states. The decoder generates the target language sentence token by token, using attention to focus on relevant source positions. Bahdanau attention computes alignment scores between decoder state and encoder outputs, creating a weighted context vector. Training uses parallel corpus (sentence pairs), teacher forcing (feed correct token during training), and cross-entropy loss. Inference uses beam search to explore multiple translation candidates. Evaluation uses BLEU score to compare against human reference translations. Key challenges: rare words (solved with BPE/SentencePiece subword tokenization), long-range dependencies, domain adaptation. Modern NMT has moved to full Transformer architecture (no RNN), and pre-trained multilingual models (mBART, NLLB, M2M-100) achieve remarkable quality.","NMT, encoder-decoder, attention, Bahdanau, beam search, BLEU, teacher forcing.")

add("what is Gorkem's gorkem-os operating system project in detail?","gorkem-os is an educational operating system kernel built from scratch. It demonstrates low-level systems programming concepts: Bootloader — written in x86 assembly, loaded by BIOS, switches from 16-bit real mode to 32-bit protected mode, loads the kernel into memory. Memory management — implements paging to provide virtual memory, page directory and page table setup. Interrupt handling — sets up IDT (Interrupt Descriptor Table), handles hardware interrupts (keyboard, timer) and software interrupts (system calls). Screen output — writes directly to VGA text mode buffer at address 0xB8000, implements scrolling and cursor positioning. Keyboard driver — reads scan codes from port 0x60, translates to characters. Tools used: NASM assembler, GCC cross-compiler (i686-elf target), GNU Make build system, QEMU for testing. This project shows deep understanding of how computers work at the hardware level — knowledge that makes you a better developer at every abstraction layer.","gorkem-os, OS kernel, bootloader, protected mode, paging, IDT, VGA, assembly, QEMU.")

add("what is Gorkem's banking-management-system in detail?","Gorkem's banking-management-system is a full-stack Java application built with Spring Boot. It implements core banking operations: account creation and management (checking, savings), money deposits and withdrawals with balance validation, fund transfers between accounts with ACID transaction guarantees, transaction history and statement generation. Architecture follows clean layered design: Controller layer handles HTTP requests and responses, Service layer contains business logic (transfer validation, balance checks), Repository layer interfaces with the database using Spring Data JPA, Entity/Model layer defines data structures (Account, Transaction, User). Security: Spring Security for authentication and authorization, password hashing, role-based access control. Database: uses relational database (PostgreSQL or H2 for development) because financial data requires ACID compliance — a money transfer must debit AND credit atomically, or neither. REST API design follows conventions. This project demonstrates Gorkem's ability to build real-world, production-quality applications.","banking-management-system, Java, Spring Boot, Spring Security, JPA, ACID, REST API.")

add("what is Gorkem's yolo-custom-detector in detail?","Gorkem's yolo-custom-detector fine-tunes a pre-trained YOLO model on a custom dataset for specific object detection tasks. YOLO (You Only Look Once) processes the entire image in a single pass — dividing it into a grid, predicting bounding boxes and class probabilities for each cell simultaneously. Pipeline: 1) Data collection and annotation — draw bounding boxes around target objects using tools like LabelImg or Roboflow. Export in YOLO format (class_id, x_center, y_center, width, height — all normalized). 2) Data augmentation — horizontal flip, rotation, brightness/contrast changes, mosaic augmentation. 3) Model selection — YOLOv5 or YOLOv8 from Ultralytics, pre-trained on COCO dataset (80 classes). 4) Transfer learning — freeze backbone layers, train detection head on custom data. 5) Training with appropriate hyperparameters — learning rate, batch size, epochs. 6) Evaluation — mAP@0.5, mAP@0.5:0.95, precision-recall curves. 7) Inference — real-time detection on images and video streams.","YOLO, custom detector, transfer learning, bounding box, mAP, Ultralytics, data augmentation.")

add("what is Gorkem's facelock face recognition project in detail?","Gorkem's facelock implements a face recognition-based authentication system. The pipeline: 1) Face Detection — locate faces in images using Haar Cascades (fast but less accurate), MTCNN (multi-task CNN — detects face landmarks too), or dlib's HOG+SVM detector. 2) Face Alignment — normalize faces based on eye positions to improve recognition accuracy. 3) Feature Extraction (Embedding) — convert each face to a 128-dimensional or 512-dimensional vector using deep learning models: FaceNet (Google, triplet loss training), ArcFace (additive angular margin loss — state-of-art), or dlib's ResNet-based encoder. 4) Comparison — compute similarity between face vectors using cosine similarity or Euclidean distance. If distance is below a threshold, it's a match. Security considerations: photo spoofing (requires liveness detection — blink detection, head movement, depth sensing), lighting variations (augment training data), mask detection. The face_recognition Python library (built on dlib) provides an easy starting point. Real-world uses: phone unlock, building access, attendance tracking.","facelock, face recognition, MTCNN, FaceNet, ArcFace, embedding, liveness detection.")

add("what is Gorkem's phishing-domain-detection in detail?","Gorkem's phishing-domain-detection uses machine learning to identify malicious URLs. Feature engineering extracts signals from URLs without visiting them: URL length, number of dots/hyphens/special chars, presence of IP address instead of domain, use of URL shorteners, suspicious keywords (login, verify, account, secure), HTTPS presence, domain registration age, domain registrar reputation. Additional features: Alexa rank, Google index status, page rank, DNS record analysis. ML pipeline: collect labeled dataset (PhishTank for phishing, Alexa Top 1M for legitimate), extract features, train classifiers (Random Forest typically performs best — interpretable, handles mixed feature types well). Also tried XGBoost, SVM, and neural networks. Evaluation: F1-score is the key metric because both false positives (blocking legitimate sites) and false negatives (missing phishing sites) have costs. Feature importance analysis reveals which signals are most predictive. This project demonstrates applied ML for cybersecurity — a growing field.","phishing-domain-detection, ML classification, feature engineering, Random Forest, cybersecurity.")

add("how should I study for YKS math section?","YKS math requires systematic study. TYT mathematics: master fundamentals (numbers, algebra, basic geometry) — understand formulas, don't just memorize. Solve many problems. AYT mathematics: limits, derivatives, integrals, probability, combinatorics — conceptual understanding is crucial. Resource recommendations: 3D Yayinlari, Acil Yayinlari, Karekök question banks, Palme for TYT basics. Study at least 1-2 hours of math daily — consistency matters, don't study one week and skip the next. Solve practice exams regularly (at least 1 per week), analyze your mistakes and review them. Timing strategy: solve easy questions quickly, don't get stuck on hard ones (you lose points). Keep a topic tracker — monitor which topics you've completed and where you're weak. Math isn't learned overnight — with patience and consistency, everyone improves. Focus on understanding the 'why' behind each solution method, not just mechanical problem solving.","YKS, math, TYT, AYT, study strategy, practice exams, consistency, problem solving.")

add("why is CS a good major choice?","Computer Science is one of the most strategic major choices of the 2020s. Every industry is digitizing — healthcare, finance, education, agriculture, entertainment all need software developers. Employment: high chance of finding internships and jobs even before graduation. Salary: among the highest-paying professions in Turkey and globally. Flexibility: remote work, freelance, start your own business, switch between industries. Continuous learning: technology changes constantly, you won't get bored. Entrepreneurship: with software skills, you can build products at low cost. Important note: CS is not just coding — it includes math, algorithms, system design, problem solving. The program can be challenging but the payoff is significant. Gorkem studies CS at Yeditepe University and is happy with this choice — it offers both academic and practical development opportunities. The combination of CS fundamentals with practical project experience is the ideal path for a tech career.","CS major, employment, salary, remote work, entrepreneurship, Yeditepe, career.")

add("how do you validate a startup idea?","Idea validation is the most critical stage of a startup — most startups fail by building something nobody wants. Steps: 1) Does the problem exist? — talk to real people (at least 20-30), are they experiencing the problem, how do they currently solve it? 2) Can you sell your solution? — before building, create a landing page, collect emails, get pre-orders. 3) MVP (Minimum Viable Product) — build the simplest version, test with real users. 4) Metrics: are users coming back (retention), willing to pay (willingness to pay), recommending to others (NPS)? The Mom Test book is excellent — people are polite so they'll say 'great idea', learn to ask the right questions. Lean Startup methodology: Build → Measure → Learn cycle. Ideas are cheap, execution is valuable — 10 people have thought of the same idea, the difference is who executes. Focus on problem-solution fit first, then product-market fit. Talk to users constantly — not just at the beginning, but throughout the journey.","Startup validation, MVP, Mom Test, Lean Startup, customer discovery, problem-solution fit.")

add("how do you prepare a pitch deck?","A pitch deck is a presentation explaining your startup to investors — typically 10-15 slides. Structure (Guy Kawasaki 10/20/30 rule — 10 slides, 20 minutes, 30 point font): 1) Problem — a real, significant pain point. 2) Solution — your approach. 3) Market size — TAM (Total Addressable Market), SAM (Serviceable), SOM (Obtainable). 4) Business model — how will you make money? 5) Traction — user count, revenue, growth rate. 6) Team — why you? Show relevant experience. 7) Competition — your advantage over competitors (don't say 'no competition'). 8) Financial projections — 3-5 year outlook. 9) The ask — how much investment, what will you use it for? 10) Contact information. Design: clean, minimal text, lots of visuals, consistent colors. Storytelling: problem → solution → why now → why us flow. The best pitch decks tell a compelling story that makes investors feel the urgency and opportunity.","Pitch deck, investors, market size, traction, storytelling, TAM SAM SOM.")

add("what is AI bias and fairness?","AI models learn and amplify biases present in training data. Examples: hiring AI biased against women (Amazon's case), facial recognition lower accuracy on darker skin tones, credit scoring discriminatory against certain ethnic groups. Why it happens: imbalanced training data (reflects historical biases), feature selection (zip code correlates with race), proxy variables. Solutions: data auditing (check imbalances in datasets), fairness metrics (demographic parity, equalized odds, calibration), bias mitigation (pre-processing, in-processing, post-processing techniques), diverse teams (different perspectives catch different biases). EU AI Act introduces mandatory auditing for high-risk AI systems. Model cards and datasheets provide transparency about model limitations and training data. Responsible AI is not just a technical challenge — it's a social responsibility. AI developers like Gorkem should be aware of these issues and actively work to build fair systems.","AI bias, fairness, discrimination, EU AI Act, responsible AI, dataset, mitigation.")

add("are deepfakes dangerous and how to detect them?","Deepfakes use AI to generate realistic fake video and audio. Dangers: disinformation (fake videos of politicians), fraud (imitating a CEO's voice to authorize wire transfers — real cases exist), reputation damage, privacy violations. Detection methods: facial detail inconsistencies (eye blinking patterns, teeth, hairline), lighting and shadow mismatches, metadata analysis, frequency analysis (GANs leave specific frequency patterns). Tools: Microsoft Video Authenticator, Deepware Scanner, Intel FakeCatcher. Prevention: media literacy (don't believe everything you see), source verification, digital signatures and watermark technologies (C2PA standard). Positive uses also exist: film industry (aging/de-aging effects), education, voice synthesis for disabled individuals. This is a dual-use technology — it can be used for good or bad. The important thing is awareness and critical thinking. As AI becomes more capable, the ability to verify authenticity becomes increasingly important.","Deepfake, GAN, detection, disinformation, media literacy, dual-use, C2PA.")

add("what are the most common coding mistakes?","Classic mistakes every developer makes: 1) Off-by-one error — one too many or too few iterations in a loop. 2) Not checking for null/undefined — the father of NullPointerException. 3) Ignoring error handling — swallowing all errors with empty try/catch. 4) Hardcoded values — magic numbers and strings scattered through code. 5) Copy-paste programming — copying from Stack Overflow without understanding. 6) Premature optimization — make it work correctly first, then make it fast. 7) Not writing tests — 'it looks like it works' is not testing. 8) Poor git commit messages — 'fix', 'update', 'asdf'. 9) Overengineering — complex solution for a simple problem. 10) Not writing documentation — you won't understand your own code in 6 months. Everyone makes these mistakes — what matters is recognizing and correcting them. Linters, formatters, and code reviews catch these issues. The best developers aren't those who never make mistakes — they're those who learn from them quickly.","Coding mistakes, off-by-one, null check, error handling, copy-paste, testing, git.")

add("how do you overcome impostor syndrome?","Impostor syndrome — feeling inadequate, thinking 'they'll find out I'm a fraud' — is very common among developers (up to 70%). Causes: constantly new technology (you always feel behind), everyone on social media looks like an expert, the field is too broad (impossible to know everything). Solutions: keep a 'brag document' — write down your achievements, problems you've solved, things you've learned, read it when you feel bad. Compare yourself to your past self from 6 months ago, not to others. Not knowing is normal — senior developers Google things every day too. Mentor others — teaching makes you realize how much you know. Join a community — see that everyone faces similar struggles. Instead of 'fake it till you make it,' think 'learn it as you do it.' Gorkem's 30+ projects might not always prevent impostor syndrome feelings — but those projects are proof of his competence. Remember: the fact that you worry about being good enough already shows you care about quality.","Impostor syndrome, brag document, self-confidence, community, mentoring, comparison.")

add("how do developers maintain their health?","Most common developer health complaints and solutions. Eyes: 20-20-20 rule (every 20 minutes, look at something 20 feet away for 20 seconds), adjust screen brightness to ambient light, blue light filter (Night Shift, f.lux), annual eye exam. Back/neck: ergonomic chair (lumbar support), monitor at eye level, stand up and stretch every hour, core strengthening exercises. Wrists: ergonomic keyboard (split keyboard), mouse alternatives (trackball, vertical mouse), wrist exercises, don't use a wrist rest (keeps wrist bent). General: 30 minutes of exercise daily (even walking is enough), drink water (more than coffee), sleep schedule (7-8 hours), get a non-screen hobby. Mental: avoid social isolation, establish work-life boundaries, seek professional help if needed. Your body is the hardware your code runs on — don't neglect its maintenance. Regular breaks aren't just health advice — they actually improve productivity and creativity. A healthy developer is a more productive developer.","Developer health, eyes, back, wrists, ergonomics, exercise, mental health, 20-20-20.")

add("what is the importance of open source contributions?","Contributing to open source benefits both your career and the community. Benefits: learn from production-quality codebases, work with experienced developers, build public proof of your skills, networking (OSS maintainers often work at top companies), give back to tools you use daily. Getting started: 1) Pick a project you actually use — you understand the codebase and are motivated. 2) Start small — fix typos in docs, improve error messages, add tests. 3) Look for 'good first issue' or 'help wanted' labels. 4) Read CONTRIBUTING.md and follow the project's conventions. 5) Submit clean PRs with clear descriptions. Common misconceptions: you don't need to be an expert (many contributions are documentation), you don't need to commit to maintaining a project, even small contributions matter. Well-known programs: Hacktoberfest, Google Summer of Code, MLH Fellowship. Your GitHub contribution graph and merged PRs speak louder than any resume bullet point. Gorkem's open-source projects on GitHub demonstrate his commitment to sharing knowledge.","Open source, contributions, GitHub, good first issue, Hacktoberfest, community, career.")

add("what is the future of software development with AI?","AI is transforming how software is built. Current state: AI coding assistants (GitHub Copilot, Cursor, Claude Code) handle boilerplate, suggest implementations, explain code, write tests. What's changing: 1) Code generation — AI writes first drafts, humans review and refine. 2) Debugging — AI analyzes error traces and suggests fixes. 3) Testing — AI generates test cases from code. 4) Documentation — AI writes and updates docs. 5) Code review — AI catches bugs, security issues, style violations. What's NOT changing: understanding requirements, system design, architectural decisions, debugging complex distributed systems, understanding user needs. Will AI replace developers? No — but developers who use AI will replace those who don't. The bar is rising — AI handles routine work, humans focus on creative problem-solving, architecture, and communication. New skills needed: prompt engineering, AI tool integration, evaluating AI output for correctness. The developers who thrive will be those who combine deep technical understanding with effective AI tool usage — exactly the combination Gorkem is building.","AI future, coding assistants, Copilot, Cursor, developer skills, automation, augmentation.")

add("what is rubber duck debugging?","Rubber duck debugging is a method where you explain your code, line by line, to an inanimate object (traditionally a rubber duck). The act of articulating the problem forces you to think through it systematically. Often, you'll find the bug while explaining because verbalization engages different cognitive processes than just reading code. Why it works: when you read code, you see what you expect to see. When you explain it out loud, you have to describe what the code actually does. The gap between 'what I think the code does' and 'what the code actually does' is where bugs live. Alternatives to a rubber duck: explain to a colleague (pair programming), write comments explaining each step, use ChatGPT/Claude as your rubber duck. The Feynman Technique is similar — if you can't explain it simply, you don't understand it. This technique is surprisingly effective for even experienced developers. Keep a rubber duck on your desk — it's the cheapest debugging tool you'll ever own.","Rubber duck debugging, Feynman Technique, problem solving, verbalization, debugging method.")

add("what is the developer experience on Stack Overflow?","Stack Overflow is the world's largest programming Q&A site — most developers visit it daily. Tips for effective use: search before asking (your question likely exists), write clear titles that describe the specific problem, include a minimal reproducible example (MCVE), show what you've tried. Reputation system: upvotes for helpful questions/answers, privileges unlock at certain levels. Don't be discouraged by strict moderation — it keeps quality high. Common frustrations: 'marked as duplicate' (sometimes incorrectly), hostile comments on beginner questions, outdated accepted answers. Alternatives: Dev.to (friendlier community, blog-style), Reddit programming subreddits, Discord communities, GitHub Discussions. Contributing answers is a great way to learn — explaining solutions deepens your understanding. Stack Overflow Surveys provide valuable industry data — technology trends, salary data, most loved/dreaded languages. Despite criticism, it remains an indispensable resource. The running joke: a developer's real skill is knowing how to search Stack Overflow effectively.","Stack Overflow, Q&A, reputation, MCVE, community, moderation, alternatives.")

add("what music is best for coding?","Music while coding is a personal preference but research suggests some patterns. Lo-fi hip hop: steady beat, no lyrics — the 'lo-fi girl' stream is the developer stereotype for a reason. Minimal cognitive distraction, helps maintain flow state. Ambient/electronic: Brian Eno's ambient works, Tycho, Boards of Canada — background texture without demanding attention. Video game soundtracks: designed to keep you focused and engaged without distraction — Minecraft, Zelda, Stardew Valley, Doom (for intense coding sessions). Classical: Bach, Debussy — the 'Mozart Effect' is debated but many developers swear by it. Nature sounds: rain, forest, ocean — masking office noise. No music: some developers prefer silence or noise-canceling headphones for deep focus. What to avoid: music with lyrics in a language you understand (interferes with code reading), surprising dynamic changes, new music you haven't heard (novelty demands attention). The key is consistency — your brain associates the music with focus mode. Tools: Spotify coding playlists, Brain.fm (AI-generated focus music), Noisli.","Coding music, lo-fi, ambient, focus, flow state, concentration, video game soundtrack.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_en17.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} English entries (part 17).")
if __name__=="__main__":
    main()
