"""Extra EN training data - Part 16. Advanced CS, OS, Networking, Compilers, Math, Gorkem Projects."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

add("what are operating system fundamentals every developer should know?","OS is the software layer between hardware and applications. Key concepts: Process management — OS schedules processes on CPU (context switching, preemption). Scheduling algorithms: Round Robin (time slices), Priority-based, CFS (Completely Fair Scheduler in Linux). Memory management — virtual memory maps process addresses to physical RAM. Page tables, TLB (Translation Lookaside Buffer) for speed. Page faults: when data isn't in RAM, load from disk (swap). File systems — ext4 (Linux), APFS (macOS), NTFS (Windows). Inodes store metadata, data blocks store content. I/O — everything is a file in Unix (devices, sockets, pipes). System calls: interface between user space and kernel (open, read, write, fork, exec). Understanding OS helps you write better software — knowing about page faults explains why sequential array access is faster than random, knowing about context switches explains why too many threads hurt performance. Gorkem's gorkem-os project explores these concepts hands-on.","OS fundamentals, process scheduling, virtual memory, page fault, file system, system calls.")

add("how does garbage collection work?","Garbage collection (GC) automatically frees memory that's no longer used. Reference counting: track how many references point to an object, free when count reaches 0. Problem: circular references (A→B→B→A, both have count 1 but unreachable). Mark and Sweep: start from root references (stack, global variables), mark all reachable objects, sweep (free) unmarked ones. Generational GC (used in Java, Python, Go, .NET): objects are divided into generations — young, old, permanent. Most objects die young (generational hypothesis). Collect young generation frequently (fast), old generation rarely. Java GC options: G1 (default, balanced), ZGC (ultra-low pause), Shenandoah (low pause). Go: concurrent tri-color mark and sweep — sub-millisecond pauses. GC trade-offs: pause time vs throughput vs memory overhead. Stop-the-world pauses: entire application freezes during GC. Modern GCs minimize this with concurrent collection. Languages without GC (Rust, C, C++): manual memory management or ownership system — harder but more predictable performance.","Garbage collection, mark and sweep, generational GC, reference counting, stop-the-world.")

add("what is the OSI model and why does it matter?","OSI (Open Systems Interconnection) model has 7 layers for network communication. Layer 1 Physical: electrical signals, cables, Wi-Fi radio (bits). Layer 2 Data Link: MAC addresses, Ethernet frames, switches (frames). Layer 3 Network: IP addresses, routing, routers (packets). Layer 4 Transport: TCP/UDP, port numbers, reliability (segments). Layer 5 Session: connection management (rarely discussed separately). Layer 6 Presentation: encryption, compression, encoding (rarely discussed separately). Layer 7 Application: HTTP, SMTP, DNS, FTP (data). In practice, TCP/IP model (4 layers) is more commonly referenced: Network Access, Internet, Transport, Application. Why it matters: debugging network issues — 'can you ping the server?' (Layer 3), 'is the port open?' (Layer 4), 'does HTTP return 200?' (Layer 7). Each layer adds a header (encapsulation). Troubleshooting tools by layer: wireshark (all layers), traceroute (L3), netstat/ss (L4), curl (L7). Understanding layers helps you pinpoint where problems occur.","OSI model, TCP/IP, layers, encapsulation, networking, troubleshooting.")

add("what is a compiler and how does it work?","A compiler translates high-level code to machine code (or bytecode). Phases: 1) Lexical analysis (lexer/tokenizer): source code → tokens. 'int x = 5;' → [INT, IDENTIFIER(x), EQUALS, NUMBER(5), SEMICOLON]. 2) Parsing (parser): tokens → Abstract Syntax Tree (AST). Defines structure according to grammar rules. 3) Semantic analysis: type checking, scope resolution, name resolution. 4) Intermediate representation (IR): AST → platform-independent IR (LLVM IR is the most popular). 5) Optimization: constant folding, dead code elimination, loop unrolling, inlining. 6) Code generation: IR → target machine code (x86, ARM, RISC-V). Interpreted languages (Python, JavaScript): source → bytecode → virtual machine executes. JIT compilation (Java HotSpot, V8): interpret first, compile hot paths to machine code at runtime. LLVM: compiler infrastructure used by Clang (C/C++), Rust, Swift. Understanding compilers helps you write more efficient code and debug strange behavior. Gorkem's wiki2bpe project touches on tokenization — the first step of compilation.","Compiler, lexer, parser, AST, LLVM, JIT, optimization, code generation.")

add("what is functional programming and when to use it?","Functional programming (FP) treats computation as evaluation of mathematical functions. Core principles: 1) Pure functions — same input always returns same output, no side effects. Easy to test, reason about, and parallelize. 2) Immutability — data doesn't change. Create new data instead of modifying. Eliminates a whole class of bugs (shared mutable state). 3) First-class functions — functions are values, can be passed as arguments, returned from functions. 4) Higher-order functions — map, filter, reduce. 5) Composition — build complex functions from simple ones. 6) Pattern matching — elegant branching logic. FP languages: Haskell (pure), Erlang/Elixir (concurrent), Clojure (JVM), F# (.NET), Scala (hybrid). FP in mainstream languages: Python (map, filter, lambda, list comprehensions), JavaScript (array methods, React hooks), Java (streams, lambdas since Java 8). When to use FP: data transformations, concurrent/parallel code, complex state management. When not to: heavy I/O, performance-critical inner loops, team unfamiliarity. Best approach: use FP principles within your OOP codebase — pure functions, immutability where possible.","Functional programming, pure functions, immutability, higher-order functions, Haskell.")

add("what is the difference between concurrency models?","Different languages handle concurrency differently. 1) Threads with locks (Java, C++, Python): OS-level threads, shared memory, synchronization with mutexes/semaphores. Pros: straightforward mental model. Cons: deadlocks, race conditions, hard to debug. 2) Actor model (Erlang, Akka): actors are independent units with their own state, communicate via messages. No shared state = no locks. Pros: fault-tolerant, scalable. Cons: message ordering complexity. 3) CSP — Communicating Sequential Processes (Go): goroutines communicate via channels. 'Don't communicate by sharing memory; share memory by communicating.' Pros: simple, built into language. 4) Async/await (JavaScript, Python, Rust): single-threaded event loop with cooperative multitasking. Pros: no threading issues, great for I/O. Cons: CPU-bound work blocks the loop. 5) Green threads/fibers (Java Loom virtual threads, Ruby fibers): lightweight user-space threads. Choosing: I/O-heavy → async/await or goroutines, CPU-heavy → threads or processes, distributed → actors. Most modern languages are adopting multiple models.","Concurrency, threads, actor model, CSP, async/await, goroutines, channels, event loop.")

add("what is Big O notation and why does it matter?","Big O describes how algorithm performance scales with input size. O(1) constant: hash table lookup — always same speed regardless of size. O(log n) logarithmic: binary search — doubling input adds one step. O(n) linear: linear search — check every element. O(n log n) linearithmic: merge sort, quicksort average — best comparison-based sorting. O(n^2) quadratic: bubble sort, nested loops — 10x input = 100x time. O(2^n) exponential: recursive fibonacci — practically useless for large n. O(n!) factorial: brute force traveling salesman — impractical beyond ~20 items. Rules: drop constants (O(2n) = O(n)), drop lower terms (O(n^2 + n) = O(n^2)), worst case unless specified. Space complexity matters too: merge sort is O(n) space, quicksort is O(log n). Amortized analysis: dynamic array append is O(1) amortized despite occasional O(n) resize. For interviews: always analyze time AND space complexity of your solution. In practice: most optimizations matter only at scale — premature optimization is the root of all evil (Knuth).","Big O, time complexity, space complexity, O(n), O(log n), amortized, algorithm analysis.")

add("what is the difference between SQL JOIN types?","JOINs combine rows from multiple tables based on a condition. INNER JOIN: returns only matching rows from both tables. If user has no orders, they don't appear. LEFT JOIN (LEFT OUTER JOIN): all rows from left table + matching rows from right. Non-matching right side is NULL. Use case: list all users with their orders (including users with no orders). RIGHT JOIN: all rows from right table + matching from left. Less common — you can always swap tables and use LEFT JOIN. FULL OUTER JOIN: all rows from both tables. NULLs where no match. CROSS JOIN: every row from table A combined with every row from table B (Cartesian product). N * M rows. Rarely needed. SELF JOIN: table joined with itself. Use case: employee-manager relationships where both are in the same table. Performance: JOINs on indexed columns are fast. Avoid JOINing on functions (WHERE YEAR(date) = 2024 — can't use index). EXPLAIN ANALYZE reveals the join strategy (nested loop, hash join, merge join). N+1 query problem: ORM lazy loading — fetching N related objects with N+1 queries instead of one JOIN.","SQL JOIN, INNER JOIN, LEFT JOIN, FULL OUTER JOIN, CROSS JOIN, N+1 problem, index.")

add("what is Kubernetes architecture?","Kubernetes cluster has control plane and worker nodes. Control plane components: API Server (front door — all communication goes through it), etcd (distributed key-value store — cluster state), Scheduler (assigns pods to nodes based on resources), Controller Manager (runs control loops — ensures desired state = actual state). Worker node components: kubelet (agent on each node, manages pods), kube-proxy (networking rules, service routing), container runtime (containerd, CRI-O — runs containers). Key objects: Pod (smallest deployable unit, usually 1 container), Deployment (manages replicas and rolling updates), Service (stable network endpoint for pods — ClusterIP, NodePort, LoadBalancer), Ingress (HTTP routing from outside), ConfigMap/Secret (configuration), PersistentVolumeClaim (storage), Namespace (virtual cluster division). Networking: every pod gets its own IP, services provide DNS names, network policies control traffic. Helm: package manager for K8s — charts are reusable templates. Operators: custom controllers that extend K8s for specific applications (databases, message queues).","Kubernetes architecture, control plane, etcd, pod, deployment, service, Helm, operator.")

add("what is the CAP theorem in practice with real databases?","CAP theorem in action with real databases. PostgreSQL (single node): CA — consistent and available but no partition tolerance (single node, no partition). PostgreSQL with synchronous replication: CP — consistent, partition-tolerant, but unavailable if replica is down (waits for sync). MongoDB (replica set): CP by default — primary handles writes, if primary goes down, election happens (brief unavailability). Can be tuned to AP with read preference 'nearest' (may read stale data). Cassandra: AP — always available, eventually consistent. Tunable consistency (QUORUM reads/writes provide stronger consistency). DynamoDB: AP by default (eventual consistency), CP with strongly consistent reads (higher latency). Redis Cluster: AP — available during partitions but may lose recent writes. CockroachDB: CP — strong consistency via Raft consensus, sacrifices availability during partitions. In practice, these are tunable — most databases let you choose the trade-off per operation. The key is understanding what your application needs.","CAP theorem, PostgreSQL, MongoDB, Cassandra, DynamoDB, consistency, availability.")

add("what is containerization vs virtualization?","Virtual Machines (VMs): run a full OS on top of a hypervisor — Type 1 (bare metal — VMware ESXi, KVM) or Type 2 (on host OS — VirtualBox, VMware Workstation). Each VM has its own kernel, drivers, libraries. Heavy (gigabytes), slow to start (minutes), but strong isolation. Containers: share the host OS kernel, isolate at process level using Linux namespaces (PID, network, mount, user) and cgroups (resource limits). Lightweight (megabytes), start instantly (milliseconds), less isolation than VMs. Docker popularized containers. Container images are layered — shared base layers save space. When to use VMs: different OS required (Linux on Windows), strong security isolation, legacy applications. When to use containers: microservices, CI/CD, consistent dev/prod environments, rapid scaling. Modern approach: containers running inside VMs — Kubernetes nodes are VMs, each running many containers. Kata Containers: VMs with container UX — VM-level isolation with container-like speed. Firecracker (AWS Lambda): microVMs — boot in 125ms.","Containerization, virtualization, VM, Docker, namespaces, cgroups, hypervisor, Kata.")

add("what is the miniature-transformers project about?","Gorkem's miniature-transformers project implements the Transformer architecture from the 'Attention Is All You Need' paper from scratch. The project builds each component manually: 1) Multi-Head Self-Attention — the core mechanism that lets the model attend to different parts of the input simultaneously. Q, K, V matrices, scaled dot-product attention. 2) Positional Encoding — sinusoidal functions to encode token positions (transformers have no inherent notion of order). 3) Feed-Forward Network — two linear layers with ReLU activation in each transformer block. 4) Layer Normalization — stabilize training. 5) Encoder-Decoder architecture — encoder processes input, decoder generates output autoregressively. Why this matters: understanding transformers deeply is essential for anyone working in AI — GPT, BERT, T5, ViT, Whisper all use this architecture. Building from scratch gives intuition that using nn.Transformer doesn't provide. The project is educational — not production-grade, but invaluable for understanding modern AI's foundation.","miniature-transformers, self-attention, positional encoding, transformer architecture, from scratch.")

add("what is Gorkem's gorkem-os project?","gorkem-os is Gorkem's educational operating system project — building an OS kernel from scratch. This teaches fundamental CS concepts that most developers never work with directly. What it covers: bootloader (loading the kernel into memory), protected mode (switching from 16-bit real mode to 32-bit), memory management (paging, virtual memory), interrupt handling (keyboard input, timer), screen output (VGA text mode, writing directly to video memory at 0xB8000), basic file system concepts. Tools: NASM (assembly), GCC cross-compiler, QEMU (emulation), GNU Make. Why it matters: understanding how computers actually work at the lowest level makes you a better developer at every level. When you understand how system calls work, how memory is managed, how interrupts are processed — you can reason about performance, debugging, and system behavior more effectively. The project demonstrates Gorkem's intellectual curiosity and willingness to go deep into fundamental computer science.","gorkem-os, operating system, bootloader, kernel, memory management, interrupts, assembly.")

add("what is Gorkem's banking-management-system?","Gorkem's banking-management-system is a full-stack Java/Spring Boot application for bank operations. Features: account management (create, view, update accounts), transaction processing (deposits, withdrawals, transfers), transaction history and reporting, user authentication and authorization. Tech stack: Java with Spring Boot (backend framework), Spring Security (authentication), Spring Data JPA (database access), PostgreSQL or H2 (database), REST API design, possibly Thymeleaf or React frontend. Architecture: follows layered architecture — Controller (handle HTTP requests), Service (business logic), Repository (data access), Model/Entity (data representation). Key learnings demonstrated: ACID transactions (critical for banking — transfer must debit AND credit or neither), input validation, error handling, REST API design principles, database modeling (one-to-many relationships between accounts and transactions). This project shows Gorkem's ability to build practical, real-world applications with proper architecture.","banking-management-system, Java, Spring Boot, ACID, REST API, full-stack.")

add("what is the phishing-domain-detection project?","Gorkem's phishing-domain-detection project uses machine learning to detect phishing websites from URLs and domain features. Approach: extract features from URLs — domain length, number of dots, special characters, HTTPS presence, domain age, IP-based URL, URL shortening services, suspicious keywords. ML pipeline: 1) Data collection — labeled datasets of phishing and legitimate URLs. 2) Feature engineering — extract URL-based, domain-based, and content-based features. 3) Model training — classification algorithms (Random Forest, XGBoost, SVM, or neural networks). 4) Evaluation — accuracy, precision, recall, F1-score (precision matters — false negatives are dangerous, false positives annoy users). 5) Deployment — API or browser extension. Why it matters: phishing is one of the most common cyber attacks. ML can detect patterns humans might miss — unusual character combinations, domain similarity to known brands (paypa1.com vs paypal.com), recently registered domains. This project combines Gorkem's AI/ML skills with cybersecurity awareness.","phishing-domain-detection, ML, feature engineering, classification, cybersecurity, URL analysis.")

add("what is the NMT neural machine translation project?","Gorkem's NMT project implements neural machine translation — translating text between languages using deep learning. Architecture: typically encoder-decoder with attention. Encoder: processes source language sentence into a context representation. Decoder: generates target language sentence word by word using the context. Attention mechanism: allows the decoder to focus on relevant parts of the source sentence for each output word — critical breakthrough (Bahdanau attention, then self-attention in Transformers). Training: parallel corpus (sentence pairs in both languages), teacher forcing (feed correct previous word during training), beam search (explore multiple translation candidates during inference). Evaluation: BLEU score (compare generated translation against human references). Challenges: rare words (subword tokenization — BPE, SentencePiece), long sentences, domain-specific vocabulary. Modern NMT uses Transformer architecture exclusively — pre-trained multilingual models (mBART, NLLB) achieve remarkable quality. This project connects with Gorkem's wiki2bpe tokenization work and his interest in NLP.","NMT, neural machine translation, encoder-decoder, attention, BLEU score, BPE, transformer.")

add("what is the wiki2bpe project?","Gorkem's wiki2bpe project implements Byte Pair Encoding (BPE) tokenization from Wikipedia text. BPE is the tokenization algorithm used by GPT, LLaMA, and most modern LLMs. How BPE works: 1) Start with individual characters as tokens. 2) Count all adjacent token pairs in the corpus. 3) Merge the most frequent pair into a new token. 4) Repeat for desired vocabulary size. Example: 'low lower lowest' → 'l', 'o', 'w' → 'lo', 'w' → 'low' → vocabulary includes common subwords. Why BPE matters: handles any word (no out-of-vocabulary problem), balances between character-level (too granular) and word-level (too many tokens), captures morphology (un+break+able). Wikipedia as source: large, diverse, high-quality text corpus. Alternatives: WordPiece (BERT), Unigram (SentencePiece), tiktoken (OpenAI). Understanding tokenization is fundamental to NLP — token boundaries affect model performance. This project shows Gorkem's deep understanding of NLP preprocessing, directly relevant to his LLM fine-tuning work.","wiki2bpe, BPE, tokenization, subword, vocabulary, NLP, LLM preprocessing.")

add("what skills does a modern full-stack developer need?","Full-stack development covers frontend, backend, and infrastructure. Frontend: HTML/CSS fundamentals (responsive design, Flexbox, Grid), JavaScript/TypeScript, React or Vue or Svelte, state management, API consumption, testing (Jest, Cypress), performance optimization. Backend: a server language (Python/Django, Node/Express, Java/Spring, Go), REST API design, authentication (JWT, OAuth), database design (SQL + NoSQL), ORM usage, error handling, logging. Database: SQL (PostgreSQL), NoSQL (MongoDB or Redis), migrations, indexing, query optimization. DevOps: Docker, CI/CD (GitHub Actions), basic Linux commands, cloud basics (AWS/GCP), monitoring. Soft skills: version control (Git), code review, agile methodology, communication. Don't try to learn everything at once — pick one stack and go deep: React + Node + PostgreSQL + Docker is a solid starting stack. Gorkem's projects span this entire stack — from frontend portfolio to Spring Boot backends to ML model deployment.","Full-stack developer, frontend, backend, DevOps, PostgreSQL, React, Docker, skills.")

add("how does HTTP/2 and HTTP/3 improve web performance?","HTTP/1.1 limitations: one request per TCP connection (head-of-line blocking), text-based headers (verbose), no server push. HTTP/2 improvements: multiplexing (multiple requests over one connection — no head-of-line blocking at HTTP level), header compression (HPACK — reduces header size by 85-90%), server push (server sends resources before client requests them), binary framing (more efficient parsing). HTTP/2 problem: head-of-line blocking at TCP level — one lost packet blocks all streams. HTTP/3 improvements: built on QUIC (UDP-based) — eliminates TCP head-of-line blocking (streams are independent), faster connection establishment (0-RTT), built-in encryption (TLS 1.3 integrated), better mobile performance (connection migration — survives network changes). Adoption: most major websites support HTTP/2, HTTP/3 adoption growing (Cloudflare, Google). As a developer: use HTTPS (required for HTTP/2+), minimize number of domains (multiplexing makes domain sharding unnecessary), keep resources small (compression matters more than concatenation).","HTTP/2, HTTP/3, QUIC, multiplexing, head-of-line blocking, HPACK, server push.")

add("what is chaos engineering?","Chaos engineering is the practice of intentionally breaking things in production to build confidence in system resilience. Netflix pioneered it with Chaos Monkey — randomly terminates production instances. Principles: 1) Define steady state — what does 'normal' look like? (latency, error rate, throughput). 2) Hypothesize that steady state will continue. 3) Introduce chaos — kill servers, inject latency, corrupt network, fill disks. 4) Observe — does the system maintain steady state? 5) Fix issues found. Types of chaos: infrastructure (kill instances, AZ failure), network (latency injection, packet loss, DNS failure), application (exception injection, resource exhaustion), dependency (third-party service outage). Tools: Chaos Monkey (Netflix), Gremlin (SaaS platform), Litmus (Kubernetes-native), Chaos Mesh (K8s), AWS Fault Injection Simulator. Start small: run in staging first, then production during business hours with the team ready. Game days: planned chaos exercises with the team. Chaos engineering is not about breaking things — it's about learning and building resilience before real failures happen.","Chaos engineering, Chaos Monkey, resilience, fault injection, game days, Gremlin.")

add("what is the difference between monolith and microservices?","Monolith: entire application in one codebase, one deployment unit. All modules share the same database and memory. Microservices: application split into small, independent services, each with its own database, deployed separately. Monolith pros: simple to develop, test, deploy, debug. No network latency between modules. Easy to maintain consistency. Monolith cons: scaling is all-or-nothing, one bug can crash everything, technology lock-in, large codebase becomes hard to understand. Microservices pros: independent scaling, technology diversity, fault isolation, team autonomy, independent deployment. Microservices cons: distributed system complexity (network failures, eventual consistency), operational overhead (monitoring, debugging), data consistency challenges, service discovery, API versioning. When to choose monolith: early stage, small team, simple domain, MVP. When to choose microservices: large team (Conway's Law), independent scaling needs, different tech requirements per service. The modular monolith is a pragmatic middle ground — monolith with clear module boundaries, can be extracted to microservices later. Start monolith, extract when pain points emerge.","Monolith, microservices, modular monolith, scaling, Conway's Law, trade-offs.")

add("what is Gorkem's approach to AI projects?","Gorkem approaches AI/ML projects with a strong emphasis on understanding fundamentals before using high-level tools. His project portfolio demonstrates this philosophy: miniature-transformers (building transformer architecture from scratch rather than just calling PyTorch APIs), wiki2bpe (implementing BPE tokenization manually), NMT (building neural machine translation), yolo-custom-detector (fine-tuning object detection), facelock (face recognition system), phishing-domain-detection (ML for cybersecurity). Current focus: LLM fine-tuning with LoRA — this project creates training data for a personalized AI assistant. His approach: 1) Understand the theory (papers, textbooks). 2) Implement core components from scratch. 3) Then use frameworks for production work. 4) Document and share knowledge. This depth-first approach is what separates a developer who uses AI tools from one who understands them. Gorkem studies at Yeditepe University CS and combines academic knowledge with practical implementation — the ideal combination for an AI Product Developer.","Gorkem AI approach, fundamentals, from scratch, LoRA, fine-tuning, depth-first learning.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_en16.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} English entries (part 16).")
if __name__=="__main__":
    main()
