"""Extra EN training data - Part 12. Programming, Data Engineering, Frontend, Mobile, Emerging Tech."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

add("what are Python metaclasses and when to use them?","A metaclass is a class of a class — it controls how classes are created. Normal classes create objects, metaclasses create classes. type is the default metaclass in Python. Use cases: ORM frameworks (Django Model Field definitions work through metaclasses), API validation, singleton pattern, enforcing abstract base classes. Write your own with class Meta(type) and override __new__ or __init_subclass__. In practice, most projects don't need metaclasses — decorators and class decorators are usually sufficient. 'If you don't know whether you need metaclasses, you don't need them' — Tim Peters. But if you're building a framework or creating a DSL, they're a very powerful tool.","Python metaclass, type, ORM, Django Model, __new__, framework.")
add("what is the Python GIL and how does it affect performance?","The GIL (Global Interpreter Lock) in CPython only allows one thread to execute Python bytecode at a time. For CPU-bound tasks, multi-threading provides no benefit — it can even be slower due to overhead. For I/O-bound tasks (network requests, file reading), the GIL isn't a problem — the thread releases the GIL while waiting. Solutions: multiprocessing (each process has its own GIL), asyncio (for I/O-bound work), C extensions (NumPy releases the GIL), alternative interpreters (PyPy, Jython). Python 3.13+ is introducing a 'free-threaded' mode — making the GIL optional. In practice: GIL isn't an issue for web servers (each request is I/O-bound), for ML training NumPy/PyTorch runs in C anyway. The GIL is Python's most misunderstood topic — don't fear it but understand it.","GIL, CPython, multi-threading, multiprocessing, asyncio, free-threaded, I/O-bound.")
add("what is Rust's ownership and borrowing system?","Rust's most unique feature — it provides memory safety without a garbage collector. Ownership rules: every value has exactly one owner, when the owner goes out of scope the value is automatically cleaned up (drop), ownership can be transferred (move). Borrowing: lend a value — &x (immutable borrow, can have multiple) or &mut x (mutable borrow, only one at a time). These rules are checked at compile time — zero runtime overhead. Result: no null pointers, no data races, no use-after-free, no double free. The learning curve is steep — 'fighting the borrow checker' is a natural part of learning Rust. But once you learn it, you get C/C++ level performance with memory safety. Perfect for WebAssembly, systems programming, and CLI tools. Ideal for low-level work like Gorkem's gorkem-os project.","Rust, ownership, borrowing, borrow checker, memory safety, move, drop.")
add("how does Apache Kafka work?","Kafka is a distributed event streaming platform — capable of processing millions of messages per second. Use cases: microservices communication, real-time data pipelines, event sourcing, log aggregation, activity tracking. Concepts: topic (message category), partition (parallelism unit), producer (sends messages), consumer (receives messages), consumer group (load balancing), broker (Kafka server), offset (message position). Unlike RabbitMQ: Kafka persists messages for a retention period, you can replay them. RabbitMQ uses push model, Kafka uses pull. Kafka Connect: integration with external systems (DB to Kafka, Kafka to S3). Kafka Streams: stream processing library. Alternatives: Amazon Kinesis, Apache Pulsar, Redis Streams. Kafka has a steep learning curve but is the industry standard for large-scale data streaming.","Kafka, event streaming, topic, partition, consumer group, Kafka Connect, retention.")
add("what is the difference between data lake and data warehouse?","Data Warehouse stores structured, cleaned data — SQL querying, BI reports, business analytics. Schema defined upfront (schema-on-write). Tools: Snowflake, BigQuery, Redshift, Azure Synapse. Data Lake stores raw data as-is — structured, semi-structured, unstructured (JSON, CSV, images, video). Schema applied at read time (schema-on-read). Tools: S3 + Athena, HDFS, Azure Data Lake. Lakehouse (new trend): combines both — Delta Lake, Apache Iceberg, Apache Hudi. Store raw data in the lake, apply warehouse-like structure on top. Which to choose: business analytics and BI → warehouse, ML and raw data analysis → lake, both → lakehouse. Beware of the data swamp — an unorganized data lake turns into a junkyard.","Data Lake, Data Warehouse, Lakehouse, schema-on-write, schema-on-read, Delta Lake.")
add("what are React Server Components?","React Server Components (RSC) allow components to run on the server and send HTML to the client. Client Components run in the browser (interactive — useState, onClick). Server Components run on the server — direct database access, not added to bundle size, SEO friendly. Next.js App Router makes RSC the default — use the 'use client' directive to designate client components. Benefits: smaller JavaScript bundle, faster initial load, direct access to server resources, reduced waterfalls. Note: you can't use state or event handlers in Server Components. Streaming enables progressive rendering — the server sends ready parts first. This is a paradigm shift — React's future is heading toward a server-first approach.","React Server Components, RSC, Next.js App Router, use client, streaming, bundle size.")
add("React Native vs Flutter which should I choose?","Two major cross-platform frameworks. React Native: JavaScript/TypeScript, quick start if you know React, uses native components (platform-appropriate look), Expo for easy setup, large JavaScript ecosystem, hot reload. Flutter: Dart language (easy to learn but new), its own rendering engine (Skia — identical look across platforms), widget-based, very fast UI rendering, material and cupertino widgets. Performance: Flutter generally better (own engine), RN's new architecture (Fabric, TurboModules) is closing the gap. Ecosystem: RN is larger (JavaScript), Flutter is growing fast. Decision: if you know React/JS go with RN, starting fresh consider Flutter, if native look matters use RN, if pixel-perfect custom UI matters use Flutter. Both are production-ready — Instagram, Airbnb (formerly) use RN; Google Pay, BMW use Flutter.","React Native, Flutter, Dart, cross-platform, Expo, Skia, performance comparison.")
add("what is the current reality of blockchain and Web3?","There's a lot of hype around blockchain and Web3 but let's be realistic. Blockchain strengths: immutable record keeping, trust without central authority, automated transactions via smart contracts. Real use cases: cryptocurrency (Bitcoin, Ethereum), DeFi (decentralized finance), supply chain tracking, digital identity, NFTs (proof of digital ownership). Problems: scalability (Ethereum handles ~30 transactions/second vs Visa ~65,000), energy consumption (PoW — Bitcoin), complex UX (wallet management, gas fees), regulatory uncertainty, prevalence of scams. The Web3 vision is appealing (user data control, decentralized apps) but mainstream adoption hasn't happened yet. As a developer, worth learning but don't put all your eggs in this basket. If you want to learn Solidity, Ethereum's developer documentation is a good starting point.","Blockchain, Web3, Ethereum, DeFi, NFT, scalability, Solidity, realistic view.")
add("how will quantum computing affect developers?","Quantum computing uses technology that can perform certain calculations classical computers cannot. Qubits use superposition (0 and 1 simultaneously) and entanglement. Potential impact areas: cryptography (RSA could be broken — transition to post-quantum cryptography has begun), drug discovery (molecular simulation), optimization problems, materials science, ML (quantum machine learning). Current state: we're in the NISQ (Noisy Intermediate-Scale Quantum) era — qubits are noisy and error rates are high. Practical quantum advantage is still limited. For developers: you can try quantum programming with Qiskit (IBM), Cirq (Google), PennyLane. It won't replace classical computers — it will complement them for specific problem types. We'll see more practical applications in 5-10 years. For now, learning the fundamentals is sufficient.","Quantum computing, qubit, superposition, Qiskit, post-quantum cryptography, NISQ.")
add("what is edge computing and why is it important for IoT?","Edge computing processes data close to the source rather than in a central cloud — on the device or a nearby server. Why: latency (an autonomous car can't wait 100ms for cloud response), bandwidth (sending all IoT sensor data to the cloud is expensive), privacy (data stays on device), reliability (works even if internet goes down). In IoT: smart factory sensors detect anomalies locally, only sending important events to the cloud. CDNs are an early example of edge computing. Cloudflare Workers, AWS Lambda@Edge, Azure IoT Edge are modern tools. AI at the edge: run ML models on mobile devices or Raspberry Pi with TensorFlow Lite, ONNX Runtime. 5G will strengthen edge computing — low latency plus high bandwidth. Edge computing knowledge is valuable for Gorkem's IoT or embedded AI projects.","Edge computing, IoT, latency, bandwidth, TensorFlow Lite, Cloudflare Workers, 5G.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_en12.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} English entries (part 12).")
if __name__=="__main__":
    main()
