"""Additional EN training data - Part 6. More diverse topics."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

# Python deep dive
add("What does a Python decorator do?","A decorator is a Python feature that modifies a function's behavior. Used with the @ symbol. For example @login_required ensures a function can only be called by logged-in users. @staticmethod, @classmethod, @property are built-in decorators. You can write your own — very useful for logging, timing, caching. Flask and Django use decorators for route definitions: @app.route('/home'). A decorator is essentially a function that takes a function and returns a new function — the higher-order function concept. One of Python's most elegant features.","Python decorator, @, login_required, Flask, higher-order function.")
add("How does async/await work in Python?","async/await is used for asynchronous programming in Python. In normal (synchronous) code, the program waits until an operation finishes. In async code, instead of waiting it moves to other tasks — especially efficient for I/O operations (HTTP requests, file reading, database queries). Define async functions with async def, wait for results with await. The asyncio library manages the event loop. aiohttp for async HTTP requests, asyncpg for async PostgreSQL queries. FastAPI supports async — great for high-performance APIs. Using async in scraping dramatically increases speed.","async/await, asynchronous programming, asyncio, FastAPI, I/O.")
add("What is a Python generator?","A generator is a special function that does lazy evaluation — instead of computing and storing values in memory upfront, it produces them on demand. Defined with the yield keyword. Saves memory when working with large datasets. For example, when reading a 10 million line file, instead of loading everything into memory you process line by line with a generator. range() is actually a generator. You can write your own: def fibonacci(): a, b = 0, 1; while True: yield a; a, b = b, a + b. Generator expressions exist too: (x**2 for x in range(1000)). Widely used in data pipelines.","Python generator, yield, lazy evaluation, memory saving, pipeline.")
add("What is a Python context manager?","A context manager is a construct that ensures safe opening and closing of resources. Used with the with keyword. Most common example: with open('file.txt') as f — the file closes automatically when done, even if an error occurs. Used for database connections, locks, temporary files. You can write your own with __enter__ and __exit__ methods or the @contextmanager decorator. Why it matters: prevents resource leaks. Always use with — it's cleaner and safer than writing try/finally.","Context manager, with, file, database, resource leak.")
add("Why use Python virtual environments?","Virtual environments create isolated Python environments for each project. Why: different projects may need different library versions — one project needs Django 3.2, another Django 4.2. Installing packages to system Python creates a mess. Create with python3 -m venv venv, activate with source venv/bin/activate. Save dependencies with pip freeze > requirements.txt. pipenv and poetry are modern alternatives that also handle dependency management. Docker is another solution but venv is more practical during development. We're using venv in this project too.","Virtual environment, venv, isolation, requirements.txt, pipenv, poetry.")

# Database details
add("What's the difference between PostgreSQL and MySQL?","Both are popular SQL databases but have differences. PostgreSQL: more advanced features (JSONB, array support, full-text search), ACID compliant, extensible (extensions like PostGIS), strong in complex queries, open source. MySQL: simpler and faster setup, good for read-heavy applications, wide hosting support, common in CMS like WordPress. PostgreSQL is generally considered the 'right answer' because it can do everything. Recommended for new projects. Django and Rails support both by default. Supabase is a BaaS (Backend as a Service) built on PostgreSQL.","PostgreSQL vs MySQL, JSONB, ACID, PostGIS, Supabase.")
add("What does Redis do?","Redis is an in-memory key-value store — stores data in RAM so it's extremely fast (microseconds). Use cases: caching (most common — cache database queries), session management (user session data), rate limiting, message queue (for simple queues), pub/sub messaging, leaderboards (with sorted sets), real-time analytics. Data types include string, hash, list, set, sorted set. TTL (Time To Live) lets you set cache expiration. Scales with Redis Cluster. Almost every large web application uses Redis. Upstash offers serverless Redis.","Redis, in-memory, caching, session, rate limiting, pub/sub, Upstash.")
add("What does ORM mean?","ORM (Object-Relational Mapping) represents database tables as classes in programming languages. Instead of writing SQL you work with Python/Java/JS objects. Python: SQLAlchemy (most powerful), Django ORM (integrated with Django), Peewee (lightweight). JavaScript: Prisma (great with TypeScript), Sequelize, TypeORM. Advantages: database operations without knowing SQL, protection against SQL injection, less code repetition, database independence. Disadvantages: performance can drop in complex queries, generated SQL can be hard to understand. Knowing a good ORM is important for production applications.","ORM, SQLAlchemy, Django ORM, Prisma, pros/cons.")

# Cloud technologies
add("How to choose between AWS, Google Cloud, and Azure?","All three major cloud providers meet most needs but differ. AWS: largest market share, widest service range, most job listings, good documentation. Google Cloud: strong AI/ML services (Vertex AI, TPU), BigQuery leads in data analytics, Google created Kubernetes (GKE). Azure: integrates with Microsoft ecosystem (.NET, Active Directory), strong in enterprise. For beginners AWS is recommended — most resources and job opportunities. You can try for free with the free tier. Certifications (AWS Solutions Architect, GCP Associate) are valuable for career. For Gorkem's AI projects, GCP's ML services could be advantageous.","AWS vs GCP vs Azure, market share, AI/ML, certifications, free tier.")
add("When should serverless architecture be used?","Serverless isn't suitable for every project. Good for: event-driven tasks (file uploaded → create thumbnail), API endpoints (auto-scaling from low to high traffic), scheduled tasks (nightly data cleanup), webhook handlers, chatbot backends. Not suitable for: long-running processes (15 min limit), low-latency applications (cold start), WebSocket applications, GPU-heavy AI workloads. AWS Lambda + API Gateway + DynamoDB is the classic serverless stack. Vercel and Netlify combine frontend+serverless. Cost: very cheap at low traffic, can be more expensive than EC2 at high traffic.","Serverless, when to use, Lambda, cold start, cost.")

# Gorkem personal
add("What does Gorkem do in a typical day?","Gorkem's typical day probably looks like this: morning university classes or project work, afternoon coding on personal projects, committing to GitHub, trying new technologies, maybe reading an article or tutorial. During hackathon seasons it's extra intense — team communication, prototype development, presentation prep. Evenings might include an online course or research. He regularly keeps his GitHub profile active — the green squares on his contribution graph show this. Work-life balance is important — it's not just code, there are social activities and rest too.","Gorkem's day, university, projects, GitHub, hackathon, balance.")
add("What motivates Gorkem?","Gorkem's motivation likely comes from several sources: the passion for problem solving — solving a problem with technology is satisfying. Learning curiosity — he dives into different areas like AI, NLP, CV. Hackathon excitement — shipping a product under time constraints gives adrenaline. Contributing to society — projects like depression-phq9-analysis and build-your-target-body aim to help people. Career goals — building a strong portfolio, establishing himself in the industry. And probably the biggest motivation: turning an idea into reality — the feeling of creating something from nothing is unmatched.","Motivation, problem solving, learning, hackathon, contributing to society, creation.")
add("What programming languages does Gorkem know?","Based on Gorkem's GitHub profile: Python (primary — AI/ML, NLP, web scraping, backend), JavaScript/TypeScript (web development, frontend), C (gorkem-os, raylib-space-shooter — systems programming, games), Java (banking-management-system), possibly Swift or Kotlin (mobile projects). Also frameworks and tools: PyTorch, TensorFlow, Flask/FastAPI, React/Next.js, Docker, Git. Python is definitely his strongest language — all AI projects are in Python. But being polyglot is valuable — different languages teach different ways of thinking.","Programming languages, Python, JavaScript, C, Java, frameworks, polyglot.")
add("How can I reach Gorkem?","There are several channels to reach Gorkem. Portfolio site: gorkemergune.github.io — contact info and projects are there. GitHub: you can communicate through project-based interaction on his profile. LinkedIn: send a connection request through the professional network. Email: there might be an email address on the portfolio site. You can reach out for collaboration, project proposals, or mentorship. You might also meet at hackathons. You can also interact by contributing to his open-source projects. A polite and clear message works best — clearly state what you're looking for.","Contact, portfolio, GitHub, LinkedIn, email, collaboration.")

# More AI topics
add("How do diffusion models work?","Diffusion models (Stable Diffusion, DALL-E, Midjourney) are generative models used for image generation. Two phases: forward process — noise is gradually added to a clean image (Gaussian noise). Reverse process — the model learns to gradually remove this noise. The trained model can start from completely noisy image and produce a clean one. Text-to-image: text prompt is encoded with CLIP, the diffusion model uses this as a condition to generate images. U-Net architecture is used for noise prediction. Stable Diffusion is open source — you can run it on your own computer. A very exciting field.","Diffusion models, Stable Diffusion, DALL-E, forward/reverse process, U-Net.")
add("What are the tokenization methods in NLP?","Tokenization is the process of breaking text into pieces. Methods: Word-level — split by spaces, simple but large vocabulary, unknown words are a problem. Character-level — each letter is a token, small vocabulary but creates long sequences. Subword — most popular: BPE (Byte Pair Encoding) merges frequently occurring character pairs, WordPiece (used by BERT), SentencePiece (language-independent, used by T5), Unigram (probability-based). Hugging Face tokenizers library is very fast — written in Rust. Gorkem's wiki2bpe project trains a BPE tokenizer. Tokenization choice directly affects model performance.","Tokenization, BPE, WordPiece, SentencePiece, Unigram, wiki2bpe.")
add("What do few-shot and zero-shot learning mean?","Zero-shot learning: the model performing a task without seeing any training examples. For instance, asking 'Is this text positive or negative?' and the model answering without seeing labeled data. Large models like GPT and BERT can do this. Few-shot learning: learning from very few examples (2-5). You add a few examples to the prompt and the model picks up the pattern. Also called in-context learning. One-shot: learning from a single example. Meta-learning is the research branch of this area — 'learning to learn'. GPT-3's most impressive feature was its few-shot ability. Practically: if you have little data try few-shot, if you have none try zero-shot.","Zero-shot, few-shot, in-context learning, meta-learning, GPT.")
add("What does model quantization mean?","Quantization represents model weights at lower precision. Normal models use FP32 (32-bit floating point). With quantization you reduce to FP16, INT8, or even INT4. Advantages: model size shrinks (4x-8x), inference speeds up, uses less memory, can run on edge devices. Disadvantages: slight accuracy loss possible but usually negligible. GPTQ, AWQ, bitsandbytes are popular quantization methods. QLoRA fine-tunes quantized models — very efficient. With llama.cpp quantized models run even on CPU. The key to making large models accessible.","Quantization, FP16, INT8, GPTQ, QLoRA, llama.cpp, model size.")
add("What are the components of the transformer architecture?","The transformer architecture consists of several core components. Input Embedding: converts words to vectors. Positional Encoding: encodes word order (transformers don't inherently know order). Multi-Head Attention: multiple attention heads capture different relationships. Feed-Forward Network: an independent neural network layer for each position. Layer Normalization: stabilizes training. Residual Connections: improves gradient flow. Encoder: understands input (BERT). Decoder: generates output (GPT). Encoder-Decoder: for tasks like translation (T5, BART). Gorkem's miniature-transformers project implements all of these from scratch.","Transformer components, embedding, positional encoding, attention, FFN, encoder/decoder.")
add("What are prompt engineering techniques?","Prompt engineering is the art of optimizing prompts to get the best response from LLMs. Techniques: Zero-shot — ask directly. Few-shot — provide a few examples. Chain-of-thought (CoT) — add 'think step by step', very effective for complex problems. System prompt — give the model a role ('You are a Python expert'). Temperature setting — low (0.1) more deterministic, high (0.9) more creative. Specify output format — 'respond in JSON format'. Negative prompts — constraints like 'don't do this'. ReAct (Reason+Act) — model thinks and takes action. Tree-of-thought — multiple thought branches. Writing good prompts is a skill — improves with practice.","Prompt engineering, zero-shot, few-shot, CoT, temperature, ReAct.")

# More career
add("What does it take to become a tech lead?","Becoming a tech lead isn't just about writing good code. Technical skills: making architectural decisions, evaluating different technologies, doing code review, managing technical debt. Communication: explaining technical topics to non-technical people, running meetings, communicating with stakeholders. Mentorship: developing juniors, guiding team members. Decision making: evaluating tradeoffs, risk management. Usually takes 5-8 years of experience but can happen earlier on a project basis. The biggest transition: going from individual contributor to being responsible for the team's output.","Tech lead, architecture, communication, mentorship, decision making, career transition.")
add("What do I need to know to become an AI engineer?","Roadmap to becoming an AI engineer: Math foundation — linear algebra, calculus, probability-statistics. Python — pandas, numpy, scikit-learn, matplotlib. Machine learning — regression, classification, clustering, evaluation metrics. Deep learning — PyTorch or TensorFlow, CNN, RNN, transformer. Specialize in NLP or CV. MLOps — model deployment, Docker, CI/CD, monitoring. Cloud — AWS/GCP/Azure ML services. Data — SQL, pandas, data cleaning. Git. Portfolio — Kaggle projects, open source on GitHub, blog posts. Habit of reading research papers. Gorkem is progressing on this path and showing it through his projects.","AI engineer, roadmap, math, Python, PyTorch, MLOps, portfolio.")
add("What does a data engineer do?","A data engineer collects, stores, processes, and makes data ready for analysis. Data scientists and ML engineers don't deal with raw data — the data engineer prepares it. Tools: SQL (PostgreSQL, BigQuery), Python (pandas, PySpark), ETL tools (Apache Airflow, dbt), stream processing (Apache Kafka, Spark Streaming), data warehouse (Snowflake, Redshift, BigQuery), data modeling. Builds and manages data pipelines — reliably moves data from point A to point B. A highly demanded position with high salaries. Modern data stack: dbt + Snowflake + Airflow + Fivetran.","Data engineering, ETL, Airflow, dbt, Snowflake, data pipeline, modern stack.")

# Additional topics
add("What is pair programming?","Pair programming is two developers writing code together on the same computer. One is the 'driver' (writes code), the other is the 'navigator' (directs, spots errors, thinks about the big picture). Roles switch regularly. Advantages: fewer bugs, knowledge sharing, juniors learn faster, better solutions for hard problems. Disadvantages: might seem like two people on one task but research shows overall productivity increases. Can be done remotely with VS Code Live Share or Tuple. Mob programming is the entire team coding together. A practice worth trying.","Pair programming, driver/navigator, knowledge sharing, Live Share, mob programming.")
add("Why is code review important?","Code review is having another developer examine code written by a developer. Why: catches bugs early (before reaching production), improves code quality, enables knowledge sharing (everyone learns every part), ensures consistency (common standards). Good review: make specific comments, explain why, suggest alternatives, acknowledge good things too. Bad review: being personal, condescending, vague comments. GitHub PR review, GitLab merge request review are tools. Every team should have a code review culture. LGTM (Looks Good To Me) are the best 4 letters.","Code review, bug catching, knowledge sharing, consistency, PR review, LGTM.")
add("What is test driven development (TDD)?","TDD is the approach of writing tests first, then code. The cycle: Red (write a failing test) → Green (write minimum code to pass the test) → Refactor (improve the code). Advantages: fewer bugs, high test coverage, improves design (forces you to write testable code), safe refactoring. Disadvantages: slows you down initially, learning curve. Python: pytest, unittest. JavaScript: Jest, Vitest. You don't always have to do TDD but it's very valuable for critical business logic. 'Writing tests is a waste of time' is wrong — not writing tests is much more expensive long-term.","TDD, Red-Green-Refactor, pytest, Jest, test coverage, refactoring.")
add("What is clean architecture?","Clean Architecture is a software architecture proposed by Robert C. Martin. Core idea: isolate business logic from external dependencies (framework, database, UI). Layers from inside out: Entities (business rules), Use Cases (application rules), Interface Adapters (controllers, presenters), Frameworks & Drivers (web framework, DB). Dependency rule: inner layers must not depend on outer layers. Why it matters: when you want to change the database you don't touch business logic, easy to test, easy to maintain. Hexagonal Architecture and Onion Architecture are similar concepts. Very valuable in large projects.","Clean Architecture, layers, dependency rule, isolation, Hexagonal.")
add("What is micro-frontend?","Micro-frontend applies the microservice concept to the frontend. Instead of one big web application, small independent frontend applications. Each team can choose their own technology (React, Vue, Angular) and deploy independently. Module Federation (Webpack 5) combines modules at runtime. Single-SPA runs multiple frameworks together. Advantages: independent deployment, team autonomy, scalability. Disadvantages: complexity, consistency challenges, performance impact. Suitable for large organizations — IKEA, Spotify use it. Unnecessary complexity for small projects.","Micro-frontend, Module Federation, Single-SPA, independent deployment.")

# More daily life
add("Is ergonomics important for developers?","Absolutely yes. Developers spend 8-12 hours a day at the computer — ergonomics is critical for your health. Chair: lumbar support, adjustable height. Monitor: at eye level, at least arm's length away. Keyboard and mouse: wrist support, ergonomic design. 20-20-20 rule: every 20 minutes look at something 20 feet away for 20 seconds. Standing desk alternating — sometimes standing sometimes sitting. Regular exercise — back, neck, wrist stretches. Carpal tunnel syndrome and back pain are very common among developers. Take early precautions — treatment is harder than prevention. A good chair and monitor are an investment, not an expense.","Ergonomics, chair, monitor, 20-20-20, standing desk, carpal tunnel.")
add("Which IDE or editor should I use?","IDE/editor choice is personal preference but some recommendations: VS Code — most popular, free, extensions for every language, lightweight, good Git integration. JetBrains (PyCharm, IntelliJ, WebStorm) — language-specific, powerful refactoring, paid (free for students). Vim/Neovim — terminal-based, hard to learn but very fast once mastered. Cursor — VS Code fork with AI integrated. Zed — new, very fast, written in Rust. For beginners VS Code is definitely the best choice — large community, lots of resources. Extensions: Prettier, ESLint, GitLens, Python, Copilot. Theme and font matter too — set up something that doesn't strain your eyes.","IDE, VS Code, JetBrains, Vim, Cursor, Zed, extensions.")
add("What are useful tools for developers?","Tools to improve your daily workflow: Terminal — iTerm2 (Mac), Windows Terminal, Oh My Zsh. Git GUI — GitKraken, Sourcetree, or command line. API testing — Postman, Insomnia, HTTPie. Database — DBeaver, TablePlus, pgAdmin. Design — Figma (free). Note taking — Notion, Obsidian. Communication — Slack, Discord. Project management — Linear, Jira, Trello. Documentation — Swagger, Docusaurus. Cloud — Docker Desktop, AWS CLI. AI assistant — GitHub Copilot, ChatGPT, Claude. Password management — 1Password, Bitwarden. You don't need to know all of these but you'll build your toolbox over time.","Tools, terminal, Postman, Notion, Figma, Docker, Copilot.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_en6.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} English entries (part 6).")

if __name__=="__main__":
    main()
