"""Extra EN training data - Part 14. Career, Freelancing, AI/ML Advanced, Tools, Testing, Frontend."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

add("how do you get started with freelancing as a developer?","Freelancing offers freedom but requires discipline. Getting started: 1) Build a portfolio — 3-5 polished projects on GitHub with good READMEs and live demos. 2) Pick a niche — 'React developer for SaaS startups' is better than 'I do everything.' 3) Platforms: Upwork (largest, competitive), Toptal (vetted, higher rates), Fiverr (gig-based), freelancer.com. 4) Start with lower rates to build reviews, then increase. 5) Cold outreach — email agencies and startups directly. Pricing: hourly vs project-based. Project-based is better — you get paid for value, not time. Always get a contract and 30-50% upfront. Communication: over-communicate, send weekly updates, manage expectations. Taxes: set aside 25-30% for taxes, track expenses, consider an LLC. Challenges: irregular income, isolation, scope creep, finding clients. Benefits: location independence, choose your projects, unlimited earning potential.","Freelancing, portfolio, Upwork, Toptal, pricing, contract, niche, cold outreach.")

add("how do you build a strong developer portfolio?","A portfolio is your developer resume — it shows what you can do, not just what you claim. What to include: 3-5 quality projects > 20 mediocre ones. Each project should have: clear README (problem, solution, tech stack, how to run), live demo or screenshots, clean code with tests. Project diversity: one full-stack app, one API/backend project, one that solves a real problem. Use your own domain (yourname.dev). GitHub profile: green contribution graph, pinned repositories, professional bio. Blog: write about what you learn — it shows depth. Example structure: hero section with tagline, about me, projects grid with links, skills, blog posts, contact. Tech choices for portfolio site: Next.js + Vercel (fast, free hosting), or even a simple HTML/CSS site — the content matters more than the framework. Gorkem's portfolio at gorkemergune.github.io is a great example — it showcases his projects clearly.","Portfolio, GitHub, README, live demo, personal brand, projects, blog.")

add("what is transfer learning in deep learning?","Transfer learning uses knowledge from one task to improve performance on another. Instead of training from scratch (millions of images, weeks of compute), start with a model pretrained on ImageNet (ResNet, EfficientNet) and fine-tune on your specific task. Process: 1) Load pretrained model. 2) Replace the final classification layer for your number of classes. 3) Freeze early layers (they learn general features — edges, textures). 4) Train only the last few layers on your dataset. 5) Optionally, unfreeze all layers and fine-tune with a very low learning rate. This works because early layers learn universal features transferable across tasks. In NLP: BERT, GPT are pretrained on massive text corpora, then fine-tuned for sentiment analysis, NER, question answering. In practice: transfer learning lets you get good results with just hundreds of labeled examples instead of millions. LoRA (Low-Rank Adaptation) is a parameter-efficient fine-tuning method — Gorkem uses this for his LLM fine-tuning project.","Transfer learning, fine-tuning, pretrained model, ImageNet, LoRA, BERT, feature extraction.")

add("what is reinforcement learning and how does it work?","Reinforcement learning (RL) is learning through trial and error — an agent takes actions in an environment and receives rewards or penalties. Key concepts: state (current situation), action (what agent does), reward (feedback signal), policy (strategy — maps states to actions), value function (expected future reward). Exploration vs exploitation: try new actions (explore) or use known good actions (exploit) — epsilon-greedy, UCB. Algorithms: Q-Learning (learn value of state-action pairs, off-policy), SARSA (on-policy), Deep Q-Network/DQN (Q-learning with neural networks — played Atari), Policy Gradient (directly learn the policy), Actor-Critic (combine value and policy learning), PPO (Proximal Policy Optimization — used in ChatGPT's RLHF). Applications: game playing (AlphaGo, OpenAI Five), robotics, recommendation systems, autonomous driving, resource allocation. RLHF (RL from Human Feedback): how ChatGPT/Claude are aligned with human preferences. RL is powerful but sample-inefficient and hard to debug.","Reinforcement learning, Q-learning, DQN, PPO, RLHF, policy, reward, exploration.")

add("what is RAG retrieval augmented generation?","RAG combines retrieval systems with LLMs — instead of relying solely on the model's training data, you retrieve relevant documents and include them in the prompt. Pipeline: 1) Indexing: split documents into chunks, generate embeddings (OpenAI, Cohere, sentence-transformers), store in vector database (Pinecone, Weaviate, Chroma, pgvector). 2) Retrieval: user query → embed query → find similar chunks via cosine similarity → top-k results. 3) Generation: pass retrieved chunks + user query to LLM → contextual answer with sources. Benefits: no hallucination on factual data, stays up-to-date (update documents, not model), domain-specific knowledge, cheaper than fine-tuning. Challenges: chunking strategy (too small = no context, too large = noise), retrieval quality, context window limits. Advanced: hybrid search (combine semantic + keyword/BM25), re-ranking, query transformation, multi-step retrieval. Frameworks: LangChain, LlamaIndex, Haystack. RAG is the most practical way to build AI applications over private data.","RAG, retrieval, embeddings, vector database, LangChain, LlamaIndex, chunking.")

add("what is the difference between unit, integration, and e2e tests?","Testing pyramid: many unit tests at the base, fewer integration tests in the middle, few E2E tests at the top. Unit tests: test individual functions/methods in isolation. Fast, reliable, easy to debug. Mock external dependencies. Tools: Jest, pytest, JUnit. Example: test that calculateTotal(items) returns correct sum. Integration tests: test how components work together. Slower, may use real database. Example: test that POST /api/users creates a user in the database and returns 201. Tools: supertest (Node), pytest with fixtures. E2E (End-to-End) tests: test the entire application from user's perspective. Slowest, most brittle, but catch issues others miss. Tools: Cypress, Playwright, Selenium. Example: user signs up, creates a post, comments on it. The testing trophy (Kent C. Dodds): more integration tests, fewer unit tests — integration tests give the most confidence per effort. In practice: aim for 70% unit, 20% integration, 10% E2E. Write tests for the behavior, not the implementation.","Testing pyramid, unit test, integration test, E2E, Jest, Cypress, Playwright.")

add("what is TDD test-driven development?","TDD follows a strict cycle: Red → Green → Refactor. 1) Red: write a failing test first — it should describe the desired behavior. 2) Green: write the minimum code to make the test pass — no more. 3) Refactor: clean up the code while keeping tests green. Benefits: forces you to think about requirements before coding, produces testable code by design, serves as documentation, gives confidence to refactor, catches regressions immediately. Critics say: slower initial development, some tests are trivial, can lead to testing implementation details, not practical for all situations (UI, exploratory coding). Pragmatic TDD: use it for complex logic, algorithms, and critical paths. Skip it for simple getters/setters and UI prototyping. BDD (Behavior-Driven Development) extends TDD: write tests in natural language — 'Given a logged-in user, When they click delete, Then the item is removed.' Tools: Cucumber, Behave. TDD is a discipline — it gets easier with practice.","TDD, Red Green Refactor, test-driven, BDD, Cucumber, testing discipline.")

add("what is CI/CD best practices?","CI (Continuous Integration): merge code to main frequently, automated tests run on every push. CD (Continuous Delivery/Deployment): automatically deploy to staging, optionally to production. Best practices: 1) Fast pipeline — under 10 minutes ideal, parallelize tests, use caching. 2) Fail fast — run linters and unit tests first, integration tests after. 3) Trunk-based development — short-lived feature branches, merge frequently. 4) Feature flags — deploy code without enabling features, decouple deploy from release. 5) Blue-green deployment — two identical environments, switch traffic. 6) Canary deployment — roll out to 1% of users first, monitor, then expand. 7) Rollback strategy — automated rollback if error rate increases. 8) Environment parity — staging should mirror production. 9) Secrets management — never commit secrets, use vault/environment variables. 10) Pipeline as code — Jenkinsfile, .github/workflows, .gitlab-ci.yml in version control. Tools: GitHub Actions, GitLab CI, Jenkins, CircleCI, ArgoCD (GitOps). Monitor your pipeline — if it's slow or flaky, developers will work around it.","CI/CD, feature flags, blue-green, canary, trunk-based, rollback, GitHub Actions.")

add("what is TypeScript and why use it over JavaScript?","TypeScript adds static types to JavaScript — it catches errors at compile time instead of runtime. Benefits: 1) Catch bugs early — typos, wrong argument types, null/undefined issues found before running code. 2) Better IDE support — autocomplete, refactoring, go-to-definition, inline documentation. 3) Self-documenting — types serve as documentation: function getUser(id: string): Promise<User>. 4) Safer refactoring — change a type, see all affected code immediately. 5) Better for teams — explicit contracts between components. Key features: interfaces, generics, union types (string | number), type guards, enums, utility types (Partial<T>, Pick<T>, Omit<T>). Strict mode: enable all strict checks — noImplicitAny, strictNullChecks. Downsides: learning curve, more verbose, build step required, some libraries have poor type definitions. Migration: start with allowJs, add types incrementally. TypeScript compiles to JavaScript — any valid JS is valid TS. It's now the standard for serious JavaScript development.","TypeScript, static types, interfaces, generics, strict mode, type safety, migration.")

add("what is Next.js and why is it popular?","Next.js is a React framework that adds server-side rendering, routing, and full-stack capabilities. Key features: 1) File-based routing — create pages/about.tsx, get /about route automatically. 2) Server-Side Rendering (SSR) — render on server for each request, great for dynamic content and SEO. 3) Static Site Generation (SSG) — render at build time, blazing fast. 4) Incremental Static Regeneration (ISR) — regenerate static pages in the background. 5) API Routes — build backend endpoints in the same project. 6) App Router (Next.js 13+) — React Server Components, layouts, loading states, error boundaries. 7) Image optimization — automatic resizing, lazy loading, WebP conversion. 8) Built-in CSS, Sass, CSS Modules, Tailwind support. Deploy: Vercel (creators of Next.js, easiest), AWS Amplify, Docker. When to use: SEO matters, content-heavy sites, full-stack apps. When not to: simple SPA without SEO needs, heavily interactive apps (consider Vite + React). Next.js has become the default way to build React applications.","Next.js, SSR, SSG, ISR, App Router, React Server Components, Vercel, file-based routing.")

add("what is Tailwind CSS and why do developers love it?","Tailwind CSS is a utility-first CSS framework — instead of writing custom CSS, you compose utility classes: <div class='flex items-center gap-4 p-6 bg-white rounded-lg shadow-md'>. Benefits: 1) Speed — no context switching between HTML and CSS files. 2) Consistency — predefined spacing, colors, breakpoints. 3) Small bundle — PurgeCSS removes unused classes, final CSS is tiny. 4) Responsive — sm:, md:, lg: prefixes. 5) Dark mode — dark: prefix. 6) Customizable — tailwind.config.js for colors, fonts, spacing. Critics say: ugly HTML with many classes, hard to read, reinventing inline styles. Response: extract components (React components naturally group styles), use @apply for repeated patterns (sparingly), IDE extensions for autocomplete and sorting. Tailwind + React/Vue components = very productive. shadcn/ui: beautiful, accessible component library built with Tailwind — copy components into your project, fully customizable. Tailwind has become the most popular CSS framework among React developers.","Tailwind CSS, utility-first, responsive, dark mode, PurgeCSS, shadcn/ui.")

add("what is Vim and why do some developers swear by it?","Vim is a modal text editor — it separates navigation from editing, making you faster once you learn it. Modes: Normal (navigate, delete, copy), Insert (type text), Visual (select text), Command (save, quit, search). Why developers love it: 1) Speed — navigate without touching the mouse. hjkl for movement, w/b for word jumps, gg/G for start/end. 2) Composability — commands combine: d2w (delete 2 words), ci' (change inside quotes), yap (yank a paragraph). 3) Available everywhere — every Linux server has vi/vim. 4) Lightweight — opens instantly, no Electron overhead. 5) Extensible — plugins via vim-plug, Vundle; Neovim + Lua for modern config. Learning curve is steep — takes 2-4 weeks to be productive. Start with vimtutor (built-in tutorial). Modern approach: use Vim keybindings in VS Code (Vim extension) or use Neovim with LazyVim/AstroNvim (IDE-like experience). Vim is not about typing faster — it's about editing at the speed of thought.","Vim, modal editing, Neovim, keybindings, navigation, composability, vimtutor.")

add("what is Git flow vs trunk-based development?","Two popular branching strategies. Git Flow: main branch (production), develop branch (integration), feature branches, release branches, hotfix branches. Pros: clear separation between stages, good for versioned releases. Cons: complex, long-lived branches cause merge conflicts, slow release cycle. Trunk-Based Development: everyone commits to main (trunk) frequently — at least daily. Short-lived feature branches (max 1-2 days). Use feature flags to hide incomplete features. Pros: simpler, fewer merge conflicts, enables continuous deployment, faster feedback. Cons: requires strong CI/CD, discipline to keep main stable, feature flags add complexity. Industry trend: moving toward trunk-based. Google, Facebook, Netflix use it. Git Flow suits: versioned software (mobile apps, libraries), teams without strong CI/CD. Trunk-based suits: web applications, SaaS, teams practicing continuous deployment. GitHub Flow is a middle ground: main + short feature branches with PRs.","Git Flow, trunk-based, branching strategy, feature flags, GitHub Flow, CI/CD.")

add("what are WebSockets and when to use them?","WebSockets provide full-duplex communication over a single TCP connection — both client and server can send data anytime. HTTP: client sends request, server responds, connection closes (request-response). WebSocket: client and server establish a persistent connection, both can push data at any time. Handshake: starts as HTTP request with Upgrade header, server responds with 101 Switching Protocols. Use cases: real-time chat, live notifications, collaborative editing (Google Docs), live dashboards, multiplayer games, stock tickers, live sports scores. Server-Sent Events (SSE): simpler alternative — server pushes to client only (one-way). Good for: notifications, live feeds. No client-to-server push. Long Polling: HTTP-based fallback — client makes request, server holds it until data available, then client immediately makes another. Less efficient than WebSocket. Libraries: Socket.IO (WebSocket + fallback + rooms), ws (Node raw WebSocket). Scale: WebSocket connections are stateful — need sticky sessions or Redis pub/sub for multi-server.","WebSocket, full-duplex, Socket.IO, SSE, long polling, real-time, persistent connection.")

add("what is Docker Compose and how to use it?","Docker Compose defines multi-container applications in a single YAML file. Instead of running multiple docker commands, one docker-compose up starts everything. Example docker-compose.yml: services with web (your app), db (PostgreSQL), redis (cache), nginx (reverse proxy). Key directives: image (use existing image), build (build from Dockerfile), ports (host:container mapping), volumes (persist data), environment (env variables), depends_on (start order), networks (service communication). Development workflow: docker-compose up -d (start detached), docker-compose logs -f (follow logs), docker-compose exec web bash (shell into container), docker-compose down (stop and remove). Best practices: use named volumes for data persistence, separate docker-compose files for dev and prod (docker-compose.override.yml), use .env file for variables, health checks for dependencies. Docker Compose v2 is now integrated into Docker CLI: docker compose instead of docker-compose. For production at scale, consider Kubernetes instead.","Docker Compose, YAML, multi-container, volumes, networking, development workflow.")

add("what is the difference between SQL and NoSQL?","SQL (relational) databases store data in tables with predefined schemas — rows and columns. ACID compliant, powerful JOIN operations. Examples: PostgreSQL, MySQL, SQLite, SQL Server. NoSQL (non-relational) databases come in several types: Document (MongoDB — JSON documents, flexible schema), Key-Value (Redis, DynamoDB — simple lookups), Wide-Column (Cassandra — massive writes, time-series), Graph (Neo4j — relationship-heavy data). SQL strengths: complex queries, data integrity, transactions, well-understood by most developers. NoSQL strengths: horizontal scaling, flexible schema, high write throughput, schema evolution. When to use SQL: structured data with relationships, financial/transactional applications, complex reporting. When to use NoSQL: rapidly changing schema, high-scale writes, document-like data, real-time applications. Modern trend: polyglot persistence — use the right database for each use case. PostgreSQL has JSON support (jsonb), blurring the line. Start with SQL unless you have a specific reason not to.","SQL, NoSQL, relational, document, key-value, schema, ACID, horizontal scaling.")

add("what is Gorkem's approach to learning new technologies?","Gorkem follows a practical, project-based learning approach. His method: 1) Understand the fundamentals — don't jump into frameworks without understanding the underlying concepts. 2) Build something — reading tutorials isn't enough, build a project that solves a real problem. 3) Document the journey — write READMEs, blog posts, explain what you learned. 4) Iterate — first version doesn't need to be perfect, improve incrementally. His 30+ GitHub projects demonstrate this: miniature-transformers (understanding transformer architecture by building from scratch), yolo-custom-detector (applying transfer learning), gorkem-os (learning OS internals), banking-management-system (full-stack with Java/Spring). The key insight: depth over breadth. It's better to deeply understand 5 technologies than superficially know 20. Gorkem's portfolio at gorkemergune.github.io showcases this depth. His advice: pick a project that excites you, and learn the tools needed to build it — motivation drives consistency.","Learning approach, project-based, fundamentals, depth over breadth, portfolio, consistency.")

add("what is the state of AI in 2025?","AI in 2025 is defined by foundation models and their applications. LLMs: GPT-4, Claude, Gemini, Llama, Mistral — capable of reasoning, coding, analysis. Multimodal: models handle text, images, audio, video together. Key trends: 1) Open-source models closing the gap (Llama 3, Mistral, Qwen). 2) Small models getting better (phi, Gemma — run on phones). 3) Agents — AI that can use tools, browse web, write and execute code. 4) RAG becoming standard for enterprise AI. 5) Fine-tuning democratized — LoRA, QLoRA make it accessible on consumer GPUs. 6) AI coding assistants mainstream — Copilot, Cursor, Claude Code. 7) Regulation emerging — EU AI Act, executive orders. Concerns: hallucination (models confidently state wrong things), job displacement, energy consumption, concentration of power. Opportunities: every industry needs AI integration — developers who understand both AI and domain problems are extremely valuable. Gorkem's focus on AI/ML positions him perfectly for this landscape.","AI 2025, LLMs, foundation models, open-source, agents, RAG, LoRA, regulation.")

add("what is prompt engineering and best practices?","Prompt engineering is the art of crafting inputs to get better outputs from LLMs. Techniques: 1) Be specific — instead of 'write code', say 'write a Python function that takes a list of integers and returns the top 3 most frequent elements.' 2) Provide context — 'you are an expert backend developer reviewing code for security issues.' 3) Few-shot examples — show 2-3 examples of input-output pairs. 4) Chain of thought — 'think step by step' dramatically improves reasoning. 5) Output format — 'respond in JSON with keys: summary, pros, cons.' 6) Negative instructions — 'do not include explanations, only output the code.' Advanced: tree of thought (explore multiple reasoning paths), self-consistency (generate multiple answers, pick the most common), ReAct (reasoning + acting — tool use). Temperature: 0 for factual/deterministic, 0.7-1.0 for creative. System prompts set behavior and constraints. Prompt engineering is becoming less necessary as models improve, but understanding it helps you use AI tools effectively.","Prompt engineering, few-shot, chain of thought, temperature, system prompt, ReAct.")

add("how do you handle technical interviews?","Technical interviews vary by company but generally include: 1) Coding challenge — solve algorithms on whiteboard/online. Practice: LeetCode (top 150 problems), HackerRank, Codeforces. Focus on arrays, strings, trees, graphs, dynamic programming. 2) System design — design large-scale systems (covered separately). 3) Behavioral — STAR method (Situation, Task, Action, Result). Prepare 5-6 stories about challenges, teamwork, failure, leadership. 4) Take-home project — build something in 3-5 hours. Clean code, tests, README matter more than features. Tips: think out loud during coding interviews — interviewers evaluate your thought process. Ask clarifying questions before coding. Start with brute force, then optimize. Test your solution with edge cases. Time management: don't spend too long on one problem. Communication: explain trade-offs, acknowledge what you don't know. Rejection doesn't mean you're bad — it means the fit wasn't right. Each interview is practice for the next one. Gorkem's diverse project portfolio gives him strong talking points for behavioral rounds.","Technical interview, LeetCode, system design, behavioral, STAR method, coding challenge.")

add("what is the difference between processes and threads?","A process is an independent program execution with its own memory space. A thread is a unit of execution within a process, sharing the process's memory. Process: separate memory, communication via IPC (pipes, sockets, shared memory), crash doesn't affect other processes, heavier to create. Thread: shared memory (heap), communication via shared variables (needs synchronization), crash can take down entire process, lighter to create. Concurrency vs Parallelism: concurrency is managing multiple tasks (may be interleaved on one CPU), parallelism is truly running simultaneously on multiple CPUs. Thread safety: race conditions occur when threads access shared data simultaneously. Solutions: mutex/lock (mutual exclusion), semaphore (counting lock), read-write lock, atomic operations, lock-free data structures. In Python: GIL prevents true thread parallelism — use multiprocessing for CPU-bound tasks, threading for I/O-bound. In Java/Go: true multi-threading. Green threads/goroutines: lightweight user-space threads — Go's goroutines can run millions concurrently.","Process, thread, concurrency, parallelism, mutex, race condition, GIL, goroutine.")

add("what are environment variables and how to manage them?","Environment variables store configuration outside your code — database URLs, API keys, feature flags. Why: different values for dev/staging/production, secrets shouldn't be in code, easy to change without redeploy. .env files: store locally, NEVER commit to git (add to .gitignore). Libraries: python-dotenv (Python), dotenv (Node.js). In Docker: ENV in Dockerfile, --env-file flag, environment in docker-compose. In CI/CD: GitHub Actions secrets, GitLab CI variables. In production: AWS Parameter Store, AWS Secrets Manager, HashiCorp Vault, Doppler. 12-Factor App methodology: store config in environment variables. Best practices: use descriptive names (DATABASE_URL not DB), provide .env.example with dummy values (committed), validate env vars on startup (fail fast), group related vars with prefix (STRIPE_API_KEY, STRIPE_WEBHOOK_SECRET). Never log environment variables — they may contain secrets. Type safety: use a config module that validates and types env vars at startup.","Environment variables, .env, secrets management, Vault, 12-Factor App, configuration.")

add("what is Agile and Scrum in practice?","Agile is a software development philosophy — deliver working software iteratively with continuous feedback. The Agile Manifesto values: individuals over processes, working software over documentation, customer collaboration over contracts, responding to change over following a plan. Scrum is the most popular Agile framework. Roles: Product Owner (defines what to build, prioritizes backlog), Scrum Master (facilitates process, removes blockers), Development Team (builds the product). Events: Sprint (1-4 week iteration), Sprint Planning (decide what to build), Daily Standup (15 min — what I did, what I'll do, blockers), Sprint Review (demo to stakeholders), Sprint Retrospective (how to improve). Artifacts: Product Backlog (prioritized list of features), Sprint Backlog (work for current sprint), Increment (potentially shippable product). Story points: estimate complexity, not time. Velocity: average points completed per sprint. Kanban is an alternative: continuous flow instead of sprints, WIP limits. In practice: most teams do 'Scrumban' — a mix. Don't do 'Cargo Cult Agile' — adopt practices that help, drop those that don't.","Agile, Scrum, Sprint, Product Owner, Scrum Master, Kanban, velocity, retrospective.")

add("what is the importance of soft skills for developers?","Technical skills get you the interview, soft skills get you promoted. Key soft skills: 1) Communication — explain technical concepts to non-technical people, write clear documentation, articulate trade-offs in design decisions. 2) Collaboration — code review (give constructive feedback), pair programming, knowledge sharing. 3) Problem-solving — break complex problems into smaller parts, ask the right questions. 4) Time management — estimate accurately (add buffer), prioritize ruthlessly, learn to say no. 5) Empathy — understand user needs, consider teammates' perspectives in code reviews. 6) Adaptability — technology changes fast, willingness to learn is more valuable than current knowledge. 7) Mentoring — teaching others reinforces your own understanding. 8) Receiving feedback — don't take code review comments personally. Common mistake: developers who are brilliant but difficult to work with are net negative for teams. A good developer who communicates well is more valuable than a great developer who can't. Leadership: you don't need a title — take initiative, help others, drive improvements.","Soft skills, communication, collaboration, empathy, mentoring, feedback, leadership.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_en14.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} English entries (part 14).")
if __name__=="__main__":
    main()
