"""Extra EN training data - Part 19. Databases Deep, Security, Architecture Patterns, Interview Prep, Misc."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

add("what is database connection pooling?","Connection pooling maintains a pool of reusable database connections instead of creating new ones for each request. Creating a DB connection is expensive — TCP handshake, authentication, SSL negotiation. Without pooling: 100 requests = 100 new connections. With pooling: 100 requests share 10-20 connections from the pool. How it works: application requests a connection from the pool → pool provides an idle connection (or creates a new one if under max limit) → application uses it → returns it to the pool when done. Configuration: min connections (keep warm), max connections (prevent overload), idle timeout (close unused connections), max lifetime (prevent stale connections). Tools: PgBouncer (external pooler for PostgreSQL), HikariCP (Java, fastest), SQLAlchemy pool (Python), pg pool (Node.js). Common mistake: setting max connections too high — each connection uses ~10MB RAM on the database server. PostgreSQL default max_connections is 100. For high-scale apps, use PgBouncer in transaction mode.","Connection pooling, PgBouncer, HikariCP, database connections, PostgreSQL, performance.")

add("what is database replication?","Database replication copies data from one server (primary/master) to one or more servers (replicas/slaves). Types: 1) Synchronous — primary waits for replica confirmation before committing. Strong consistency but higher latency. 2) Asynchronous — primary commits immediately, replica catches up later. Fast but potential data loss if primary crashes. 3) Semi-synchronous — primary waits for at least one replica to acknowledge. Compromise. Use cases: read scaling (send read queries to replicas — 80% of traffic is reads), high availability (promote replica if primary fails), geographic distribution (replica in each region for lower latency), backups (replica for backup without impacting production). PostgreSQL: streaming replication with WAL shipping. MySQL: binary log replication. Replication lag: time between write on primary and it appearing on replica — can cause issues (user creates account, immediate read goes to replica, account not found yet). Solutions: read-your-own-writes consistency, critical reads from primary. Multi-master replication: multiple nodes accept writes — conflict resolution is complex (last-write-wins, CRDTs).","Database replication, primary-replica, synchronous, asynchronous, replication lag, WAL.")

add("what is database migration and how to handle it?","Database migrations are version-controlled changes to your database schema. Instead of manually running ALTER TABLE, you write migration files that can be applied and rolled back. Tools: Django migrations (Python, automatic), Alembic (SQLAlchemy), Knex.js (Node), Flyway (Java), Liquibase (enterprise). Best practices: 1) Never edit or delete a migration that's been applied to production. 2) Make migrations backward-compatible — add columns with defaults, don't rename or drop columns in the same deploy. 3) Test migrations on a production-copy database first. 4) Keep migrations small and focused. 5) Data migrations separate from schema migrations. Blue-green deployment migration strategy: add new column → deploy code that writes to both columns → backfill data → deploy code that reads from new column → drop old column. This is the expand-contract pattern. Dangerous operations: adding NOT NULL without default, dropping columns, renaming columns. Always have a rollback plan. Large table migrations (millions of rows) need special handling — pt-online-schema-change (MySQL), pg_repack (PostgreSQL).","Database migration, schema change, Alembic, Flyway, backward-compatible, expand-contract.")

add("what is XSS and how to prevent it?","Cross-Site Scripting (XSS) injects malicious JavaScript into web pages viewed by other users. Types: 1) Stored XSS — malicious script stored in database (comment, profile) and served to all visitors. Most dangerous. 2) Reflected XSS — script in URL parameter reflected in page response. Requires victim to click malicious link. 3) DOM-based XSS — client-side JavaScript processes untrusted data into the DOM. Prevention: 1) Output encoding — escape HTML entities before rendering user content. &lt; instead of <, &amp; instead of &. 2) Content Security Policy (CSP) header — restrict which scripts can execute. CSP: script-src 'self' blocks inline scripts. 3) Use frameworks that auto-escape — React auto-escapes JSX, Django auto-escapes templates. 4) Sanitize HTML input — if you must accept HTML, use DOMPurify (client) or bleach (Python). 5) HttpOnly cookies — prevent JavaScript access to session cookies. 6) Don't use innerHTML or dangerouslySetInnerHTML with user input. XSS can steal sessions, redirect users, deface pages, and capture keystrokes.","XSS, cross-site scripting, CSP, output encoding, DOMPurify, HttpOnly, sanitization.")

add("what is CSRF and how to prevent it?","Cross-Site Request Forgery tricks authenticated users into performing actions they didn't intend. Example: you're logged into your bank. You visit a malicious site with <img src='https://bank.com/transfer?to=attacker&amount=10000'>. Your browser sends the request with your bank cookies — transfer happens without your knowledge. Prevention: 1) CSRF tokens — server generates a random token, includes it in forms as hidden field and session. On submit, server verifies they match. Attacker can't know the token. 2) SameSite cookies — Set-Cookie: session=abc; SameSite=Strict (or Lax). Browser won't send cookie with cross-origin requests. 3) Check Origin/Referer headers — reject requests from unexpected origins. 4) Custom headers — AJAX requests can include X-CSRF-Token header. Simple form submissions from other sites can't add custom headers. 5) Re-authentication for sensitive actions — require password for transfers, email changes. Most frameworks handle this: Django includes CSRF middleware by default, Express has csurf, Spring has CSRF protection. SameSite=Lax is now the default in modern browsers — significantly reduces CSRF risk.","CSRF, cross-site request forgery, CSRF token, SameSite, cookie security, prevention.")

add("what is CORS and why does it exist?","CORS (Cross-Origin Resource Sharing) controls which domains can access your API from a browser. Same-Origin Policy: browsers block requests from one origin (domain:port) to another. This prevents malicious sites from calling your API with the user's cookies. CORS relaxes this: server sends Access-Control-Allow-Origin header specifying allowed origins. Preflight request: for non-simple requests (PUT, DELETE, custom headers), browser sends OPTIONS request first to check permissions. Server responds with allowed methods, headers, and origins. Headers: Access-Control-Allow-Origin (which domains), Access-Control-Allow-Methods (which HTTP methods), Access-Control-Allow-Headers (which custom headers), Access-Control-Allow-Credentials (allow cookies). Common mistake: Access-Control-Allow-Origin: * with credentials — not allowed, must specify exact origin. CORS only applies to browsers — server-to-server requests are not affected. Libraries: cors middleware (Express), django-cors-headers, Flask-CORS. Debug tip: CORS errors are always client-side — check the server's response headers, not the client code.","CORS, cross-origin, same-origin policy, preflight, Access-Control-Allow-Origin, cookies.")

add("what is the strangler fig pattern?","The Strangler Fig pattern is a migration strategy for gradually replacing a legacy system. Named after strangler figs — trees that grow around a host tree until the host dies. Instead of a risky big-bang rewrite, incrementally build the new system alongside the old one. Process: 1) Identify — pick a feature/module to migrate. 2) Build — implement it in the new system. 3) Route — redirect traffic for that feature from old to new (reverse proxy, API gateway). 4) Repeat — migrate feature by feature. 5) Eventually — old system handles no traffic, decommission it. Benefits: lower risk (if new feature fails, route back to old), incremental delivery (business value throughout migration), no big-bang cutover, old and new coexist. Implementation: use an API gateway or reverse proxy (Nginx, Kong) to route requests. Path-based routing: /api/v2/users → new service, /api/v1/orders → old system. Monitor both systems during transition. Companies like Amazon, Netflix, and LinkedIn have used this pattern successfully for major system migrations.","Strangler fig pattern, legacy migration, incremental, reverse proxy, API gateway, rewrite.")

add("what is the saga pattern for distributed transactions?","The Saga pattern manages distributed transactions across multiple microservices without a traditional 2PC (two-phase commit). A saga is a sequence of local transactions — each service completes its local transaction and publishes an event to trigger the next step. If a step fails, compensating transactions undo previous steps. Two types: 1) Choreography — each service listens for events and decides what to do. Decentralized but can become complex with many services. 2) Orchestration — a central orchestrator coordinates the saga steps. Clearer flow but single point of control. Example (order saga): Order Service creates order → Payment Service charges card → Inventory Service reserves stock → Shipping Service creates shipment. If Inventory fails: compensating transactions — refund payment, cancel order. Challenges: compensating transactions must be idempotent, handling concurrent sagas, debugging across services (distributed tracing essential). Frameworks: Temporal (workflow orchestration), Axon Framework (Java), MassTransit (C#). The saga pattern trades immediate consistency for eventual consistency — but it's the only practical option for distributed microservice transactions.","Saga pattern, distributed transactions, choreography, orchestration, compensating, eventual consistency.")

add("what is event sourcing?","Event sourcing stores all changes as a sequence of events rather than just current state. Instead of UPDATE account SET balance=90, you store Event: {type: 'MoneyWithdrawn', amount: 10, timestamp: '...'}. Current state is derived by replaying all events. Benefits: complete audit trail (every change recorded), temporal queries (what was the state at any point in time?), debugging (replay events to reproduce bugs), event-driven integration (other services react to events). Challenges: event store grows forever (use snapshots for performance), eventual consistency, schema evolution (events are immutable — how to handle format changes?), steep learning curve. Implementation: event store (EventStoreDB, or PostgreSQL with events table), projections (materialize current state from events for queries), snapshots (periodically save current state to avoid replaying all events). When to use: financial systems (audit trail critical), complex domains where understanding history matters, systems requiring undo/replay. When not to: simple CRUD applications, when eventual consistency is unacceptable. Often combined with CQRS — separate read and write models.","Event sourcing, events, audit trail, replay, CQRS, snapshot, projection, EventStoreDB.")

add("what is the circuit breaker pattern?","The circuit breaker prevents cascading failures in distributed systems — like an electrical circuit breaker. States: 1) Closed (normal) — requests pass through. If failure rate exceeds threshold, switch to Open. 2) Open — all requests immediately fail (fast fail) without calling the downstream service. After timeout, switch to Half-Open. 3) Half-Open — allow a limited number of test requests. If they succeed, switch to Closed. If they fail, back to Open. Why: without a circuit breaker, a slow/failing downstream service causes: thread exhaustion (all threads waiting for timeout), cascading failures (caller's callers also fail), resource waste. With circuit breaker: fail fast, give the downstream service time to recover, degrade gracefully. Implementation: Resilience4j (Java), Polly (.NET), opossum (Node.js), or custom. Configuration: failure rate threshold (50%), slow call threshold, wait duration in open state, permitted calls in half-open. Often combined with: retry (with exponential backoff), timeout, fallback (return cached/default response), bulkhead (isolate failures). Netflix Hystrix popularized this pattern (now deprecated, use Resilience4j).","Circuit breaker, cascading failure, Resilience4j, Hystrix, fallback, distributed systems.")

add("how do you prepare for behavioral interviews?","Behavioral interviews assess soft skills, teamwork, and problem-solving through past experiences. STAR method: Situation (context), Task (your responsibility), Action (what YOU did — not the team), Result (outcome, ideally with metrics). Prepare 6-8 stories covering: 1) Challenging technical problem you solved — shows problem-solving. 2) Disagreement with a teammate — shows communication and conflict resolution. 3) Project that failed — shows learning from failure and accountability. 4) Time you had to learn quickly — shows adaptability. 5) Leading or mentoring — shows leadership potential. 6) Working under pressure/tight deadline — shows composure. Common questions: 'Tell me about a time you disagreed with your manager,' 'Describe a project you're most proud of,' 'Tell me about a mistake you made.' Tips: be specific (names, dates, technologies), focus on YOUR actions, quantify results ('reduced load time by 40%'), be honest about failures but emphasize lessons learned. Practice out loud — stories sound different spoken vs in your head. Amazon's Leadership Principles, Google's Googleyness — research the company's values and align your stories.","Behavioral interview, STAR method, soft skills, leadership, conflict resolution, preparation.")

add("what is the difference between SQL window functions?","Window functions perform calculations across rows related to the current row without collapsing the result set. Syntax: function() OVER (PARTITION BY col ORDER BY col ROWS/RANGE ...). Key functions: ROW_NUMBER() — sequential number within partition (1,2,3...). No ties. RANK() — same rank for ties, gaps after (1,1,3). DENSE_RANK() — same rank for ties, no gaps (1,1,2). LEAD(col, n) — value from n rows ahead. LAG(col, n) — value from n rows behind. Great for comparing with previous/next row. SUM() OVER — running total. AVG() OVER — moving average. FIRST_VALUE(), LAST_VALUE() — first/last value in window. NTILE(n) — divide rows into n equal groups. Use cases: top N per group (ROW_NUMBER with PARTITION BY), running totals, year-over-year comparison (LAG), percentile calculation, moving averages. Frame clause: ROWS BETWEEN 2 PRECEDING AND CURRENT ROW — 3-row moving average. Window functions are more readable and often more efficient than self-joins or subqueries for the same result.","SQL window functions, ROW_NUMBER, RANK, LEAD, LAG, PARTITION BY, running total.")

add("what is API rate limiting strategies?","Rate limiting protects APIs from abuse and ensures fair usage. Strategies: 1) Per-user — each authenticated user gets N requests per time window. Fair but requires authentication. 2) Per-IP — limit by IP address. Simple but problematic with NAT (many users behind one IP) and proxies. 3) Per-API-key — each key has its own limit. Good for third-party API access. 4) Tiered — different limits for different subscription levels (free: 100/day, paid: 10000/day). Headers to include: X-RateLimit-Limit (max requests), X-RateLimit-Remaining (remaining), X-RateLimit-Reset (when limit resets), Retry-After (when to retry after 429). Implementation: Redis is ideal — INCR + EXPIRE for sliding window, sorted sets for sliding window log. API Gateway level: Kong, AWS API Gateway, Cloudflare handle rate limiting out of the box. Graceful degradation: instead of hard 429, consider returning cached/simplified responses under load. Cost-based limiting: expensive operations (search, AI inference) cost more 'tokens' than simple reads. Always communicate limits clearly in API documentation.","API rate limiting, per-user, per-IP, Redis, 429, headers, API Gateway, tiered, throttling.")

add("what is the difference between REST and RPC APIs?","REST (Representational State Transfer): resource-oriented — URLs represent resources (/users/123), HTTP methods represent operations (GET, POST, PUT, DELETE). Stateless, cacheable, uniform interface. Best for: CRUD operations, public APIs, web services. JSON typically. RPC (Remote Procedure Call): action-oriented — call functions on remote servers. URL represents the action (/getUser, /createOrder). Less constrained, can use any transport. gRPC: Google's modern RPC using Protocol Buffers and HTTP/2. Binary serialization, code generation, streaming, strongly typed. Best for internal microservice communication. JSON-RPC: simple, lightweight RPC over HTTP with JSON. tRPC: TypeScript RPC — end-to-end type safety between client and server, no code generation needed. Popular in TypeScript monorepos. Comparison: REST is the default for public APIs (familiar, cacheable, tools). gRPC for internal high-performance communication. tRPC for TypeScript full-stack apps. GraphQL is another alternative — query language rather than fixed endpoints. Most companies use REST externally and gRPC or message queues internally.","REST, RPC, gRPC, JSON-RPC, tRPC, Protocol Buffers, API design, resource vs action.")

add("what is the role of an API Gateway?","An API Gateway is a single entry point for all client requests in a microservice architecture. Functions: 1) Request routing — route /users to user service, /orders to order service. 2) Authentication/Authorization — verify JWT tokens, API keys centrally. 3) Rate limiting — enforce request limits per client/API key. 4) Load balancing — distribute requests across service instances. 5) Request/response transformation — modify headers, aggregate responses from multiple services. 6) Caching — cache frequently requested data. 7) SSL termination — handle HTTPS at the gateway. 8) Monitoring/logging — centralized request logging and metrics. 9) Circuit breaking — protect against failing downstream services. Popular options: Kong (open source, plugin ecosystem), AWS API Gateway (serverless, managed), Nginx (reverse proxy + gateway), Traefik (container-native), Envoy (service mesh proxy). BFF pattern (Backend for Frontend): separate API gateways for web, mobile, third-party — each optimized for its client. Don't put business logic in the gateway — it should only handle cross-cutting concerns.","API Gateway, routing, authentication, rate limiting, Kong, AWS API Gateway, BFF, Envoy.")

add("what is technical writing for developers?","Technical writing is a crucial skill most developers undervalue. Types: README files, API documentation, architecture decision records (ADRs), runbooks, blog posts, code comments. README essentials: project title + one-line description, installation steps, usage examples, configuration options, contributing guidelines. Write for your audience — a README for developers is different from one for end users. API docs: use OpenAPI/Swagger for REST APIs, include request/response examples, document error codes, provide SDKs and code snippets. Architecture Decision Records: short documents recording why you made architectural choices — invaluable for future developers. Format: title, status, context, decision, consequences. Writing tips: use active voice ('the function returns' not 'the value is returned'), be concise (every word should earn its place), use examples (show, don't just tell), structure with headers and lists, keep sentences short. Tools: Notion, Confluence, Docusaurus (docs website), Mintlify (API docs). Good documentation reduces onboarding time, support tickets, and makes open source projects more adoptable.","Technical writing, README, API documentation, ADR, Docusaurus, OpenAPI, developer docs.")

add("what is the difference between monorepo and polyrepo?","Monorepo: all projects and services in one repository. Polyrepo: each project/service in its own repository. Monorepo benefits: code sharing is easy (shared libraries, types), atomic changes across projects (single PR updates API + client), consistent tooling and CI/CD, easier dependency management, discoverability (all code in one place). Monorepo challenges: repository gets large (git operations slow down), CI/CD complexity (need to detect which parts changed), requires specialized tooling, access control is harder (everyone can see everything). Monorepo tools: Turborepo (fast, caching), Nx (advanced dependency graph, affected commands), Bazel (Google's build system), Lerna (npm packages). Polyrepo benefits: clear ownership, independent CI/CD, technology flexibility, simpler git history, fine-grained access control. Polyrepo challenges: code duplication, dependency hell, cross-repo changes need multiple PRs, tooling inconsistency. Companies: Google, Meta, Microsoft use monorepos. Netflix, Amazon, Spotify use polyrepos (mostly). Choose based on team size and coupling between services. Small team with shared code → monorepo. Large org with independent teams → polyrepo.","Monorepo, polyrepo, Turborepo, Nx, code sharing, repository strategy, CI/CD.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_en19.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} English entries (part 19).")
if __name__=="__main__":
    main()
