"""Ek TR training data - Bölüm 4. Görkem'in projeleri, kariyer, üniversite, yapay zeka derinlemesine."""
import json, random
E = []
def add(q, a, t):
    E.append([{"content":q,"images":None,"role":"user","thinking":None,"tool_calls":None},{"content":a,"images":None,"role":"assistant","thinking":t,"tool_calls":None}])

# Görkem projeleri detaylı
add("Görkem'in yolo-custom-detector projesi hakkında bilgi ver","yolo-custom-detector, Görkem'in YOLO (You Only Look Once) modelini custom veri setiyle eğittiği bir proje. Custom object detection demek kendi belirlediğin nesneleri tanıyan bir model eğitmek. Mesela sadece belirli bir ürünü, bir hayvanı veya bir işareti tanımak istiyorsun — YOLO'yu kendi verinle fine-tune ediyorsun. LabelImg gibi araçlarla veri etiketlemesi yapılıyor, sonra model eğitiliyor. YOLOv5 veya YOLOv8 kullanılmış olabilir. Bu proje Görkem'in computer vision alanındaki yetkinliğini gösteriyor.","YOLO projesi detayı, custom detection, labeling, fine-tuning.")
add("facelock projesi ne yapıyor?","facelock, Görkem'in yüz tanıma teknolojisi kullanarak kimlik doğrulama yapan projesi. Kameradan yüzü algılayıp, önceden kaydedilmiş yüzlerle karşılaştırarak kişiyi tanıyor. OpenCV ve dlib veya face_recognition kütüphanesi kullanılmış olabilir. Face detection (yüz bulma) ve face recognition (yüz tanıma) iki farklı adım — ilk adımda yüzün nerede olduğu bulunuyor, ikinci adımda kimin yüzü olduğu belirleniyor. Güvenlik sistemlerinde, akıllı kilit sistemlerinde kullanılabilir. Biyometrik doğrulama geleceğin güvenlik teknolojisi.","facelock projesi, yüz tanıma, OpenCV, biyometrik.")
add("wiki2bpe ne işe yarıyor?","wiki2bpe, Görkem'in Wikipedia verisini BPE (Byte Pair Encoding) tokenizer ile işlediği proje. BPE, NLP'de en yaygın kullanılan tokenization yöntemlerinden biri — GPT modelleri de BPE kullanıyor. Wikipedia'dan metin verisi çekip kendi tokenizer'ını eğitiyorsun. Bu tokenizer daha sonra dil modeli eğitiminde kullanılabilir. Hugging Face Hub'a publish edilmiş olabilir. Tokenization NLP'nin temel taşı — metni modelin anlayabileceği parçalara ayırıyorsun. Bu proje Görkem'in NLP derinliğini gösteriyor.","wiki2bpe, BPE tokenization, Wikipedia, NLP temelleri.")
add("turkish-english-nmt projesi hakkında bilgi ver","turkish-english-nmt, Türkçe-İngilizce makine çevirisi (Neural Machine Translation) projesi. Seq2seq (sequence-to-sequence) model veya transformer tabanlı bir çeviri modeli eğitilmiş. Encoder metni kaynak dilde anlıyor, decoder hedef dilde üretiyor. Attention mekanizması hangi kelimelere odaklanılacağını öğreniyor. BLEU score ile çeviri kalitesi ölçülüyor. Bu proje NLP'nin en zorlu görevlerinden biri çünkü iki dil arasında yapısal farklar var. Google Translate da benzer ama çok daha büyük ölçekte çalışıyor.","NMT projesi, seq2seq, transformer, attention, BLEU score.")
add("email-phishing-detection projesi ne yapıyor?","email-phishing-detection, e-posta içeriğini analiz ederek phishing (oltalama) saldırılarını tespit eden bir proje. Makine öğrenmesi ile e-postaların metin içeriği, gönderen bilgileri, URL'ler inceleniyor ve şüpheli olanlar işaretleniyor. NLP teknikleri — TF-IDF veya transformer tabanlı embedding'ler kullanılıyor olabilir. Bu siber güvenlik ve AI'ın kesişim noktası. Phishing saldırıları internet güvenliğinin en büyük tehditlerinden biri ve AI tabanlı tespit sistemleri giderek önem kazanıyor. Görkem'in hem AI hem güvenlik ilgisini gösteriyor.","Phishing detection, NLP, TF-IDF, siber güvenlik, AI.")
add("face-detection-pipeline projesi ne yapıyor?","face-detection-pipeline, yüz algılama için uçtan uca bir pipeline (iş akışı) oluşturan proje. Pipeline demek ham görüntüden sonuca kadar tüm adımları otomatize etmek: görüntü ön işleme, yüz algılama, yüz hizalama, özellik çıkarma, ve sonuç üretme. OpenCV, dlib, MTCNN gibi araçlar kullanılmış olabilir. Pipeline mimarisi önemli çünkü gerçek dünya uygulamalarında sadece model yetmez — veriyi modele hazırlamak ve sonucu işlemek de gerekiyor. Modüler bir pipeline bakımı ve geliştirmesi kolay kod demek.","Face detection pipeline, ön işleme, modüler mimari, OpenCV.")
add("writing-analyzer projesi ne yapıyor?","writing-analyzer, metin analizi yapan bir NLP projesi. Yazı stilini, karmaşıklığını, duygu tonunu veya diğer dilsel özellikleri analiz edebilir. Metin istatistikleri — kelime sayısı, cümle uzunluğu, okunabilirlik skoru gibi metrikler çıkartıyor olabilir. NLP kütüphaneleri — NLTK, spaCy veya transformers kullanılmış olabilir. Bu tür araçlar eğitimde, içerik üretiminde, ve akademik yazarlıkta kullanılıyor. Görkem'in NLP becerilerini pratik bir uygulamada gösteriyor.","Writing analyzer, metin analizi, NLP, okunabilirlik, stil analizi.")
add("gorkem-os projesi ne?","gorkem-os, Görkem'in kendi işletim sistemi çekirdeğini yazdığı proje. İşletim sistemi kavramlarını gerçekten anlamak için en iyi yol kendi OS'ini yazmak. Boot sürecinden başlayarak bellek yönetimi, süreç yönetimi, dosya sistemi gibi kavramları implemente ediyorsun. C ve Assembly dillerinde yazılıyor genelde. Bu proje Görkem'in sadece üst seviye AI/ML değil, aynı zamanda düşük seviye sistem programlama bilgisini de gösteriyor. Bilgisayar mühendisliğinin temellerini anlıyor demek. Bu tür projeler kariyer açısından çok değerli.","gorkem-os, işletim sistemi, kernel, C, Assembly, sistem programlama.")
add("build-your-target-body projesi ne?","build-your-target-body, fitness ve sağlık alanında bir uygulama projesi. Kullanıcının hedef vücuduna ulaşması için egzersiz ve beslenme önerileri sunuyor olabilir. Yazılımın sadece teknoloji alanında değil, günlük hayata dokunabileceğini gösteren bir proje. Full-stack olabilir — frontend arayüz, backend API, belki bir veritabanı. Sağlık teknolojisi (health-tech) hızla büyüyen bir sektör. Görkem farklı alanlardaki problemlere teknoloji ile çözüm üretmeyi seviyor.","build-your-target-body, fitness uygulaması, health-tech.")
add("re-mind projesi ne?","re-mind, hatırlatıcı veya zihinsel sağlık alanında bir uygulama olabilir. İsim 're-mind' olarak düşünülürse tekrar hatırlamak, akılda tutmak gibi bir konsept. Spaced repetition (aralıklı tekrar) tabanlı bir öğrenme aracı olabilir veya meditasyon ve mindfulness uygulaması. Her iki durumda da kullanıcıların günlük yaşamına dokunuyor. Görkem sadece teknik projeler değil, insanların hayatını iyileştiren ürünler de geliştiriyor.","re-mind projesi, hatırlatıcı, zihinsel sağlık, spaced repetition.")
add("depression-phq9-analysis projesi ne?","depression-phq9-analysis, PHQ-9 (Patient Health Questionnaire-9) formunu kullanarak depresyon analizi yapan bir proje. PHQ-9 klinik ortamlarda kullanılan standart bir depresyon tarama aracı. Bu proje muhtemelen form yanıtlarını analiz edip depresyon seviyesini değerlendiriyor. Health-tech ve AI'ın birleşimi. Ruh sağlığı alanında teknolojinin kullanılması çok önemli bir konu. Görkem'in sağlık teknolojisine olan ilgisini ve toplumsal sorunlara çözüm üretme motivasyonunu gösteriyor.","PHQ-9, depresyon analizi, health-tech, ruh sağlığı.")
add("sorting-visualizer projesi ne?","sorting-visualizer, sıralama algoritmalarını görselleştiren bir uygulama. Bubble sort, quick sort, merge sort, insertion sort gibi algoritmaların nasıl çalıştığını adım adım animasyonla gösteriyor. Eğitim amaçlı harika bir araç — algoritmaları görsel olarak anlamak çok daha etkili. JavaScript ve canvas veya React ile yapılmış olabilir. Bu tür projeler hem programlama yeteneğini hem de eğitim materyali oluşturma becerisini gösteriyor. Algoritmalar CS müfredatının temel taşı.","Sorting visualizer, sıralama algoritmaları, görselleştirme, eğitim aracı.")
add("study-tracker projesi ne?","study-tracker, çalışma süresini takip eden bir uygulama. Pomodoro tekniği veya benzeri yöntemlerle çalışma zamanını yönetiyor olabilir. Hangi derse ne kadar çalıştığını kaydetme, istatistik görüntüleme, hedef koyma gibi özellikler içerebilir. YKS hazırlanan öğrenciler veya üniversite öğrencileri için çok faydalı. Görkem'in hem eğitime hem teknolojiye olan ilgisinin birleşimi. Kendi kullandığı bir araç da olabilir.","Study tracker, çalışma takibi, Pomodoro, eğitim, verimlilik.")
add("miniature-transformers-from-scratch projesi hakkında bilgi ver","miniature-transformers-from-scratch, transformer mimarisini sıfırdan implemente eden bir proje. 'Attention Is All You Need' makalesindeki mimariyi Python ve PyTorch ile kodlamak. Multi-head attention, positional encoding, feed-forward layers, layer normalization — tüm bileşenler sıfırdan yazılıyor. Bu projeyi yapmak transformer'ları gerçekten anlamak demek. ChatGPT, BERT, T5 hepsi transformer tabanlı — bu mimariyi anlamak modern AI'ı anlamak demek. Görkem'in teorik bilgiyi pratiğe dökmesinin en güzel örneği.","Transformer from scratch, attention, PyTorch, mimari, derinlemesine anlama.")
add("synonym-master projesi ne?","synonym-master, eş anlamlı kelime bulma veya öğretme amaçlı bir proje. NLP kullanarak kelimelerin eş anlamlılarını buluyor olabilir — WordNet, word embeddings (Word2Vec, GloVe) veya transformer tabanlı modeller kullanılmış olabilir. Dil öğrenme aracı olarak da düşünülebilir. Kelime haznesini geliştirmek isteyenler için faydalı. NLP'nin pratik bir uygulaması.","synonym-master, eş anlamlı, NLP, WordNet, word embeddings.")
add("python-llm-agent projesi ne?","python-llm-agent, büyük dil modellerini (LLM) kullanarak otonom bir ajan oluşturan proje. Ajan, belirli görevleri yerine getirmek için LLM'i araç olarak kullanıyor — web araması, dosya işleme, kod çalıştırma gibi. LangChain veya benzeri framework'ler kullanılmış olabilir. Bu proje AI agent'ların geleceğini temsil ediyor — sadece soru cevap değil, gerçek görevleri otonom olarak yerine getiren sistemler. Çok güncel bir konu.","LLM agent, otonom ajan, LangChain, araç kullanımı.")

# Kariyer ve iş dünyası
add("yazılım mühendisliğinde ilk iş deneyimi nasıl kazanılır?","İlk deneyimi kazanmak en zor kısım ama birçok yol var. Staj başvuruları — LinkedIn, Kariyer.net, şirketlerin kariyer sayfaları. Open-source projelere katkı — GitHub'da issue'lara çözüm yaz, PR gönder. Freelance projeler — Upwork, Fiverr'da küçük projeler al. Kendi projelerin — bir portfolyo sitesi oluştur, GitHub'ını aktif tut. Hackathon'lara katıl — Görkem BTK, Foodathon gibi hackathon'larda yer aldı ve bu deneyimler CV'de çok değerli. Networking — meetup'lara git, LinkedIn'de insanlarla bağlantı kur. İlk adım en zoru ama bir kez başladın mı ivme kazanırsın.","İlk iş deneyimi, staj, open-source, freelance, hackathon, networking.")
add("yazılım mülakatlarına nasıl hazırlanılır?","Yazılım mülakatları genelde 3 aşamada olur: teknik mülakat, davranışsal mülakat, ve sistem tasarımı. Teknik mülakat için LeetCode, HackerRank'te algoritma soruları çöz — en az 100-150 soru. Veri yapıları (array, linked list, tree, graph, hash map) ve algoritmaları (sorting, searching, dynamic programming, BFS/DFS) iyi bil. Davranışsal sorulara STAR yöntemiyle hazırlan (Situation, Task, Action, Result). Sistem tasarımı için 'System Design Interview' kitabını oku. Görkem'in hackathon deneyimleri davranışsal sorularda harika örnekler oluşturur.","Mülakat hazırlığı, LeetCode, veri yapıları, algoritmalar, STAR, sistem tasarımı.")
add("junior developer olarak nelere dikkat etmeliyim?","Junior olarak en önemli şey: öğrenmeye açık ol ve ego yapma. Kod review'larda gelen yorumları kişisel alma — bu senin gelişimin için. Git ve versiyon kontrolünü iyi öğren. Clean code prensiplerini takip et. Sormaktan çekinme — aptalca soru yoktur, sormadan yanlış yapmak daha kötü. Dökümantasyon yaz — hem kendin hem takım için. Test yaz — 'test yazmaya zamanım yok' en tehlikeli cümle. Meeting'lerde not al. Mentör bul. Ve en önemlisi: her gün biraz öğren, tutarlılık yeteneğin üstündedir. Görkem de öğrenci olarak sürekli öğreniyor.","Junior developer tavsiyeleri, öğrenme, clean code, test, mentör.")
add("remote çalışma hakkında ne düşünüyorsun?","Remote çalışma pandemiyle birlikte normalleşti ve artık birçok yazılım şirketi remote veya hybrid model sunuyor. Avantajları: esneklik, yolda vakit kaybetmemek, global şirketlerde çalışabilmek, kendi çalışma ortamını yaratmak. Zorlukları: disiplin gerektirir, sosyal izolasyon, ev ile iş arası sınır belirsizleşir. İyi remote çalışma için: düzenli program oluştur, çalışma alanını ayır, düzenli mola ver, takımla iletişimi güçlü tut. Async iletişim araçları (Slack, Notion) önemli. Türkiye'den global şirketlere remote çalışmak maaş açısından avantajlı olabiliyor.","Remote çalışma, avantaj/dezavantaj, disiplin, async iletişim.")
add("startup mı yoksa büyük şirket mi tercih etmeliyim?","Her ikisinin de avantajları var, kariyer aşamana göre karar ver. Startup: çok şey öğrenirsin, sorumluluk alanın geniş, büyümeyi yakından görürsün, ama stabilite düşük, maaş düşük olabilir, iş yükü fazla. Büyük şirket (FAANG vb.): yapılandırılmış eğitim, mentorluk, iyi maaş, iş güvencesi, ama bürokrasi, dar sorumluluk alanı, impact hissetmek zor. Junior iken ikisi de iyi — startup'ta hızlı öğrenirsin, büyük şirkette temelleri düzgün öğrenirsin. Görkem startup tarafında çalışmayı seviyor çünkü bir fikri sıfırdan ürüne dönüştürmek motive edici.","Startup vs büyük şirket, avantaj/dezavantaj, kariyer kararı.")
add("freelance yazılımcılık nasıl yapılır?","Freelance yazılımcılık özgürlük veriyor ama disiplin gerektiriyor. Platformlar: Upwork, Freelancer, Toptal (senior için), Fiverr. Portfolio çok önemli — önceki çalışmalarını göster. İlk müşterilerin için fiyatı düşük tutup iyi referanslar topla, sonra artır. Uzmanlık alanı belirle — 'her şeyi yaparım' yerine 'React frontend' veya 'Python backend' gibi. Sözleşme yap — scope, deadline, ödeme koşulları net olsun. Zaman yönetimi kritik. Vergi ve fatura işlerini öğren. İlk yıl zorlu olabilir ama iyi bir ağ kurduğunda sürekli iş bulursun.","Freelance, platformlar, portfolio, uzmanlık, sözleşme, vergi.")

# Üniversite ve eğitim
add("Yeditepe Üniversitesi bilgisayar mühendisliği nasıl?","Yeditepe Üniversitesi İstanbul'da özel bir üniversite ve bilgisayar mühendisliği bölümü güçlü bir eğitim veriyor. İngilizce eğitim veriliyor, bu uluslararası kariyer için avantaj. Kampüs İstanbul'un Anadolu yakasında. Vakıf üniversitesi olmanın avantajı daha küçük sınıflar ve hocalarla yakın iletişim. Lab imkanları ve proje odaklı eğitim önemli. Erasmus ve staj imkanları var. Görkem burada okuyor ve aldığı eğitimi kendi projeleriyle destekliyor — üniversite teorik temel veriyor, projelerde pratiğe dönüştürüyorsun.","Yeditepe, bilgisayar mühendisliği, İngilizce eğitim, kampüs, kariyer.")
add("üniversitede hangi derslere odaklanmalıyım?","Bilgisayar mühendisliğinde bazı dersler kariyerin için kritik. Veri yapıları ve algoritmalar — mülakatların temeli. İşletim sistemleri — bilgisayarın nasıl çalıştığını anlarsın. Veritabanı sistemleri — her yazılımda var. Bilgisayar ağları — web'in nasıl çalıştığını öğrenirsin. Yapay zeka ve makine öğrenmesi — geleceğin alanı. Matematik dersleri (lineer cebir, olasılık) — AI için çok önemli. Yazılım mühendisliği — proje yönetimi, tasarım kalıpları. Seçmeli derslerde ilgi alanına yönel. Ama sadece derslere güvenme — Görkem gibi yan projeler yap, pratiği artır.","Üniversite dersleri, veri yapıları, algoritmalar, AI, matematik, proje.")
add("erasmus'a gitmeli miyim?","Erasmus muhtemelen üniversite hayatının en değerli deneyimlerinden biri olabilir. Sadece akademik değil — farklı kültür, farklı bakış açısı, bağımsızlık, uluslararası ağ. Teknik açıdan farklı üniversitelerin farklı güçlü yanlarını görürsün. İngilizce veya başka bir dilde eğitim almak dil becerisini geliştirir. CV'de uluslararası deneyim çok değerli. Hazırlık: GPA'ni yüksek tut, dil sınavını (TOEFL/IELTS) hazırlan, başvuruları takip et. Maddi yardım ve burs imkanları var. Gidebileceksen kesinlikle git.","Erasmus, uluslararası deneyim, kültür, dil, CV, başvuru.")
add("CS öğrencisi olarak yaz tatilinde ne yapmalıyım?","Yaz tatili kariyer için altın dönem. En ideali staj yapmak — gerçek iş deneyimi edinirsin. Staj bulamadıysan: kendi projeni geliştir, bir online kurs bitir (Coursera, Udemy, CS50), bir hackathon'a katıl, open-source projeye katkıda bulun, bir teknoloji kitabı oku, algoritma soruları çöz. Bir portfolio sitesi yap ve projelerini oraya koy. Blog yazmaya başla — öğrendiklerini anlatmak hem seni hem başkalarını geliştiriyor. Tamamen boş geçirme ama burnout olmamak için dinlenmeyi de ihmal etme.","Yaz tatili, staj, proje, kurs, hackathon, portfolio, blog.")

# AI derinlemesine
add("attention mekanizması nasıl çalışır?","Attention mekanizması, bir modelin girdi dizisinin hangi kısımlarına odaklanması gerektiğini öğrenmesini sağlar. Üç temel bileşen var: Query (ne arıyorsun), Key (neye bakıyorsun), Value (ne döndürüyorsun). Attention score = softmax(Q * K^T / sqrt(d_k)) * V formülüyle hesaplanır. Multi-head attention birden fazla attention hesaplamasını paralel yaparak farklı ilişkileri yakalar. Self-attention bir cümledeki kelimelerin birbirleriyle ilişkisini öğrenir. Transformer mimarisinin kalbi attention — 'Attention Is All You Need' makalesi bunun için bu ismi aldı. Görkem'in miniature-transformers projesi bunu sıfırdan implemente ediyor.","Attention mekanizması, Q-K-V, multi-head, self-attention, transformer.")
add("transfer learning ne demek?","Transfer learning, bir görevde eğitilmiş modelin bilgisini başka bir göreve aktarma tekniği. Mesela ImageNet'te eğitilmiş ResNet'i alıp kendi görüntü sınıflandırma görevinde kullanırsın. Büyük veri setinde öğrenilen genel özellikler (kenar algılama, şekil tanıma) yeni göreve transfer olur. Fine-tuning: son katmanları yeni veri ile yeniden eğitirsin. Feature extraction: modeli sabit tutar sadece son katmanı değiştirirsin. BERT, GPT, ResNet hep transfer learning ile kullanılıyor. Az veriniz varsa transfer learning şart — sıfırdan eğitmek yerine hazır bilgiyi kullanırsın.","Transfer learning, fine-tuning, feature extraction, BERT, ResNet.")
add("GAN (Generative Adversarial Network) nasıl çalışır?","GAN iki sinir ağından oluşur: Generator (üretici) ve Discriminator (ayırt edici). Generator sahte veri üretmeye çalışır, Discriminator gerçek ile sahteyi ayırt etmeye çalışır. İkisi birbirini geliştirerek öğrenir — Generator daha gerçekçi üretir, Discriminator daha iyi ayırt eder. Sonuçta Generator o kadar iyi olur ki Discriminator ayırt edemez. Uygulamaları: görüntü üretimi (StyleGAN ile gerçekçi yüzler), resim tamamlama, stil transferi, veri augmentation. Eğitimi zor çünkü iki ağın dengesi bozulabilir (mode collapse). Ian Goodfellow 2014'te tanıttı.","GAN, Generator, Discriminator, eğitim, uygulamalar, mode collapse.")
add("reinforcement learning ne demek?","Reinforcement Learning (Pekiştirmeli Öğrenme), bir ajanın çevreyle etkileşerek ödül ve ceza yoluyla öğrenmesi. Supervised learning'den farklı — etiketli veri yok, ajan deneyerek öğreniyor. Temel kavramlar: state (durum), action (eylem), reward (ödül), policy (strateji). Q-learning ve Deep Q-Network (DQN) temel algoritmalar. AlphaGo, OpenAI Five (Dota 2), ChatGPT'nin RLHF (Reinforcement Learning from Human Feedback) aşaması hep RL kullanıyor. Otonom araçlar, robotik, oyun AI'ları için kullanılıyor. Zorlu ama çok güçlü bir yöntem.","Reinforcement learning, ajan, ödül, Q-learning, AlphaGo, RLHF.")
add("RAG (Retrieval-Augmented Generation) ne demek?","RAG, büyük dil modellerinin (LLM) kendi bilgi havuzlarının dışındaki verilere erişmesini sağlayan bir teknik. LLM'in eğitim verisinde olmayan güncel veya özel bilgileri bir veritabanından çeker ve yanıtına dahil eder. Adımlar: kullanıcı sorusu gelir, ilgili dökümanlar vektör veritabanından (Pinecone, Chroma, FAISS) çekilir, bu dökümanlar prompt'a eklenir, LLM bu bilgiyle yanıt üretir. Hallucination'ı azaltır çünkü model gerçek verilere dayanarak yanıt veriyor. Chatbot'lar, müşteri destek sistemleri, bilgi yönetimi için çok kullanılıyor. Çok güncel bir konu.","RAG, LLM, vektör veritabanı, hallucination, chatbot.")
add("embedding ne demek?","Embedding, metni veya diğer verileri sayısal vektörlere dönüştürme. Kelimeler, cümleler veya dökümanlar sabit boyutlu vektörler olarak temsil edilir. Benzer anlamlı kelimeler yakın vektörlerde olur — 'kral' ve 'kraliçe' vektörleri birbirine yakın. Word2Vec, GloVe kelime embedding'leri. Sentence-BERT cümle embedding'leri. OpenAI'ın text-embedding-ada-002 modeli popüler. Embedding'ler arama, öneri sistemleri, benzerlik hesaplama, ve RAG'da vektör veritabanına kaydetme için kullanılıyor. Modern NLP'nin temel kavramı.","Embedding, vektör, Word2Vec, benzerlik, NLP.")
add("fine-tuning ile prompt engineering arasındaki fark ne?","İkisi de LLM'i belirli bir göreve uyarlamak için kullanılır ama çok farklı yaklaşımlar. Prompt engineering: modeli değiştirmezsin, sadece iyi yazılmış talimatlarla yönlendirirsin. Hızlı, ucuz, ama sınırlı. Few-shot, chain-of-thought prompting teknikleri var. Fine-tuning: modelin ağırlıklarını kendi verinle güncellersin. Daha güçlü, kalıcı ama veri ve hesaplama gerektirir. LoRA gibi verimli fine-tuning yöntemleri var. Genelde önce prompt engineering dene, yetmezse fine-tuning yap. Bu projede de fine-tuning yapıyoruz — kendi verilerimizle modeli eğitiyoruz.","Fine-tuning vs prompt engineering, fark, LoRA, ne zaman hangisi.")
add("LoRA (Low-Rank Adaptation) ne demek?","LoRA, büyük dil modellerini verimli şekilde fine-tune etme yöntemi. Normal fine-tuning'de tüm model ağırlıklarını güncelersin — milyarlarca parametre. LoRA'da orijinal ağırlıkları dondurursun ve küçük düşük-rank matrisler eklersin. Bu matrisler çok daha az parametre içerir (orijinalin %1'i bile olabilir). Avantajları: çok daha az GPU belleği, hızlı eğitim, orijinal model korunur, birden fazla LoRA adaptörü birleştirilebilir. Hugging Face PEFT kütüphanesi LoRA implementasyonu sağlıyor. Biz de bu projede LoRA kullanıyoruz. QLoRA ise LoRA'nın quantize edilmiş hali — daha da verimli.","LoRA, düşük-rank adaptasyon, PEFT, QLoRA, verimli fine-tuning.")
add("vektör veritabanı ne?","Vektör veritabanı, yüksek boyutlu vektörleri (embedding'leri) depolayan ve benzerlik araması yapabilen özel veritabanı. Geleneksel veritabanları tam eşleşme arar, vektör veritabanları benzerlik arar — 'bu vektöre en yakın 10 vektörü bul'. Pinecone, Chroma, Weaviate, Milvus, FAISS popüler çözümler. RAG sistemlerinde dökümanların embedding'leri burada tutulur. Öneri sistemlerinde benzer ürünler bulunur. Arama motorlarında semantik arama yapılır. AI uygulamalarının altyapı bileşeni haline geldi.","Vektör veritabanı, embedding, benzerlik araması, Pinecone, RAG.")

# Günlük hayat ve motivasyon
add("yazılımda motivasyonu nasıl koruyabilirim?","Motivasyonu korumak herkesin yaşadığı bir zorluk. Birkaç strateji: küçük hedefler koy — 'bir uygulama yap' yerine 'bugün login sayfasını bitir'. İlerlemeyi görünür yap — GitHub streak, todo list, proje milestone'ları. Toplulukla bağlantıda kal — Discord, Reddit, Twitter'da yazılımcılarla etkileşim. Farklı projeler dene — sıkılıyorsan alan değiştir, web'den mobile, AI'dan game dev'e. Mükemmeliyetçiliği bırak — her proje mükemmel olmak zorunda değil, çalışan bir şey yapmak bile başarı. Burnout belirtilerini tanı ve mola ver. Ve unutma: herkes bazen motivasyonsuz hisseder, normal bu.","Motivasyon koruma, küçük hedefler, topluluk, burnout, mükemmeliyetçilik.")
add("imposter syndrome ile nasıl başa çıkılır?","Imposter syndrome (sahtekar sendromu) neredeyse her yazılımcının yaşadığı bir şey. 'Ben yeterince iyi değilim', 'beni keşfedecekler' hissi. Gerçek: bu alanda her şeyi bilmek imkansız, herkes bir şeyleri bilmiyor. Başa çıkma yolları: başarılarını kaydet — yaptığın projeleri, çözdüğün bugları not al. Başkalarıyla karşılaştırmayı bırak — herkesin yolculuğu farklı. Öğrenme sürecini kabul et — bilmemek normal, öğrenmemek sorun. Mentör veya akran desteği al. Ve hatırla: imposter syndrome hissetmen genelde iyi bir işaret — çünkü farkındalığın var demek.","Imposter syndrome, sahtekar sendromu, başa çıkma, farkındalık.")
add("iyi bir GitHub profili nasıl olmalı?","İyi bir GitHub profili seni anlatan bir portfolyo. README profili ekle — kim olduğun, ne yaptığın, ilgi alanların. Projelerine düzgün README yaz — ne yaptığı, nasıl kurulacağı, ekran görüntüleri. Contribution graph'ın yeşil olsun — düzenli commit yap. Projelerini çeşitlendir — web, mobile, AI, CLI araçları. Star aldığın projeler güzel ama asıl önemli olan kalite. Commit mesajlarını düzgün yaz — 'fix bug' yerine 'fix authentication error when token expires'. Görkem'in GitHub profilinde 30'dan fazla proje var ve çok çeşitli konuları kapsıyor — bu çok iyi bir örnek.","GitHub profili, README, contribution graph, commit mesajı, portfolyo.")
add("blog yazmak kariyere katkı sağlar mı?","Kesinlikle evet. Blog yazmak birçok açıdan faydalı: öğrendiklerini yazarak pekiştirirsin (Feynman tekniği), iletişim becerisini geliştirirsin (teknik yazarlık), online görünürlüğün artar, aynı konuda takılanların sorununu çözersin. Medium, Dev.to, Hashnode, kişisel blog (GitHub Pages) platformları var. Ne yazacağını bilmiyorsan: öğrendiğin bir teknolojiyi anlat, çözdüğün bir problemi paylaş, bir proje tutorial'ı yaz. Haftada bir yazı bile yeterli. Süreklilik önemli. Mülakatlarda 'blog yazıyorum' demek artı puan.","Blog yazma, Feynman tekniği, Medium, Dev.to, iletişim becerisi, mülakat.")
add("yazılımcı olarak networking nasıl yapılır?","Networking sadece iş bulmak için değil, öğrenmek ve büyümek için de önemli. Online: LinkedIn'de aktif ol, Twitter'da tech topluluğuna katıl, Discord/Slack kanallarında takıl, open-source projelere katkı yap. Offline: meetup'lara git, konferanslara katıl, hackathon'lara katıl. Networking'in kuralı: vermeden almaya çalışma — bilgi paylaş, yardım et, değer kat. Görkem hackathon'lara katılarak hem networking yapıyor hem deneyim kazanıyor. Bir bağlantı bir gün seni işe alabilir, tavsiye edebilir, projeye dahil edebilir. İlişkileri uzun vadeli düşün.","Networking, LinkedIn, hackathon, meetup, değer katma, uzun vade.")

# Teknoloji trendleri
add("2024-2025'te hangi teknolojiler öne çıkıyor?","AI ve LLM'ler kesinlikle en büyük trend — ChatGPT, Claude, Gemini ve bunların API'ları ile uygulama geliştirme. RAG ve AI agent'lar çok popüler. Rust güvenlik ve performans için yükseliyor. WebAssembly (WASM) tarayıcıda native hızda kod çalıştırma. Edge computing ve IoT. Quantum computing araştırması ilerliyor. Kubernetes ve cloud-native geliştirme standart haline geldi. Low-code/no-code platformlar artıyor ama geliştiricilerin yerini almıyor. Siber güvenlik her zaman kritik. Görkem AI alanında kalarak doğru bir strateji izliyor.","2024-2025 teknoloji trendleri, AI, LLM, Rust, WASM, Kubernetes.")
add("yapay zeka işleri elimizden alacak mı?","Bu sorunun cevabı nüanslı. AI bazı işleri otomatize edecek ama yeni işler de yaratacak. Tekrarlayan, kalıp tabanlı görevler otomatize olacak — veri girişi, basit kod yazma, müşteri hizmetleri. Ama yaratıcılık, stratejik düşünme, insan ilişkileri, etik kararlar gerektiren işler uzun süre insan gerektirmeye devam edecek. Yazılımcılar için: AI ile birlikte çalışmayı öğren, AI'ı araç olarak kullan, problem çözme ve mimari düşünme becerilerini geliştir. AI'dan korkmak yerine onu kullanmayı öğren. Görkem de AI ile projeler yaparak bu dönüşüme hazırlanıyor.","AI ve işler, otomasyon, yaratıcılık, AI ile çalışma, adaptasyon.")
add("edge computing nedir?","Edge computing, veri işlemeyi merkezi sunuculardan (cloud) kullanıcıya yakın noktalara (edge) taşımak. Neden? Gecikme azalır — verinin uzak sunucuya gidip gelmesi yerine yakın noktada işlenir. Bant genişliği tasarrufu — tüm veriyi cloud'a göndermek pahalı. Gizlilik — hassas veri lokal kalabilir. Örnekler: akıllı fabrikalar, otonom araçlar, IoT cihazları, AR/VR uygulamaları. AWS Wavelength, Azure Edge, Google Distributed Cloud çözümler sunuyor. 5G ile birlikte edge computing daha da önem kazanacak.","Edge computing, gecikme, IoT, 5G, cloud alternatifi.")
add("blockchain ve Web3 hala önemli mi?","Blockchain teknolojisi tartışmalı bir konu. Cryptocurrency hype'ı azaldı ama teknoloji kendisi hala gelişiyor. Supply chain takibi, dijital kimlik, oy verme sistemleri, NFT'ler (sanat ötesinde), DeFi — gerçek kullanım alanları var ama mainstream adoption henüz tam gerçekleşmedi. Solidity (Ethereum) en popüler smart contract dili. Web3 developer'lara talep var ama AI kadar değil. Benim görüşüm: temelini öğren ama tüm kariyerini buna bağlama. AI ile blockchain'in kesişimi ilginç bir alan — on-chain AI, decentralized ML. Dengeli yaklaş.","Blockchain, Web3, kullanım alanları, Solidity, AI kesişimi.")

# YKS ve sınav
add("YKS'de sayısal bölüm tercihinde nelere dikkat etmeliyim?","Tercih yaparken sadece puanına değil, birçok faktöre bak. Şehir — büyük şehirlerde daha fazla staj ve iş imkanı. Üniversitenin sektörel bağlantıları — şirketlerle ilişkisi, kariyer merkezi aktifliği. Müfredat — güncel teknolojiler müfredata dahil mi. Erasmus ve yurt dışı imkanları. Burs imkanı. Eğitim dili — İngilizce eğitim uluslararası kariyer için avantaj. Kampüs ve sosyal imkanlar. Bilgisayar mühendisliği, yazılım mühendisliği, yapay zeka mühendisliği bölümleri arasındaki farkları araştır. Görkem Yeditepe'de okuyor ve memnun — ama herkesin tercihi farklı olabilir.","YKS tercih, şehir, müfredat, Erasmus, İngilizce eğitim, bölüm farkları.")
add("YKS'de son 3 ayda nasıl çalışmalıyım?","Son 3 ay çok kritik. Deneme sınavlarına ağırlık ver — haftada en az 2-3 deneme. Yanlış defteri tut — her denemeden sonra yanlışlarını analiz et. Zayıf konulara odaklan ama güçlü konuları da ihmal etme. Konu tekrarı yap, yeni konu ekleme. Zaman yönetimi pratik et — sınavda zamanı doğru kullanmak çok önemli. Uyku düzenini koru — gece çalışıp gündüz uyumak verimsiz. Beslenmeye dikkat et. Sosyal medyayı azalt. Motivasyonu koru — hedefini hatırla. Panik yapma, sürecine güven. Ve sınav günü: erken yat, kahvaltını yap, sınav yerine erken git.","YKS son 3 ay, deneme, yanlış defteri, zaman yönetimi, uyku, motivasyon.")
add("matematik çalışmak için öneriler verir misin?","Matematik pratik gerektiren bir ders. Formül ezberlemek yerine mantığını anla — neden bu formül bu sonucu veriyor. Bol soru çöz — farklı soru tiplerini gör. Her konuyu bir öncekine bağla — matematik kümülatif. Geometri ve cebirsel düşünme altyapısını güçlendir. Video anlatımlar işe yarar ama sorularla pekiştirmezsen unutursun. Zorlandığın konuda 20-30 soru çöz, hala zorlanıyorsan bir alt konuya dön. Kademe kademe ilerle. Hız için zamanlı soru çöz. Paragraf sorularını iyi oku — çoğu hata soruyu yanlış anlamaktan gelir. Matematik AI için de çok önemli — lineer cebir ve olasılık makine öğrenmesinin temeli.","Matematik çalışma, mantık, pratik, geometri, cebir, AI bağlantısı.")
add("fizik çalışmak zor, nasıl kolaylaştırabilirim?","Fizik formüller ve kavramlar bir arada. İlk adım: kavramları gerçek hayatla ilişkilendir — Newton'un 3. yasası neden araba sürerken önemli? Formülleri grupla — hareket, kuvvet, enerji, elektrik. Her formülün birimleri bilmek çok önemli — birim analizi seni doğru yola yönlendirir. Grafik yorumlama pratiği yap — fizik grafikleri çok soruluyor. Deneyler izle — YouTube'da fizik deneyleri kavramları görselleştirmeye yardımcı olur. Soru çözerken çizim yap — serbest cisim diyagramı gibi. Adım adım çöz, bir adımı atlamadan diğerine geçme. Fizik de matematik gibi kümülatif — temel atlamadan ilerle.","Fizik çalışma, kavram, formül, birim, grafik, deneyler, çizim.")

# Çeşitli teknik
add("Docker Compose ne işe yarar?","Docker Compose, birden fazla Docker container'ı bir arada yönetmeye yarıyor. Mesela bir web uygulamanda frontend, backend, veritabanı, Redis var — hepsini tek tek docker run ile çalıştırmak yerine docker-compose.yml dosyasında tanımlarsın. docker-compose up komutuyla hepsi birden ayağa kalkar. Geliştirme ortamında çok kullanışlı — yeni bir developer projeye katıldığında docker-compose up der ve her şey çalışır. Servisler arası ağ otomatik kurulur. Volume'lar veri kalıcılığı sağlar. Environment variable'lar .env dosyasından okunur. Production'da Kubernetes'e geçilir genelde ama development için Compose yeterli.","Docker Compose, multi-container, yml, geliştirme ortamı, Kubernetes.")
add("CI/CD pipeline nedir detaylı anlat","CI/CD, Continuous Integration ve Continuous Deployment/Delivery. CI: her commit'te otomatik build ve test çalışır — hata erken yakalanır. CD: testler geçerse otomatik deploy olur. Pipeline adımları: kod push → build → unit test → integration test → code quality check → staging deploy → smoke test → production deploy. Araçlar: GitHub Actions (en popüler), GitLab CI, Jenkins, CircleCI. GitHub Actions'ta .github/workflows altında YAML dosyaları yazarsın. Her PR'da testler otomatik çalışır, main branch'e merge edilince production'a deploy olur. DevOps kültürünün temel taşı. Görkem'in projelerinde CI/CD kullanması profesyonelliğini artırır.","CI/CD, pipeline adımları, GitHub Actions, otomatik deploy, DevOps.")
add("Kubernetes nedir basitçe anlat","Kubernetes (K8s), container orchestration platformu. Docker container'larını büyük ölçekte yönetir. Ne yapar: otomatik ölçekleme (trafik artarsa yeni container açar), self-healing (bir container çökerse yenisini başlatır), yük dengeleme, rolling update (sıfır downtime ile güncelleme), secret yönetimi. Pod (en küçük birim, bir veya daha fazla container), Service (ağ erişimi), Deployment (pod yönetimi), Ingress (dış trafik yönlendirme) temel kavramlar. AWS EKS, Google GKE, Azure AKS managed Kubernetes çözümleri. Öğrenme eğrisi dik ama büyük sistemler için standart.","Kubernetes, K8s, container orchestration, pod, service, ölçekleme.")
add("NoSQL ve SQL arasındaki fark ne?","SQL veritabanları (MySQL, PostgreSQL) ilişkisel — tablolar, satırlar, sütunlar, şema zorunlu, JOIN ile tablolar birleştirilir. ACID uyumlu — tutarlılık ve güvenilirlik. NoSQL veritabanları (MongoDB, Cassandra, Redis) şemasız veya esnek şemalı — JSON benzeri dökümanlar, key-value, graph, columnar. Hangisi ne zaman: yapılandırılmış veri ve karmaşık sorgular → SQL. Esnek şema, yatay ölçekleme, yüksek yazma hızı → NoSQL. Çoğu büyük sistem ikisini birlikte kullanır (polyglot persistence). PostgreSQL JSON desteğiyle ikisinin arasında bir yerde. Seçim projenin ihtiyacına göre yapılmalı.","SQL vs NoSQL, ilişkisel, döküman, ne zaman hangisi, polyglot.")
add("API gateway ne yapar?","API gateway, tüm API isteklerinin tek bir noktadan geçtiği bir aracı katman. Microservice mimarisinde istemci 10 farklı servise ayrı ayrı istek yapmak yerine tek gateway'e istek yapar, gateway doğru servise yönlendirir. Sağladıkları: kimlik doğrulama (tüm isteklerde), rate limiting, request/response dönüştürme, caching, logging, load balancing, SSL termination. AWS API Gateway, Kong, Traefik popüler çözümler. Backend for Frontend (BFF) pattern'ı ile her frontend için ayrı gateway oluşturabilirsin. Microservice mimarisinin olmazsa olmazı.","API gateway, microservice, kimlik doğrulama, rate limiting, Kong.")

def main():
    random.shuffle(E)
    with open("scrapers/bulk_tr4.json","w",encoding="utf-8") as f:
        json.dump({"train":E},f,ensure_ascii=False,indent=4)
    print(f"Generated {len(E)} Turkish entries (part 4).")

if __name__=="__main__":
    main()
