# -*- coding: utf-8 -*-
"""turk_klasik_kitaplari_lora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rU4ELlXbK8DnsF_l-LIUTJCRyu-BD0dO
"""

turk_klasik_kitaplari_lora.ipynb

!pip install -q -U unsloth datasets trl transformers accelerate bitsandbytes

import torch

print("PyTorch:", torch.__version__)
print("CUDA kullanılabilir:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

from unsloth import FastLanguageModel

print("Unsloth başarıyla açıldı.")

from huggingface_hub import notebook_login

notebook_login()

from unsloth import FastLanguageModel

max_seq_length = 512

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit",
    max_seq_length=max_seq_length,
    load_in_4bit=True
)

print("Model yüklendi.")

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj"
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
    use_rslora=False,
    loftq_config=None
)

print("LoRA katmanları eklendi.")

from datasets import load_dataset

dataset = load_dataset(
    "haticenurcakr/turkish-classic-books-qa",
    split="train"
)

print("Kayıt sayısı:", len(dataset))
print("Sütunlar:", dataset.column_names)
print(dataset[0])

def format_dataset(batch):
    metinler = []

    for konusma in batch["train"]:
        metin = tokenizer.apply_chat_template(
            konusma,
            tokenize=False,
            add_generation_prompt=False
        )

        metinler.append(metin)

    return {"text": metinler}


dataset = dataset.map(
    format_dataset,
    batched=True
)

print(dataset[0]["text"])

dataset_split = dataset.train_test_split(
    test_size=0.1,
    seed=42
)

train_dataset = dataset_split["train"]
eval_dataset = dataset_split["test"]

print("Eğitim verisi:", len(train_dataset))
print("Test verisi:", len(eval_dataset))

from trl import SFTTrainer, SFTConfig
from unsloth import is_bfloat16_supported

training_args = SFTConfig(
    output_dir="turkish_classic_lora_outputs",

    dataset_text_field="text",
    max_length=max_seq_length,
    packing=False,

    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,

    learning_rate=2e-4,
    warmup_ratio=0.1,
    weight_decay=0.01,
    lr_scheduler_type="linear",

    fp16=not is_bfloat16_supported(),
    bf16=is_bfloat16_supported(),

    logging_steps=5,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,

    optim="adamw_8bit",
    seed=3407,
    report_to="none"
)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    args=training_args
)

print("Trainer hazır.")

trainer_stats = trainer.train()

from google.colab import drive
drive.mount("/content/drive")

lora_klasoru = (
    "/content/drive/MyDrive/"
    "turkish_classic_books_qwen_lora"
)

model.save_pretrained(lora_klasoru)
tokenizer.save_pretrained(lora_klasoru)

print("LoRA Drive'a kaydedildi:")
print(lora_klasoru)

FastLanguageModel.for_inference(model)

mesajlar = [
    {
        "role": "user",
        "content": "Araba Sevdası romanının yazarı kimdir?"
    }
]

girdi = tokenizer.apply_chat_template(
    mesajlar,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt"
).to("cuda")

cikti = model.generate(
    input_ids=girdi,
    max_new_tokens=80,
    do_sample=False,
    use_cache=True
)

yeni_tokenlar = cikti[0][girdi.shape[1]:]

cevap = tokenizer.decode(
    yeni_tokenlar,
    skip_special_tokens=True
)

print("Modelin cevabı:")
print(cevap)

repo_id = "haticenurcakr/turkish-classic-books-qwen-lora"

model.push_to_hub(
    repo_id,
    commit_message="Upload Turkish classic books LoRA adapter"
)

tokenizer.push_to_hub(
    repo_id,
    commit_message="Upload tokenizer files"
)

print("LoRA adaptörü yüklendi:")
print(f"https://huggingface.co/{repo_id}")