# -*- coding: utf-8 -*-
"""turk_klasik_kitaplari_bpe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9qT2r__7bY1MzcbXNcYD072k6xbbgIy
"""

from google.colab import drive
drive.mount("/content/drive")

!pip install -q datasets tokenizers transformers huggingface_hub

from datasets import load_dataset

dataset = load_dataset(
    "haticenurcakr/turkish-classic-books-qa",
    split="train"
)

print("Kayıt sayısı:", len(dataset))
print("Sütunlar:", dataset.column_names)
print(dataset[0])

import os

proje_klasoru = (
    "/content/drive/MyDrive/"
    "turk_klasik_kitaplari_tokenizer"
)

os.makedirs(proje_klasoru, exist_ok=True)

corpus_yolu = f"{proje_klasoru}/tokenizer_corpus.txt"

metinler = []

for kayit in dataset:
    for mesaj in kayit["train"]:
        icerik = mesaj["content"].strip()

        if icerik:
            metinler.append(icerik)

with open(corpus_yolu, "w", encoding="utf-8") as dosya:
    for metin in metinler:
        dosya.write(metin + "\n")

print("Corpus satır sayısı:", len(metinler))
print("Corpus kaydedildi:", corpus_yolu)

from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.trainers import BpeTrainer
from tokenizers.pre_tokenizers import ByteLevel
from tokenizers.decoders import ByteLevel as ByteLevelDecoder

tokenizer = Tokenizer(
    BPE(unk_token="<unk>")
)

tokenizer.pre_tokenizer = ByteLevel(
    add_prefix_space=False
)

tokenizer.decoder = ByteLevelDecoder()

trainer = BpeTrainer(
    vocab_size=3000,
    min_frequency=2,
    special_tokens=[
        "<pad>",
        "<unk>",
        "<bos>",
        "<eos>"
    ],
    initial_alphabet=ByteLevel.alphabet()
)

tokenizer.train(
    files=[corpus_yolu],
    trainer=trainer
)

print("BPE Tokenizer eğitildi.")
print("Sözlük boyutu:", tokenizer.get_vocab_size())

from transformers import PreTrainedTokenizerFast

tokenizer_klasoru = f"{proje_klasoru}/tokenizer"

fast_tokenizer = PreTrainedTokenizerFast(
    tokenizer_object=tokenizer,
    unk_token="<unk>",
    pad_token="<pad>",
    bos_token="<bos>",
    eos_token="<eos>"
)

fast_tokenizer.save_pretrained(tokenizer_klasoru)

print("Tokenizer kaydedildi:")
print(tokenizer_klasoru)

test_metni = (
    "Kürk Mantolu Madonna, Sabahattin Ali "
    "tarafından yazılmıştır."
)

tokenlar = fast_tokenizer.tokenize(test_metni)
token_idleri = fast_tokenizer.encode(test_metni)
geri_cevrilen = fast_tokenizer.decode(token_idleri)

print("Orijinal metin:")
print(test_metni)

print("\nTokenlar:")
print(tokenlar)

print("\nToken ID'leri:")
print(token_idleri)

print("\nGeri çevrilen metin:")
print(geri_cevrilen)

from huggingface_hub import notebook_login

notebook_login()

repo_adi = "haticenurcakr/turkish-classic-books-bpe-tokenizer"

fast_tokenizer.push_to_hub(
    repo_adi,
    commit_message="Upload Turkish classic books BPE tokenizer"
)

print("Tokenizer Hugging Face'e yüklendi:")
print(f"https://huggingface.co/{repo_adi}")