"""Small, validated JSON pantry store used by the lesson 8 tools.

The checked-in example data uses relative expiry offsets so the example remains
useful after the course date changes.  A runtime state file contains only
canonical ISO dates and is written with a replace-on-success operation.
"""

from __future__ import annotations

import json
import math
import os
import tempfile
import uuid
from collections.abc import Mapping
from copy import deepcopy
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

_MODULE_DIR = Path(__file__).resolve().parent
DEFAULT_SEED_PATH = _MODULE_DIR / "data" / "pantry.example.json"
DEFAULT_STATE_PATH = _MODULE_DIR / ".state" / "pantry.json"
SCHEMA_VERSION = 1
MAX_NAME_LENGTH = 120
MAX_TEXT_LENGTH = 40
MIN_EXPIRING_DAYS = 0
MAX_EXPIRING_DAYS = 365

_RUNTIME_FIELDS = ("id", "name", "quantity", "unit", "category", "expires_on")
_SEED_FIELDS = ("id", "name", "quantity", "unit", "category", "expires_in_days")


class PantryError(Exception):
    """Expected storage, validation, or domain error exposed to the tool layer."""

    def __init__(self, code: str, message: str):
        self.code = str(code)
        self.message = str(message)
        super().__init__(self.message)


def _fail(code: str, message: str) -> PantryError:
    return PantryError(code, message)


def _is_strict_number(value: Any) -> bool:
    return (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
        and math.isfinite(float(value))
    )


def _validate_quantity(value: Any, field: str = "quantity") -> int | float:
    if not _is_strict_number(value) or float(value) <= 0:
        raise _fail("VALIDATION_ERROR", f"{field} pozitif ve sonlu bir sayı olmalıdır.")
    return value


def _validate_text(value: Any, field: str, maximum: int) -> str:
    if not isinstance(value, str):
        raise _fail("VALIDATION_ERROR", f"{field} metin olmalıdır.")
    cleaned = value.strip()
    if not cleaned:
        raise _fail("VALIDATION_ERROR", f"{field} boş olamaz.")
    if len(cleaned) > maximum:
        raise _fail("VALIDATION_ERROR", f"{field} en fazla {maximum} karakter olabilir.")
    return cleaned


def _validate_id(value: Any) -> str:
    # IDs are generated by this module but are also persisted input, so reject
    # whitespace-only or non-string IDs rather than silently repairing them.
    return _validate_text(value, "id", MAX_NAME_LENGTH)


def _validate_date(value: Any, field: str = "expires_on") -> str:
    if not isinstance(value, str):
        raise _fail("VALIDATION_ERROR", f"{field} YYYY-AA-GG biçiminde bir metin olmalıdır.")
    try:
        parsed = date.fromisoformat(value)
    except (TypeError, ValueError) as exc:
        raise _fail("VALIDATION_ERROR", f"{field} geçerli bir YYYY-AA-GG tarihi olmalıdır.") from exc
    if parsed.isoformat() != value:
        raise _fail("VALIDATION_ERROR", f"{field} YYYY-AA-GG biçiminde olmalıdır.")
    return value


def _validate_root(payload: Any, *, seed: bool) -> list[dict[str, Any]]:
    if not isinstance(payload, dict) or set(payload) != {"version", "items"}:
        raise _fail("STORAGE_ERROR", "Envanter JSON şeması geçersiz.")
    version = payload.get("version")
    if isinstance(version, bool) or version != SCHEMA_VERSION:
        raise _fail("STORAGE_ERROR", f"Envanter JSON sürümü {SCHEMA_VERSION} olmalıdır.")
    raw_items = payload.get("items")
    if not isinstance(raw_items, list):
        raise _fail("STORAGE_ERROR", "Envanter items alanı liste olmalıdır.")

    fields = set(_SEED_FIELDS if seed else _RUNTIME_FIELDS)
    items: list[dict[str, Any]] = []
    known_ids: set[str] = set()
    for index, raw in enumerate(raw_items):
        if not isinstance(raw, dict) or set(raw) != fields:
            raise _fail("STORAGE_ERROR", f"Envanter kaydı {index} şemaya uymuyor.")
        try:
            item_id = _validate_id(raw["id"])
            if item_id in known_ids:
                raise _fail("STORAGE_ERROR", f"Tekrarlı envanter kimliği: {item_id}.")
            known_ids.add(item_id)
            item = {
                "id": item_id,
                "name": _validate_text(raw["name"], "name", MAX_NAME_LENGTH),
                "quantity": _validate_quantity(raw["quantity"]),
                "unit": _validate_text(raw["unit"], "unit", MAX_TEXT_LENGTH),
                "category": _validate_text(raw["category"], "category", MAX_TEXT_LENGTH),
            }
            if seed:
                offset = raw["expires_in_days"]
                if isinstance(offset, bool) or not isinstance(offset, int):
                    raise _fail("STORAGE_ERROR", f"Envanter kaydı {index} expires_in_days tam sayı olmalıdır.")
                item["expires_in_days"] = offset
            else:
                item["expires_on"] = _validate_date(raw["expires_on"])
        except PantryError as exc:
            # Files that cannot be trusted are storage failures even where the
            # same value would be a normal input validation error on add_item.
            if exc.code == "VALIDATION_ERROR":
                raise _fail("STORAGE_ERROR", f"Envanter kaydı {index} geçersiz: {exc.message}") from exc
            raise
        items.append(item)
    return items


class PantryStore:
    """Validated JSON-backed pantry state with deterministic read operations."""

    def __init__(
        self,
        path: str | Path | None = None,
        *,
        seed_path: str | Path | None = None,
        today: date | None = None,
    ) -> None:
        if today is None:
            current_day = datetime.now().astimezone().date()
        elif isinstance(today, date) and not hasattr(today, "hour"):
            current_day = today
        else:
            raise _fail("VALIDATION_ERROR", "today date olmalıdır.")

        self.path = Path(path) if path is not None else DEFAULT_STATE_PATH
        self.seed_path = Path(seed_path) if seed_path is not None else DEFAULT_SEED_PATH
        self.today = current_day
        self._items: list[dict[str, Any]]

        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise _fail("STORAGE_ERROR", "Envanter klasörü oluşturulamadı.") from exc

        if self.path.exists():
            self._items = self._load_runtime()
        else:
            self._items = self._load_and_materialize_seed()
            self._persist(self._items)

    def _read_json(self, path: Path) -> Any:
        try:
            with path.open("r", encoding="utf-8") as handle:
                return json.load(handle)
        except FileNotFoundError as exc:
            raise _fail("STORAGE_ERROR", "Envanter dosyası bulunamadı.") from exc
        except (OSError, UnicodeError, json.JSONDecodeError) as exc:
            raise _fail("STORAGE_ERROR", "Envanter JSON dosyası okunamadı.") from exc

    def _load_runtime(self) -> list[dict[str, Any]]:
        return _validate_root(self._read_json(self.path), seed=False)

    def _load_and_materialize_seed(self) -> list[dict[str, Any]]:
        seed_items = _validate_root(self._read_json(self.seed_path), seed=True)
        materialized: list[dict[str, Any]] = []
        for item in seed_items:
            offset = item.pop("expires_in_days")
            try:
                expires_on = self.today + timedelta(days=offset)
            except (OverflowError, TypeError) as exc:
                raise _fail("STORAGE_ERROR", "Seed tarihi materialize edilemedi.") from exc
            materialized.append({**item, "expires_on": expires_on.isoformat()})
        # Validate the transformed records once more before writing them.
        return _validate_root({"version": SCHEMA_VERSION, "items": materialized}, seed=False)

    @staticmethod
    def _stored_item(item: Mapping[str, Any]) -> dict[str, Any]:
        return {field: item[field] for field in _RUNTIME_FIELDS}

    def _persist(self, items: list[dict[str, Any]]) -> None:
        payload = {"version": SCHEMA_VERSION, "items": [self._stored_item(item) for item in items]}
        temporary: str | None = None
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                dir=self.path.parent,
                prefix=f".{self.path.name}.",
                suffix=".tmp",
                delete=False,
            ) as handle:
                temporary = handle.name
                json.dump(payload, handle, ensure_ascii=False, indent=2)
                handle.write("\n")
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, self.path)
            temporary = None
        except (OSError, TypeError, ValueError) as exc:
            raise _fail("STORAGE_ERROR", "Envanter dosyası yazılamadı.") from exc
        finally:
            if temporary is not None:
                try:
                    os.unlink(temporary)
                except OSError:
                    pass

    @staticmethod
    def _derived(item: Mapping[str, Any], today: date) -> dict[str, Any]:
        expires = date.fromisoformat(str(item["expires_on"]))
        days_remaining = (expires - today).days
        if days_remaining < 0:
            status = "geçmiş"
        elif days_remaining == 0:
            status = "bugün"
        elif days_remaining <= 2:
            status = "acil"
        elif days_remaining <= 7:
            status = "yakında"
        else:
            status = "sonra"
        return {**dict(item), "days_remaining": days_remaining, "status": status}

    @staticmethod
    def _validate_filter_days(value: Any) -> int:
        if isinstance(value, bool) or not isinstance(value, int) or not MIN_EXPIRING_DAYS <= value <= MAX_EXPIRING_DAYS:
            raise _fail(
                "VALIDATION_ERROR",
                f"expiring_within_days {MIN_EXPIRING_DAYS} ile {MAX_EXPIRING_DAYS} arasında bir tam sayı olmalıdır.",
            )
        return value

    def list_items(self, expiring_within_days: int = 7, include_expired: bool = True) -> dict[str, Any]:
        days = self._validate_filter_days(expiring_within_days)
        if not isinstance(include_expired, bool):
            raise _fail("VALIDATION_ERROR", "include_expired boolean olmalıdır.")
        visible: list[dict[str, Any]] = []
        for item in self._items:
            derived = self._derived(item, self.today)
            remaining = derived["days_remaining"]
            if remaining < 0:
                if not include_expired:
                    continue
            elif remaining > days:
                continue
            visible.append(derived)
        visible.sort(key=lambda item: (item["expires_on"], str(item["name"]).casefold(), item["id"]))
        return {"items": visible, "today": self.today.isoformat(), "count": len(visible)}

    def add_item(
        self,
        name: str,
        quantity: float,
        unit: str,
        category: str,
        expires_on: str,
    ) -> dict[str, Any]:
        item = {
            "id": f"item-{uuid.uuid4().hex}",
            "name": _validate_text(name, "name", MAX_NAME_LENGTH),
            "quantity": _validate_quantity(quantity),
            "unit": _validate_text(unit, "unit", MAX_TEXT_LENGTH),
            "category": _validate_text(category, "category", MAX_TEXT_LENGTH),
            "expires_on": _validate_date(expires_on),
        }
        candidate = [*self._items, item]
        self._persist(candidate)
        self._items = candidate
        return {"item": deepcopy(item)}

    @staticmethod
    def _validate_item_id(item_id: Any) -> str:
        return _validate_text(item_id, "item_id", MAX_NAME_LENGTH)

    def consume_item(self, item_id: str, quantity: float) -> dict[str, Any]:
        canonical_id = self._validate_item_id(item_id)
        amount = _validate_quantity(quantity)
        index = next((i for i, item in enumerate(self._items) if item["id"] == canonical_id), None)
        if index is None:
            raise _fail("UNKNOWN_ITEM", f"Envanter ürünü bulunamadı: {canonical_id}.")
        current = self._items[index]
        if float(amount) > float(current["quantity"]):
            raise _fail("INSUFFICIENT_QUANTITY", f"{canonical_id} için stok miktarı yetersiz.")
        remaining = round(float(current["quantity"]) - float(amount), 12)
        if math.isclose(remaining, 0.0, abs_tol=1e-9) or remaining <= 0:
            candidate = [*self._items[:index], *self._items[index + 1 :]]
            self._persist(candidate)
            self._items = candidate
            return {"removed_item": deepcopy(current), "deleted": True}
        updated = {**current, "quantity": remaining}
        candidate = [*self._items]
        candidate[index] = updated
        self._persist(candidate)
        self._items = candidate
        return {"item": deepcopy(updated), "deleted": False}

    def remove_item(self, item_id: str) -> dict[str, Any]:
        canonical_id = self._validate_item_id(item_id)
        index = next((i for i, item in enumerate(self._items) if item["id"] == canonical_id), None)
        if index is None:
            raise _fail("UNKNOWN_ITEM", f"Envanter ürünü bulunamadı: {canonical_id}.")
        removed = self._items[index]
        candidate = [*self._items[:index], *self._items[index + 1 :]]
        self._persist(candidate)
        self._items = candidate
        return {"removed_item": deepcopy(removed)}


__all__ = [
    "DEFAULT_SEED_PATH",
    "DEFAULT_STATE_PATH",
    "MAX_EXPIRING_DAYS",
    "MAX_NAME_LENGTH",
    "MAX_TEXT_LENGTH",
    "SCHEMA_VERSION",
    "PantryError",
    "PantryStore",
]
