"""
Giresun kültürü Q&A çiftleri.

Her çift (soru, cevap) elle yazılmış, kaynaktaki olgulara bağlıdır.
qa_tr: Türkçe çiftler. qa_en: İngilizce karşılıkları.

Yapı, hedef formata (messages: [user, assistant]) sarılmak üzere
düz (soru, cevap) tuple listesi olarak tutulur.
"""

# -------------------- TÜRKÇE --------------------
qa_tr = [
    # Genel
    ("Giresun hangi bölgede yer alır?",
     "Giresun, Türkiye'nin Karadeniz Bölgesi'nde yer alan bir ildir."),
    ("Giresun'un plaka numarası kaçtır?",
     "Giresun'un plaka numarası 28'dir."),
    ("Giresun'un kaç ilçesi vardır?",
     "Giresun'un 15 ilçesi vardır: Piraziz, Bulancak, Keşap, Espiye, Tirebolu, Görele, Eynesil, Alucra, Çamoluk, Çanakçı, Dereli, Doğankent, Güce, Şebinkarahisar ve Yağlıdere."),
    ("Giresun'un komşu illeri hangileridir?",
     "Giresun'un komşuları doğuda Trabzon ve Gümüşhane, batıda Ordu, güneyde Erzincan ve Sivas'tır. Kuzeyinde ise Karadeniz yer alır."),
    ("Giresun ne zaman kurulmuştur?",
     "Arkeolojik araştırmalara göre Giresun'un milattan önce 350'li yıllarda kurulduğu belirtilir. Şehir tarih boyunca birçok medeniyete ev sahipliği yapmıştır."),
    ("Giresun'un tarihi hakkında ne söylenebilir?",
     "Giresun köklü bir tarihe sahiptir. Milattan önce 350'li yıllarda kurulduğu belirtilir ve tarih boyunca birçok medeniyete ev sahipliği yapmıştır."),

    # Fındık
    ("Giresun hangi tarım ürünüyle ünlüdür?",
     "Giresun, fındığıyla ünlüdür. Fındık, Giresun ile özdeşleşmiş en önemli tarım ürünüdür."),
    ("Giresun'da fındığın kültürel önemi nedir?",
     "Giresun'da fındık yalnızca bir tarım ürünü değil, aynı zamanda ekonomik ve kültürel bir değer olarak görülür. Fındık hasadı yöre halkı için hem geçim kaynağı hem de geleneksel bir süreçtir."),
    ("Giresun fındığı hangi sektörde öne çıkar?",
     "Giresun fındığı, çikolata ve şekerleme sektöründe özel bir yere sahiptir."),
    ("Giresun'da fındıktan yapılan ürünler nelerdir?",
     "Giresun mutfağında fındık ezmesi, fındıklı tatlılar ve fındıklı atıştırmalıklar yaygındır."),
    ("Fındık havası nedir?",
     "Fındık havası, Giresun'da fındık toplarken söylenen türkülere verilen addır."),

    # Ada
    ("Giresun Adası'nın özelliği nedir?",
     "Giresun Adası, Türkiye'nin Karadeniz kıyısındaki üzerinde bitki örtüsü bulunan tek adasıdır. Şehir merkezine yaklaşık 1,6 km mesafede ve yaklaşık 40.000 metrekare yüzölçümündedir."),
    ("Giresun Adası şehir merkezine ne kadar uzaktır?",
     "Giresun Adası, şehir merkezine yaklaşık 1,6 km mesafededir ve yaklaşık 40.000 metrekare yüzölçümüne sahiptir."),
    ("Giresun Adası'nın antik dönemdeki adı neydi?",
     "Giresun Adası antik dönemde Aretias adıyla bilinirdi."),
    ("Giresun Adası ile ilgili hangi efsaneler anlatılır?",
     "Efsaneye göre Giresun Adası Amazon kadınları tarafından kurulmuştur ve Amazon kraliçeleri savaş tanrısı Ares adına burada bir tapınak yaptırmıştır. Ayrıca Altın Post efsanesine göre Herkül'ün de içinde bulunduğu Argonautlar adaya ulaşmıştır."),
    ("Giresun Adası Amazonlarla nasıl ilişkilendirilir?",
     "En güçlü efsaneye göre Giresun Adası Amazon kadınları tarafından kurulmuştur ve Amazon kraliçeleri savaş tanrısı Ares adına adada bir tapınak yaptırmıştır."),
    ("Giresun Adası'nda hangi tarihi kalıntılar bulunur?",
     "Adada Alexius II dönemine ait sur kalıntıları, kuleler, manastır ve tarihi pişmiş toprak fıçılar bulunur. Ada, Cenevizliler ve Venedikliler tarafından uzun süre gemi sığınağı olarak kullanılmıştır."),
    ("Hamza Taşı nedir?",
     "Hamza Taşı, Giresun Adası'nda bulunan sacayağı biçiminde bir taştır. Ana tanrıça Kybele'yi temsil eder ve halk arasında 'dilek taşı' olarak bilinir."),
    ("Giresun Adası'nın doğal yapısı nasıldır?",
     "Adada Akdeniz defnesi ve yalancı akasya başta olmak üzere 71 doğal bitki türü bulunur. Ada aynı zamanda göçmen kuşların uğrak yeridir ve ikinci derece doğal sit alanı olarak korunur."),

    # Aksu
    ("Aksu Festivali nedir?",
     "Aksu Festivali (Uluslararası Aksu Festivali), Giresun'un en önemli geleneksel etkinliğidir. Her yıl 20 Mayıs'ta düzenlenir."),
    ("Aksu Festivali ne zaman düzenlenir?",
     "Aksu Festivali her yıl 20 Mayıs'ta düzenlenir."),
    ("Aksu Festivali'nde hangi gelenekler uygulanır?",
     "Festivalde Giresun Adası'nın etrafında tekne ile dolaşılır ve soyun sürdürülmesi inancıyla Hamza Taşı'nın (sacayağı) altından geçme geleneği uygulanır."),
    ("Aksu Festivali'nin kültürel önemi nedir?",
     "Aksu Festivali, Giresun Adası'nın kültürel ve mitolojik yönünü öne çıkaran en önemli yerel etkinliktir ve yerli yabancı çok sayıda ziyaretçi çeker."),

    # Müzik
    ("Giresun'un en önemli halk oyunları nelerdir?",
     "Giresun oyunları içinde en önemlileri Giresun Karşılaması ve horondur."),
    ("Horon nasıl oynanır?",
     "Horon, erkekler tarafından bölgenin meşhur çalgısı olan kemençe veya davul-zurna eşliğinde oynanır. Düz horon, sık sara, dik horon ve sallama gibi çeşitleri vardır."),
    ("Horonun çeşitleri nelerdir?",
     "Horonun düz horon, sık sara, dik horon ve sallama gibi çeşitleri vardır."),
    ("Giresun neden kemençeyle özdeşleşmiştir?",
     "Giresun, zengin kemençe geleneği nedeniyle 'kemençenin başkenti' olarak kabul edilir. Yörede önemli bir kemençe ekolü gelişmiştir."),
    ("Katip Şadi kimdir?",
     "Katip Şadi, Giresun yöresi kemençe ekolünün en önemli temsilcilerinden biridir."),
    ("Giresun'da kıyı ve iç kesim müziği arasında ne fark vardır?",
     "Kıyı kesiminde horon ve kemençe öne çıkarken, iç kesimlerde bağlama ve oturak havaları yaygındır. Kıyıda yalı havaları, dağlık bölgelerde ise yayla havaları söylenir."),
    ("Görele'nin müzik kültüründeki yeri nedir?",
     "Görele ilçesi kemençe kültürünün merkezlerinden biridir ve burada Uluslararası Kemençe ve Horon Festivali düzenlenir."),
    ("Giresun ezgilerinin ritmik yapısı nasıldır?",
     "Giresun'da çalınan ezgiler ağırlıkla 7 ve 9 zamanlıdır. 9 zamanlı ezgiler genellikle karşılama havasıdır."),

    # Yemek
    ("Giresun'un en meşhur yemekleri nelerdir?",
     "Giresun'un en meşhur yemekleri arasında pancar (karalahana) çorbası, fasulye turşusu ve fasulye kavurması yer alır."),
    ("Giresun mutfağını coğrafya nasıl etkilemiştir?",
     "Karadeniz'in engebeli coğrafyası nedeniyle Giresun'da tahıl tarımı yerine bahçe sebzeciliği, hayvancılık yerine balıkçılık gelişmiştir. Bu yüzden mutfakta sebze ve balık yemekleri öne çıkar."),
    ("Giresun mutfağında hangi sebzeler öne çıkar?",
     "Giresun mutfağında karalahana (yörede pancar da denir), mısır, fasulye ve kabak gibi sebzeler öne çıkar."),
    ("Giresun mutfağında balığın yeri nedir?",
     "Başta hamsi olmak üzere balık ve balık yemekleri Giresun mutfağında önemli yer tutar."),
    ("Giresun ismiyle anılan ürünler nelerdir?",
     "Giresun ismiyle anılan ürünler arasında Giresun fındığı, Giresun kirazı, Giresun pidesi, Giresun kadayıfı ve Giresun güllacı bulunur."),
    ("Giresun pidesinin özelliği nedir?",
     "Giresun pidesi, ince hamuru ve taş fırında pişirilmesiyle öne çıkar."),
    ("Giresun'un yöresel lezzetlerinden örnekler verir misin?",
     "Giresun'un yöresel lezzetleri arasında ısırgan otu yemeği, galdirik kavurması, taflan kavurması, mısır ekmeği ve lahana diblesi sayılabilir."),
    ("Giresun mutfağı neden 'yeşil mutfak' olarak anılır?",
     "Giresun'un yöresel mutfağı bol yeşillik içermesi nedeniyle 'yeşil mutfak' olarak tanıtılır ve her yıl düzenlenen Yeşil Lezzetleri Gastronomi Festivali ile öne çıkarılır."),

    # Islık dili
    ("Islık dili nedir?",
     "Islık dili, Giresun'un Çanakçı, Görele, Eynesil ve Tirebolu ilçelerinde yaşatılan geleneksel bir iletişim yöntemidir. Dağlık coğrafyada kilometrelerce uzaklıktaki kişiler arasında haberleşmeyi sağlar."),
    ("Islık dilini kaç kişi biliyor?",
     "Islık dilini yaklaşık 10 bin kişinin konuşabildiği veya anlayabildiği tahmin edilir."),
    ("Islık dili UNESCO listesinde mi?",
     "Evet, ıslık dili UNESCO Acil Koruma Gerektiren Somut Olmayan Kültürel Miras Listesi'nde yer alır."),
    ("Islık dili hangi ilçelerde yaşatılır?",
     "Islık dili özellikle Giresun'un Çanakçı, Görele, Eynesil ve Tirebolu ilçelerinde yaşatılır."),

    # Kıyafet
    ("Giresun'un yöresel kıyafetleri nasıldır?",
     "Giresun'un yöresel kıyafetleri çevre illerle benzerlik gösterir. Geleneksel kadın giyiminde ketenden beyaz gömlek, dize kadar beyaz çorap ve gömlek üstüne fistan bulunur."),
    ("Giresun'da erkek yöresel giyimi nelerden oluşur?",
     "Erkek giyiminde gömlek, siyah şalvar, 'alaçordup' denilen çorap ve çorap üzerine çarık yer alır."),
    ("Peştamal Giresun giyiminde nerede kullanılır?",
     "Peştamal, Giresun kadın giyiminin değişmez bir parçasıdır."),
    ("Giresun yöresel kıyafetlerinde hangi renkler baskındır?",
     "Kadın kıyafetlerinde bordo, yeşil ve altın işleme renkleri baskınken, erkek kıyafetlerinde siyah ve beyaz öne çıkar."),

    # Tarihi yerler
    ("Giresun'un önemli tarihi kaleleri nelerdir?",
     "Giresun Kalesi şehrin önemli tarihi yapılarından biridir. Ayrıca Şebinkarahisar Kalesi ve Tirebolu Kalesi ilin önemli tarihi kaleleri arasındadır."),
    ("Giresun'un öne çıkan yaylaları hangileridir?",
     "Sis Dağı, Kümbet, Gölyanı, Bektaş ve Kulakkaya yaylaları Giresun'un öne çıkan yaylalarıdır."),
    ("Giresun'da yayla kültürü nasıldır?",
     "Yayla kültürü Giresun'un önemli bir parçasıdır. Yayla göçü ve yayla şenlikleri geleneksel eğlence ortamları arasında yer alır."),
    ("Giresun'da hangi kültürel mekanlar bulunur?",
     "Giresun Müzesi ve Giresun Atatürk Evi ilin kültürel mekanları arasındadır."),

    # Türkü
    ("Giresun türküleri hakkında ne söylenebilir?",
     "Giresun türküler yönünden zengin bir ildir. Bilinen türküleri arasında Mican, Tamzara, Karahisar Türküsü, Fingil ve 'Aksu Derler Adına' sayılabilir."),
    ("'Aynalıdır Aynalı' nedir?",
     "'Aynalıdır Aynalı', Giresun yöresine ait bilinen türkülerden biridir."),

    # Gelenek
    ("Giresun'da Mart ayında hangi gelenek vardır?",
     "Giresun'da her yıl Mart ayının 14'ünde 'yılbaşı' adı verilen mevsimlik bir gelenek tutulur. O sabah erkenden kalkılıp deniz veya akarsudan su alınması adettir."),
    ("Giresun'da başlıca eğlence ortamları nelerdir?",
     "Yayla yolculukları, otçu göçü, yayla şenlikleri, nişan ve kına düğünleri Giresun'un başlıca çalgılı eğlence ortamlarıdır."),
]


# -------------------- İNGİLİZCE --------------------
qa_en = [
    ("Which region is Giresun located in?",
     "Giresun is a province located in the Black Sea Region of Turkey."),
    ("What is Giresun's license plate number?",
     "Giresun's license plate number is 28."),
    ("How many districts does Giresun have?",
     "Giresun has 15 districts: Piraziz, Bulancak, Keşap, Espiye, Tirebolu, Görele, Eynesil, Alucra, Çamoluk, Çanakçı, Dereli, Doğankent, Güce, Şebinkarahisar and Yağlıdere."),
    ("Which provinces border Giresun?",
     "Giresun borders Trabzon and Gümüşhane to the east, Ordu to the west, and Erzincan and Sivas to the south. The Black Sea lies to its north."),
    ("When was Giresun founded?",
     "According to archaeological research, Giresun is said to have been founded around 350 BC. The city has hosted many civilizations throughout history."),
    ("What can be said about the history of Giresun?",
     "Giresun has a deep-rooted history. It is said to have been founded around 350 BC and has hosted many civilizations over the centuries."),

    ("Which agricultural product is Giresun famous for?",
     "Giresun is famous for its hazelnuts. The hazelnut is the most important agricultural product identified with Giresun."),
    ("What is the cultural significance of hazelnuts in Giresun?",
     "In Giresun, the hazelnut is not only an agricultural product but also an economic and cultural value. The hazelnut harvest is both a source of livelihood and a traditional process for local people."),
    ("In which industry does the Giresun hazelnut stand out?",
     "The Giresun hazelnut holds a special place in the chocolate and confectionery industry."),
    ("What products are made from hazelnuts in Giresun?",
     "Hazelnut paste, hazelnut desserts and hazelnut snacks are common in Giresun cuisine."),
    ("What is a 'hazelnut tune' (fındık havası)?",
     "A 'hazelnut tune' (fındık havası) is the name given in Giresun to folk songs sung while harvesting hazelnuts."),

    ("What makes Giresun Island special?",
     "Giresun Island is the only island with vegetation on Turkey's Black Sea coast. It is about 1.6 km from the city center and covers roughly 40,000 square meters."),
    ("How far is Giresun Island from the city center?",
     "Giresun Island is about 1.6 km from the city center and covers approximately 40,000 square meters."),
    ("What was Giresun Island called in antiquity?",
     "In antiquity, Giresun Island was known as Aretias."),
    ("What legends are told about Giresun Island?",
     "According to legend, Giresun Island was founded by the Amazon women, and the Amazon queens built a temple there dedicated to Ares, the god of war. Also, according to the Golden Fleece legend, the Argonauts, including Hercules, reached the island."),
    ("How is Giresun Island associated with the Amazons?",
     "According to the strongest legend, Giresun Island was founded by the Amazon women, and the Amazon queens built a temple on the island dedicated to Ares, the god of war."),
    ("What historical remains are found on Giresun Island?",
     "The island holds wall remains, towers, a monastery and historic terracotta barrels from the era of Alexius II. It was long used as a ship shelter by the Genoese and the Venetians."),
    ("What is the Hamza Stone?",
     "The Hamza Stone is a tripod-shaped stone on Giresun Island. It represents the mother goddess Cybele and is popularly known as a 'wish stone'."),
    ("What is the natural structure of Giresun Island like?",
     "The island hosts 71 native plant species, chiefly Mediterranean laurel and false acacia. It is also a stopover for migratory birds and is protected as a second-degree natural site."),

    ("What is the Aksu Festival?",
     "The Aksu Festival (International Aksu Festival) is Giresun's most important traditional event. It is held every year on May 20."),
    ("When is the Aksu Festival held?",
     "The Aksu Festival is held every year on May 20."),
    ("What traditions are practiced at the Aksu Festival?",
     "During the festival people circle Giresun Island by boat, and, out of a belief in the continuation of lineage, practice the tradition of passing under the Hamza Stone (the tripod)."),
    ("What is the cultural importance of the Aksu Festival?",
     "The Aksu Festival is the most important local event highlighting the cultural and mythological side of Giresun Island, and it attracts many local and foreign visitors."),

    ("What are the most important folk dances of Giresun?",
     "The most important dances of Giresun are the Giresun Karşılaması and the horon."),
    ("How is the horon danced?",
     "The horon is danced by men accompanied by the kemençe, the region's famous instrument, or by davul-zurna. It has varieties such as düz horon, sık sara, dik horon and sallama."),
    ("What are the varieties of the horon?",
     "The horon has varieties such as düz horon, sık sara, dik horon and sallama."),
    ("Why is Giresun identified with the kemençe?",
     "Giresun is regarded as the 'capital of the kemençe' because of its rich kemençe tradition, and an important kemençe school has developed in the region."),
    ("Who is Katip Şadi?",
     "Katip Şadi is one of the most important representatives of the Giresun regional kemençe school."),
    ("What is the difference between coastal and inland music in Giresun?",
     "On the coast the horon and kemençe stand out, while inland the bağlama and 'oturak' tunes are common. Coastal areas sing 'yalı' tunes, while mountainous areas sing 'yayla' (highland) tunes."),
    ("What is Görele's place in music culture?",
     "The district of Görele is one of the centers of kemençe culture, and the International Kemençe and Horon Festival is held there."),
    ("What is the rhythmic structure of Giresun melodies?",
     "Melodies played in Giresun are predominantly in 7 and 9 beats. The 9-beat melodies are usually karşılama tunes."),

    ("What are the most famous dishes of Giresun?",
     "Among Giresun's most famous dishes are black cabbage (pancar) soup, pickled beans and sautéed beans."),
    ("How has geography shaped Giresun's cuisine?",
     "Because of the Black Sea's rugged geography, garden vegetable growing developed in Giresun instead of grain farming, and fishing instead of animal husbandry. As a result, vegetable and fish dishes stand out in the cuisine."),
    ("Which vegetables stand out in Giresun cuisine?",
     "Vegetables such as black cabbage (also called pancar locally), corn, beans and squash stand out in Giresun cuisine."),
    ("What is the place of fish in Giresun cuisine?",
     "Fish, chiefly anchovy (hamsi), and fish dishes hold an important place in Giresun cuisine."),
    ("Which products carry the Giresun name?",
     "Products carrying the Giresun name include Giresun hazelnut, Giresun cherry, Giresun pide, Giresun kadayıf and Giresun güllaç."),
    ("What is special about Giresun pide?",
     "Giresun pide stands out for its thin dough and being baked in a stone oven."),
    ("Can you give examples of Giresun's local delicacies?",
     "Giresun's local delicacies include nettle dishes, sautéed galdirik, sautéed cherry laurel (taflan), corn bread and cabbage diblesi."),
    ("Why is Giresun cuisine called the 'green cuisine'?",
     "Giresun's local cuisine is promoted as the 'green cuisine' because it contains abundant greens, and it is highlighted through the annual Green Delicacies Gastronomy Festival."),

    ("What is the whistling language?",
     "The whistling language is a traditional communication method kept alive in Giresun's Çanakçı, Görele, Eynesil and Tirebolu districts. It enables communication between people kilometers apart across mountainous terrain."),
    ("How many people know the whistling language?",
     "It is estimated that about 10,000 people can speak or understand the whistling language."),
    ("Is the whistling language on the UNESCO list?",
     "Yes, the whistling language is on UNESCO's List of Intangible Cultural Heritage in Need of Urgent Safeguarding."),
    ("In which districts is the whistling language kept alive?",
     "The whistling language is kept alive especially in Giresun's Çanakçı, Görele, Eynesil and Tirebolu districts."),

    ("What are Giresun's traditional clothes like?",
     "Giresun's traditional clothes resemble those of neighboring provinces. Traditional women's clothing includes a white linen shirt, white socks up to the knee, and a fistan worn over the shirt."),
    ("What does men's traditional clothing consist of in Giresun?",
     "Men's clothing includes a shirt, black şalvar (baggy trousers), socks called 'alaçordup', and çarık (rawhide shoes) worn over the socks."),
    ("Where is the peştamal used in Giresun clothing?",
     "The peştamal (waist cloth) is an unchanging part of women's clothing in Giresun."),
    ("Which colors dominate Giresun's traditional clothes?",
     "Women's clothes are dominated by maroon, green and gold embroidery, while men's clothes are dominated by black and white."),

    ("What are Giresun's important historical castles?",
     "Giresun Castle is one of the city's important historical structures. Şebinkarahisar Castle and Tirebolu Castle are also among the province's important historical castles."),
    ("Which are Giresun's prominent highlands (yayla)?",
     "Sis Dağı, Kümbet, Gölyanı, Bektaş and Kulakkaya are among Giresun's prominent highlands."),
    ("What is highland (yayla) culture like in Giresun?",
     "Highland culture is an important part of Giresun. Highland migration and highland festivals are among the traditional forms of entertainment."),
    ("What cultural venues are found in Giresun?",
     "The Giresun Museum and the Giresun Atatürk House are among the province's cultural venues."),

    ("What can be said about Giresun's folk songs?",
     "Giresun is rich in folk songs. Its well-known songs include Mican, Tamzara, Karahisar Türküsü, Fingil and 'Aksu Derler Adına'."),
    ("What is 'Aynalıdır Aynalı'?",
     "'Aynalıdır Aynalı' is one of the well-known folk songs of the Giresun region."),

    ("What tradition takes place in Giresun in March?",
     "In Giresun, a seasonal tradition called 'yılbaşı' (new year) is observed every year on March 14. On that morning it is customary to rise early and draw water from the sea or a stream."),
    ("What are the main entertainment settings in Giresun?",
     "Highland journeys, the 'otçu' migration, highland festivals, engagements and henna nights are Giresun's main settings for music-accompanied entertainment."),
]
